ocaml/opam

- src/client/opamAction.ml
- src/client/opamAction.mli
- src/client/opamArg.ml
- src/client/opamClient.ml
- src/client/opamRepositoryCommand.ml
- src/client/opamSolution.ml
- src/client/opamState.ml
- src/core/opamGlobals.ml
- src/core/opamMisc.ml
- src/core/opamMisc.mli
- src/core/opamParallel.ml
- src/core/opamProcess.ml
- src/core/opamProcess.mli
- src/core/opamSystem.ml
- src/core/opamTypesBase.ml
- src/core/opamTypesBase.mli
- src/solver/opamCudf.ml
Fixes the one-file-package bug
> Pass information after download rather than guess again the kind of dl

- src/client/opamState.ml
- src/repositories/opamLocal.ml
> Fixed failures from rsync that could be ignored

- doc/dev-manual/dev-manual.tex
> Document '!<formula>' in the dev-manual

- src/client/opamClient.ml
- src/solver/opamSolver.ml
- src/solver/opamSolver.mli
> Check for conflicts after update

- README.md
Trivial fixes to the README.md including spelling mistakes.
> Fixed two spelling mistakes and flow of wording in several places

- src/client/opamArg.ml
> Lookup plugins in the OPAM env

- admin-scripts/to_1_1.ml
> Fix 1.1 rewrite scripts for :enable variables

- src/client/opamAction.ml
- src/client/opamClient.ml
- src/client/opamState.ml
- src/client/opamState.mli
- src/client/opamSwitchCommand.ml
- src/core/opamCompiler.ml
- src/core/opamCompiler.mli
- src/core/opamGlobals.ml
Ref: #1999
Not closing because, while this should fix the bug, the situation needs some cleanup
(not during beta stage though)
> Fixed system compiler definition generation for devel versions

- src/client/opamAction.ml
- src/client/opamArg.ml
- src/client/opamClient.ml
- src/client/opamClient.mli
- src/core/opamFile.ml
- src/core/opamProcess.ml
- src/solver/opamHeuristic.ml
Closes #2010: thanks for reporting this hard-to-trigger bug (was due to
the disjunction in lwt's dependencies AND the fact that one branch
was unavailable)
> Fixed heuristics, and some messages improvements

- src/core/opamGlobals.ml
> Reset console paramaters after a CTRL-C

- src/client/opamArg.ml
- src/client/opamSolution.ml
- src/core/opamGlobals.ml
- src/core/opamGlobals.mli
- src/core/opamTypesBase.ml
- src/core/opamTypesBase.mli
- src_ext/Makefile
- src_ext/patches/cmdliner/backport_pre_4_00_0.patch
and rewrite documentation accordingly
Closes #2015
> Unset VC detection at 'pin add' by default

- CHANGES
- src/client/opamAction.ml
- src/client/opamArg.ml
- src/client/opamClient.ml
- src/client/opamRepositoryCommand.ml
- src/client/opamRepositoryCommand.mli
- src/client/opamState.ml
- src/client/opamState.mli
- src/core/opamFilename.ml
- src/core/opamGlobals.ml
- src/core/opamGlobals.mli
- src/core/opamProcess.ml
- src/core/opamSystem.ml
- src/core/opamSystem.mli
- src/repositories/opamLocal.ml
> Finer verbosity control

- doc/pages/Manual.md
- doc/pages/index.menu
Rewrite and reorganisation of the most useful parts of the LaTeX dev-manual
for easier reference and access
> On-line manual

- src/client/opamClient.ml
- src/client/opamSwitchCommand.ml
> Fixed switch-reinstall and locking

- src/client/opamAction.ml
- src/core/opamMisc.ml
- src/core/opamMisc.mli
This reverts commit 6fc3079e7e844418629e477ead83b3f9aa01a505.
Was too noisy
> Revert "Notify when environment variables at overriden during build"

- src/core/opamVersion.ml.in
> Fix bad cache magic number

- admin-scripts/lint.ml
- src/client/opamArg.ml
- src/core/opamFile.ml
- src/core/opamFile.mli
- src/tools/opam_admin_top.ml
- src/tools/opam_admin_top.mli
for easier processing and filtering
> Give numbers to opam lint's warn/errors

- src/client/opamState.ml
- src/solver/opamSolver.ml
with the default arguments, for backwards compatibility, closes #2085
> Allow simple path to aspcud-compatible solvers

- src/client/opamArg.ml
- src/client/opamClient.ml
- src/client/opamClient.mli
- src/client/opamSwitchCommand.ml
- src/client/opamSwitchCommand.mli
> Don't error out with --no-switch flag if compiler is installed

- src/core/opamSystem.ml
> Simply copy package archives of unknown formats

- CHANGES
> note findlib package name change

- src/client/opamArg.ml
- src/client/opamClient.ml
- src/client/opamClient.mli
- src/solver/opamSolver.ml
Allows to get a consistent solution for installing a set of packages. Needed
for https://github.com/ocaml/opam-depext/issues/8
> Implement 'opam list --resolve'

- src/core/opamProcess.ml
When `OpamProcess.command` is called with `allow_stdin:false` it will
create new channel for `stdin`, that will be duplicated in the child
process, but never closed in the parent.
The only place that currently disables stdin is in the `OpamCudf`
module.
Looks like, that this was the particular issue, that break BAP
installation ocaml/opam-repository#3994.
This issue starts to manifest on all our yosemite machines, when we're
trying to install BAP, after the aspcud was added to macports.
> This PR will solve a fd leak

- src/client/opamClient.ml
- src/core/opamSystem.ml
> Make opam-list exit non-zero only when patterns don't match

- src/repository/opamDownload.ml
Closes #2164. Thanks for reporting!
> Fix setting OPAMFETCH=wget

- src/client/opamArg.ml
Closes  #2177 -- thanks a lot for reporting!
> Fix the --use-internal-solver option

- src/client/opamArg.ml
- src/client/opamClient.ml
- src/client/opamConfigCommand.ml
- src/client/opamConfigCommand.mli
- src/format/opamFile.ml
- src/format/opamFile.mli
- src/format/opamFilter.ml
- src/format/opamPackage.ml
- src/format/opamPackage.mli
- src/format/opamVariable.ml
- src/format/opamVariable.mli
- src/state/opamState.ml
- src/state/opamState.mli
- src/tools/opam_check.ml
- src/tools/opam_mk_repo.ml
Also, some cleanup (removing quite a few static string checks)
> Allows using `_:var` to reference a variable for the current package

- src/state/opamState.ml
got broken with the preloading of the switch_config
> fixed 'opam config env'

- .gitignore
- doc/modules
- src/client/opamArg.ml
- src/client/opamClient.ml
- src/client/opamClient.mli
- src/format/opamFile.ml
- src/format/opamTypes.mli
- src/format/opamTypesBase.ml
- src/format/opamTypesBase.mli
- src/solver/opamSolver.ml
- src/state/opamState.ml
- src/state/opamStateConfig.ml
- src/state/opamStateConfig.mli
- src/tools/opam_mk_repo.ml
> Implements the `dev` flag

- src/client/opamClient.ml
- src/client/opamSwitchCommand.ml
- src/state/opamState.ml
- src/state/opamState.mli
> Fixes issues with env, switch install and global_config

- src/format/opamFile.ml
> Lint warning for ambiguous dev-repo addresses

- doc/pages/Install.md
- doc/pages/Manual.md
- doc/pages/Usage.md
- add section on external solvers in 'Usage.md'
- reformat Manual.md's with anchors for all fields
> Doc update

- src/state/opamState.ml
- src/state/opamState.mli
this is needed for opam-bundle
> OpamState: pass variables to add_to_env

- src/state/opamAction.ml
Seems from the comment I actually spotted this a while ago but figured there
had to be a good reason for it...
Fixes #2258
> Fixed forgetting some package reinstallations

- src/state/opamState.ml
- src/tools/opam_admin_top.ml
> Fixed automatic variables for non-system preinstalled switches

- src/client/opamClient.ml
i.e. compute the dependency cone of <pkg> and do recompilations within it. Otherwise,
the next upgrade will recompile <pkg> anyway.
> On 'upgrade <pkg>', perform related planned reinstallations

- src/client/opamClient.ml
- src/format/opamFile.ml
- src/format/opamFile.mli
- src/state/opamAction.ml
- src/state/opamAction.mli
- src/state/opamSolution.ml
- src/state/opamState.ml
- src/state/opamState.mli
Compilers are allowed to do this, and I am progressively closing
the gap between the two.
> Allow packages to add env variables

- src/format/opamFile.ml
- src/format/opamFile.mli
This might help plugin writer to share the configuration-file parser.
> Export some internals of OpamFile

- src/client/opamListCommand.ml
A small patch along the lines of #2380
> better opam info format

- doc/pages/Install.md
> Remove trailing slash from /usr/local/bin/ in installation instructions.

- .merlin
> Fix .merlin

- Makefile
- shell/bootstrap-ocaml.sh
Some minor improvements, see the commit messages.
> Some make cold improvements

- .travis-ci.sh
- .travis.yml
Version of ocaml installed by homebrew is no 4.02.3
> Fix ocaml version on OS X in Travis CI script

- src/Makefile
- src/tools/opam_admin.ml
- src/tools/opam_format_upgrade.ml
- src/tools/tools.ocp
for now, doing only the compilers to packages transition, but more may
be added later.
> Add '--upgrade-format' to opam-admin

- src/core/opamStd.ml
- src/core/opamStd.mli
- src/repository/opamVCS.ml
- src/state/opamEnv.ml
(and a mixed-mode rsync regression introduced some time ago)
> Correct multiple updates of a single environment variable

- src/client/opamMain.ml
- src/state/opamEnv.ml
to handle cases where the variables have been changed outside of opam better.
> Make environment variable de-update a bit more agressive

- src/client/opamArg.ml
- src/client/opamArg.mli
- src/client/opamListCommand.ml
- src/client/opamListCommand.mli
- src/client/opamMain.ml
- src/client/opamSwitchCommand.ml
- src/client/opamSwitchCommand.mli
- src/core/opamStd.ml
- src/state/opamSwitchState.ml
- src/state/opamSwitchState.mli
The long-awaited `opam list` rehaul!
> Interface improvements, in particular to `opam list`

- src/repository/opamDownload.ml
The user agent will appear as something like "opam/1.2.2"
My modest attempt at #2598
> Set user-agent on opam downloads

- src/client/opamSwitchCommand.ml
- src/solver/opamCudf.ml
check availability of packages, support --show
> OpamSwitchCommand fixes

- doc/pages/Manual.md
- shell/opam_switch_eval.sh
- src/Makefile
- src/client/opamArg.ml
- src/client/opamClient.ml
- src/client/opamConfigCommand.ml
- src/client/opamConfigCommand.mli
- src/client/opamListCommand.ml
- src/client/opamMain.ml
- src/client/opamSwitchCommand.ml
- src/core/opamDirTrack.ml
- src/core/opamDirTrack.mli
- src/core/opamFilename.ml
- src/core/opamFilename.mli
- src/core/opamStd.ml
- src/core/opamSystem.ml
- src/core/opamSystem.mli
- src/format/opamPackage.ml
- src/repository/opamDownload.ml
- src/repository/opamDownload.mli
- src/repository/opamHTTP.ml
- src/solver/opamActionGraph.ml
- src/state/opamAction.ml
- src/state/opamAction.mli
- src/state/opamEnv.ml
- src/state/opamEnv.mli
- src/state/opamScript.mli
- src/state/opamSolution.ml
- src/state/opamSwitchState.ml
Most notably, cleanup of obsolete init code, many improved messages
and error handling; archive and source handling now go through our
process handling, improving parallelism; caching of prefix tracking.
> Various fixes, cleanup, interface and doc enhancements.

- .gitignore
- src/client/opamArg.ml
- src/client/opamArg.mli
- src/client/opamListCommand.ml
- src/client/opamListCommand.mli
- src/client/opamMain.ml
- src/format/opamTypesBase.ml
- src/format/opamTypesBase.mli
Thanks @Drup for the feedback!
> Improvements to `opam list` and `opam show`

- src/client/opamClient.ml
- src/client/opamClient.mli
- src/client/opamListCommand.ml
- src/client/opamListCommand.mli
- src/client/opamMain.ml
- src/client/opamRepositoryCommand.ml
- src/client/opamRepositoryCommand.mli
- src/client/opamSwitchCommand.ml
- src/client/opamSwitchCommand.mli
- src/format/opamFile.ml
- src/state/opamAction.ml
- src/state/opamFormatUpgrade.ml
- src/state/opamGlobalState.ml
- src/state/opamGlobalState.mli
- src/state/opamPackageVar.ml
- src/state/opamRepositoryState.ml
- src/state/opamRepositoryState.mli
- src/state/opamStateTypes.mli
- src/state/opamSwitchAction.ml
- src/state/opamSwitchAction.mli
- src/state/opamSwitchState.ml
- src/state/opamSwitchState.mli
Implementation is here but the UI is in progress
> Allow per-switch repository selection

- CHANGES
- Makefile
- opam-client.opam
- opam-core.opam
- opam-devel.install
- opam-devel.opam
- opam-format.opam
- opam-repository.opam
- opam-solver.opam
- opam-state.opam
- src/Makefile
- src/client/client.ocp
- src/client/opamListCommand.ml
- src/core/core.ocp
- src/format/format.ocp
- src/repository/repository.ocp
- src/solver/solver.ocp
- src/state/opamFormatUpgrade.ml
- src/state/opamSwitchState.ml
- src/state/state.ocp
- src/tools/tools.ocp
> Package the opam libs as several different packages

- src/client/opamMain.ml
Closes #2405, thanks for reporting!
> Fix man page section order

- src/tools/opam_format_upgrade.ml
With `--mirror <baseURL>`, will keep the repository intact but put the 2.0
mirror under `2.0/` and add redirect directives to the `repo` files, so that
both opam 1.2 and 2.0 will work seamlessly.
> 'opam admin upgrade-format': add mirror option

- doc/pages/Manual.md
- src/client/opamSolution.ml
- src/format/opamLexer.mll
- src/format/opamPackage.ml
- src/solver/opamActionGraph.ml
- src/solver/opamActionGraph.mli
- src/solver/opamSolver.ml
- src/solver/opamSolver.mli
Closes #2683
Anyone who had pinned packages with characters not in the restricted set: sorry about this.
> Restrict package names to a sane character set

- doc/pages/Manual.md
- src/format/opamFile.ml
- src/format/opamFilter.ml
- src/format/opamFilter.mli
- src/format/opamFormat.ml
- src/format/opamFormat.mli
- src/format/opamLexer.mll
- src/format/opamPackage.ml
- src/format/opamTypes.mli
- src/format/opamTypesBase.ml
- src/format/opamTypesBase.mli
- src/tools/opam_format_upgrade.ml
Also putting the manual and parser in sync. These are backports from #2702
> Sanitize package names and ident handling

- src/solver/opamSolver.ml
Reported at
https://gforge.inria.fr/tracker/index.php?func=detail&aid=20984&group_id=4395&atid=13808
> Work around memory explosion in dose's Algo.Depsolver.trim

- opam-devel.opam
- shell/opam_completion.sh
- shell/opam_completion_zsh.sh
- src/client/opamMain.ml
- update with new commands
- support auto completion of flag arguments (--root, --switch, etc.)
> Refresh and update bash completion script

- doc/pages/Manual.md
- src/client/opamListCommand.ml
- src/client/opamListCommand.mli
- src/client/opamMain.ml
- src/format/opamFile.ml
- src/format/opamFile.mli
- src/state/opamPath.mli
- src/state/opamSwitchState.ml
- src/state/opamSwitchState.mli
- src/tools/opam_format_upgrade.ml
This might be the missing piece we needed most from `provides:`, but without the problems that come with the other ones
> PROPOSAL: add 'conflict-class:'

- src/client/opamArg.ml
- src/client/opamClientConfig.mli
- src/state/opamStateConfig.ml
- src/state/opamStateConfig.mli
- src/state/opamSwitchState.ml
> Add `--ignore-constraints-on` to more easily test dependencies

- src/core/opamProcess.ml
- src/core/opamSystem.ml
- src/core/opamSystem.mli
- src/repository/opamDarcs.ml
- src/repository/opamGit.ml
- src/repository/opamHg.ml
- src/repository/opamRepository.ml
- src/repository/opamRepositoryBackend.ml
Apropos of yesterday's Slack discussion, a few changes to the handling of patch files during opam update.
> Logging improvements

- README.md
Such that the build result pages can be easily found.
> Add TravisCI and AppVeyor badges

- .gitattributes
- .gitignore
- Makefile
- configure
- configure.ac
- m4/ocaml.m4
- src/Makefile
- src/client/opamCommands.ml
- src/tools/opam_installer.ml
- src_ext/Makefile
A handful of hopefully non-controversial changes.
The .gitattributes file inclusion here is a lot easier than the OCaml one was, as there don't appear to have been any erroneous CRLF commits.
> Various tweaks

- src/client/opamAdminCommand.ml
- src/client/opamSolution.ml
- src/format/opamFile.ml
- src/format/opamFile.mli
- src/state/opamFormatUpgrade.ml
Fix translation of the 'test' and 'doc' dependency flags (to the 'with-test' and 'with-doc' variables)
Correctly translate dev-repo: to guess VCed repos
> Fixes to 'opam admin upgrade'

- src/repository/opamGit.ml
we don't use it internally, but it's best, in particular for `opam source --dev`.
> Document 'origin' of fetched git repos

- .gitignore
- Makefile
- doc/Makefile
- opam-repository.opam
- opam-solver.opam
- opam-state.opam
- src/Makefile
- src/client/client.ocp
- src/opam.ocp
- src/state/state.ocp
- src/tools/tools.ocp
Hopefully nothing controversial here, just some miscellaneous tidying and also a small fix to allow the docs to build on a Windows system.
> Misc tidying

- src/client/opamAdminCommand.ml
- src/client/opamArg.ml
- src/client/opamCommands.ml
- src/tools/opam_installer.ml
> Use const instead of pure

- doc/pages/Manual.md
- src/client/opamAdminRepoUpgrade.ml
- src/client/opamConfigCommand.ml
- src/format/opamFile.ml
- src/format/opamFile.mli
- src/format/opamFormat.ml
- src/format/opamFormat.mli
- src/state/opamFileTools.ml
- src/state/opamPackageVar.ml
and proposes a more useful format instead (unused yet)
NOTE: will need rebase
> This discards the unused `features:` field

- src/tools/opam_installer.ml
> Fixes for opam-installer

- .travis-ci.sh
- opam-solver.opam
- src/client/opamArg.ml
- src/client/opamClientConfig.mli
- src/solver/opamBuiltinMccs.ml.dummy
- src/solver/opamBuiltinMccs.ml.real
- src/solver/opamCudf.ml
- src/solver/opamCudf.mli
- src/solver/opamCudfSolver.ml
- src/solver/opamCudfSolverSig.ml
- src/solver/opamSolver.ml
- src/solver/opamSolverConfig.ml
- src/solver/opamSolverConfig.mli
- src/state/opamEnv.ml
- src_ext/Makefile
- tests/packages/P1-0.opam
(from which most of the fixes come)
Also adds solver timeouts
> This fixes some (built-in) solver cases, and uses latest ocaml-mccs

- .travis-ci.sh
- opam-solver.opam
- src/solver/opamBuiltinMccs.ml.real
- src_ext/Makefile
by tweaking the criteria (uses latest version of ocaml-mccs with
finer-grained criteria to do so without regression on the quality of the
results).
> Fix performance issue with the builtin solver on some requests

- doc/pages/Manual.md
- src/client/opamSolution.ml
- src/format/opamFile.ml
- src/format/opamFile.mli
Might be useful for saving snapshots of your opam root, for example
> Add pre- and post-session hooks

- Makefile
> Make sure `make install` installs opam-installer too

- CHANGES
- doc/pages/Manual.md
- opam-installer.opam
- shell/opam-bin-cache.sh
- src/client/opamAction.ml
- src/client/opamCommands.ml
- src/client/opamConfigCommand.ml
- src/client/opamListCommand.ml
- src/client/opamSolution.ml
- src/format/opamFilter.ml
- src/format/opamFormat.ml
- src/format/opamTypes.mli
- src/format/opamVariable.ml
- src/format/opamVariable.mli
- src/state/opamSwitchState.ml
- src/state/opamSwitchState.mli
- src/state/opamSysPoll.ml
Also improves variables so that they can expand to argument lists
Also provides additional variables to session hooks
> Allow automatic depext handling as a pre-session hook

- CHANGES
- src/client/opamArg.ml
- src/client/opamArg.mli
- src/client/opamAuxCommands.ml
- src/client/opamAuxCommands.mli
- src/client/opamCommands.ml
- src/client/opamPinCommand.ml
also improves handling of opam files during local switch creation a lot.
> Provide installation and local switch creation with locked opam files

- src/state/opamGlobalState.ml
> Fix spurious creation of the opamroot dir when unitialised

- shell/install.sh
- shell/opam_installer.sh
> Restore legacy 'opam_installer.sh'

- src/core/opamUrl.ml
- src/core/opamUrl.mli
> Add detection of git backend for `git@*` URLs

- src/repository/opamDownload.ml
Closes #3142. Thanks for reporting!
> Fix handling of `curl` command failing

- src/client/opamCommands.ml
> Fail on missing arg to `opam pin remove`

- src/client/opamArg.ml
- src/client/opamMain.ml
> Fix exit codes for errors on 'opam exec'

- .travis-ci.sh
- ISSUE_TEMPLATE.md
- doc/pages/FAQ.md
- shell/install.sh
- src/client/opamCommands.ml
- src/client/opamConfigCommand.ml
- src/client/opamConfigCommand.mli
- src/state/opamEnv.ml
- src/state/opamEnv.mli
- src/state/opamSwitchAction.ml
> No longer set OPAMROOT or OPAMSWITCH automatically as part or 'opam env'

- ISSUE_TEMPLATE.md
- src/state/opamUpdate.ml
Fixes #3183. Thanks for reporting!
> Fix overriding package meta overlay in some cases

- release/Dockerfile.in
- release/Makefile
- release/release.sh
- src/client/opamAuxCommands.ml
- src/client/opamPinCommand.ml
- src/client/opamPinCommand.mli
- src/state/opamFormatUpgrade.ml
> Fix version and availability issues on 'opam pin .'

- shell/bootstrap-ocaml.sh
- src_ext/Makefile
> make lib-ext: fix curl call and cache URL

- shell/bwrap.sh
Much nicer interface than using namespaces directly, and delegates the issues
of namespaces not generally being accessible as user.
> Add sandboxing wrapper based un "bubblewrap"

- admin-scripts/couverture.ml
- shell/bwrap.sh
- shell/opam-bin-cache.sh
- src/client/opamArg.ml
- src/client/opamClient.ml
- src/client/opamCommands.ml
- src/client/opamConfigCommand.ml
- src/client/opamListCommand.ml
- src/client/opamMain.ml
- src/client/opamSwitchCommand.ml
- src/core/opamFilename.ml
- src/core/opamFilename.mli
- src/format/opamSwitch.ml
- src/state/opamStateConfig.ml
- src/state/opamStateConfig.mli
This should handle cases like #3258 much more nicely
> Resolve '_opam' links to system switches

- doc/pages/Manual.md
- src/core/opamStd.ml
- src/state/opamGlobalState.ml
- src/state/opamPackageVar.ml
ref. #3240 (better fallback than before, but this doesn't fix OS detection on
nixOS)
> Fix undefined 'os' and related variables

- src/core/opamUrl.ml
I had to do some debugging on the URL handling a while ago, and tidied up and committed a few of the resulting changes...
> OpamURL regexp tweaks

- src/state/opamGlobalState.ml
This PR is related to issue #3282: sometimes wrong error message when opam root is missing and creation of the lock in an existing opam root.
Moved the check before the creation of the lock, like that no directory nor lock is created. And the good error message is displayed given the case.
> Accurate error message when opam root is missing

- doc/Makefile
> make doc: adjust for change between jbuilder beta19 and beta20

- doc/pages/FAQ.md
- src/client/opamCommands.ml
- src/client/opamInitDefaults.ml
- src/core/opamUrl.ml
- src/state/bwrap.sh
This PR contains:
- Change bwrap error
- Update FAQ to explain bwrap use
- update `--show-default-opamrc` to be launched at the beginning of init.
> A few fixes: bwrap, opamrc

- src/client/opamClient.ml
- src/format/opamFile.ml
- src/format/opamFile.mli
- src/state/bwrap.sh
- src/state/opamEnv.ml
Move message, remove comment, clean config
> A few fixes

- src/client/opamAuxCommands.ml
- src/client/opamAuxCommands.mli
- src/client/opamCommands.ml
- src/client/opamPinCommand.ml
> Fix `opam install . --deps-only` updating the pinning sets

- src/client/opamClient.ml
- src/state/bwrap.sh
> Improve message: bwrap & error missing tools

- src/state/opamSwitchState.ml
Currently, for `file-depends`, opam can detect when a file changes or when it is deleted. What it can't detect at the moment is when a file **appears**.
This alters the logic for `file-depends` so that if the checksum given is zero then the file is expected **not** to exist.
This allows, for example, the `ocaml-system` package to depend on the *lack* of `graphics.cmi` and so trigger a recompile if the user on Debian, for example, has `ocaml-nox` installed and then adds `ocaml`.
> Allow file-depends to include deleted files

- opam-solver.opam
- src/client/opamCommands.ml
- src/core/opamStd.ml
- src/solver/opamBuiltinMccs.ml.dummy
- src/solver/opamBuiltinMccs.ml.real
- src/solver/opamBuiltinMccs.mli
- src/solver/opamCudf.ml
- src/solver/opamCudfSolver.ml
- src/solver/opamCudfSolver.mli
- src/solver/opamCudfSolverSig.ml
- src/solver/opamSolverConfig.ml
- src/state/shellscripts/bwrap.sh
- src_ext/Makefile.sources
Not enabled by default, but this will make testing them a little easier.
> Add the newer mccs backends

- doc/pages/Tricks.md
- src/client/opamAuxCommands.ml
It would select the right compiler atoms, but ignore the additional
constraints...
> Better automatic compiler selection for local switches

- shell/install.sh
Not for merge until public announcement (planned tuesday)
> Bump the install.sh script to choose rc2 by default

- src/client/opamConfigCommand.ml
> Fix 'add --set-opam{switch,root}' nag on 'opam env'

- src/client/opamCommands.ml
- src/state/opamUpdate.ml
which would break some scripts
> Make sure 'opam init -n' does not ask questions

- src_ext/Makefile.sources
> Mccs checksum update

- src/client/opamCommands.ml
- src/core/opamSystem.ml
> Add tar handling: ignoring pax_global_header file

- src/core/opamHash.ml
Splits off the completed commit from #3349
> Make hash function LF/CRLF-agnostic

- shell/install.sh
> Install script: create directory if inexistant

- shell/install.sh
Not to merge until public announcement.
> Bump the install.sh script to choose rc3 by default 

- src/client/opamArg.ml
Signed-off-by: Anil Madhavapeddy <anil@recoil.org>
> fix some typos in man pages in the client

- src/state/shellscripts/bwrap.sh
- src/state/shellscripts/sandbox_exec.sh
> Avoid rogue stderr from sandboxing script (ccache handling)

- src/client/opamCommands.ml
> Do not clean sources of pinned packages

- src/client/opamClient.ml
> Remove -a include base packages to keep

- shell/bootstrap-ocaml.sh
See https://github.com/ocaml/opam/issues/3480#issuecomment-407433227 (and rest of thread)
> Remove GNUism from bootstrap-ocaml.sh

- .travis-ci.sh
- tests/Makefile
> Set user identity when creating a test Git repository

- shell/install.sh
Fix portability issue, openssl output is not the same over distrib
> install.sh: cut openssl 512 check output

- configure
- configure.ac
> configure: add patch & bunzip2

- src/client/opamCommands.ml
- src/client/opamListCommand.ml
- src/client/opamListCommand.mli
> list: add --silent option for scripts

- src/core/opamHash.ml
As seen in PR #3516, some macOS version don't provides `sha512` option in `openssl`, and don't exit with an error code in that case.
This PR adds as fallback mechanism the use of the internal library, as it is already the case when `openssl` is missing. 
Related to https://github.com/ocaml/opam-repository/pull/12613.
> hash: fallback to internal library in case of openssl error

- src/client/opamCommands.ml
Fixes #3557 and related to https://github.com/ocaml/opam-repository/issues/12677.
> Fix `opam list --external`

- doc/pages/Install.md
- doc/pages/Upgrade_guide.md
Closes #3556. cf https://github.com/ocaml/opam/issues/3556#issuecomment-424046471
> Update documentation for 2.0.0 and repo upgrade

- opam-solver.opam
- src_ext/Makefile.sources
> Update ocaml-mccs archive

- release/Makefile
- src_ext/Makefile
- src_ext/update-sources.sh
this is an alternative of #3574 /cc @dra27 @rneswold
> avoid sed -i, a GNU sed extension.  use > YYY.tmp and mv YYY.tmp YYY instead

- doc/pages/FAQ.md
- doc/pages/Install.md
- doc/pages/Manual.md
- doc/pages/Packaging.md
- doc/pages/Upgrade_guide.md
- src/core/opamFilename.mli
- src/state/opamFormatUpgrade.mli
https://github.com/ocaml/opam/pull/3554/commits/dea8ba4d9f21eb3731f062dcd0b382258775bc61 & https://github.com/ocaml/opam/pull/3554/commits/d53a7d90ce2b2ceec4faf4565044f1a0855a27ce related to PR #3540
https://github.com/ocaml/opam/pull/3554/commits/f276995d7ad17141c504d53749b3c89b833bb063 Related https://github.com/ocaml/opam/issues/2255#issuecomment-429168012
https://github.com/ocaml/opam/pull/3554/commits/c2962a9962d578d646561e05eb899696c931292c fixes #3612 
https://github.com/ocaml/opam/pull/3554/commits/af4b7ee4220b545b2bdbd2f5fe2ea2d922f8ab82 related to https://github.com/ocaml/opam/issues/3606#issuecomment-431146875
> Doc: update & fix

- doc/pages/Manual.md
> doc: fix show default opamrc option

- src/state/opamFormatUpgrade.ml
- src/state/opamFormatUpgrade.mli
Add function to upgrade opam file, including its auxiliary files: `descr`, `url`, `files/`.
> Format Upgrade

- src/client/opamClient.ml
- src/client/opamCommands.ml
> pin: upgrade pin depends on pinning

- src/client/opamAdminCommand.ml
- src/client/opamAuxCommands.ml
- src/core/opamFilename.mli
Some littles fixes
- opam admin: minimal refactor
- opam show: remove pin depends messages
> Some fixes

- src/state/opamPinned.ml
> `install --locked`: check consistency with opam file

- src/client/opamPinCommand.ml
To avoid lint warning 57 (descripton error) on 1.2 opam file pinning, add auxiliary files (descr, url) before linting —it was added after linting.
> pin: add aux files on pinning 1.2 opam files

- src/client/opamArg.ml
> Fix cmdliner error message on manpages

- doc/pages/Install.md
with new release & guix install info
> Doc: update install page

- src/client/opamCommands.ml
Reintroduce a more complete version of deprecated `--file` option with new option `--just-file`: permit to show opam files, their fields, without loading switch state.
Fixes #3721
> opam show: reintroduce file only information display

- src/state/opamFileTools.ml
> lint: warning error 47 on descr first line

- src/state/opamFileTools.ml
related to AltGr/Camelus/issues/27
> lint: add warning for with-test in run-test field

- doc/pages/Tricks.md
If anyone knows a better technique (e.g. how depexts can be integrated in the story, I didn't give it a thought) or has more details about the kind of selection the solver performs, please comment I'll update the PR with the information.
> tricks.md: Add a trick to install a lot of packages

- src/client/opamAdminCommand.ml
- src/format/opamPackage.ml
- src/format/opamPackage.mli
> Admin: add package selection to `add_hashes`

- src/state/opamRepositoryState.ml
> repo state cache: disable developer mode check

- src/client/opamCommands.ml
This is part of something else I've been working on, but seems to be a good feature in its own right, so I've separated it. This change includes the values of any configuration variables defined by the base/compiler packages of the switch in the output of `opam config report`. So you get output like this instead...
```
```
> Include config variables of base packages in opam config report

- src/client/opamAction.ml
- src/client/opamSolution.ml
- src/repository/opamRepository.ml
and some more explicit download error messages
> Fix bug in handling of download errors during actions processing

- doc/pages/Packaging.md
> doc: add need of gh ssh key registration for opam publish

- doc/pages/Packaging.md
fixes ocaml/opam-repository#13951
> docs/Packaging: adapt to 2.0.0 branch being master now

- src/state/opamEnv.ml
> opamenv: don't advice an infinite sourcing loop

- src/solver/opamActionGraph.ml
> Change symbol for download action

- shell/msvs-detect
Adds Visual Studio 2019 support, fixes operational problems with MSYS2.
> Update shell/msvs-detect to 0.4.0

- src/core/opamSystem.ml
`OpamSystem.resolve_command` already check permission; Propagate the information. 
related to #3649
> error diplays: differentiate command not found & permission denied

- src/client/opamPinCommand.ml
> pin-depends: update confirmation message to add skip option

- src/client/opamConfigCommand.ml
> fish: add colon for fish manpath

- .travis-ci.sh
- Makefile
- src/tools/opam_admin_top.ml
- src/tools/opam_admin_top.mli
Interface change in ca64cd9 not propagated from #3752
> Fix opam-admin.top

- src/client/opamListCommand.ml
> show: with `normalise` disable terminal width wrapping

- doc/pages/Distribution.md
Switch temporarily to list view
related to https://github.com/ocaml/opam/pull/3914#issuecomment-508885385 & ocaml/omd#188
> doc: distribution page

- .travis-ci.sh
- .travis.yml
This is the `master` version of #3934
> Ensure configure generates consistently

- doc/pages/Packaging.md
As per comment of @pictyeye in https://github.com/ocaml/opam-repository/pull/14678#discussion_r314073818
> Add -j jobs to the dune example command

- .travis-ci.sh
- shell/pkg-stats.sh
This used to be in 'opam admin stats', but was removed and didn't scale anymore anyway
> Add script for package number plotting

- src/state/opamEnv.ml
on sandbox script update, ask user in case it overwrites local modifications.
> sandbox: don't overwrite user's modifications

- src/state/shellscripts/bwrap.sh
- src/state/shellscripts/sandbox_exec.sh
> sandbox: add dune cache as rw

- .travis-ci.sh
- .travis.yml
> travis: add a stage to test opam1.2 upgrade

- doc/pages/Manual.md
- src/client/opamClient.ml
- src/format/opamFile.ml
- src/format/opamFile.mli
- src/state/opamStateConfig.ml
- src/state/opamSysPoll.ml
- src/state/opamSysPoll.mli
- src/state/opamUpdate.ml
> Determine jobs number at launch (state config launch)

- doc/pages/Install.md
The install command seems easier and more suitable.
https://linux.die.net/man/1/install
> Use install command instead of cp and chmod

- .travis-ci.sh
- .travis.yml
I guess it's time to check both.
> Add OCaml 4.08 and 4.09 in Travis

- .travis-ci.sh
- .travis.yml
- Makefile
Port some master travis related PRs
* #3998 adds ocaml 4.08.0 & 4.09.0
* #4015 adds an upgrade test
* #3971 fix repository commit for basic test
> Update travis on 2.0

- src/state/opamPackageVar.ml
> var: sort & clean pkg:depends

- README.md
- opam-installer.opam
- src/client/opamAuxCommands.mli
- src/core/opamParallel.mli
- src/core/opamSystem.mli
- add/fix some code documentation
- add 2.0 branch badges in the readme
- fix opam installer opam file
> Doc & installer fix

- src/client/opamSolution.ml
> fetch action: display error even if non verbose

- src/client/opamAdminCommand.ml
> admin: add constraint on depopts

- src/client/opamClient.ml
- src/client/opamSolution.ml
- src/client/opamSolution.mli
- src/core/opamDirTrack.ml
* Add precision of kind of tracking, and gather together kinds
* propagate `--force` on removal to changes revert
Related to #4091
> Tracking: log & force

- src/client/opamAdminCommand.ml
- src/client/opamAdminRepoUpgrade.ml
- src/client/opamArg.ml
- src/client/opamCommands.ml
- src/client/opamRepositoryCommand.mli
- src/core/opamUrl.ml
- src/core/opamUrl.mli
- src/state/opamFileTools.ml
- src/state/opamUpdate.ml
> url: catch Failure & propose a `parse_opt`

- src/core/opamDirTrack.ml
- src/core/opamDirTrack.mli
these are the remaining changes needed for orb (written by @rjbou, rebased on top of master). thanks.
> opamDirTrack: add string_of_changes (remaining changes for orb)

- src/client/opamSwitchCommand.ml
The trick is to only warn when no package in the invariant has a *direct*
dependency to a compiler. This way, "compiler selection packages" like `ocaml`
can be used as switch invariants, while packages further down the chain will
still warn.
> Don't warn on switch creation with 'ocaml' as invariant

- src/client/opamClientConfig.ml
> opam_init: handle log_dir in arg and as a env variable

- src/core/opamSystem.ml
This PR proposes to use pure ocaml code instead of calling to the `cp` or `install` programs in order to copy files around.
This is here restricted to invocations of `cp` that copy a single file, and invocations of `install`. Calls to `cp -r` are not modified.
The copy code itself has been taken as-is from dune (see `src/stdune/io.ml`).
I do realize that such a PR should be carefully reviewed, as it might result in subtle bugs if the new code differs from coreutils' `cp` on some corner-cases that occur in practice. 
Taking that into consideration, I still think it is a risk worth taking, considering the following:
I benchmarked an invocation of `opam install` on the following [317 packages](https://gist.github.com/Armael/2f75cd0a3114e4c94d88c5d6bee460ff).
Both invocations run from a fresh …
> Copy files using OCaml code instead of calling to cp or install

- Makefile
- configure
- configure.ac
- src/core/opamCompat.ml
- src/core/opamCompat.mli
- src/core/opamFilename.ml
- src/core/opamProcess.ml
- src/core/opamStd.ml
- src/core/opamStd.mli
- src/core/opamVersionCompare.mli
Revert adding `dune-profile`, it errors opam package install with opam
Fix the underlying errors and warnings
related #4100
> Fix unused module

- src/client/opamCommands.ml
in some case a `Not_found` could be triggered.
> Fix issue with `opam switch create . --deps`

- .gitattributes
- .github/scripts/changelog_checker
- .github/workflows/changelog_check.yml
- master_changes.md
The github action checks that the file `master_changes.md` has been updated in the PR.
Some files are concerned by this check (travis, appveyor, etc.)
> Add master changelog and github action check

- master_changes.md
- src/client/opamClient.ml
Fixes #3630 , see discussion there
> unpin: don't keep unpinned package version if it exists in repo

- master_changes.md
- src/client/opamClient.ml
> upgrade: fix atoms constraint dropped with `--all`

- doc/pages/Distribution.md
- doc/pages/Install.md
Hello.
This pull request updates install instruction on Arch Linux, as follows:
* Update link to latest one
* Change yaourt (not maintained) to yay
* Update current packaged version (2.0.7)
Thank you!
> doc: update how to install on Arch Linux

- master_changes.md
- src/core/opamConsole.ml
- tests/reftests.ml
- tests/reftests/show.test
& somes fixes
* disable chrono when timestamps are disabled
* Update reftests with envrionement variable definition as opam command prefix
~_Not merge before #4179_~
> Add show cram test

- .travis.yml
- src_ext/Makefile.sources
* add 2.0 cache in travis yml
* fix extlib url
> 2.0: travis fixes

- doc/pages/Install.md
- master_changes.md
> install page: add some badges

- master_changes.md
- src/client/opamArg.ml
- src/client/opamAuxCommands.ml
- src/client/opamCommands.ml
- src/core/opamUrl.ml
- src/core/opamUrl.mli
- src/format/opamFile.ml
- src/format/opamFormat.ml
- src/repository/opamGit.ml
- src/repository/opamRepository.ml
- src/state/opamFileTools.ml
> Fix path resolution with `file://` prefix

- master_changes.md
- src/solver/opamSolver.ml
This was a regression introduced with switch-invariants
> Fix Cudf generation for compat with external solvers

- master_changes.md
- src/core/opamStd.ml
- src/core/opamStd.mli
- src/solver/opamCudf.ml
For faster and more reliable response in case of conflicts.
Also, a few utility functions in the stdlib
> Check for a solution before calling the solver

- .travis-ci.sh
- .travis.yml
Playing ping-pong with commits between `master` and `2.0`, here are two commits from #4262 which need to go back on master
> Travis fixes

- master_changes.md
- src/client/opamSolution.ml
cf. https://github.com/ocaml/opam/pull/4269#issuecomment-660643529
> Fix not_found error on non-existing package

- .travis.yml
- shell/install.sh
> Bump dev install to `2.1.0~alpha2`

- .github/scripts/changelog_checker
- shell/install.sh
Download and check corresponding sha
> install script: add a download only option

- master_changes.md
- src/client/opamCommands.ml
> Support -d for opam lock

- master_changes.md
- src/repository/opamGit.ml
> Git empty repository (just initialised) error message

- shell/install.sh
> install.sh: add 2.1.0-beta binaries

- master_changes.md
- src/client/opamConfigCommand.ml
- src/client/opamRepositoryCommand.ml
- src/client/opamSolution.ml
- src/core/opamCached.ml
- src/core/opamCached.mli
- src/format/opamPath.ml
- src/format/opamPath.mli
- src/state/opamEnv.ml
- src/state/opamEnv.mli
- src/state/opamRepositoryState.ml
- src/state/opamSwitchAction.ml
- src/state/opamSwitchState.ml
- src/state/opamSwitchState.mli
* make repo/switch loading a bit faster with more caching and better
cache usage
* avoid loading it altogether when possible for 'opam exec' calls
> A bunch of small optimisations to reduce the startup cost

- doc/pages/Install.md
Currently, there is no mention of Windows on the install page. Add a note saying we are looking for help with Opam on Windows.
> Add note about Windows

- shell/install.sh
> install.sh: add 2.1.0-beta2 binaries

- master_changes.md
- src/solver/opamActionGraph.ml
> Removal postponing: protect against addition of cycles

- master_changes.md
- src/client/opamPinCommand.ml
> Urlpin format upgrade

- doc/pages/Manual.md
- master_changes.md
- src/client/opamSolution.ml
> Allow pre/post-session-commands hook to print to the console

- master_changes.md
- opam-client.opam
- src/client/opamPinCommand.ml
> opam-client lib: fix dependency constraints for cmdliner, extlib

- Makefile
- master_changes.md
> Makefile: Add missing spaces between DUNE_ARGS and DUNE_PROMOTE_ARGS

- doc/pages/Distribution.md
- master_changes.md
> doc/Distributions: Updates regarding nicoo

- doc/pages/Usage.md
- master_changes.md
> doc: specify url syntax in opam pin usage

- master_changes.md
- src/client/opamSolution.ml
> Clean version pinned build directory

- master_changes.md
- src/state/opamFileTools.ml
> Lint add W66: check that strings in filtered package formula can resolve to bool

- master_changes.md
- src/client/opamClient.ml
- src/client/opamSwitchCommand.ml
- src/core/opamFilename.ml
- src/core/opamFilename.mli
- src/state/opamRepositoryState.ml
- src/state/opamRepositoryState.mli
> Add an update advise for `opam switch create'

- master_changes.md
- src/client/opamAction.ml
> Add logging information about patches and substitutions application

- master_changes.md
- src/client/opamCommands.ml
This is not strictly an opam command, but it's useful to have here. Closes
> Add `opam update --depexts` to replace `opam depext -u`

- master_changes.md
- src/client/opamSolution.ml
> action: run switch pre/post session hooks

- .gitattributes
- configure
- configure.ac
- master_changes.md
> Advertise make compiler in configure

- release/Makefile
- shell/install.sh
(merge once release published)
Also adjusts the release script for the actual build used on arm64
> Upgrade install.sh for new beta

- doc/pages/Manual.md
- master_changes.md
~Should be merged after https://github.com/ocaml/opam/pull/4492~
> Document the default build environment variables

- master_changes.md
- opam-client.opam
- opam-solver.opam
While waiting for https://github.com/ocaml/opam/pull/4515
> Update the dependency constraints

- master_changes.md
- src/client/opamArg.ml
- src/client/opamArg.mli
- src/client/opamClient.ml
- src/client/opamClient.mli
- src/client/opamCommands.ml
- src/client/opamPinCommand.ml
- src/client/opamPinCommand.mli
- src/state/opamPinned.ml
- src/state/opamPinned.mli
> Don't look for lock file of pin depends packages

- master_changes.md
- src/state/opamFileTools.ml
> lint: W59 & E60 handles conf flag fix

- master_changes.md
- src/client/opamArg.ml
- src/client/opamClientConfig.ml
- src/state/opamStateConfig.ml
> Add environment variables OPAMASSUMEDEPEXTS, OPAMNODEPEXTS

- master_changes.md
- tests/reftests/dune.inc
- tests/reftests/pat-sub.test
~To be merged after #4504 i~
As tests are frozen until it is merged, this PR is open to agreggate all new tests
> Some tests

- .github/scripts/hygiene.sh
- .github/scripts/main.sh
- master_changes.md
and add some debug to trace the weird solver timeout error
> Github CI : (macos) fixes

- master_changes.md
- src/client/opamClient.ml
> With `--deps-only`, set direct dependencies as root by default

- .github/workflows/ci.yml
- master_changes.md
Both caches depend on the compiler version!
> More CI caching

- .gitattributes
Simple quality of life improvement.
Inspired by https://twitter.com/dbrgn/status/1381547785116344323
> Always avoid merge conflicts in master_changes.md

- master_changes.md
- src/format/opamFile.ml
- tests/reftests/upgrade-format.test
> Fix empty field rewriting with preserved format

- master_changes.md
- src/client/opamArg.ml
- src/client/opamArgTools.ml
- src/client/opamArgTools.mli
- tests/reftests/cli-versioning.test
- tests/reftests/dune.inc
- tests/reftests/switch-creation.test
like `--color [always|never|auto]`
> Cli versioning for enums in flags with enum

- doc/pages/FAQ.md
- master_changes.md
This FAQ is quite cool. It even mentions nfsopam ! :)
> some typo in the FAQ

- master_changes.md
- src/client/opamClient.ml
- tests/reftests/init.test
Aaaah, default values for undefined variables <3
Fixes #4640
> Don't be too optimistic about undefined availability of compilers

- master_changes.md
- src/client/opamCommands.ml
> Fix typo in switch creation docs

- master_changes.md
- src/client/dune
- src/client/opamCommands.ml
- src/core/opamVersion.ml
- src/core/opamVersion.mli
- src/state/opamFormatUpgrade.ml
> Build release tags as release tarballs

- .github/scripts/main.sh
- src/client/dune
As for #4665, but without the new API in `OpamVersion` and with a more devilish PR number 😈
> Build release tags as release tarballs [2.0 version]

- master_changes.md
- src/state/opamFormatUpgrade.ml
- src/state/shellscripts/env_hook.sh
- src/state/shellscripts/env_hook.zsh
- tests/reftests/opamroot-versions.test
otherwise shell hooks try to `eval()` it 8(
> Send the 'opam root layout update' message to stderr

- Makefile
- doc/pages/Install.md
- master_changes.md
- opam-devel.opam
- shell/bootstrap-ocaml.sh
- tests/reftests/dune
- tests/reftests/dune.inc
- tests/reftests/gen.ml
* make cold: add a hint for missing `openssl`
* opam-devel.opam: Remove test field as they need the network
* tests: dune files compatible with dune < 2.0
> Some build fixes

- .github/scripts/main.sh
> GH: fix opam pinning for opam-rt

- master_changes.md
- opam-admin.opam
- opam-client.opam
- opam-core.opam
- opam-devel.opam
- opam-format.opam
- opam-installer.opam
- opam-repository.opam
- opam-solver.opam
- opam-state.opam
- opam.opam
Backport fixes from https://github.com/ocaml/opam-repository/pull/18869
> Add missing license field and lower-bound constraint to the opam files

- opam-core.opam
Backport of https://github.com/ocaml/opam/pull/4714
> [2.1 backport] Add missing lower-bound constraint

- .github/scripts/ocaml-cache.sh
- .github/scripts/preamble.sh
- .github/scripts/solvers.sh
- .github/workflows/ci.yml
- master_changes.md
- src/client/opamArg.ml
- src/solver/opamBuiltinZ3.ml.real
- src/solver/opamSolverConfig.ml
- src/solver/opamSolverConfig.mli
> Z3 compile fix & tests

- .github/scripts/ocaml-cache.sh
- master_changes.md
> gha: fix ocaml link

- CHANGES
- src/state/opamSysInteract.ml
> Set `DEBIAN_FRONTEND=noninteractive` for unsafe-yes

- Makefile
Extracts the Dune 2.9 part of #4752 for 2.0.9
> [2.0] Fix compatibility with dune 2.9

- master_changes.md
- src/client/opamCliMain.ml
- src/client/opamCommands.ml
- src/client/opamConfigCommand.ml
- src/format/opamFile.ml
- src/state/opamFormatUpgrade.ml
- src/state/opamFormatUpgrade.mli
- src/state/opamGlobalState.ml
- src/state/opamStateConfig.ml
- src/state/opamStateConfig.mli
- src/state/opamSysInteract.ml
- tests/reftests/dune
- tests/reftests/opamroot-versions.test
- tests/reftests/run.ml
Aggregate PRs #4715 #4750 #4756 #4758
> Port 2.1 error free newer/older opam root handling + alpine fix

- .github/scripts/hygiene.sh
- shell/install.sh
> Update install script with 2.0.9 & 2.1.0

- master_changes.md
- src/client/opamConfigCommand.ml
- tests/reftests/var-option.test
> Fix typo in error message for opam var

- master_changes.md
- src/state/opamSysInteract.ml
> depexts/brew: Add support for casks and full-names

- master_changes.md
- src/state/opamSysInteract.ml
partially fix #4759
Use `pacman -Si` to get all package information
> depexts on archlinux: virtual packages detection

- configure
- configure.ac
- m4/ocaml.m4
- master_changes.md
- opam-devel.opam
I didn't have spdx_licenses in my opam switch or the right version of dose3!
> Overhaul configure checks

- doc/pages/Manual.md
- master_changes.md
> Fix span tags in manual

- master_changes.md
- src/repository/opamGit.ml
> git: disable colored output

- doc/pages/Manual.md
- master_changes.md
> Document the 'avoid-version' package flag

- doc/pages/Manual.md
- master_changes.md
> Document custom licenses

- master_changes.md
- src/client/opamCLIVersion.ml
- src/core/opamCompat.ml
- src/core/opamCompat.mli
- src/core/opamFilename.ml
- src/core/opamHash.ml
- src/core/opamStd.ml
- src/core/opamStd.mli
- src/core/opamUrl.ml
- src/core/opamVersion.ml
- src/crowbar/opamFilename_crowbar.ml
- src/crowbar/opamHash_crowbar.ml
- src/crowbar/opamUrl_crowbar.ml
- src/crowbar/opamVariable_crowbar.ml
- src/format/opamSysPkg.ml
- src/format/opamVariable.ml
> Add non polymorphic comparison functions to some modules

- .github/workflows/main.yml
- appveyor.yml
- master_changes.md
- src_ext/Makefile
> bootstrap: update ocaml version

- .github/workflows/ci.yml
- appveyor.yml
- src_ext/Makefile
> Backport #4927 on 2.1

- master_changes.md
- src/client/opamArg.ml
- src/client/opamArg.mli
- src/client/opamCommands.ml
> Backport #4908 on opam 2.1

- master_changes.md
- src/core/opamSystem.ml
If file exists check magic number, otherwise check extension
> System: homogeneise is_archive tar & zip

- master_changes.md
- src/client/opamAdminRepoUpgrade.ml
> Fix admin repo upgrade internal error

- master_changes.md
- src/client/opamCommands.ml
- src/client/opamConfigCommand.ml
- src/client/opamConfigCommand.mli
- tests/reftests/env.test
> Add opam exec --no-switch

- master_changes.md
- src/client/opamSolution.ml
- tests/reftests/opamrt-reinstall.test
- tests/reftests/upgrade-format.test
Fixes https://github.com/ocaml/opam/issues/4925
> Make the status of pinned packages more explicit

- master_changes.md
- tests/reftests/run.ml
Alternative to https://github.com/ocaml/opam/pull/5007
> reftest: Escape regexps characters in string replacements primitives

- Makefile
- master_changes.md
- src/client/opamCommands.ml
- src/format/opamPath.ml
- src/format/opamPath.mli
- src/state/opamSwitchAction.ml
- tests/reftests/clean.test
- tests/reftests/dune.inc
fix #4831
See test file for behaviour
> Add clean `--untracked`

- dune-project
- master_changes.md
- opam-admin.opam
- opam-client.opam
- opam-core.opam
- opam-devel.opam
- opam-format.opam
- opam-installer.opam
- opam-repository.opam
- opam-solver.opam
- opam-state.opam
- opam.opam
- tests/cram/unix/dune
- tests/cram/unix/list.t
- tests/reftests/clean.test
> Add some unix-only cram tests to test for #4216 before fixing it

- master_changes.md
- src_ext/patches/mccs.common/0001-Add-lgcc_s-on-Cygwin.patch
Split off from #5055 so that CI there should pass.
> Patch mccs for Cygwin32 in lib-ext

- master_changes.md
- tests/reftests/assume-built.test
- tests/reftests/dune.inc
- tests/reftests/inplace.test
- tests/reftests/shared-fetch.test
- tests/reftests/working-dir.test
It is fixed with #4879 #5082 #5083
> Add working dir, inplace, and assume-built tests

- .github/scripts/depexts/generate-actions.sh
- .github/workflows/ci.ml
- .github/workflows/depexts.yml
- .github/workflows/main.yml
- .github/workflows/scripts.yml
- master_changes.md
& constraint github actions path changes trigger only for files of the given job
> GHA: add gentoo depext test

- .github/scripts/main/solvers.sh
- master_changes.md
> GHA: upgrade packages for solver jobs

- shell/install.sh
* Add `--dowload-only` in help message
* Resolve `~` for bindir using `eval` (fix #3927)
> Some fixes in install.sh

- master_changes.md
- src/client/opamAuxCommands.ml
- tests/reftests/lock.test
* Fix pinned status display in action list
* Fix repin of locked pins when no changes is detected
fix #4313
> Fix lock behaviour on pinning

- master_changes.md
- src/client/opamAuxCommands.ml
- tests/reftests/lock.test
> Fix `opam install <filename>` with lock file

- master_changes.md
- src/state/opamSysInteract.ml
> Increase verbose logging of depext commands

- doc/pages/Distribution.md
- master_changes.md
I'm not the package maintainer, but I've added an entry for the current LTS version of Ubuntu and removed the obsolete ones.
Please let me know if I should squash these changes into a single commit or something.
> Docs: Update package versions for Ubuntu in distributions list

- README.md
- master_changes.md
> adjust opam-publish link

- README.md
- master_changes.md
> Fix link to developer manual

- master_changes.md
- tests/reftests/working-dir.test
> Add some tests showing how --working-dir behaves on updated dependency constraints

- master_changes.md
- src/client/opamAction.mli
> Update `OpamAction.install_package` documentation

- CHANGES
- master_changes.md
> 2.1.3 changes

- CHANGES
- shell/bootstrap-ocaml.sh
> Backport #5223 in 2.1.3

- CHANGES
- Makefile
- master_changes.md
- src/client/opamClient.ml
- src/core/opamProcess.ml
- src/repository/opamDarcs.ml
- src/repository/opamGit.ml
- src/repository/opamHg.ml
- src/repository/opamVCS.ml
- src/repository/opamVCS.mli
- src/state/opamSwitchState.ml
- tests/reftests/conflict-resto.test
- tests/reftests/dune.inc
- tests/reftests/gen.ml
- tests/reftests/list.unix.test
- tests/reftests/opamrt-big-upgrade.test
- tests/reftests/pin.unix.test
- tests/reftests/working-dir.test
> Backport PR to 2.1.3

- master_changes.md
- shell/bootstrap-ocaml.sh
Suggestion from @hannesm in https://github.com/ocaml/opam/pull/5230#issuecomment-1207383541
> Improve warning wording if curl/wget is not present

- master_changes.md
- tests/reftests/working-dir.test
Suggested by @AltGr in https://github.com/ocaml/opam/pull/5252#issuecomment-1228402148
> Fix the reftests under some heavy parallel hardwear

- master_changes.md
- src/state/shellscripts/bwrap.sh
> Fix sandbox ccache symlink resolution

- master_changes.md
- src/client/opamCommands.ml
- src/client/opamConfigCommand.ml
- tests/reftests/var-option.test
fix #5279 
And remove some dead code
> Var: catch an package not found error and print skipping message

- master_changes.md
- src/state/opamUpdate.ml
- src/state/opamUpdate.mli
- tests/reftests/repository.test
Sequel of #5043 : if the is no changes in all updated repositories, do not write the unmodified repos-config & cache.
> Repository update with no changes: cache part

- master_changes.md
- src/client/opamArg.ml
Noticed in https://github.com/ocaml/opam/issues/5283
> Finer definition of the --ignore-constraints-on documentation

- .github/workflows/ci.ml
- .github/workflows/main.yml
- master_changes.md
- release/Makefile
- src_ext/Makefile
> Upgrade the bootstrap compiler to OCaml 4.14.0

- doc/pages/Manual.md
- master_changes.md
- src/client/opamAction.ml
- src/client/opamAction.mli
- src/client/opamArg.ml
- src/client/opamClient.ml
- src/client/opamClientConfig.mli
- src/client/opamCommands.ml
- src/client/opamListCommand.ml
- src/client/opamListCommand.mli
- src/client/opamLockCommand.ml
- src/client/opamSolution.ml
- src/client/opamTreeCommand.ml
- src/format/opamFilter.ml
- src/format/opamFilter.mli
- src/state/opamFileTools.ml
- src/state/opamPackageVar.ml
- src/state/opamPackageVar.mli
- src/state/opamPinned.ml
- src/state/opamStateConfig.ml
- src/state/opamStateConfig.mli
- src/state/opamSwitchState.ml
- src/state/opamSwitchState.mli
- tests/reftests/dune.inc
- tests/reftests/with-dev-setup.test
> Rename `--with-tools` to `--with-dev-setup`

- master_changes.md
- tests/reftests/opamroot-versions.test
> reftests: generalise opam root version test

- master_changes.md
- tests/reftests/opamroot-versions.test
* add repos-config file check
* add some comments
* add some global state rw commands
* update generator to handle repos-config and clean root
* fix --set-default that update config (instead of just updating repo config)
* add repos-config rw loading for last update
> reftests: some opam root version upgrade & fixes

- master_changes.md
- src/client/opamConfigCommand.ml
- tests/reftests/var-option.test
> Make archive-mirrors modifiable via opam config

- master_changes.md
- src/client/opamCommands.ml
- src/core/opamFilename.ml
- src/core/opamFilename.mli
- tests/reftests/repository.test
> repository: on set-url fetch failure (sync or file error), revert url change an fetch old one

- shell/install.sh
> shell/install.sh: set 2.1.4 as the latest version

- CHANGES
This step of the release process seem to have been forgotten since 2.1.0~rc2
> Add missing changelog entries from the 2.1 branch on master

- .github/scripts/main/archives-cache.sh
- .github/scripts/main/create-ocaml-cache.sh
- .github/scripts/main/hygiene.sh
- .github/scripts/main/legacy-cache.sh
- .github/scripts/main/legacy.sh
- .github/scripts/main/main.sh
- .github/scripts/main/ocaml-cache.sh
- .github/scripts/main/opam-bs-cache.sh
- .github/scripts/main/opam-rt.sh
- .github/scripts/main/reftests.sh
- .github/scripts/main/solvers.sh
- .github/scripts/main/test.sh
- .github/scripts/main/upgrade.sh
- .github/scripts/scripts/hygiene.sh
- .github/workflows/ci.ml
- .github/workflows/main.yml
- master_changes.md
The Z3 solvers job has been failing on macOS for the last couple of weeks, presumably because of a change in the runner's configuration.
> Assume availability of Python 3 on GHA runners

- .github/scripts/main/hygiene.sh
- .github/workflows/main.yml
- master_changes.md
- src_ext/Makefile.sources
Upgrades to Version 3.19 of the SPDX License List
> Upgrade spdx_licenses to 1.2.0

- master_changes.md
- src_ext/Makefile.sources
Fixes https://github.com/ocaml/opam/issues/5339
> Upgrade the vendored sha to 1.15.4

- master_changes.md
- src/format/opamFile.ml
- src/state/opamFormatUpgrade.ml
- tests/reftests/init.test
- tests/reftests/opamroot-versions.test
> Upgrade root version to 2.2~alpha

- .github/scripts/main/main.sh
- dune-project
- master_changes.md
- opam-core.opam
- src/client/dune
- src/client/opamTreeCommand.ml
- src/core/dune
- src/format/dune
- src/repository/dune
- src/solver/dune
- src/tools/dune
- tests/reftests/dune
Split off from #4770 - won't build until that's merged!
> Use (implicit_transitive_deps false) in CI

- .github/workflows/changelog_check.yml
- .github/workflows/scripts.yml
- master_changes.md
Noticed this. This doesn't have any impact on us and is purely internal for the checkout action.
> gha: update to checkout@v3

- master_changes.md
- src/state/opamEnv.ml
> Fix opam init menu default

- master_changes.md
- src/state/opamFileTools.ml
- tests/reftests/lint.test
- tests/reftests/lock.test
> Fix URL in warning 62

- shell/install.sh
> install.sh: set last version to 2.1.5

- AUTHORS
- CHANGES
- master_changes.md
- opam-admin.opam
- opam-client.opam
- opam-core.opam
- opam-devel.opam
- opam-format.opam
- opam-installer.opam
- opam-repository.opam
- opam-solver.opam
- opam-state.opam
- opam.opam
- src/client/opamArg.ml
* Fixes in CHANGES
* Fix @kit-ty-kate email
* Fix heading in manpage
> Some fixes in changes & authors

- master_changes.md
- release/Makefile
- release/release.sh
- shell/install.sh
Both of them are now present in the multiarch/alpine images: https://hub.docker.com/r/multiarch/alpine
> release script: Add ppc64le and s390x support

- master_changes.md
- src/client/opamCommands.ml
- tests/reftests/lint.test
> Fix extra-files handling on linting

- release/Makefile
- release/readme.md
- release/release.sh
Following changes from https://gitlab.com/kit-ty-kate/qemu-base-images
Related to https://github.com/ocaml/opam/pull/5616/files#r1273867852 for the change in the Makefile
Tested on top of https://github.com/ocaml/opam/pull/5383
> Update the release script according to the opam 2.2.0~alpha3 release process

- master_changes.md
- src/client/opamSwitchCommand.ml
> switch: more precise message for fatal error on switch creation

- .github/workflows/ci.ml
- .github/workflows/main.yml
- configure
- configure.ac
- master_changes.md
- opam-solver.opam
- src_ext/Makefile.sources
Opening this PR in prevision of the release.
See https://github.com/ocaml-opam/ocaml-mccs/pull/50 for detail of the fix.
> Upgrade to mccs.1.1+17

- master_changes.md
- src/state/opamEnv.ml
- tests/reftests/dune.inc
- tests/reftests/init-scripts.unix.test
- tests/reftests/init-scripts.win32.test
This PR is an off-shoot from #5802. Same two first commits, to make it easier to review and produce a cleaner history
> Shell integration: Test if file exists before sourcing in fish + powershell

- master_changes.md
- src/format/opamFile.ml
- tests/reftests/init.test
- tests/reftests/opamroot-versions.test
- tests/reftests/swhid.unix.test
- tests/reftests/var-option.test
See https://github.com/ocaml/opam/issues/5720
> Disable Software Heritage fallbacks by default

- master_changes.md
- tests/bench/bench.ml
> Benchmark opam install --deps-only of an already installed package

- release/Dockerfile.in
- release/Makefile
- release/readme.md
Matching what is in the Dockerfile and what is in the Makefile to make it compile on macOS for the 2.1 branch
> Release script fixes and improvements

- .github/workflows/ci.ml
- .github/workflows/depexts.yml
- .github/workflows/main.yml
- master_changes.md
- release/Makefile
- src_ext/Makefile
Partially f.i.x.e.s https://github.com/ocaml/opam/issues/5956
> Upgrade the vendored OCaml compiler to 4.14.2

- master_changes.md
- src/core/opamStd.ml
Some PRs are bigger than others!
> Harden OpamStd.Sys.check_dll

- master_changes.md
- src/core/opamConsole.ml
> Fix OpamConsole.menu > 9 options

- master_changes.md
- release/readme.md
- src/format/opamFile.ml
- src/state/opamFormatUpgrade.ml
- tests/reftests/opamroot-versions.test
> 2.2: Final 2.2 opam root bump

- master_changes.md
- src/client/opamCliMain.ml
- src/client/opamClientConfig.ml
- src/client/opamCommands.ml
- src/state/opamStateConfig.ml
- src/state/opamStateConfig.mli
> 2.2:Restore signature of OpamStateConfig.opamroot

- master_changes.md
- src/state/opamSysInteract.ml
> 2.2: Adjust common flags passed to Cygwin setup

- master_changes.md
- opam-core.opam
> 2.2: Synchronise  opam-core opam file with opam repo one

- master_changes.md
- src/solver/opamCudf.ml
- tests/reftests/dune.inc
- tests/reftests/empty-conflicts-007.test
> Package name encoding in conflict message

- doc/pages/Install.md
- master_changes.md
> Documentation: remove the ppa from the installation instructions on Ubuntu

- master_changes.md
- release/Dockerfile.in
- release/Makefile
- release/readme.md
Backports https://github.com/ocaml/opam/pull/6084
> [2.2 backport] Remove opam 2.1 support from the release script

- .github/scripts/depexts/generate-actions.sh
- master_changes.md
> [2.2] GHA: Several fixes on depexts workflow

- README.md
- master_changes.md
> doc: fix pinning instruction in readme

- master_changes.md
- tests/bench/bench.ml
Could be useful to benchmark https://github.com/ocaml/opam/pull/6122 and the feature in general
> Benchmark opam install --check

- .github/workflows/ci.ml
- .github/workflows/depexts.yml
- .github/workflows/main.yml
- master_changes.md
> [2.2] GHA: bump version of actions

- release/readme.md
Requires https://github.com/ocaml-opam/opam-publish/pull/161
> release: show the right opam-publish command to run

- master_changes.md
- release/Dockerfile.in
Backports https://github.com/ocaml/opam/pull/6175
> [2.2 backport] release: fix the docker phase

- release/Dockerfile.in
Backports https://github.com/ocaml/opam/pull/6175
> [2.0 backport] release: fix the docker phase

- master_changes.md
- src/client/opamConfigCommand.ml
- tests/reftests/var-option.test
ask user what they want to do
fix #4730
> Warn when setting a variable that shadow an option

- .github/scripts/main/main.sh
- Makefile
- master_changes.md
- release/Dockerfile.in
- release/Makefile
Suggested in https://github.com/ocaml/opam/pull/6204#discussion_r1771256137
> Simplify the making of stripped binaries by introducing the 'make opam-stripped' target

- master_changes.md
- src/state/opamSwitchState.mli
- tests/reftests/dune
- tests/reftests/readme.md
- tests/reftests/reftests.test
- tests/reftests/run.ml
> [2.3] Reftest: add opam-cache printing command

- doc/pages/Install.md
- master_changes.md
- release/Dockerfile.in
- release/Makefile
- release/readme.md
- release/release.sh
> Release script improvements after 2.3.0~beta1

- release/Makefile
- release/release.sh
Forward-ported PR of https://github.com/ocaml/opam/pull/6258 to master
> Release script: Add NetBSD/x86_64 to the build matrix

- release/readme.md
- release/windows.md
Backport of https://github.com/ocaml/opam/pull/6264 to the 2.3 branch
> [2.3 backport] Reorder the release steps

- master_changes.md
- src/client/opamInitDefaults.ml
- src/repository/opamRepositoryConfig.ml
This unifies the fetching behaviour across platforms
> Prefer curl over any other download tools on every systems, if available

- .github/dependabot.yml
- .github/workflows/changelog_check.yml
- .github/workflows/ci.ml
- .github/workflows/main.yml
- .github/workflows/scripts.yml
- Enable Dependabot to automate GitHub Actions updates
- Update GitHub Actions
> Update GitHub Actions

- master_changes.md
- src_ext/Makefile.sources
> Upgrade the vendored spdx_licenses to 1.3.0

- doc/pages/Manual.md
- master_changes.md
This is fairly hard to explain. Does anyone know a better way to explain it?
cc @christinerose
> Add an explanation of how plugins work to the manual

- master_changes.md
- src/client/opamAction.ml
- src/client/opamAdminCommand.ml
- src/client/opamListCommand.ml
- src/client/opamPinCommand.ml
- src/client/opamSwitchCommand.ml
- src/repository/opamRepository.mli
- src/repository/opamRepositoryBackend.ml
- src/repository/opamRepositoryBackend.mli
- src/repository/opamVCS.ml
> Change the type returned by `OpamRepository.revision` from version to string

- .github/workflows/depexts.yml
- master_changes.md
> GHA: Unbreak the depexts workflow by updating the opam-repository hash

- master_changes.md
- src/client/opamAuxCommands.ml
- tests/reftests/simulated-pin.test
> Fix simulated pinned packages reinstall trigger

- master_changes.md
- release/Makefile
Applies https://github.com/ocaml/opam/pull/6526 to the release script
> Release: Call the opam configure script with  on Windows

- master_changes.md
- tests/reftests/dune.inc
- tests/reftests/opam-repo-ci.test
Test for https://github.com/ocurrent/opam-repo-ci/issues/441
queued on
> reftest: add test for opam repo ci reinstall workflow

- master_changes.md
- src/format/opamFormula.ml
- src/format/opamPackage.ml
- tests/reftests/show.test
Follow up to #6638
~Queued on #6638~
related to #6396
> Handle non-displayable characters when detecting an erroneous package name or version

- master_changes.md
- src/client/opamSwitchCommand.ml
- src/core/opamHash.ml
- src/core/opamHash.mli
Extracted from https://github.com/ocaml/opam/pull/6625
> Add OpamHash.check_string

- master_changes.md
- tests/reftests/tree.test
Fixes https://github.com/ocaml/opam/issues/6543
> Add a test showing the behaviour of opam tree on local packages that happen to be already pinned

- master_changes.md
- src/client/opamAction.ml
- src/client/opamCommands.ml
- tests/reftests/extrafile.test
- tests/reftests/extrasource.test
> Pretty printing of some error for opam source & build actions
