ocaml/opam

src/solver/opamSolver.ml
Doesn't cause trouble yet on opam-repo, but I managed to get a stack overflow
at this call with my experimental compilers-to-packages repo (that adds lots
of direct dependencies to "ocaml")
Better workaround it before it bites us, until the issue is fixed. Upstream
bug:
https://gforge.inria.fr/tracker/index.php?func=detail&aid=18453&group_id=4395&atid=13808
=> (transient) workaround Dose stack-overflow

src/client/opamArg.ml, src/client/opamArg.mli, src/core/opamMisc.ml
Ref: #1447 (waiting for reviews and tests before closing)
=> Better shell initialisation.

doc/pages/Packaging.md, doc/pages/Usage.md
The typos in Usage.md were notified by @herbelin . The minor changes in Packaging.md are just slight reformulations.
=> fix a few typos in the documentation

src/client/opamAction.ml, src/core/opamSystem.ml, src/core/opamSystem.mli
i.e. let the command fail normally rather than raise an exception
=> Don't raise on command not found in build/remove scripts

src/core/opamParallel.ml, src/core/opamParallel.mli
Not used at the moment but will come in very handy for better handling
of the 'install' field.
=> OpamParallel: allow to specify mutually exclusive jobs

admin-scripts/compilers-to-packages.ml, admin-scripts/to_1_1.ml, opam-lib.install, src/client/opamAction.ml, src/client/opamClient.ml, src/client/opamConfigCommand.ml, src/client/opamPinCommand.ml, src/client/opamSolution.ml, src/client/opamState.ml, src/client/opamState.mli, src/core/opamFile.ml, src/core/opamFile.mli, src/core/opamFilter.ml, src/core/opamFilter.mli, src/core/opamFormat.ml, src/core/opamFormat.mli, src/core/opamTypes.mli, src/core/opamTypesBase.ml, src/core/opamTypesBase.mli, src/core/opamVariable.ml, src/core/opamVariable.mli
The intent is to have this included in 1.2.1 as a "beta" feature, i.e. not
allowed yet in the repository, but there for people to test (and maybe for
forwards-compat, in case it stays as is, but I wouldn't count on it).
`opam lint` will warn about this.
=> Beta version of the 'features' field

src/client/opamSwitchCommand.ml
Fixes the second point in #1984
=> No env warnings with print_short

src/core/opamSystem.ml
Package installation log would be in CWD, quite the pollution with --debug
=> Fixed location of some log files

CHANGES, src/client/opamArg.ml, src/client/opamClient.ml, src/client/opamPinCommand.ml, src/client/opamState.ml, src/client/opamState.mli, src/core/opamGlobals.ml
Convenient when there are several packages compiled from the same repo
=> Allow <name>.opam in the source of packages

src/client/opamState.ml, src/core/opamVersion.ml.in, src/core/opamVersion.mli
Beta2 change caused it to be skipped, incurring a long load time at the first
run of OPAM after boot
=> Fixed state-cache loading

src/client/opamState.ml
"string_of_env_update" is using OCaml's %S for escaping strings in shell scripts!
=> ad hoc fix for csh (more general problem remains)

src/client/opamAction.ml, src/client/opamState.ml
Closes #2021
Actually the overlays need to be kept at unpinning when the package is still
installed AND has no other metadata: otherwise we lose the uninstall
instructions. OPAM cleans up stale overlays at startup, but there was a bug
-- hereby fixed -- in its condition.
=> Fixed handling of overlays at package unpin/remove

src/core/opamTypesBase.ml
working around the lack of pinning-kind field for 'dev-repo'. Ref #2026
Still needs some proper documentation
=> Allow addresses of the form 'git+ssh://', 'hg+https://'

src/core/opamRepository.ml
The observable bug is that when I update the `url` file in a package to change
the `archive` source but not the checksum, this never propagates after an
`opam update`.  The reason is that the update is skipped due to the
optimisation that prevents recompilation of a package when the location
changes, but not the checksum.
Unfortunately, if using OPAM with a `local` remote, this makes it impossible
to fix a broken location without manually munging around in `~/.opam`.
Debugged with @samoht
=> Back out the optimisation to recompile only when archive checksum changs

doc/pages/FAQ.md, src/client/opamState.ml, src/core/opamRepository.ml, src/core/opamRepository.mli
OPAM would reinstall all packages after each update :( The 'package states'
are not well defined, and the interface between OpamRepository and OpamState 
for that purpose is very fragile (it relies in the same lists being computed,
in the same order, from two modules). But since this will go in 1.3, there is
no point in rewriting it now.
=> Fix update bug introduced in fef5f0704f59459dad119dbb30f63e92babc6d1f

.travis-ci.sh, .travis.yml
OCaml versions were out of sync (both brew, and 4.02.0 still referenced while
4.02.1 was installed)
=> Update travis test to reflect the currently available versions

doc/pages/Manual.md, src/client/opamArg.ml, src/solver/opamCudf.ml, src_ext/Makefile
These patches don't affect the logic of opam or its build environment. It simply fixes some spelling mistakes in messages.
=> Fix incorrect contractions in messages.

src_ext/Makefile
Under NetBSD, un-tar'ing a project's archive may result in an extra file getting created. NetBSD's `tar` recognizes GNU `tar` archives but places extra information in a file outside the directory tree that gets extracted. The extra file breaks the `Makefile` command that tries to move the archive's tree out of `tmp`.
This patch replaces the `mv` command with a slightly more complicated command that only moves directories out of the `tmp` directory. Because we may be leaving a file in `tmp`, the `rmdir` command is replaced with a `rm -rf` command.
This commit allows me to build OPAM on NetBSD with no libraries installed in the base system.
=> Fix to build OPAM on NetBSD without any installed libraries.

src/client/opamArg.ml, src/client/opamState.ml, src/client/opamState.mli
This set of patches add an alternative format dump for opam (PEF : package export format). It is meant to be the new interface between the dose tools and opam to perform repository analysis. It is also needed for the new version of ows.irill.org, the upcoming new version of the opam weather service. This format is different from cudf as versions are strings and not integers. In the future I plan to add more fields to the export format.
Ex:
package: cohttp
version: 0.9.14
maintainer: anil@recoil.org
depends: fieldslib (>= 109.20.00) , cstruct (>= 1.0.1) , ounit , uri (< 1.5.0) , uri (>= 1.3.8) , re , ocamlfind
reccomends: lwt | async
conflicts: mirage-tcpip-xen (< 0.9.5) , mirage-tcpip-unix (< 0.9.5) , lwt (>= 2.4.7) , lwt (< 2.4.3) , async (> 109.53.02) , async (< 109.15.00)
=> add new export format for opam compatible with dose-distcheck

admin-scripts/compilers-to-packages.ml, admin-scripts/extract_mini_repository.sh, src/tools/opam_mk_repo.ml
This script is able to generate a minimalistic and self-contained 
opam-repository for a given set of packages and compiler versions.
The resulting repository will be in './opam-mini-repository.tar.gz'.
```
./extract-mini-repository ocp-indent lwt
./extract-mini-repository ocaml.4.02.1 ocaml.4.01.0 ocp-indent lwt
```
Then, the resulting repository can be used to replace the default opam
repository on computer without internet access and with only few spare
disk space.
```
tar xf opam-mini-repository.tar.gz
opam init --root /tmp/opam default ./opam-mini-repository --comp 4.02.1
```
=> Add ./admin-script/extract-mini-repository

src_ext/Makefile
So don't compile native libraries without ocamlopt, and don't compile bytecode
libraries without ocamlc.
This addresses the issue #2119.
I first bumped into the issue when compiling without ocamlopt, but decided to add ocamlc support for sake of completeness and to make testing easier. The symptoms when compiling lib-ext without ocamlopt are:
no -c -I extlib/ extlib/enum.ml
/bin/sh: 5: no: not found
=> Don't compile lib-ext targets that cannot be compiled due to missing compiler #2119

src/core/opamFile.ml, src/core/opamFormat.ml, src/core/opamFormat.mli
Ref #3944
This makes most file format errors pass silently -- in particular unknown
fields or idents. Some "typing" errors (eg string where an ident is expected)
will lead to the whole field being ignored ; lint will report an error 2 "bad
format" in that case.
Also normalises some messages
=> OpamFile: make 'permissive mode' the default without strict or debug

src/client/opamArg.ml
This should help to reduce any confusion in remebering what
the command is that generates this output.
Fixes #2127
=> Change wording to reflect the command used

doc/dev-manual/dev-manual.tex, doc/pages/Manual.md, src/client/opamAction.ml, src/client/opamArg.ml, src/core/opamFile.ml, src/core/opamFile.mli
ref: ocaml/opam-repository/issues/3944
=> Allow _tag_ `"flags:plugin"` instead of _flag_ `plugin`

src/client/opamSolution.ml, src/core/opamFile.ml
advertising 'opam depext'. This probably also obsoletes lint warning 38
("declares depexts, but no helpful post-messages")
=> Add default troobleshooting message when a package fails to install and has depexts

src/client/opamArg.ml, src/client/opamClient.ml, src/client/opamState.ml, src/core/opamFilename.ml, src/core/opamFilename.mli, src/core/opamGlobals.ml, src/core/opamGlobals.mli, src/core/opamSystem.ml, src/core/opamSystem.mli, src/repositories/opamHTTP.ml
I use a script to do caching on OPAM's download requests (to avoid pounding the servers, to work around overzealous firewalls, and to isolate myself from server failures and removed files). Unfortunately, the caching gets in the way when the contents of a file changes at the same URL.
In most cases, `opam` already knows about it because the checksum is updated in the package repository. This PR makes `opam` pass the checksum to the OPAMFETCH command (as `%{checksum}%`) which allows me to index my cache by checksums and avoid all problems with different files versions at the same URL.
=> Pass the expected checksum to the OPAMFETCH program

src/repositories/opamHTTP.ml
If the repository being packed up contains symbolic links, tar
does not follow them unless you pass to it the -h flag.
From the manpage of tar:
-h, --dereference
follow symlinks; archive and dump the files they point to
Symlinks pointing outside the repository are dangling if you don't
follow them.  Without the -h flag, opam admin make fails to produce
a usable index in a scenario where the files could be correctly served
by an HTTP server.  For example one could have
/var/www/allrepos/repo1/packages/p/p.1
/var/www/allrepos/repo1/index.tar.gz
/var/www/allrepos/repo2/packages/p/p.1 -> ../../../repo1/packages/p/p.1
/var/www/allrepos/repo2/index.tar.gz
This is useful if repo2 is a subset of repo1, and use symlinks to avoid
duplication, e.g. imagine allrepos being maintained under git.
=> Add option -h to tar when building index.tar.gz

src/client/opamPinCommand.ml, src/core/opamParallel.ml, src/format/opamTypes.mli, src/format/opamTypesBase.ml, src/format/opamTypesBase.mli, src/solver/opamActionGraph.ml, src/solver/opamActionGraph.mli, src/solver/opamCudf.ml, src/solver/opamCudf.mli, src/solver/opamHeuristic.ml, src/solver/opamHeuristic.mli, src/solver/opamSolver.ml, src/state/opamAction.ml, src/state/opamAction.mli, src/state/opamSolution.ml, src/tools/opam_mk_repo.ml
This uses a new separate action `Build in the concrete action graph,
making use of the build/install separation in opam files.
As a consequence,
- install step is unparallelised, which will allow for easily tracking changes
- the verbose package flag only prints install instructions, not the build anymore (needs doc!)
- the install step could be made to have access to stdin and query the user
=> Separate build and install steps

src/client/opamConfigCommand.ml, src/state/opamState.ml
* Correctly handle the case of the variable being unset
- This fixes the "missing manpages" bug.
* Do not put quotes around array expansions:
set -gx PATH  $PATH  "/blah"  # Good
set -gx PATH "$PATH" "/blah"  # Bad
* Add logic for CDPATH, for future-proofing
- It is the only other special array variable we have
to potentially worry about.
=> Fix Fish shell assignments on array env variables

src/state/opamAction.ml
the commands are not directly printed, because we try different -p settings
until one fits, and that can be very verbose
=> Print patch applications in verbose mode

src/client/opamArg.ml, src/client/opamClient.ml, src/client/opamClient.mli, src/client/opamClientConfig.ml, src/core/opamSystem.ml, src/core/opamSystem.mli, src/state/opamState.ml, src/state/opamStateConfig.ml, src/state/opamStateConfig.mli
also fixes a duplicate --jobs option on 'opam init' Detection thanks to
@dbuenzli at http://stackoverflow.com/questions/16269393/how-to-get-the-number-of-cores-on-a-machine-with-ocaml
=> Detect number of CPUs on init to enable parallelism

doc/dev-manual/dev-manual.tex, doc/pages/Manual.md
The documentation of the `substs` field was subtly wrong as it was calling the field `subst`. Please let me know if you can think of other places to make this change or if you'd like me to generate something (`dev-manual.pdf`?).
=> Fix documentation of substs field from "subst"

Makefile
Cygwin paths have spaces in them typically, so path expressions need to be surrounded by quotes.
=> escape path properly for cygwin after "make cold"

src/core/opamSystem.ml
as mentioned in #2180 `getconf _NPROCSSOR_ONLN` does not work on FreeBSD, but `sysctl -n hw.ncpu` does.
=> use sysctl on FreeBSD to find the amount of online processors

.travis-ci.sh, src/client/opamConfigCommand.ml, src/state/opamAction.ml, src/state/opamPath.ml, src/state/opamPath.mli, src/state/opamState.ml, src/state/opamState.mli, src/tools/opam_installer.ml
**rebase before merge, this duplicates commits**
There is no configuration options for the user yet, but OPAM will now honor the paths defined in the switch's global config (making it less useless!)
=> Make switch paths configurable (honoring switch/config/global-config.config)

src/core/opamSystem.ml
Found while running 'opam init' without any system compiler in PATH.
=> Avoid error on lock creation.

src/format/opamFile.ml, src/format/opamFile.mli
This mights help external tools based on opam-lib to reuse the parser.
=> Export OpamFile.Make

src/repository/opamRepository.ml
With ```Pervasives.compare```, priority is not the main sorting key.
=> Fix repository ordering.

src/solver/opamSolver.ml
It was removed for release as a safeguard against a crash in Dose; I need it 
for opam-ci, and will test it again
=> Restore OpamSolver.installable

META.in, admin-scripts/Makefile, src/format/opamFile.ml, src/format/opamFile.mli, src/state/opamState.ml
since there is no format changes yet, and opam 1.2 later chokes on the
1.3-advertised file, this was annoying
=> Only update opam version of ~/.opam/config to 1.2

doc/dev-manual/dev-manual.tex
Found by @toolslive in ocaml/opam-repository#4368.
=> Fix typo in documentation of dev-repo

src/core/opamFilename.ml, src/core/opamFilename.mli, src/format/opamFile.ml
We recently had a url file with an invalid checksum (with an extra character) sneak through:
http://opam.ocaml.org/builds/20ff97ad14c79484d876c1200ba5e83dd7ca46ae/logs/local-ubuntu-14.04-ocaml-4.02.1/raw/sawja.html
This PR adds checksum validity checking during parsing so that errors can be caught earlier and reported more clearly.
=> Check checksum format during parsing

src/state/opamSolution.ml
(I disabled this earlier to avoid a bug in the engine, but that's now fixed)
=> Apply mutual exclusion for package installs

admin-scripts/depopts_to_conflicts.ml, admin-scripts/to_1_1.ml, opam, src/format/opamFile.ml, src/format/opamFormat.ml, src/format/opamFormat.mli, src/format/opamFormula.ml, src/solver/opamSolver.ml
this has been bothering me for a while ; note that it is NOT a
backwards-compatible change, but files advertised as before 1.3 will be
handled silently. Just a few packages used it though.
A lint warning is provisionned, too, but inhibited for now (files < 1.3)
Closes #2246
=> Properly treat conflicts as a disjunction

src/client/opamArg.ml, src/client/opamClient.ml, src/client/opamClient.mli, src/client/opamConfigCommand.ml, src/client/opamConfigCommand.mli, src/format/opamFile.ml, src/format/opamFile.mli
- new commands 'set' and 'unset' for custom switch variables
- 'exec' now expands variables in command and arguments
- new command 'expand' to simply opam-evaluate a string
=> Extend 'opam config' interface

doc/pages/Install.md, doc/pages/Usage.md
We also detail how to explicitly specify a specific solver, as
recommended by Hezekiah M. Carty.
I guessed the `#Externalsolvers` id; can someone confirm that this will be correct demangling at release time?
Also, it would be nice if there was a way to ask OPAM which solver it will use, for users to check that the solver-detection heuristics worked (and that the solver is correctly installed, etc.). Is such an option hidden somewhere?
=> move "External solvers" documentation from Usage to Install (#2261)

doc/pages/Packaging.md
The URL was displayed as https://github.com/ocaml/opam-repository but pointed to http://opam.ocaml.org/doc/Packaging.html
=> Broken URL to OPAM repository

opam
This fixes compilation of a direct `opam pin add opam-lib --dev`
command, which currently picks up dose4
=> Sync local `opam` file with opam-repository

src/client/opamRepositoryCommand.ml
This how we found out that `rsync` was missing.
=> Print exception caught instead of just "Could not fetch repo"

src_ext/Makefile
The file http://opam.ocaml.org/archives/dose.3.3+opam.tar.gz changed, an update of the md5 is needed. This is currently preventing the travis script on the compiler repository to run correctly.
=> MD5 sum for dose 3.3 changed

src/client/opamArg.ml, src/core/opamStd.ml
why use an unreadable DSL passed as strings when you can use OCaml ?
=> Cleanup uses of Re

src/core/opamSystem.ml
**Enhance detection of Zip archives**
Stash doesn't put any extension to its release archives. Currently, opam detects Zip archives by checking the filename's extension. This patch uses system's file command instead.
**Add support for packages with everything in the root**
Let's consider the following package tree:
```
/tmp/opam-xxx-yyy/
|- Makefile
|- src
|- toto.ml
```
Currently, opam only moves `src` to `.opam/<switch>/build/<package.a.b.c>`, instead of moving the whole tree.
This patch handles this case by directly moving `opam-xxx-yyy`, if regular files are found in it.
**Notes**
I didn't know whether the Makefile was generated or handwritten, so I added a dependency to the `str` package without really knowing what I was doing. :s
=> Support for packages from Atlassian's Stash

src/client/opamClient.ml, src/client/opamClient.mli, src/client/opamMain.ml, src/format/opamTypes.mli, src/format/opamTypesBase.mli, src/state/opamSolution.ml
* allow `-u` to upgrade if installed
* avoid error on `opam install foo --deps-only` when foo is unavailable
=> Some improvements to `opam install`

src/client/opamClient.ml, src/client/opamRepositoryCommand.ml
the latter was just an issue of cache being revalidated after having been invalidated.
=> Allows to install new packages on `opam upgrade` after confirmation, fix `repo add` not to need update

doc/pages/Manual.md
I don't understand much of the current documentation of version order in the manual, which says in particular:
> - version strings are sliced into alternate, possibly empty non-digit / digit
>   sequences, always starting with a non-digit sequence. `1.0~beta2` is thus
>   `["";1;".";0;"~beta";2]`.
>
> - those are sorted lexicographically, using resp. ASCII (with symbol > letter)
>   and number order. For example `a` gives `["a"]`, and `1` gives `["";1]`, so
>  `a` is latest (`"" < "a"`).
What does "resp. ASCII (with symbol > letter)" mean? I understand "symbol" to mean "something other than letter or number" (is this correct?), but in my `utop` I have `Char.code '#' = 35` and `Char.code 'a' = 97`, so do we have `"#" > "a"` as "(symbol > letter)" suggests of `"#" < "a"` as ASCII suggests? …
=> doc/Manual.md: attempt to clarify version ordering

doc/modules, src/client/opamConfigCommand.ml, src/core/opamConsole.ml, src/core/opamConsole.mli, src/core/opamParallel.ml, src/format/opamFile.ml, tests/Makefile, tests/packages/P1-1.opam, tests/packages/P1-1/build.sh, tests/packages/P1-2.opam, tests/packages/P1-2/build.sh, tests/packages/P4/build.sh
It requires 'opam config env' to load the full switch state currently.
But I'm counting on @OCamlPro-Henry's PR to fix that !
=> Fix and test the 'setenv:' field

src/client/opamRepositoryCommand.ml, src/state/opamState.ml, src/state/opamState.mli
when a package was installed in a switch and pinned in another, 'opam update' didn't
propagate the reinstall information correctly
=> Fix spurious reinstalls of pinned packages across switches

src/core/opamStd.ml, src/core/opamStd.mli, src/format/opamFile.ml, src/format/opamFile.mli, src/state/opamPath.ml, src/state/opamPath.mli, src/state/opamState.ml, src/state/opamState.mli
The environment updates are cached in <root>/<switch>/environment.
It is updated whenever the <root>/<switch>/state is updated.
This might be used by external tools (e.g. opam-manager) to read the
environment updates without having to depend on `OpamState`. This might
also permit to add a "costly topological sort" when computing the
environment updates.
=> Cache environment updates in a separate file.

src/client/opamPinCommand.ml, src/state/opamState.ml
The ~switch/environment files are thus now fully expanded. Note that if you used the latest
version that may temporarily break your opam root (if you ended up with variables in the file).
Simply remove the file to fix.
=> Expand env values earlier

Makefile, admin-scripts/add-github-dev.ml, admin-scripts/compilers-to-packages.ml, admin-scripts/depopts_to_conflicts.ml, src/format/opamFile.ml, src/format/opamFile.mli, src/state/opamAction.ml, src/state/opamState.ml, src/state/opamState.mli, src/tools/opam_admin_top.ml
It reprints unchanged fields as they were in the original file.
The new function is bound in opam-admin.top so that it makes minimal modifications.
See
- https://github.com/ocaml/opam-repository/pull/5140 
- https://github.com/ocaml/opam-repository/pull/5176
- http://lists.ocaml.org/pipermail/opam-devel/2015-November/001266.html
=> Implement a printer that preserves (some) formatting

src/solver/opamHeuristic.ml
If the keyword `implicit` were ever added to the language, this change would allow OPAM to continue to build.
=> Rename a variable

Makefile
so that local OCaml overrides any previously installed one (such as 3.11.x that is too old in CentOS 6)
Same fix needs to go into master, but this 1.2 one unblocks container builds for Travis CI
=> make cold: Fix order of PATH variable 

src/state/opamState.ml
In Fish, `or` is a command of its own, not a syntax element. So you need a semicolon before it to start a new command. Reference: [`fish` documentation: commands – `or`](http://fishshell.com/docs/current/commands.html#or)
This should be the last fix needed to solve https://github.com/ocaml/opam/issues/2255 – the other issues were fixed by 758c3912cd1661d116a3bca47e52c2881a95afd5 (use `source`) and c87a2802fe73e94599c1064afac72c45b7d534f6 (don’t quote array variables).
=> Fix Fish shell error in opamState.ml

src/client/opamConfigCommand.ml, src/client/opamMain.ml, src/state/opamState.ml, src/state/opamState.mli
Previously, `opam config exec` would always set the `OPAMSWITCH` environment variable. This causes issues when running processes like shells with `opam config exec -- bash` or similar because the shell's environment is not precisely the same as the parent process's environment. In partiular, the absence of `OPAMSWITCH` was not preserved and therefore the use of interactive opam commands was more unwieldy.
Using `opam config exec` to spawn a shell is a common technique when scripting with opam in order to avoid needing to run a separate command to set up the environment in a subshell. See <http://lists.ocaml.org/pipermail/opam-devel/2016-February/001393.html>.
=> opam config exec now does not set OPAMSWITCH unless --switch or OPAMSWITCH

src/client/opamArg.ml, src/client/opamConfigCommand.ml, src/client/opamState.ml, src/client/opamState.mli
Previously, `opam config exec` would always set the `OPAMSWITCH` environment variable. This causes issues when running processes like shells with `opam config exec -- bash` or similar because the shell's environment is not precisely the same as the parent process's environment. In partiular, the absence of `OPAMSWITCH` was not preserved and therefore the use of interactive opam commands was more unwieldy.
(cherry picked from commit a19c1384177c6080f21516e674929cabbcf34565 submitted as #2444)
=> Backport #2444 to 1.2.x

src/client/opamArg.ml
An attempt to fix #1835. I'm uncertain if this fixes it for OPAMJOBS as well.
=> Make `opam install -j' only accept positive args

src/format/opamFile.ml
Witthout the fix, the comparison prints the warning only for packages which are using a reference to themselves (and obviously, their own name is not in the depends). Currently, it is only "bat"...
=> Fix warning 41

src/core/opamStd.ml
Useful to be able to parse the output of `opam lint`: setting a high-value will print each warning/error on a different line, by preventing the formatter from adding line breaks.
=> Set OPAM_COLUMNS to force the formatting line length

doc/pages/Usage.md
The current basic usage guide uses ocaml 4.02.1. It is confusing for newcomers as you can see [here](http://irclog.whitequark.org/ocaml/2016-04-02#1459592018-1459592392;).
=> Update basic guide to recommend ocaml 4.02.3 instead of 4.02.1

src/state/opamPath.ml
The `Unix.tm_mon` is a zero-based month and so should be incremented when using as a human-readable month.
```
$ opam install ...
...
The former state can be restored with opam switch import "/home/simonbe/.opam/4.02.2/backup/state-20160301102642.export"
$ date
Fri Apr  1 10:49:39 UTC 2016
```
The month should be 04, not 03. No, this is not an April fools commit :)
Signed-off-by: Si Beaumont <simon.beaumont@citrix.com>
=> Fix off-by-one in state backup timestamp

.gitignore, shell/opam_prompt.sh, src/Makefile, src/state/opamScript.mli, src/state/opamState.ml
This pull request modifies the opam installation process put in place a shell function&mdash;namely `__opam_ps1`&mdash;that a user can use to display the currently active opam switch in his shell prompt.
Note that as is, the code does not actually modify the user's shell prompt. The user must explicitly modify a shell configuration file to utilize the function. To place the current opam switch at the beginning of the prompt, the user would defined `PS1` as follows:
```
PS1="$(__opam_ps1 "%s")\u@\h:\w\$"
```
This would result in the following prompt:
```
(system)user@host:~$
```
... where `system` indicates the default system switch is active. If another switch is selected, that part of the prompt would change appropriately.
=> add support for displaying active switch in prompt

src/client/opamConfigCommand.ml, src/client/opamListCommand.ml, src/client/opamListCommand.mli, src/client/opamPinCommand.ml, src/core/opamSystem.ml, src/format/opamFile.ml, src/format/opamFile.mli, src/format/opamFilter.ml, src/format/opamFilter.mli, src/format/opamFormat.ml, src/format/opamFormat.mli, src/format/opamTypes.mli, src/state/opamEnv.ml, src/state/opamFileTools.ml, src/state/opamPackageVar.ml, src/state/opamPackageVar.mli, src/state/opamSolution.ml, src/state/opamSwitchState.ml
Define 'name' and 'version' in switch scope in opam files, and allow
references.
This makes it possible e.g. for a package to depend on another one at the
same version.
depends: "bar" { = version }
=> Allow version references in the 'depends' and 'depopts' fields

src/state/opamGlobalState.ml
that caused installed package definitions (including compiler defs
generated in a previous step) to be lost.
@Drup: sorry!
=> Fix bug in ~/.opam format upgrade

src/client/opamArg.ml, src/client/opamArg.mli, src/client/opamListCommand.ml, src/client/opamListCommand.mli, src/client/opamMain.ml, src/format/opamFile.ml, src/state/opamFileTools.ml, src/state/opamFileTools.mli
Document the fact that this can now print any field, from 'opam show' or
from the package description if suffixed with ':' (which is the general
convention when referring to opam file fields).
`opam show --file - --field f` can be useful to third-party tool that want
to access opam metadata.
=> Allow 'opam show --file', add '-' to read from stdin

src/client/opamClient.ml, src/state/opamEnv.ml
Also, fixes the (yet unseen) case of multiple variable upgrades ('setenv:' field)
=> Don't process reinstalls of parents on package upgrade

appveyor.yml
The environment variable OCAML_TOPLEVEL_PATH is not set under Cygwin, this change is a first step towards detecting what's wrong.
See https://github.com/ocaml/opam/issues/2362
=> AppVeyor: print opam config env at end of compilation

src/solver/opamSolver.ml, src/state/opamSwitchState.ml
This resolves for the most part the solving delay issues for
2.0~alpha (#2534, #2548), but needs more testing
=> Remove unneeded compiler versions from the universe.

.gitignore, Makefile, opam-client.opam, opam-core.opam, opam-format.opam, opam-repository.opam, opam-solver.opam, opam-state.opam, src/client/client.ocp, src/core/core.ocp, src/format/format.ocp, src/opam.ocp, src/repository/repository.ocp, src/solver/solver.ocp, src/state/state.ocp, src/tools/tools.ocp
relying on more advanced ocp-build features, and the new opam `{=
version}` capability.
=> Update the sub-lib packages

shell/wrap-build.sh, shell/wrap-install.sh, shell/wrap-remove.sh, src/format/opamFile.ml, src/format/opamFile.mli, src/format/opamFormat.ml, src/state/opamAction.ml
These are defined in ~/.opam/config and allow to wrap all command
invocation; this is primarily intended for testing purposes at the moment,
and the fields can only be set by hand.
The wrappers are resolved in the scope of the command that is run (package
variables are available). One intended usage is to restrict read/write
access of the commands on the testing frameworks (so that e.g. a package
that tries to install during its build phase will fail).
I use it for example with a shell script build wrapper:
```
exec unshare -Umnr /bin/sh -se "$@" <<EOF
mount --bind ~ ~
mount --bind . .
mount -o remount,ro,bind ~
cd . # required to update to the mount
exec "\$@"
EOF
```
that prevents writing to everywhere but . (i.e. the build dir), as well as network access.
=> Add global `wrap-build/install/remove-commands:` fields

CHANGES, doc/index.html, doc/modules, shell/wrap-build.sh, shell/wrap-remove.sh, src/Makefile, src/client/opamListCommand.ml, src/client/opamListCommand.mli, src/client/opamMain.ml, src/core/core.ocp, src/core/opamDirTrack.ml, src/core/opamDirTrack.mli, src/core/opamFilename.ml, src/core/opamFilename.mli, src/format/opamFile.ml, src/format/opamFile.mli, src/format/opamFormat.ml, src/format/opamFormat.mli, src/state/opamAction.ml, src/state/opamAction.mli, src/state/opamPath.ml, src/state/opamPath.mli
=> Track files installed by packages, allow query and use for removal

src/client/opamArg.ml
This prevents different behaviour if the command is executed with
`opam` vs `/usr/bin/opam`.
This is a backport to the 1.2 branch, as the bug is fixed in
OPAM trunk already.  See #2317.
=> For external plugin search, always do a full PATH search

src/client/opamMain.ml, src/core/opamParallel.ml, src/core/opamParallel.mli, src/solver/opamActionGraph.ml, src/solver/opamActionGraph.mli, src/state/opamAction.ml, src/state/opamAction.mli, src/state/opamPath.ml, src/state/opamPath.mli, src/state/opamSolution.ml, tests/packages/P5.opam
Now that OPAM is able to distinguish between the 'build' and 'install' rules, we want, when reinstalling a package, to build the new version before to remove the old one: whenever the new version fails to build, the old one is still installed and the opam repository is left untouched.
This is what this patch implements.
Unfortunatly, we might not apply this strategy with all packages. When a package A depends on a package B, for preserving the consistency of then .opam directory we still need to remove A before to remove B. Then, we can't wait for B to be built before to remove the old version. Still, we wait for A to be successfully built before to remove B.
=> Delay removal of packages as much as possible.

src/client/opamMain.ml, src/client/opamSwitchCommand.ml, src/tools/opam_format_upgrade.ml, tests/Makefile
This will likely break some scripts.
'opam switch foo' or 'opam switch set foo' will NO LONGER try and install
'foo', it can now only switch to an existing switch
'opam switch create SWITCH [COMPILER]' is now preferred over 'opam switch
install'; '--alias-of' is no longer allowed or necessary, since the
positional argument is used instead; '--empty' and '--package' give the
full extent of possibilities.
=> 'opam switch' interface cleanup (script-breaking changes)

opam-devel.opam, src/client/opamMain.ml, src/client/opamSwitchCommand.ml, src/client/opamSwitchCommand.mli, src/core/opamFilename.ml, src/core/opamFilename.mli, src/format/opamSwitch.ml, src/format/opamSwitch.mli, src/repository/opamLocal.ml, src/state/opamGlobalState.ml, src/state/opamPath.ml, src/state/opamStateConfig.ml, src/state/opamSwitchAction.ml, src/state/opamSwitchAction.mli, src/state/opamSwitchState.ml
This PR provides the possibility to use directories as switch handles,
which holds the switch contents below `_opam` at that path. The switch
is then automatically selected if opam is run from the given directory
or a descendent.
External switches are still registered globally in ~/.opam/config,
which allows listings, format upgrade, global repository settings
changes, etc. ; but the case where they aren't registered should be
handled nicely.
=> Local switches

opam-devel.opam, src/client/opamArg.ml, src/client/opamClientConfig.mli, src/state/opamAction.ml, src/state/opamAction.mli, src/state/opamSolution.ml, src/state/opamStateConfig.ml, src/state/opamStateConfig.mli
This will only affect packages listed on the command-line, which have
an URL pointing to a local directory (typically, pinned paths) ; they
will be built and installed directly from their source dir.
=> Add --inplace-build

src/core/opamSystem.ml, src/format/opamSwitch.ml, src/format/opamSwitch.mli, src/state/opamStateConfig.ml, src/state/opamSwitchState.ml
resolve _opam symlinks, so that they can be used to share a local switch between projects without problems
also small fixes for unregistered switch selection, and dirname normalisation
=> Better resolution of local-switches

src_ext/Makefile
Signed-off-by: Anil Madhavapeddy <anil@recoil.org>
=> Correct the extlib-1.5.3 source URL, now that Google Code is retired

src/core/opamConsole.ml, src/format/opamFormula.mli, src/solver/opamCudf.ml, src/solver/opamSolver.ml, src/state/opamFileTools.ml, src/state/opamSwitchState.ml
in fact stripping all conflicting compiler versions. Solver times back to normal
(we were already hinting to the solver that we wanted to keep the specific package versions,
so it could have done this optimisation itself, but it seems it didn't)
=> Strip packages conflicting with the compiler

src/client/opamArg.ml, src/client/opamMain.ml
mostly an alias for `opam config var`, although lists the defined
variables without a VAR argument
=> Add the `opam var` command

src/client/opamClient.ml
since this PR makes it required (once you hit a hash that requires it,
that is)
=> Add init-check for openssl

src/client/opamMain.ml, src/client/opamRepositoryCommand.ml
* much simplified 'opam repo' command
* lifted 'var', 'env', 'exec' from 'opam config' to the toplevel (e.g. 'opam env' instead of 'opam config env')
=> CLI simplifications

Makefile.config.in, configure, configure.ac, src/Makefile, src/client/opamListCommand.ml, src/client/opamSolution.ml, src/core/opamCompat.ml.4.01, src/core/opamCompat.ml.4.03, src/core/opamCompat.mli.4.01, src/core/opamCompat.mli.4.02, src/core/opamCompat.mli.4.03, src/core/opamConsole.ml, src/core/opamDirTrack.ml, src/core/opamHash.ml, src/core/opamStd.ml, src/format/opamPackage.ml, src/format/opamTypes.mli, src/solver/opamCudf.ml, src/solver/opamCudf.mli, src/solver/opamSolver.ml
There is one left on matching `Sys_error "Broken pipe"` ; but not sure how to avoid it
(we do register a signal handler; but what may happen is that the signal is caught before the handler is registered, and we do get that exception)
=> Fix warnings on OCaml 4.03.0

src/client/opamMain.ml, src/state/opamSwitchState.ml, src/state/opamSwitchState.mli
limited to universe dump at the moment, intended for interaction with OWS
=> Re-add PEF export functions

doc/pages/Manual.md, src/client/opamAction.ml, src/core/opamFilename.mli, src/core/opamSystem.ml, src/core/opamSystem.mli
Being stricter means we don't have to try the patch for all values of
'-p', with the portability problems that caused, and that we can get the error
reports when patches fail to apply.
Closes #2576, and follows some fixes on packages in the repo at 
https://github.com/ocaml/opam-repository/pull/7645
=> Assume patches apply with '-p1'

src/tools/opam_mk_repo.ml
It's still needed for compat with older versions.
=> Re-add generation of 'urls.txt' for now

shell/md5check.ml, src/client/opamAction.ml, src/client/opamAction.mli, src/client/opamArg.ml, src/client/opamClient.ml, src/client/opamClientConfig.ml, src/client/opamClientConfig.mli, src/client/opamMain.ml, src/client/opamPinCommand.ml, src/client/opamSolution.ml, src/format/opamTypes.mli, src/format/opamTypesBase.ml, src/format/opamTypesBase.mli, src/repository/opamHTTP.ml, src/repository/opamLocal.ml, src/repository/opamRepository.ml, src/repository/opamRepository.mli, src/repository/opamRepositoryBackend.ml, src/repository/opamRepositoryBackend.mli, src/repository/opamVCS.ml, src/state/opamSwitchState.ml, src/state/opamSwitchState.mli, src/state/opamUpdate.ml, src/state/opamUpdate.mli, src_ext/Makefile
The removal of "mixed mode" should be made painless by a new message
that warns you about uncommitted changes. Also, greatly improved
internal interface for downloading packages.
=> Simplify the pinning system, remove "mixed", add "--working-dir"

src/client/opamSolution.ml
This fixes invalid JSON output as a repeated key is not allowed:
```
{
"opam-version": "2.0~alpha5 (33f70c51dffb22010df343bf781b68b17a69f497)",
"command-line": [
"opam",
"install",
"--show-actions",
"--json=actions.json",
"mirage.2.9.1",
"lwt.2.6.0",
"core.113.33.02+4.03"
],
"opam-version": "2.0~alpha5 (33f70c51dffb22010df343bf781b68b17a69f497)",
"command-line": [
"opam",
"install",
"--show-actions",
"--json=actions.json",
"mirage.2.9.1",
"lwt.2.6.0",
"core.113.33.02+4.03"
],
```
=> do not output `opam-version` twice in `install --json`

src_ext/Makefile
Hyphens in dependencies can be computed as uptodate, and so
opam-file-format doesnt get compiled. The trivial change to an
underscore fixes the build on Ubuntu 16.04 among others.
Fixes #2773
=> fix src_ext build on some versions of GNU make

doc/pages/Manual.md, doc/pages/Packaging.md, src/state/opamFileTools.ml, src/state/opamFileTools.mli, src/state/opamUpdate.ml, src/tools/opam_format_upgrade.ml
That is:
- use the single-file layout with upgrade-format
- warn and ignore extra url/descr files when both exist
=> Transition more aggressively towards one-file package specifications

src/core/opamSystem.ml
POSIX-compliant, should be generally useful, and solves #2814
=> Add '-p' to calls to the 'cp' command

src/format/opamFile.mli
What are the chances that the one field that I want to set using OpamFile.OPAM isn't exposed? Non-zero probability, it turns out...
=> Expose `with_tags` in the OpamFile.OPAM signature

shell/opam_completion.sh, src/client/opamMain.ml, src/client/opamRepositoryCommand.ml, src/core/opamDirTrack.ml, src/core/opamDirTrack.mli, src/state/opamGlobalState.ml, src/state/opamGlobalState.mli, src/state/opamRepositoryState.ml, src/state/opamSwitchState.ml
Provides tools for using a project directory from CWD.
Will auto-init and create a local switch unless specified otherwise.
Scans for local opam files and builds based on them.
Can install by copying the artefacts from the local switch to a given prefix.
Handling a local conf file that can give the specifics of how to create the
switch would be a nice addition.
=> Add prototype 'opam build' command

doc/pages/Install.md
The `opam` package has moved to the official distribution and thus is now much easier to install for newcomers.
=> Improve Archlinux installation instructions

src/client/opamArg.ml, src/client/opamArg.mli, src/client/opamListCommand.ml, src/client/opamListCommand.mli, src/client/opamMain.ml, src/client/opamMain.mli
Removes the discrepancy with 'opam search', which is now an alias,
allows reusing them in other scopes for better expressivity and
consistency.
=> Factorise 'opam list' options

src/client/opamArg.ml
where `Arg.conv` is introduced. It would be nice if this could make it in the subsequent `rc`s before 2.0.0.
=> Avoid name clash with next version of cmdliner.

src/client/opamMain.ml, src/format/opamFilter.ml
The coinstallability check is still very slow, but at least you can
now work around it with `--compiler=`
=> Several improvements and fixes to 'opam build'

doc/pages/Usage.md
I see that the instructions seem to have been rewritten for opam2 recently, but the change is not in production on the website (which is reasonable if you ask me given that all distribution-installed OPAMs will remain 1.x for a some time). Is there a way to get a change to the production website?
(I plan to move to 4.04.1 or 4.05.0 once one of these is released, so another similar PR may show up at some point.)
(Also: @AltGr, I sent you an unrelated email last week, please check your mailbox.)
=> update the Basic guide to recommend 4.04 instead of 4.02.3

shell/bootstrap-ocaml.sh
Without this, `ocamlc.byte` is installed and the build fails. We might
as well use ocamlopt.opt as the build time isn't that much slower
and we get a more complete OCaml environment.
=> make cold: fix the bootstrap compiler to install the faster compiler

src/client/opamArg.ml
Newer cmdliner detects this, and makes `opam pin` unusable.
=> Remove deprecated option, solving conflict on '-e'

shell/wrap-build.sh, shell/wrap-install.sh, shell/wrap-remove.sh
Added a layer to make the processes run as their normal uids/gids, which may
at the same time prevent problems with build scripts that would be confused by
thinking they are root, and prevents these scripts from changing our
sandboxing mounts.
=> Better linux-namespace command wrappers

src/state/opamSwitchState.ml
e.g. on `opam install --switch .` when there is no pre-existing local switch
in the current dir.
=> Fix handling of non-existing local switches

doc/pages/Manual.md, src/client/opamAction.ml, src/client/opamAction.mli, src/client/opamArg.ml, src/client/opamSolution.ml, src/format/opamFile.ml, src/format/opamFile.mli, src/format/opamFilter.ml, src/state/opamFileTools.ml, src/state/opamFormatUpgrade.ml, src/state/opamPackageVar.ml, src/state/opamStateConfig.ml
- `build-test:`, `build-doc:` are deprecated
- they should be integrated into `build:` and `install:`, with filters
based on the new variables `with-test`, `with-doc`
- variables `test` and `doc` available in the `depends:`, `depopts:`
fields renamed to `with-test`, `with-doc` for consistency
- likewise, command-line options `--build-test` renamed to
`--with-test`, etc.
- `run-test:` is also available and will be run after `build:`, when
tests have been requested
NOTE: the updated repository migration breaks build/test handling in opam 2.0
up to beta2 (will add the new variables in the package defs). Hold on merging
this to the repo-rewriting opam-admin on opam.ocaml.org/2.0 at least until a
newer beta is released.
=> Clarify the story on building/running/installing tests and doc

src/state/opamGlobalState.ml, src/state/opamGlobalState.mli
Don't Sys.chdir to opamroot
This was intended to solve issues with removed CWD during the run of opam, but
may cause further issues with filename resolution: not worth it for now.
Is a partial revert of "Don't let opam-lib leave empty dirs in /tmp"
(commit 73854c23214f6848b041d5736b5b2ba81d960bf0.)
=> Fix `opam config subst`

src/format/opamTypesBase.ml
I'm using opam-lib v1.3.0 to generate nix packages from the opam-repository with [opam2nix](https://github.com/timbertson/opam2nix-packages). I know opam 2 is coming, so I'm not sure whether opam-lib is also due for an upgrade or is still being actively maintained.
Anyway, I recently upgraded from 1.2.x -> 1.3, and was surprised to see masses of generated URLs go from `https` -> `http`. Simple repro:
```
val url : OpamFile.URL.t = <abstr>
- : OpamTypes.address = ("http://example.com/foo.tgz", None)
```
Looking at the code for `parse_url`, it seems to be splitting on `://` and then looking for _another_ `://`, and if it can't find that then it'll assume http. This PR just returns the original url with protocol included. With that, there's no need for the `git://` branch nor the "assume …
=> parse_url: return actual protocol instead of assuming http

src/client/opamAuxCommands.ml, src/client/opamAuxCommands.mli, src/client/opamCommands.ml
Only affects packages that were pinned to the given target.
Note that specifying an opam file is not supported at the moment, while `opam install <opam-file>` is accepted.
=> Support for `opam upgrade|reinstall|remove <dir>`

src/client/opamAction.ml, src/client/opamAction.mli, src/core/opamDirTrack.ml
I hit this testing ocamlfind on the Windows port. It should be possible to trigger the problem elsewhere by putting an incorrect filename in `ocamlfind.install` (for my particular test I expected the problem - it's to do with opam not knowing to install ocamlfind.exe instead of ocamlfind).
There seems to be a typo in `OpamDirTrack.revert` - it doesn't qualify the filename used when reading the checksum (so I get a stat error).
The other more serious problem is to do with the default directory used for `OpamAction.remove_package` - it assumes that the sources will have been put in the "remove" directory but if something fails during installation then the sources will be in the "build" directory. I have fixed this by adding an optional parameter but this should maybe be thought through so …
=> Fix two glitches when removing failed installations

doc/pages/Manual.md, src/Makefile, src/client/opamClient.ml, src/client/opamClient.mli, src/client/opamCommands.ml, src/client/opamPinCommand.ml, src/format/format.ocp, src/format/opamFilter.ml, src/format/opamFilter.mli, src/format/opamFormat.ml, src/state/opamPackageVar.ml, src/state/opamPath.ml, src/state/opamPath.mli
Note: stacking the config-files is done per field: the latest
definition for any given field overrides the previous ones.
Some might want to be able to merge e.g. repository definitions from
several config files, though ? That would be more complex... but in
practice, if you redefine e.g. `eval-variables:`, you need to include
the def for `sys-ocaml-version` or the default repository would be
broken.
=> Some more customisation for `opam init`; some var resolving fixes in `depends`

src_ext/Makefile
d7bf17fffe354ea0ca72b385ac500a016d78e4b9 reverted a change in c87c77cfec457e3c1410bce5848326910c9228c4 breaking opam-admin.top when compiled
using lib-ext.
=> Fix lib-ext build of extlib

.travis-ci.sh, doc/pages/Manual.md, src/format/opamFilter.ml, src/format/opamFormat.ml, src/format/opamTypes.mli, src_ext/Makefile
See also https://github.com/ocaml/opam-file-format/pull/4 - this PR should have a commit updating `src_ext` before it is merged.
The `?` operator evaluates to false if the expression is undefined (i.e. contains undefined variables) and true in all other instances.
This operator removes the need for evil uses of `"%{variable}%"` (which expands to an empty string if variable is undefined). In particular, for the `ocaml-system` package, it allows a slightly less unclear `available` field:
```
available:
sys-ocaml-version = "4.02.2" &
!(?switch-arch & switch-arch != sys-ocaml-arch) &
!(?switch-cc & switch-cc != sys-ocaml-cc) &
!(?switch-libc & switch-libc != sys-ocaml-libc)
```
=> Add ? operator to filter syntax

doc/pages/Install.md
Update the install documentation for Ubuntu to make it clear that opam is available via apt for "recent" releases.
Also remove the paragraph about broken releases, since the two affect releases are waaaaay out of support.
=> Update Ubuntu install instructions

Makefile, src/Makefile, src_ext/Makefile
Patch Makefile to support total clean of source tree via make distclean and ensure that it can be run twice (so don't attempt to regenerate Makefile.config)
=> Support make distclean at toplevel

src/client/opamAction.ml, src/client/opamAdminCommand.ml, src/client/opamCommands.ml, src/core/opamProcess.ml, src/core/opamSystem.ml, src/format/opamFile.ml, src/format/opamFile.mli, src/state/opamFormatUpgrade.ml
Adds a "stamp" field for repositories served over HTTP, and useful info to process error reports during package builds
=> Helpers to track build and package errors

src/client/opamAction.ml, src/client/opamCommands.ml, src/repository/opamDarcs.ml, src/repository/opamGit.ml, src/repository/opamHTTP.ml, src/repository/opamHg.ml, src/repository/opamLocal.ml, src/repository/opamRepository.ml, src/repository/opamRepositoryBackend.ml, src/repository/opamRepositoryBackend.mli, src/repository/opamRepositoryPath.ml, src/repository/opamRepositoryPath.mli, src/repository/opamVCS.ml, src/repository/opamVCS.mli, src/state/opamPath.ml, src/state/opamPath.mli, src/state/opamUpdate.ml
This should speed things up a lot when downloading the same git repositories
(or different forks) multiple times; it needs some testing, though, and we
need to consider what happens if the cache is wiped (the local git clones
might still rely on it).
As usual, there might also be issues with older git versions. Concurrent 
downloads _should_ work, but we need to verify that too.
It already gives a huge speedup when pinning lots of packages to the same
repository, though.
=> Experiment: add a global cache of git objects

.gitignore, .merlin.in, .travis-ci.sh, CHANGES, Makefile.config.in, README.md, configure, configure.ac, opam-core.opam, src/Makefile, src/core.META.in, src/core/core.ocp, src/core/opamJson.ml, src/core/opamJson.mli, src_ext/Makefile
Remove the `jsonm` and transitive `uutf` dependency. 
This allows to ease debian bootstrapping: latest versions of `jsonm` and `uutf` use `topkg` and hence `opam-installer` which is provided by `opam` itself.
@AltGr note that the output is now minified which used not to be the case. I hope it's not a problem as it allows for a very simple encoder implementation. If people need to read the json they can always pipe the output into `jsontrip -pp`.
/cc @hendriktews
=> Get rid of jsonm dep

shell/opam_installer.sh
If 4.05.0 seems too recent I'm happy to replace with 4.04.2, but 4.02.1 seems definitely wrong.
=> update default ocaml compiler to latest release

doc/Makefile
This allows building the docs even without jbuilder on the PATH.
There's some code duplication which I'm not sure how to fix, since the relative path needs to be different for the two Makefiles.
=> Use jbuilder from src_ext in doc Makefile

src_ext/Makefile
This is good practice anyway but I'm also seeing the downloads fail with curl using the HTTP URL.
The remaining, non-GitHub HTTP URLs don't appear to support HTTPS due to certificate issues.
=> Use HTTPS for all GitHub URLs

doc/pages/Install.md
It appears that the link to the rpm in the installation instructions is not working anymore. I believe [this is the correct one](https://software.opensuse.org/package/opam).
=> fixing outdated link to OpenSUSE build server in Install.md

src/client/opamArg.ml, src/client/opamClientConfig.mli, src/state/opamStateConfig.ml, src/state/opamStateConfig.mli, src/state/opamSwitchState.ml
This makes single commands such as `opam upgrade ocaml --unlock` possible
=> Add option '--unlock-base' to change the compiler

doc/pages/Manual.md, src/client/opamAdminRepoUpgrade.ml, src/client/opamArg.ml, src/client/opamClient.ml, src/client/opamListCommand.ml, src/client/opamListCommand.mli, src/format/opamFile.ml, src/format/opamFilter.ml, src/format/opamFilter.mli, src/solver/opamSolver.ml, src/solver/opamSolver.mli, src/state/opamFileTools.ml, src/state/opamPackageVar.ml, src/state/opamPackageVar.mli
This resolves #2649, and provides a solution for ocaml/opam-repository#7543, and a better story for `base` packages (#2996). It also allows to have the `ocaml` package be installed with the switch, rather than lazily afterwards, which apparently created some confusion.
Two notes though:
- maybe find a better name ? Dependencies tagged `reverse` may, or may not, actually be reverse dependencies (e.g. `a` with `depends: ["b" {reverse}]` does not imply that `b` depends on `a`, although that may often be the case). Better avoid this kind of confusion
- ~~I added the flag before realising that it was mostly equivalent to just specifying `!build`, which may actually be easier to understand (a dependency that is not active at build time). So we could remove commit ae4f3764, and adapt the …
=> Add a 'post' dependency flag.

src/client/opamAdminRepoUpgrade.ml
The hardcoded `base` packages don't have the `ocaml` dependency added, and
can't have their `available:` rewritten as dependencies to the
`ocaml-xxx` implementation packages. This was due to the ordering problem that
`{post}` dependencies fixed, so they could be removed altogether, but let's
not change more than necessary.
=> repo upgrade: remove base-metaocaml-ocamlfind from hardcoded base packages

src/client/opamAction.ml, src/client/opamClient.ml, src/client/opamMain.ml, src/core/opamProcess.ml, src/core/opamProcess.mli, src/core/opamStd.ml, src/core/opamStd.mli, src/core/opamSystem.ml, src/core/opamSystem.mli, src/repository/opamRepositoryConfig.ml, src/solver/opamCudfSolver.ml, src/state/opamEnv.ml, src/state/opamFormatUpgrade.ml
Work around bug in OCaml 4.05.0: https://caml.inria.fr/mantis/view.php?id=7640
The resolution is only done for non-qualified command paths
=> Resolve paths of commands before calling Unix.execvpe

doc/index.html, src/client/opamAction.ml, src/client/opamArg.ml, src/client/opamCommands.ml, src/client/opamInitDefaults.ml, src/core/opamProcess.ml, src/core/opamStd.ml, src/core/opamStd.mli, src/core/opamSystem.ml, src/state/opamEnv.ml, src/state/opamFormatUpgrade.ml, src/state/opamGlobalState.ml, src/state/opamPackageVar.ml, src/state/opamSwitchAction.ml, src/state/opamSysPoll.ml, src/state/opamSysPoll.mli, src/tools/opam_installer.ml
This includes definition of the `arch`, `os`, `os-distribution`,
etc. variables, to be used anywhere in packages. The code of
`opam-depext` will also be much simpler, only the interaction with the
host package manager will remain.
Closes #3058
=> Following #3058, this brings the system detection code in

src/client/opamSolution.ml, src/solver/opamActionGraph.ml, src/solver/opamActionGraph.mli
packages that were going to be removed weren't passed properly as installed.
This should fix #3079
=> Fix universe passed to package actions before removals

src/client/opamAction.ml, src/client/opamMain.ml, src/core/opamFilename.ml, src/format/opamPath.ml, src/format/opamPath.mli, src/state/opamEnv.ml, src/state/opamEnv.mli
i.e. making the latest installed instance of the plugin available
across switches (an existing instance from the current switch still
prevails).
This is simply done through a symlink in ~/.opam/plugins/bin, which is
removed on uninstall.
=> This implements #3102, globally providing plugins for convenience

doc/pages/Manual.md, src/format/opamFilter.ml
After some discussion with @dra27, it seems in general safer to hold the 
positional argument with an empty string rather than shift the possible 
remaining arguments.
So for example, with
build: ["some-command" foo "bar"]
Previously, if `foo` wasn't defined, that would become `["some-command"
"bar"]`. To avoid that, you had to use a string interpolation such as:
build: ["some-command" "%{foo}%" "bar"]
which is a little heavy under the fingers. With this patch, the behaviour
would be the same.
Obtaining the previous behaviour is still possible by using an explicit 
filter:
build: ["some-command" foo {?foo} "bar"]
which makes it explicit that the positional argument might be present or not
=> In commands, resolve undefined to "" rather than no argument

src/client/opamCommands.ml
In the 1.2.2 manual, `opam help list` held the following:
DESCRIPTION
This command displays the list of installed packages when called
without argument, or the list of available packages matching the given
pattern.
Unless the --short switch is used, the output format displays one
package per line, and each line contains the name of the package, the
installed version or -- if the package is not installed, and a short
description. In color mode, root packages (eg. manually installed) are
underlined.
In opam 2.0, the underlined mention has disappeared:
DESCRIPTION
List selections of opam packages.
Without argument, the command displays the list of currently installed
packages. With pattern arguments, lists all available packages matching
one of the patterns.
See section PACKAGE SELECTION …
=> opam-list: explain in man why some listed packages are underlined

shell/install.sh
Fixes the case where on some systems "du" prints the summary with the
unit (K) appended, causing an error like the following:
./install.sh: 213: [: Illegal number: 6593020K
=> install.sh: Fix use of "du" to always use -k

configure, m4/ocaml.m4
A minor niggle, but rather annoying doing the Windows testing when configure picks up another installation's ocamlfind and assumes there are working packages!
The changes are prepared for upstream in https://github.com/dra27/ocaml-autoconf/tree/various-improvements and noted on [the OCaml Forge](https://forge.ocamlcore.org/tracker/index.php?func=detail&aid=1471&group_id=69&atid=363), but ocaml-autoconf isn't very actively maintained.
=> Ensure ocamlfind is from a compatible installation

src/client/jbuild
Hi:
When opam is built in an isolated environment `git rev-parse` which pollutes the build output
=> Silence errors in git rev-parse command

src/client/opamAdminRepoUpgrade.ml, src/state/opamFileTools.ml, src/state/opamFileTools.mli, src/state/opamFormatUpgrade.ml
when that variable refers to `darwin` (or `osx`, which was probably a
mistake, but there are some occurences)
Closes #3148
=> Fix the format upgrade of filters mentionning the 'os' variable

src/core/opamSystem.ml
`OpamSystem.resolve_command` caches results. This cannot work - the ocamlfind package, for example, installs an `ocaml` script which is intended to wrap the system-installed `ocaml` command. This script is not invoked if `ocaml` has been previously executed, because the path to the system-installed `ocaml` command is cached.
There are various shims which could mitigate this for opam-installed binaries/scripts only, but it seems better just not to cache the results at all.
=> Disable caching in OpamSystem.resolve_command

src/solver/opamCudf.mli, src/solver/opamSolver.ml
This helps the solver a lot by penalising older versions more (and thus
making the decision of which package to roll back easier), and solves,
albeit not by a large margin, #3161.
=> Make `version-lag` cubic

shell/context_flags.ml, src/client/opamClient.ml, src/client/opamSwitchCommand.ml, src/core/jbuild, src/core/opamCompat.ml.4.01, src/core/opamCompat.ml.4.02, src/core/opamCompat.ml.4.03, src/core/opamCompat.ml.4.05, src/core/opamCompat.ml.4.06, src/core/opamCompat.mli.4.01, src/core/opamCompat.mli.4.02, src/core/opamCompat.mli.4.03, src/core/opamCompat.mli.4.05, src/core/opamFilename.ml, src/core/opamStd.ml, src/core/opamStd.mli, src/core/opamSystem.ml, src/format/opamFile.ml, src/format/opamPp.ml, src/solver/opamCudfSolver.ml, src/state/opamGlobalState.ml, src/state/opamRepositoryState.ml, src/state/opamSwitchState.ml
This should finally enable us to get usable backtraces without hacks!
=> Add some handling to preserve backtraces through wrappers on OCaml 4.05+

src/client/opamArg.ml, src/client/opamConfigCommand.ml, src/client/opamMain.ml, src_ext/Makefile
=> Fix PATH lookup for `opam exec` on OCaml 4.06

appveyor.patch
Let AppVeyor run first, just in case actual coding errors had been missed...
=> Fix AppVeyor native builds

src/repository/opamGit.ml
`opam update` failed several times due to external git diff driver.
I use:
```
GIT_EXTERNAL_DIFF=/home/user/.opam/4.05.0/bin/patdiff-git-wrapper
```
```
...
00:01.000  PARALLEL                Collected task for job 0 (ret:0)
00:01.000  PARALLEL                Next task in job 0: /usr/bin/git add .
00:01.005  PARALLEL                Collected task for job 0 (ret:0)
00:01.005  PARALLEL                Next task in job 0: /usr/bin/git diff -R -p refs/remotes/opam-ref --
00:01.010  PARALLEL                Collected task for job 0 (ret:128)
00:01.010  SYSTEM                  rm /home/user/.opam/log/git-diff-19973-5f1023
00:01.010  SYSTEM                  error: Git error: refs/remotes/opam-ref not found.
```
```
$ opam --version
2.0.0~beta6
```
=> Force git diff to not use external diff

src/core/opamUrl.ml
It seems safer to exclude the extra `/` in this case when converting to the 
normal `[git+]ssh://name@host/foo`
Closes #3211
=> Fix handling of addresses in the form 'name@host:/foo'

configure, configure.ac
MCCS will be automatically disabled if no C++ compiler is found; an error will occur if `--with-mccs` is specified and no C++ compiler is present.
=> Ensure a C++ compiler exists if MCCS is enabled

src_ext/Makefile, src_ext/Makefile.sources, src_ext/update-sources.sh
Did you miss me?
Updates cppo to 1.6.2 in src_ext and also includes a little tweak to disable cppo's ocamlbuild plugin in src_ext mode (it's a nuisance if, like me, you more regularly type `jbuilder build` than `make`). The upgrade to 1.6.2 eliminates a jbuilder warning from cppo's test `jbuild` file (see also AltGr/ocaml-mccs#5)
I got bored of updating these references by hand, so I ~wasted~ invested a little time in a script. It has colours and everything. Blow away 7ac96c2 and run `src_ext/update-sources.sh` for colour-based update-prettiness...
=> src_ext management script

src/client/jbuild
The good: no OCaml syntax `jbuild` file any more
The bad: the trick to achieve this, but still have the current git SHA is almost as evil as OCaml syntax `jbuild` files
The intermediate: I'll discuss with Dune devs whether we could have a `mode` option in the `rule` stanza which can do this less evily.
=> Eliminate the ocaml-mode jbuild file in the client

src/client/opamCommands.ml
Fixes #3245: pin_target is now smart enough to detect Janestreet's
version naming convention as a version and not as a directory.
=> Fixes the version parsing starting with 'v' for pinning.

src/client/opamAuxCommands.ml, src/client/opamAuxCommands.mli, src/client/opamCommands.ml, src/client/opamListCommand.ml, src/client/opamPinCommand.ml, src/client/opamPinCommand.mli, src/format/opamFilter.ml
and add a `--no-lint` option
The interface is still a little weird if you query the `url` field, since this
goes through a local pinning: you will get the local dir.
=> Fix 'opam show <dir|file>'

src/state/opamFileTools.ml
This PR fixes the issue https://github.com/ocaml/opam/issues/3208. 
It adds a warning in case of space character or an empty string in `depexts` field.
And a tiny fix on linter error/warning numbering.
=> linter checks spaces and empty string on 'depexts' field

src/state/bwrap.sh
The `OPAM_SWITCH_PREFIX` was not bind on build with bwrap, causing some `opam-rt` test failure.
=> bwrap: add opam switch prefix bind for build

src/client/opamConfigCommand.ml, src/client/opamSwitchCommand.ml, src/core/opamFilename.ml, src/core/opamFilename.mli, src/core/opamSystem.ml, src/core/opamSystem.mli, src/state/opamEnv.ml, src/state/opamFormatUpgrade.ml, src/state/opamGlobalState.ml, src/state/opamRepositoryState.ml, src/state/opamSwitchState.ml
File locking behaves differently under Windows - if a file is to be written or read using a lock, then the same fd needs to be used. Alter the OpamFilename.with_flock functions to pass the fd of the lock file
instead of unit.
=> Pass fd to functions in OpamFilename.with_flock*

src/core/opamStd.ml, src/core/opamStd.mli
At present, opam bases shell detection entirely on `$SHELL`. This is fine for the default shell, but doesn't cope with a shell launched from another shell.
This PR adds various mechanisms based on `/proc` and `ps` which I believe should work for both Linux and the BSDs. If all three mechanisms fail, it falls back to $SHELL. Note that in this context, "fail" means "doesn't identify a shell" (so, for example, if for some strange reason you start `fish` using a symlink called `fishy`, then opam will continue to inspect `$SHELL`).
=> Better shell detection

src/repository/opamDarcs.ml, src/repository/opamGit.ml, src/repository/opamHTTP.ml, src/repository/opamHg.ml, src/repository/opamLocal.ml, src/repository/opamRepository.ml, src/repository/opamRepositoryBackend.ml, src/repository/opamRepositoryBackend.mli, src/repository/opamVCS.ml, src/repository/opamVCS.mli
* Adds [repo_update_complete] to the signature of {OpamRepositoryBackend.S}
and calls it after an update is validated to provide the VCS backend with
the opportunity to reset the working set explicitly. Mercurial requires
this after the patch is applied to update its internal state tracking the
identity of the changeset. Also, the Mercurial handler has various updates
to improve correctness in the presence of a) subrepositories, b) multiple
heads on the same branch, and c) bookmarks on the server.
=> Issue #3281: Improve 'opam update' with repositories of kind 'hg'.

src/client/opamAdminCheck.ml, src/core/opamStd.ml, src/core/opamStd.mli, src/format/opamFilter.ml, src/format/opamFilter.mli, src/format/opamFormula.ml, src/format/opamFormula.mli, src/format/opamTypesBase.ml, src/format/opamTypesBase.mli, src/solver/opamCudf.ml, src/solver/opamSolver.ml, src/solver/opamSolver.mli
by reviewing the whole loading process, this achieves x2 speedup on a basic `opam install` run.
Involved changes:
- optimise and make tail-rec some functions on the manipulation of formulas (e.g. add cases for CNF conversion when trivial, which is thankfully most of the time)
- review opam to cudf conversion to be based on computing maps from the universe and running `Map.merge` (rather than converting packages one by one)
- simplify handling of optional dependencies when activated, since these are only used to build the dependency graph
- factorise as much as possible the loading between runs with different flags (build, post, opt), including CNF conversion
This also includes a fix in computing the dependency graph, which was
over-approximating dependencies in some cases with …
=> Big optimisation pass on universe loading

src/client/opamCommands.ml
The output looks roughly like this (plus emphasis).
```
add NAME [ADDRESS] [QUORUM] [FINGERPRINTS]
Adds under NAME the repository at address ADDRESS to the list of
configured repositories, if not already registered, and sets this
repository for use in the current switch (or the specified scope).
ADDRESS is required if the repository name is not already
registered, and is otherwise an error if different from the
registered address. The quorum is a positive integer that
determines the validation threshold for signed repositories, with
fingerprints the trust anchors for said validation.
Note: By default, the repository is only be added to the current
switch. To add a switch to other repositories, you need to use the
--all or --set-default options (see below). If you want to enable a …
```
=> add an explicit warning about the single-switch behavior of `repo add` (#3292)

src/client/opamClient.ml
This PR is about warning and error message:
- at `update`, if nondev packages are given as argument, an explicit message is displayed, and returns with the good return code (Sync Error). It is related to #2951.
- at `install`, if an `update` has not been done since a while (3 weeks), a note invites the user to update repositories. It is related to #2999.
=> Messages at `update` and `install`

src/client/opamCommands.ml, src/core/opamStd.ml, src/core/opamStd.mli
The list of configuration files being consulted (the first "NOTE" from `opam init`) displays the files in ascending order of priority which is not wholly intuitive. I've tweaked the wording so that the note now appears as:
```
[NOTE] Will configure from /home/dra/.opamrc, then /etc/opamrc, and finally from built-in defaults.
```
or
```
[NOTE] Will configure from /home/dra/.opamrc and then from built-in defaults.
```
I've also added, but then not used, a `?last_sep` parameter to `OpamStd.List.concat_map` which allows you to have lists written `x and y` or `x, y and z` (or even `x, y, and z` if you are so inclined). There are definitely other places in the client where the messages could be augmented by use of that parameter.
=> Try to improve opam init message about configuration files

src/client/opamClient.ml, src/client/opamClientConfig.mli, src/client/opamCommands.ml, src/client/opamConfigCommand.ml, src/client/opamConfigCommand.mli, src/state/opamEnv.ml, src/state/opamEnv.mli, src/state/opamStateConfig.ml, src/state/opamStateConfig.mli
This PR contains an update of shell configuration scripts to have always opam variables set (evaluation at each command). It was inspired from [direnv](https://github.com/direnv/direnv) (thanks @samoht). Available for all opam handled shells.
For `bash`, I kept sourcing scripts on profile config files (cf. #1447), assuming that profile files are sourced in `.bashrc`. Added a message for the user in this case.
=> Shell config update

src/client/opamCommands.ml, src/core/opamStd.ml, src/core/opamStd.mli, src/core/opamSystem.mli, src/repository/opamRepository.ml, src/repository/opamRepositoryPath.ml, src/repository/opamRepositoryPath.mli
When running `opam pin distant_url`, there was a first download of the archive
or git repo to guess package name, and another ones for every package name
found. This PR adds a cache for these case of pin, in order to download
only once.
=> Cache for pin download

src/client/opamAdminRepoUpgrade.ml
The config-generation scripts in the `ocaml` and `ocaml-system` packages don't take the `.exe` extension on Windows **and Cygwin** into account. Proposing this now to solve Cygwin, as that should be otherwise working in 2.0.0.
The `set_binary_mode_in` is for native Windows - it should have no effect on any other platform, but on Windows it will cause the trailing `\r` in the output of `ocamlc -where` to be stripped (which is the behaviour required).
=> Fix ocaml-system and ocaml scripts for Windows

src/client/opamClient.ml
The error message given when an "opam upgrade" leaves some
packages alone because newer versions would conflict with other
installed packages was confusing to naive users. The new one is a bit
longer and much more explicit.
This is a partial fix for #3334.
=> Improve an error message in "opam upgrade"

doc/pages/Manual.md, src/client/opamAdminRepoUpgrade.ml
This builds on the feature added in #3343 and enables the following user experience:
```
dra@bionic:~$ opam install graphics
The following actions will be performed:
∗ install graphics 1.0 
<><> Gathering sources ><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
[ERROR] The compilation of graphics failed at "/home/dra/.opam/opam-init/hooks/sandbox.sh build ocamlc -custom graphics.cma -o test".
#=== ERROR while compiling graphics.1.0 =======================================#
<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
┌─ The following actions failed
│ λ build graphics 1.0
└─ 
╶─ No changes have been performed
<><> graphics.1.0 troubleshooting …
```
=> Recompile ocaml-system on (dis)appearance of graphics.cmi

Makefile, configure, configure.ac, src/core/opamCompat.ml, src/core/opamCompat.mli, src/core/opamConsole.ml, src/core/opamFilename.ml, src/core/opamFilename.mli, src/core/opamStd.ml, src/core/opamStd.mli, src/core/opamSystem.ml, src/core/opamSystem.mli, src/core/opamUrl.ml, src/tools/jbuild, src/tools/opam_check.ml, tests/Makefile, tests/packages/P1-1/P1.config.in, tests/packages/P1-2/P1.config.in, tests/packages/P2/P2.config.in, tests/packages/P3/P3.config.in
This is a first chunk of #3260, separated off. Hopefully these are the non-controversial parts.
=> Various bits 'n bobs

src/client/opamClient.ml, src/client/opamSwitchCommand.ml, src/core/opamSystem.ml, src/core/opamSystem.mli, src/state/opamRepositoryState.ml
Another bit from #3260.
These three commits are worth looking at individually.
- `Close all lock files on error`: this, as you noted in #3260, this shouldn't be necessary, but given that any coding error could result in this, I'd prefer to keep it. It could possibly be extended to display warnings if `OpamSystem.release_all_locks` actually has to release any locks? It would seem to be much better to have warnings displayed, which need fixing, than to get error messages about being unable to remove a directory (in this case `~/.opam`), as failing to delete the directory in this instance will probably result in worse error messages for the user on the next command they run.
- `Fix file locking on Windows`: this is sound, though could potentially result in the loss of the lock to another …
=> Fix file locking on Windows

Makefile, README.md, doc/pages/FAQ.md, doc/pages/Manual.md, src/client/opamClient.ml, src/format/opamFormat.ml
This PR contains:
- Some documentation fixes
- Formula printer: print inner parenthesis, even if it is in a `Block`, to avoid conflicts on regenerated `opam` files 
- Improve upgrade message in case of conflict (related to #3334)
- Fix manpage installation: they need to be generated before `opam-actual.install` generation, in order to be installed by `opam-installer` (close #3318)
=> Doc fix, formula printer & upgrade message

src/client/opamAdminRepoUpgrade.ml, tests/Makefile
This fixes `opam install -t opam-devel` by:
- ignoring the archive hash cache update when the file can't be written to
- disabling sandboxing within `make tests`
=> Make it so that 'make tests' can pass from within opam

src/client/opamListCommand.ml
=> opam show: string fields printed with quotes, as lists

src/format/opamFilter.mli, src/format/opamFormat.mli
When generating the docs with `dune build @doc` and odoc master,
the new parser emits some warnings. This fixes some of the markup
to be more compliant.
=> improve the formatting of docstrings with odoc master

src/state/opamEnv.ml
Prior to this patch, a fresh install of opam (master) did not copy complete.sh to the opam-init folder.
=> opam init --bare: Copy bash completion script to opam-init

src/client/opamAction.ml, src/client/opamAction.mli, src/client/opamAdminCommand.ml, src/client/opamCommands.ml, src/client/opamPinCommand.ml, src/client/opamSolution.ml, src/format/opamTypes.mli, src/repository/opamDownload.ml, src/repository/opamDownload.mli, src/repository/opamHTTP.ml, src/repository/opamLocal.ml, src/repository/opamRepository.ml, src/repository/opamVCS.ml
This PR closes #3393.
It adds two levels of download error message: a short one to be displayed on normal mode and a more complete one on verbose mode (when it is needed, when the message itself is short, it is the same on both modes). For the moment, no specific error download message is displayed to user, it is only filled on json file output when option is set.
=> Download error message

src/state/shellscripts/bwrap.sh, src/state/shellscripts/sandbox_exec.sh
fixes #3395 
cc @AltGr, @avsm 
I have tested the patchset on my machine (Linux, ccache installed). I have not tested it on macos (so the `sandbox_exec.sh` change is untested), or on a machine without ccache.
@AltGr is there a way to factorize common code between the two files?
This implementation ignores the CCACHE_DISABLED setting: it will add the cache directory (rw) even if ccache is available but disabled in the system. I could take this into account (there is a line of the `--print-config` output that tells whether ccache is currently disabled), but I thought it wasn't worth the trouble and extra script complexity.
=> if 'ccache' is installed, add its cache directory to the sandbox (rw)

.travis-ci.sh
Fix Travis jobs with test, with no cache, there is an error on init, which results to an invalid opam root.
=> Travis: opam boostrap version

src/client/opamArg.ml, src/client/opamArg.mli, src/client/opamClient.ml, src/client/opamClient.mli, src/client/opamCommands.ml, src/client/opamSolution.ml, src/client/opamSolution.mli
This PR is related to this issue #3380.
If a package `foo` is locally pinned, option `--assume-built` can be set to skip build steps and perform only install commands. 
If a package is not locally pinned and the option is set, it will be skipped.
Packages dependencies are *locked* on their current version: if a dependency `bar` of the package `foo` needs an upgrade, and a `foo` install with `--assume-built` is launched, opam won't propose to upgrade the dependency  `bar` and reinstall `foo`. 
EDIT:
- Add the option to `reinstall`
- Always reinstall `foo` with the option (even if no changes detected)
- if a package `baz` depends on `foo`, on `foo` reinstall `baz` will be recompiled/reinstalled (even if non-locally pinned).
=> Add `--assume-built` option

src/state/shellscripts/sandbox_exec.sh
This PR, on top of #3399 (which switched sanbbox_exec.sh to `bash` instead of `sh`), use POSIX-friendly shebangs `/usr/bin/env bash -ue` instead of `/bin/bash -ue` as suggested by @hannesm. I don't know enough about the porability issues underhand to decide whether that's a good move, but the PR is here for consideration.
=> Posix shebangs

doc/pages/Upgrade_guide.md, src/core/opamSystem.ml
A rather more controversial part of #3260!
~This relies on ~two~three bits of #3346, but the actual content of this PR still needs work/discussion anyhow.~
Further comment ~to follow~ below.
=> Adapt patch behaviour for LF/CRLF compatibility

doc/pages/Manual.md, src/client/opamCommands.ml, src/client/opamConfigCommand.ml, src/client/opamPinCommand.ml, src/core/opamStd.ml, src/core/opamStd.mli, src/state/opamEnv.ml
This PR closes #3391.
- It fixes `OpamStd.split_delim` implementation which had the same behaviour than `OpamStd.split`. Now they respectively keep & clean empty strings from the returned list.
- An option is added to `OpamStd.Sys.split_path_variable`, permiiting to retrieve a cleaned path or no.
- A fix on environment variables construction, in order to keep the trailing delimiter when it should be.
edit:
- Fix #3403: on local pin, versionned directory, if opam file is not versionned retrieve the one found locally in source directory
- ~Fix # 3398: Escape json extended ascii characters~
- Update pinning doc
=> Fixes: Env var & delimiters, unversionned opam file pin, doc

src/state/shellscripts/bwrap.sh
Previously, `/tmp` was made a dedicated tmpfs; but that completely
breaks running from an opam root within /tmp.
=> bwrap script: allow writes to /tmp

src/state/opamEnv.ml
even if the files have been moved / the switch renamed.
This is not a complete fix to #3411 (doesn't add a warning, and the PATH
will only become correct once a package operation has been done), but
avoids the pathological cases.
=> Ensure OPAM_SWITCH_PREFIX is correctly set by `opam env`

src/state/opamFileTools.mli
Warning 52 is the "needless `light-uninstall`" warning. Warning 53 is "mismatching extra-files".
=> Wrong warning number in comment

src/client/opamAction.ml, src/client/opamSolution.ml, src/repository/opamDownload.ml, src/repository/opamRepository.ml
This PR update the download error message display: 
- Fix a lost short message propagation
- by default always show the short one, and the long one in verbose mode
=> Update download error message

src/client/opamCommands.ml
`opam init -i --enable-xx` would enable `xx` and confirm the rest. It
will now ignore the rest, and ask to confirm enabling `xx`.
=> CLI fix for 'opam init'

src/client/opamSolution.ml, src/format/opamTypes.mli, src/repository/opamRepository.ml
This PR completes commit 5ec161401d51c2e153e5467bead902fcab21bc4b (https://github.com/ocaml/opam/pull/3428#issuecomment-401756482), that introduced an error raised on the first mirror cache fail, and some typos.
=> Don't raise error when retrieving mirror cache fails

src/core/opamFilename.ml, src/core/opamFilename.mli, src/core/opamSystem.ml, src/core/opamSystem.mli, src/repository/opamRepository.ml
This PR is a partial fix for #3433. For patches generated by opam (http & local backends), CRLF translation is not performed.
=> No CRLF translation for opam generated patches

src/client/opamCommands.ml
This PR adds version control guess on `opam repo add` and `opam repo set-url` commands.
=> Guess version control on repo add

src/state/shellscripts/bwrap.sh
On Qubes `/usr/local/` is usually a symlink to `/rw/usrlocal/`.
I had trouble installing `cpuid` because it calls out to `opam`, but since `/usr/local/` is a symlink to the unmounted path `/rw/usrlocal/` the `opam` binary in `/usr/bin/` got precedence.
=> Add /rw/usrlocal to bwrap.sh

src/core/opamSystem.ml, src/core/opamSystem.mli, src/repository/opamRepositoryPath.ml
More consistent doc &  temporary directory functions use.
=> OpamSystem temp dir

src/client/opamArg.ml, src/client/opamAuxCommands.ml, src/client/opamAuxCommands.mli, src/client/opamClientConfig.mli, src/client/opamCommands.ml, src/client/opamPinCommand.ml, src/state/opamPinned.ml, src/state/opamPinned.mli, src/state/opamStateConfig.ml, src/state/opamStateConfig.mli
there is no reason it should be available in 'opam install' and not
'opam pin'; this also avoids the issue that 'opam update PKG' would not
accept the --locked option and detect a changed opam file.
There is still a few corner-cases, the combination with the
pinned-package-update can sometimes be a bit strange.
=> Make '--locked' a full-fledged build option

src/state/shellscripts/env_hook.fish, src/state/shellscripts/env_hook.sh, src/state/shellscripts/env_hook.zsh
This PR fixes #3431, stderr is dropped in order to not pollute user shell in case of inconsistent opam state or uninstalled opam.
- Working on bash, sh, zsh, and fish (csh do not permit redirecting only stderr)
- With fish, do not handle inexistant opam binary, the error is raised at fish level
=> Redirect shell hook stderr to /dev/null

src/client/opamAdminCommand.ml
This is still WIP: cache should be saved at some interval, not just at
the end, and hashes other than source (e.g. extra-sources) are not
considered.
=> "opam admin add-hashes" helper to add more secure hashes to the repo

src/client/opamCommands.ml, src/client/opamListCommand.ml, src/client/opamListCommand.mli
Currently, if a package is pinned, opam retrieves package information from the switch.
This PR fixes #3423.
=> opam show with local opam file returns local file information

doc/pages/Install.md, src/client/opamInitDefaults.ml, src/core/opamSystem.ml
This PR is a partial fix for #3433, more specifically https://github.com/ocaml/opam/issues/3433#issuecomment-400346546.
It conflicts with #3443, need to be rebased before merge.
=> Use gpatch on openBSD

src/core/opamSystem.ml
This is still slightly in progress.
The first commit fixes `OpamSystem.translate_patch` corrupting binary patches by incorrectly applying CRLF transformations. The revised version both detects that a file has mixed line endings (i.e. some are CRLF and some are LF) and does the same thing with *all* the chunks of the patch. If either the file being patched or the patch chunks themselves have mixed endings, then no translations occur. The edge cases for binary files which happen to be CRLF or LF encoded are also sound (the patch will either maintain them and, if it changes the "endings" then the `+` lines and `-` lines would have different endings which would also disable the function).
However, doing that has made the original function even uglier than it was and so the following commit …
=> Fix binary patching

src/core/opamConsole.ml
The sequence `[m` was replaced with `[0m` in #3346 which required an additional case in the VT-100 translator in OpamConsole. Not quite sure how I missed this one, as `opam init` fails (I think it's because for ages now I've been using the testsuite, which of course pipes the output and so disables colour)...
=> Missing case in Windows VT-100 translator

src/state/shellscripts/bwrap.sh
Before this change, the invocation to `bwrap` assumed `TMPDIR=/tmp` and/or that scripts hardcode `/tmp`. This binds `/tmp` in the bubblewrap to the host `TMPDIR` and then points all tmp-related env vars to `/tmp`. Notably, this makes `opam` work better on NixOS. It may also affect which temp dir gets used on other systems.
=> Respect user's TMPDIR when invoking bwrap

src/core/opamSystem.ml, src/repository/opamRepository.ml
This PR closes #3497.
If a `tar` extract fails, it checks the presence of underlying command (`bzip2`, `xz`, `lzma`, `gzip`) to display the error message in verbose mode.
=> Tar extract fail error message

shell/install.sh
In some OSX installations there is no `root` group so this command fails, if we instead default to `-g 0`, it will install correctly using the `wheel` group
=> install.sh: use `-g 0` instead of `-g root`

shell/install.sh
On some macOS versions openssl doesn't come with sha256 support by default:
```
[~] openssl sha512 < /dev/null
openssl:Error: 'sha512' is an invalid command.
```
If that's the case the installation script currently fails with a checksum mismatch, which is not desiderable
=> Don't continue with checksum check if openssl sha512 is unavailable

src/client/opamCommands.ml, src/client/opamPinCommand.ml, src/state/opamPinned.ml, src/state/opamPinned.mli
If an `opam pin --edit` concerns an opam file not defining the field `name`, an error is raised
```
$ opam pin --edit opam-core --dev -n
Fatal error:
Field 'name:' is required
```
=> pin edit: fix editing an opam file whithout a name field

src/client/opamInitDefaults.ml, src/core/opamSystem.ml
OpenBSD tar does not support the ‘J’ flag
=> Update OpenBSD support, OpenBSD requires gtar

.gitignore, Makefile, doc/Makefile
At the moment a jbuilder-less installation cannot do `sudo make install` because opam attempts to build things. I believe the GNU standards recommend that `make` should do everything necessary so that `make install` doesn't have to build anything. This PR attempts to move towards that. You can now run:
- `./configure`
- `make lib-ext`
- `make opam-actual.install`
- `sudo make install`
in an environment which *only* has OCaml installed.
=> Steps towards sudo-enabled make install

shell/install.sh
```sh
mkdir: /usr/local/bin: Permission denied
```
=> install.sh: xsudo when creating bin dir

src/state/shellscripts/bwrap.sh
- add usage OPAM_USER_PATH_RO environment variable for setting
unusual paths in mount bind_ro list
- remove some unusual path from the script (/nix/store /rw/usrlocal)
- fix problem of build in the sandbox
Some modules generates an error if the complete infra of {opam_root}
is not seen in the sandbox
-> [ERROR] /work/CG-2.1/_build/_opam exists, but does not appear
to be a valid opam root.....
They also need to write in $(dirname $OPAM_SWITCH_PREFIX)/log
=>
Need to mount $(dirname $OPAM_SWITCH_PREFIX) in ro
but need to mount $(dirname $OPAM_SWITCH_PREFIX)/log in rw
=> Adding way to mount unusual path in bwrap sandbox 

doc/pages/Install.md
I'm the Fedora packager for opam. There was a discussion in #2953 about the lack of install instructions for Fedora-- now that there is an opam package available in the Fedora repositories, the documentation should be updated to reflect that.
This will resolve #2953.
(There's still no CentOS/RHEL package. When I first started packaging opam, the version of ocaml available in RHEL 7 was too old. But it's since been updated, so when I get a chance I might try to build one. If I do, I'll open another pull request).
=> Docs: Add install instructions when using Fedora

src/client/opamCommands.ml
I'm still not entirely sure what: `If you want to enable a repository only to install its switches, you may be looking for $(b,opam switch create --repositories=REPOS).` is supposed to mean - does a repository contain `switches`? can I `opam switch create --repositories=RRR` where `RRR` is not known to opam before?
=> minor: improve documentation of opam repo add

src/state/opamFileTools.ml
Partial fix of https://github.com/ocaml/opam-repository/issues/12729.
An error is raised if `descr` & `synopsis` are both inexistent, or if they are both empty.
=> lint: Add error if no description nor synopsis

src/repository/opamGit.ml
This PR fixes #3523 and #3548.
More details on theses comments https://github.com/ocaml/opam/issues/3523#issuecomment-417039577.
=> git: fetch all repo to get sha1 with git < 2.14

configure, configure.ac, src_ext/Makefile
Addresses two shortcomings of the configure script:
- not having wget or curl is now only a hard-error if `src_ext/archives` doesn't contain the archives (i.e. if `make -C src_ext cache-archives` has not been run) which means that this should no longer be a requirement for building with the "full" tarball
- the C++ test for MCCS is now moved to the correct place and the message as to whether the solver will be built should work correctly with `--disable-checks`. Note that not having a C++ compiler is not considered an error if `--disable-checks` is specified because `configure` is permitted to believe that the mccs library exists even if it couldn't detect it.
cc @hannesm, @pmetzger
Fixes #3551
=> Fix configure tests

src/client/opamInitDefaults.ml, src/state/shellscripts/bwrap.sh
This PR updates URIs in error messages for bwrap. The new URI is <http://opam.ocaml.org/doc/FAQ.html#Why-does-opam-require-bwrap>.
=> Update FAQ URIs for bubblewrap

src/state/opamFileTools.ml
This PR add lin warning if variables `test` and `doc` are present in the opam file, and advise to use `with-test` and `with-doc` if it was what uer wanted first: opam2 format changed builti-in varibales `test` and `doc` to `with-test` and `with-doc`.
Fixes #3580 and partial fix of https://github.com/ocaml/opam-repository/issues/12729.
=> lint: add test & doc variables warning

src/client/opamAdminRepoUpgrade.ml
When upgrading a repo, if a compiler file contains a source git defined url, it results to an assert failure. Opam tries to download the archive to get its md5 (if missing from file or from cache), and assuming its a single file uses direct download (http or rsync backend).
Fix #3590.
=> upgrade: handle non http backend on repo upgrade

.gitignore, .travis-ci.sh, .travis.yml, appveyor.patch, appveyor_build.cmd, src_ext/Makefile, src_ext/Makefile.packages, src_ext/Makefile.sources, src_ext/jbuild-seq-src, src_ext/patches/seq.pkg/0001-switch-between-definition-alias-module-depending-on-.patch, src_ext/patches/seq/0001-seq-0.2-for-jbuilder.patch, src_ext/update-sources.sh
- Three tweaks to the `src_ext` vendoring script.
- Minor fix to AppVeyor bootstrap compaction
- Shift the cold compiler to 4.07.~0~1 and include 4.07.~0~1 in the test matrix
- ~Disable Cygwin64 testing - it's been only been enabled because the cached copy of OCaml 4.06.0 was still in place. flexdll needs patching, I've nagged the guy who wrote the patch to finish it...~ (cherry-picked in cac57424)
=> Updates for OCaml 4.07.1

src/state/shellscripts/sandbox_exec.sh
This is a PR to address #3576 (see discussion there).
~~I added a test which presumably makes that the fix works on both linux and MacOS X (on MacOS X, we use `getconf` to get the per-user temporary directory).~~
@rjbou clarified that the file `sandbox_exec.sh` is actually only for MacOS X. I updated the PR to simplify the comment explaining the situation.
Tested on MacOS 10.11.1 both with TMPDIR set and unset.
=> Sandboxing on MacOS: considering the possibility that TMPDIR in unset

src_ext/Makefile, src_ext/Makefile.sources, src_ext/patches/seq.pkg/0001-switch-between-definition-alias-module-depending-on-.patch, src_ext/patches/seq/0001-seq-0.2-for-jbuilder.patch
I forgot to use `git format-patch --no-renames` when I generated the patches for seq.
Recommended for 2.0.1 as mentioned earlier.
=> Eliminate renames in patches

src_ext/Makefile, src_ext/Makefile.sources, src_ext/patches/seq.pkg/0001-switch-between-definition-alias-module-depending-on-.patch, src_ext/patches/seq/0001-seq-0.2-for-jbuilder.patch
* Eliminate renames in patches
* ensure that `patch` removes zero-length files
This fixes the build on some platforms like Alpine where
this behaviour is not active by default, and thus results
in empty `.ml` files being generated in the source tree.
Signed-off-by: Anil Madhavapeddy <anil@recoil.org>
* Revert "ensure that `patch` removes zero-length files"
This reverts commit f6d001761256eec3e9db640f82e377823b44be21.
* Workaround strict POSIX patching
POSIX patch will leave src_ext/seq/seq.ml{,i} as zero-length files but
patch -E is non-POSIX.
=> Eliminate renames in patches (#3617)

src/state/opamFileTools.ml
Fixes #3625.
Flag checked was `conf` instead of `light-uninstall`
=> lint: fix light_uninstall flag for error 52

src/client/opamCommands.ml
Closes #3614
`opam init --compiler=` fails at compiler package selection, this PR adds the fallback to default compiler selection.
=> init: don't fail if empty compiler given

src/core/opamProcess.ml, src/core/opamProcess.mli, src/core/opamStd.ml, src/core/opamStd.mli, src/core/opamStubs.ml.dummy, src/core/opamStubs.ml.win32, src/core/opamStubs.mli, src/core/opamSystem.ml, src/core/opamSystem.mli, src/core/opamUrl.ml, src/core/opamUrl.mli, src/repository/opamGit.ml, src/repository/opamLocal.ml, src/repository/opamVCS.ml
Yet another bit from #3260.
~This also borrows a commit from #3346, so it will need rebasing before merge.~
This set of patches address two fundamental issues:
- It allows native Windows opam to call Cygwin tools correctly, by converting their arguments to Cygwin-style paths when necessary.
- It allows native Windows opam to appear to be able to execute shell scripts directly (by interpreting `#!` comments) and also ensures that command line arguments passed to Cygwin executables are correctly encoded/escaped, since they don't follow the same rules as native Windows executables. Note that this has **nothing** to do with shell escaping: this is dealing with the conversion of arguments as a string list to a single string (which is how Windows passes the command line) by the calling process …
=> Allow native Windows to use Cygwin tools

src/core/opamFilename.ml, src/core/opamFilename.mli, src/core/opamSystem.ml, src/core/opamSystem.mli, src/state/opamFormatUpgrade.ml
This PR contains a fix for format upgrade, it add extraction of archived source files of version-pinned packages. opam1.2 stores the archive file while opam2 the extract.
Related to #3600.
=> Upgrade pin source

src/state/shellscripts/bwrap.sh, src/state/shellscripts/sandbox_exec.sh
Which was incompatible with `set -e` on some configuration.
Fixes #3607.
=> Sandbox scripts: change one-line conditional to if statement

src/repository/opamRepository.ml
In function `OpamRepository.pull_upstream`, add check of no checksum option.
Fixes #3652
=> Do not check hash with --no-checksum on pull_upstream

src/state/shellscripts/sandbox_exec.sh
This commit allows applications to use unix sockets.
It also allows them to write to /dev/dtracehelper. This permission is
not strictly needed, as no program is broken by a denied access. However,
MacOS' dynamic loader (hence almost all the applications) wants to access
it, so the system logs are flooded by messages such as "SandboxViolation:
sh(49331) deny(1) file-write-data /dev/dtracehelper" when using opam.
=> Fix #3659: Sandboxing on MacOS is too strict

src/state/shellscripts/bwrap.sh
On some OSes, like CentOS and Arch Linux (so I've read), `/bin` is a symlink to `/usr/bin`, `/lib` is a symlink to `/usr/lib`, etc. 
Mounting them directly with `--ro-bind` resolves the symlinks. This breaks paths like `/bin/../libexec`: when `/bin` is a symlink to `/usr/bin`, `/bin/../libexec` points to `/usr/libexec`; but if it gets resolved first, it points to `/libexec`.
Fixes #3660
=> Handle symlinks in bwrap

src/client/opamArg.ml, src/client/opamArg.mli, src/client/opamClient.ml, src/client/opamCommands.ml
* Add undocumented environment variables doc
* Reinsert `alias-of` & `no-autoinstall` option: it does nothing, but don't error & display a deprecation message (fixes #3390)
* Deprecate `no-aspcud`
=> Option, manpage, doc

src/core/opamFilename.ml, src/core/opamFilename.mli, src/state/opamStateConfig.ml
Default opam root is resolved at creation, in order to have the correct linked path.
fixes #3622
=> Resolve opam root path

shell/install.sh
Very small followup to my previous PR: it looks like in certain shell implementations `$((` is not a valid token
=> Fix installer

doc/pages/Install.md
Point out Anil's ppa that packages the current stable `opam`.
The version packaged in Ubuntu versions older than 19.04 is opam 1.2
=> Update installation instructions for opam

src/client/opamConfigCommand.ml, src/state/opamEnv.ml, src/state/opamEnv.mli
Regenerate missing environment file. In order to do that, switch is loaded, which can sometimes slow `opam env`, but only in this case.
Fixes #3690  #3594.
=> Regenerate missing environment file

src/client/opamAuxCommands.ml, src/client/opamAuxCommands.mli, src/client/opamCommands.ml, src/client/opamSwitchCommand.ml, src/client/opamSwitchCommand.mli
Allow creation of local switch with unknown compiler directory.
Fixes #3713
=> switch: allow local compiler switch creation

src/client/opamConfigCommand.ml, src/state/opamGlobalState.ml, src/state/opamGlobalState.mli
`opam config list` and `opam config var <var>` don't give the same result, as the first one look first at switch modified variables (e.g. with `opam config set`) while the second does the opposite.
Fixed to the same behavior: resolving it first with switch state (loading it only for package defined variables), otherwise, global state.
Confusing pointed in #3717.
=> Fix variable display

src/client/opamAction.ml
On version pinning, source directory isn't automatically updated with the new archive.
Fixes #3651.
=> pin: fix update source of version-pinned package

CHANGES, doc/design/depexts-plugins, doc/design/depopts-and-features, doc/design/provides.md, doc/pages/External_solvers.md, doc/pages/Specifying_Solver_Preferences.md, doc/pages/Tricks.md, opam-devel.opam, shell/install.sh, src/client/opamAdminCommand.ml, src/client/opamAuxCommands.mli, src/client/opamCommands.ml, src/client/opamConfigCommand.ml, src/client/opamInitDefaults.mli, src/core/opamProcess.ml, src/core/opamStd.mli, src/core/opamVersionCompare.ml, src/format/opamVariable.ml, src/repository/opamRepositoryBackend.mli, src/solver/opamCudf.ml, src/solver/opamCudf.mli, src/state/opamGlobalState.mli, src/state/opamStateTypes.mli, src/state/opamUpdate.mli, tests/README.unittest
Fix small misspellings.
They were found by https://github.com/client9/misspell.
=> Fix small misspellings

src/client/opamCommands.ml
The `opam clean` command seems slightly too strict when it comes to errors in subcommands.
My use-case here is that I have mounted `~/.opam/4.07.1/.opam-switch/build` into tmpfs to avoid unnecessary write and disk space taken on my SSD but when I try to execute `opam clean` to remove the archive cache for example, it fails trying to remove this directory.
My proposal here is to ignore all failures to when trying to remove directories during `opam clean` and instead display a note to the user telling this command failed and has been ignored.
=> opam clean: Ignore errors trying to remove directories

src/state/opamFileTools.ml
When adding auxiliary files, sometimes opam report erroneously mismatching extra files:
```
00:00.248  opam-file   Mismatching extra-files at .opam/repo/default/packages/ocb-stubblr/ocb-stubblr.0.1.1-1
00:00.290  opam-file   Mismatching extra-files at .opam/repo/default/packages/conf-dbm/conf-dbm.1.0.0
00:00.440  opam-file   Mismatching extra-files at .opam/repo/default/packages/ocaml-config/ocaml-config.1
00:00.485  opam-file   Mismatching extra-files at .opam/repo/default/packages/zarith-freestanding/zarith-freestanding.1.7-1
```
=> Erroneous report of mismatching extra-files

src/core/opamUrl.ml
`hg://https://...` is wrongly translated to `hg+ssh://https//...` instead of `hg+https://...`
=> Fix hg / darcs opam1.2 url parsing

src/state/shellscripts/sandbox_exec.sh
If `TMPDIR` is set to something else than `/tmp`, it is not mounted, which can be blocking for some programs.
Related to ocaml/opam-repository#13339
=> sandbox: on osx, always rw mount /tmp

src/client/opamCommands.ml, src/state/opamFileTools.ml, src/state/opamFileTools.mli
To check reachability & availability of archive, and verify checksums.
Adds:
- warning 59: check_upstram && no checksum given
- error 60: check_upstream && (unavailable archive or don't verify at least one checksum)
=> lint: add check_upstream option

src/client/opamArg.ml, src/repository/opamVCS.ml
`working-dir` option didn't copy all local files, just uncomiited changes of version controlled ones, which leads to some rsync errors (if a file is deleted), and not handling new ones.
This PR changes this behavior by copying all current source directory (except `_build` directory). It may result to some build failure is current source directory is not clean.
=> Update working dir

src/core/opamSystem.ml
When opam is blocked (waiting for a lock to be released) signals abort this blocking state, like SIGWINCH wich is launched when a window is resized. This PR catch interruption caused by signals in order to ignore them.
Terminal signals still terminates the program.
=> Locked state and signals, avoid 

src/client/opamConfigCommand.ml
Hello, I would like feedback on this change and advice on how to write a test for it. I briefly looked through the test directory and saw some scaffolding for "fake packages", but could not figure out what the right way to set up a "fake switch" is for testing purposes.
My system opam packaged by Manjaro (version `2.0.1`, sha256sum `2b76b39ed8d53923b81985b618d4ef13fca1eabb7110bb477c7f9a3e4ae01767`) does not produce a fish shell fragment for the `MANPATH` environment variable, causing `opam` to erroneously report that the environment is out of sync.
As a workaround, I have been using the following `fish` function. `setenv` is a valid fish command and the quoting strategy used by `OpamConfigEnv.print_csh_env` seems to work for fish if the paths contain sensible characters.
function opam_env …
=> fish unconditionally display manpath when fish version is 2.7 or later

src/client/opamCommands.ml, src/client/opamMain.ml, src/client/opamSwitchCommand.ml, src/state/opamGlobalState.ml, src/state/opamGlobalState.mli, src/state/opamRepositoryState.ml, src/state/opamRepositoryState.mli, src/state/opamSwitchState.ml, src/state/opamSwitchState.mli
This PR, coming out of joint work with @Armael, can be summarized by the corresponding mli documentation:
```ocaml
(** Releases any locks on the given global state and then ignores it.
Using [drop gt] is equivalent to [ignore (unlock gt)],
and safer than other uses of [ignore]
where it is not enforced by the type-system
that the value is unlocked before it is lost.
*)
val drop: 'a global_state -> unit
```
The idea is applied to all three kinds of states-with-locks (global, switch, repos), and then `drop` is consistently used within the whole opam codebase, to remove `ignore` on possibly-still-locked locks as a code smell. See the commit message of the first commit for more design details.
Example from the patch:
```diff
- ignore (OpamSwitchState.unlock st);
- ignore (clear_switch gt …
```
=> Introduce `drop` to replace `ignore (unlock ..)` for more lock-type-safety

src/client/opamClient.ml, src/client/opamSolution.ml, src/client/opamSolution.mli, src/client/opamSwitchCommand.ml, src/format/opamTypes.mli
The goal of this PR is to make `OpamSolution.apply` return a bit more information about what happened, in particular for the jobs that failed.
This is joint work with @gasche .
=> Refactor the return types of OpamSolution.{apply,resolve_and_apply}

src/repository/opamGit.ml
Rebase on master & close #3628 that fixes #3627.
=> use git -c diff.noprefix=false diff

src/client/opamArg.ml, src/client/opamArg.mli, src/client/opamCommands.ml, src/client/opamLockCommand.ml, src/client/opamLockCommand.mli, src/repository/opamDarcs.ml, src/repository/opamGit.ml, src/repository/opamHTTP.ml, src/repository/opamHg.ml, src/repository/opamLocal.ml, src/repository/opamRepositoryBackend.ml, src/repository/opamRepositoryBackend.mli, src/repository/opamVCS.ml, src/repository/opamVCS.mli, src/state/opamPinned.ml
Integrates lock option in opam. In order to do that, I've made also some needed changes:
- split `--locked` into `--locked` && `--lock-suffix`, no change on `OPAMLOCKED`
- add new `get_remote_url` on `OpamVCS`that retrieve repo remote url , and in case of hash (branch or commit) check that they are present in distant repo (used for `pin-depends`).
`lock` option is mainly the same than `opam-lock` plugin, except it is more integrated in opam uses: not only take files, but paths and packages, check for uninstalled dependencies, nonexistent packages.
Closes #3734, closes #3769 and related to #3694
=> Add `lock` option

src/client/opamSolution.ml, src/core/opamParallel.ml, src/core/opamParallel.mli
This generalises the "mutually excusive sets", by providing separate job
pools for different subsets of the tasks. This will be useful to
parallelise downloads and builds efficiently.
=> Experimental generalisation of the job scheduler

src/core/opamParallel.ml, src/core/opamParallel.mli, src/crowbar/opamActionGraph_crowbar.ml, src/solver/opamSolver.ml, src/solver/opamSolver.mli
This PR provides JSON in/out functions for OpamParallel graphs, and in particular for the `OpamSolver.solution` type.
I needed to introduce new functions to the OpamParallel API, and to make the signatures less abstract (to reveal that the graph is unlabelled). See the commit messages for explanations.
(feature request from @Armael in the context of our marracheck work)
=> JSON (de)serialization for OpamParallel graphs

src/client/opamSolution.ml, src/core/opamConsole.ml, src/core/opamConsole.mli, src/format/opamTypes.mli, src/format/opamTypesBase.ml, src/repository/opamRepository.ml, src/solver/opamActionGraph.ml, src/solver/opamActionGraph.mli, src/solver/opamCudf.ml, src/solver/opamSolver.ml, src/state/opamUpdate.ml
Caveats:
- ~~Change of behavior: in the current implementation, if a "remove" needs a "fetch" and the fetch fails, opam will print a warning but do the remove nonetheless (by just removing the files). In this PR, if the fetch fails, the remove will automatically get cancelled. In practice, this can happen only for a few packages that do not use light-uninstall, but it would be annoying nonetheless. It would probably be nice to give the user a way around this, using --force or something.~~
- Currently, the jobs pool is shared between build and fetch actions. This can be improved, by implementing two separate pools in the scheduler, which should improve parallelism further.
This can be done in a separate PR.
=> Interleave download actions with build/install actions

src/client/opamSolution.ml, src/format/opamPackage.ml, src/format/opamPackage.mli, src/state/opamPackageVar.ml, src/state/opamStateTypes.mli, src/state/opamSwitchAction.ml, src/state/opamSwitchState.ml
Currently, the API for accessing `.config` files is a little awkward - only one `.config` file may be installed, and they physically never refer to version numbers, yet the API uses `OpamPackage.t` with slightly awkward calls to `OpamPackage.package_of_name` (awkward because it forces you to query the set of installed packages in order to get a fake version of the package to look up a file from a map which was keyed on name only, not name+version!).
This PR changes the type of `conf_files` to be a `name_map`. The semantics of `OpamSwitchState.package_config` are subtly different in that a `.config` file can be loaded for a package which is not installed - that at present would indicate a "corrupt" OPAMROOT but happens to be rather useful for something I'm working on...
=> Change OpamStateTypes.switch_state.conf_files from package_map to name_map

.travis-ci.sh
`seq.0.1`' `ocamlbuid.0` dependency is broken on 4.02.3 job as ocaml is build with `no-ocamldoc --no-ocamlbuild` options.
=> travis: remove `no-ocamlbuild` option for 4.02.3

src/client/opamArg.ml, src/client/opamClient.ml, src/client/opamClientConfig.ml, src/client/opamClientConfig.mli, src/repository/opamGit.ml
Mainly for CI.
It permit to not block update of packages previously installed with `--working-dir` (or that happen to have a dirty source tree).
Related to #3727 and more especially https://github.com/ocaml/opam/issues/3727#issuecomment-459016232.
/cc @RalfJung
=> Add OPAMDROPWORKINGDIR env variable

src/client/opamCommands.ml
This is a quickfix, we can probably do better than that ; see #3828
=> Don't remove git cache objects that may be used

src/client/opamInitDefaults.ml
except for win32 & freebsd (cf. [`cpu_count`](https://github.com/ocaml/opam/blob/master/src/core/opamSystem.ml#L563)), to avoid errors like
```
$ opam --version
2.0.3
$ opam init
[NOTE] Will configure from built-in defaults.
Fatal error:                                           "getconf": command not found.        
```
@dra27, does it need a special handling for cygwin?
=> init defaults: add `getconf` to required tools 

doc/pages/Install.md
Guix has changed its terminology, so the full system is now called Guix System instead of GuixSD (see [this note](https://www.gnu.org/software/guix/manual/en/html_node/Introduction.html#DOCF2) in the manual).
Guix also added a simpler alias to `guix package -i` called `guix install` and we try to encourage users to use it most of the time.
Thanks :)
=> Update guix install instructions

src/client/opamClient.ml
`opam update` don't propagate working-dir property. Fixes #3807
=> Fix `working-dir` on update command

opam-solver.opam, src/solver/dune, src/solver/opamBuiltinZ3.ml.dummy, src/solver/opamBuiltinZ3.ml.real, src/solver/opamBuiltinZ3.mli, src/solver/opamCudfSolver.ml
Support will be compiled and linked in if Z3 is installed on the opam
switch. This requires the latest update of the Z3 package
(https://github.com/ocaml/opam-repository/pull/14173) for proper
static linking.
Z3 has been shown to perform much better on pathological cases,
avoiding many timeouts, while being only a bit slower on most basic
cases. The cost is a doubled binary size, with static linking... Also,
the compilation time of Z3 should be considered.
For now, I made opam-solver depend on `mccs | z3` ; in reality, both
should be depopts, but we prefer people not to end up with opam
without a solver by mistake (it requires an external `aspcud` at
runtime in that case).
Perhaps we should keep `mccs` a dependency, and make `z3` a depopt,
though, to avoid the latter from being randomly …
=> Add support for Z3 as a solver backend

src/client/opamCommands.ml, src/state/opamFileTools.ml, src/state/opamFileTools.mli
fixes #3046.
As described in https://github.com/ocaml/opam/issues/3046#issuecomment-495246961, format is:
```
"lint": 
[
{ "file"     : string <filename>,
"result"   : string (passed | error | warning),
"warnings" :
[ { "id"      : int,
"message" : string <warning message> },
...
],
"errors"   :
[ { "id"      : int,
"message" : string <error message> },
...
]
},
...
]
```
=> lint: add result in json output

src/repository/opamHTTP.ml
https://github.com/ocaml/opam-repository/pull/14287 introduced `.gitattributes` files to opam-repository. There's no need for the project-specific ones to be included in `index.tar.gz` so this PR updates `OpamHTTP.make_index_tar_gz` to exclude them.
At the moment, the files have been removed (https://github.com/ocaml/opam-repository/pull/14294), but I've tested this locally.
Posix has very little to say about `tar`, so it's possible that the `--exclude` option locks to this GNU tar. Not sure if that particularly matters for `opam admin`. It'd be handy if this patch were applied to the `opam` which regenerates `https://opam.ocaml.org/index.tar.gz`, though.
=> Don't include .gitattributes in index.tar.gz

src/repository/opamGit.ml, src/repository/opamHg.ml
Since https://github.com/ocaml/opam-repository/pull/14287, opam-repository marks patch files as binaries.
However, in https://github.com/ocaml/opam-repository/pull/14331, a problem occurs: upon `opam update`, opam doesn't transfer binary files from the source repository to the local repository.
This PR should fix the problem. However I'm not too sure why opam uses diff in the first place. Moreover, it seems that `opam update` with a git repository as source will let the local repository in a state with non-committed changes and with no new git commits at all. I'm wondering if a better fix would be to simply remove this diff function which doesn't seem to be used anywhere but in `OpamVCS.fetch_repo_update`. I'll be happy to provide a patch if so.
In the meantime I think this patch is …
=> Opam{Git,Hg}: Fix diffs in presence of binary files

src/state/opamPackageVar.ml
The jobs variable was always read from the opam config file, so didn't reflect the `OPAMJOBS` variable or `--jobs parameter`. This hurts https://github.com/ocaml/opam-repository/pull/14257, as it means there's no way to prevent parallelism.
In general, using `jobs` to control build system parallelism is of course imperfect, although for OCaml itself this is more likely to be sound, since the compiler is usually a bottleneck during package installation.
This PR makes `jobs` behave in the same way as `make`, reading the `OpamStateConfig` value, which is influenced by `OPAMJOBS` and also `--jobs`. With this change, `OPAMJOBS=1000 opam config var jobs` displays 1000 instead of the value of `jobs` recorded at `opam init` time.
=> Read jobs variable from OpamStateConfig

src/repository/opamGit.ml
This change ensures that Git always disables text file line-ending normalisation when cloning changes from a Git remote.
Separate (still to be done) work on the `OpamLocal` driver, `opam admin`, and `opam lint` code will ensure that hashes for text files are always **initially** computed using the _repository_ normalisation. This differs from the approach of previous PRs which potentially hashed two versions of the file by determining from the git if the file needs transforming prior to the single hash being computed. The only time this transformation comes into play is if a Local (i.e. rsync) remote of a Git clone is added on a platform with `core.autocrlf` set to `true` (i.e. if you are working in a Git clone of a remote with `core.autocrlf` set to `true`)
=> Set core.autocrlf and core.eol for Git remotes

src/client/opamAuxCommands.ml, src/client/opamAuxCommands.mli, src/client/opamCommands.ml, src/client/opamSolution.mli, src/client/opamSwitchCommand.ml, src/client/opamSwitchCommand.mli, src/core/opamStd.ml, src/core/opamStd.mli
On local switch creation, if no compiler is specified or & single infered, there is the choice between several candidates that comply with the local opam file, defined as a conjunction that leads to an unresolvable solver request.
Fixes #3874
=> switch install: fix multiple compiler candidates

src/client/opamAction.ml, src/core/opamFilename.ml, src/core/opamFilename.mli, src/core/opamSystem.ml, src/core/opamSystem.mli, src/format/dune, src/format/opamFilter.ml, src/format/opamFilter.mli, src/format/opamInterpLexer.mli, src/format/opamInterpLexer.mll
And the last portion of #3260 split off.
This borrows parts of ~#3346~ and #3348 but also contains at least bit which needs further discussion.
Further comment to follow.
=> Deal with Windows path conventions (backslashes, .exe, etc.)

.gitattributes, Makefile, src/client/opamArg.ml, src/client/opamClientConfig.mli, src/client/opamCommands.ml, src/core/opamConsole.ml, src/core/opamCoreConfig.ml, src/core/opamCoreConfig.mli, src/core/opamStd.ml, src/core/opamSystem.mli, src/solver/opamBuiltinMccs.ml.real, src/solver/opamCudfSolver.ml, tests/dune, tests/patcher-test.reference, tests/patcher.ml
This splits off the tests added in #3449. Three tasks remain for this PR:
- ~The debug_sections should be converted to be an int option String.Map.t so that there is internally at least the option to have different levels for different sections.~
- ~`OPAMDEBUGSECTIONS` needs adding (either just supporting a list of sections, or full-blown support for specifying levels as well)~
- The test cases and the harness are still the result of my iterative hacking, and need tidying up...
=> Patch rewrite tests

src/stubs/opam-putenv.c
As the sole contributor of this file, I confirm its licensing under LGPL 2.1+OCaml Linking Exception
=> Fix licence for src/stubs/opam-putenv.c

src/client/opamCommands.ml, src/client/opamListCommand.ml, src/client/opamListCommand.mli, src/format/opamFormula.ml, src/format/opamFormula.mli
Show by default don't admit as argument several versions of a given package name. This pr adds an option `--all-versions` to display information of __all__ packages that satisfy `PACKAGES` constraints.
Closes #2980
=> Show multiple versions of a package

CHANGES, doc/pages/External_solvers.md, doc/pages/FAQ.md, doc/pages/Manual.md, doc/pages/Specifying_Solver_Preferences.md, doc/pages/Usage.md, src/client/opamCommands.ml, src/client/opamConfigCommand.mli, src/format/opamFile.ml, src/state/opamStateConfig.mli, src/state/shellscripts/bwrap.sh
Taken from https://sources.debian.org/patches/opam/2.0.3-1/0002-Fix-spelling-error-in-manpage.patch/
with some further amendments.
NB I've based this PR on 2.0 - the commit cleanly rebases onto master as well.
cc @mehdid
=> Typos fixed downstream by Debian

src/client/opamAdminCommand.ml, src/state/opamSwitchState.ml, src/state/opamSwitchState.mli
Still try to compute it, with a sane default, for the "virtual state"
cases. This helps e.g. for packages with `available: false` and `opam
admin list`.
=> Fix handling of availability outside of switches

Makefile, doc/Makefile, src_ext/Makefile, src_ext/Makefile.packages, src_ext/Makefile.sources
Allows compilation with OCaml 4.08.0 - this is for 2.0 branch only, `master` should be bumped to latest Dune (though there's some work to deal with the `jbuild` deprecation warning needed).
=> Bump src_ext Dune to 1.6.3

src/client/opamAdminCommand.ml, src/client/opamArg.ml, src/client/opamCommands.ml, src/client/opamPinCommand.ml, src/client/opamSwitchCommand.ml, src/core/opamFilename.ml, src/state/opamEnv.ml
Corrected messages which had hard-coded forward slashes in messages (e.g. `~/.opam`) either to use `Filename.dir_sep` (for simple cases like that) or `Filename.concat` to build the display properly. Messages on Windows should always use backslashes (and certainly not end up displaying a mix).
`OpamFilename.create` and `OpamFilename.Dir.of_string` (already) both normalise forward-slash to back-slash on Windows.
Note that while Windows doesn't have a concept of `~` in the normal way, it's not unreasonable to assume it (Vim-for-Windows, for example, automatically displays `~` if you set `%HOME%`, and I have another shell-related commit which sets `%HOME%` for opam users)
=> Correct display of dir separator on Windows

src/state/opamEnv.ml
`opam init -y` asked the user setup configuration question and then answers no: advertise `--shell-setup` instead.
=> Clarify message in opam init --yes

src/client/opamClient.ml, src/client/opamClient.mli, src/client/opamCommands.ml
Add an option `--check` to install command. It checks that dependencies of given packages are satisfied in the switch. ~If not, report missing ones, and asks to install them (equivalent to install package with `--deps-only` option). Another option `--no-inst` can be used if just the check is required.
Fails with exit code `1` if dependencies are missing.~ edit: cf. further comment
Related to #3823
=> Check package dependencies

src/stubs/opamWindows.c
Stub was checking the *input* character rather than the *output* character and thus assumed all glyphs were available...
=> Tested wrong variable in OPAMW_HasGlyph

appveyor.yml, appveyor_build.cmd, tests/Makefile, tests/packages/P1-0.opam, tests/packages/P1-0/P1.install.in, tests/packages/P1-1.opam, tests/packages/P1-1/P1.install.in, tests/packages/P1-2.opam, tests/packages/P1-2/P1.install.in, tests/packages/P2.opam, tests/packages/P2/P2.install.in, tests/packages/P2/build.sh, tests/packages/P3.opam, tests/packages/P3/P3.install.in, tests/packages/P3/build.sh, tests/packages/P4/build.sh, tests/packages/P5/build.sh, tests/packages/ocaml/ocaml.system/files/gen.sh
This PR contains one commit which is still work-in-progress and all the work is dependent on #3242, #3248 and #3255. It also has to point the testsuite to my unstable fork of opam-repository, so it's definitely not for merging just yet. The squashing of the three base PRs means that GitHub's review interface is largely useless, but this can start the conversations going about the architectural changes.
This PR adds sufficient native Windows support to opam to create a full testsuite pass, and in full VT100 TechniColor. There is still more to come, as it excludes all of the shell integration and additional features required to support Windows *well*.
The PR is best viewed in two sections: the first 22 commits add/fix the required support; the remaining 14 commits concern porting the …
=> Fully test native Windows in the testsuite

src/format/opamFile.ml
Oops, bumping that was premature and fine handling is implemented already as part of #3499
=> Revert package definition files format to 2.0

src/client/opamInitDefaults.ml, src/repository/opamDownload.ml, src/repository/opamRepositoryConfig.ml
thanks a lot to @rjbou for the commit, I adjusted (as requested in #3735 the command line arguments of `fetch`/`ftp` in the last commit (and rebased the others to master), namely:
- pass user-agent
- pass output filename
- pass URL
I read through the command-line arguments passed to curl, and that looks pretty similar (e.g. fetch follows redirects automatically). I also tested this on FreeBSD, working nicely (don't have a OpenBSD to really test it, maybe someone else (/cc @avsm @adamsteen) would like to do this?
> @rjbou On default init config, I've only put `fetch`/`ftp` as required tools, and in OpamDownload, I've set `fetch`/`ftp` as default command, curl as fallback. In that case, should we add `curl` in recommended_tools:?
in contrast to Linux, both BSDs ship their distribution as …
=> default to use "fetch" on FreeBSD / "ftp" on OpenBSD

src/repository/opamDownload.ml
I could reproduce the issue seen by @adamsteen while testing `ftp` on OpenBSD -- once the URL is parsed, all other arguments are ignored. This lead to `ftp` downloading the archive, but instead of saving at the location opam intended, it was saved as `filename`, which opam did not expect.
=> pass url last in download commands, this is necessary for ftp at least

doc/Makefile, doc/man.sed
Dune 1.7.0 displays a deprecation warning for jbuild files which needs to be suppressed when generating the man pages.
Fixes #3870.
=> Support Dune 1.7.0 and later

src/repository/opamDownload.ml
opamDownload: terminate (with double dashes) list of command-line options preceding unnamed positional arguments to bolster opam against problems with dashes in weird places.
Failure to do this is a pretty common source of security issues, see for instance [CVE-2018-1000006](https://web.archive.org/web/20190702112128/https://medium.com/0xcc/electrons-bug-shellexecute-to-blame-cacb433d0d62).
Note that this is different from e.g. [CVE-2017-17519](https://security-tracker.debian.org/tracker/CVE-2017-17519) ([code](https://github.com/ocaml-batteries-team/batteries-included/blob/master/src/batteriesConfig.mlp#L28)); passing each argument as an array element to execve does not preclude argument parsing, it merely prevents whitespace issues from breaking up the arguments differently than …
=> opamDownload: terminate (with double dashes) list of command-line opts

src/client/opamCommands.ml, src/client/opamConfigCommand.ml, src/client/opamConfigCommand.mli, src/client/opamSwitchCommand.ml
`opam switch create foo --empty` doesn't write an `environment` file. At this point, `opam config revert-env` will not return any updates. `opam env` will regenerate file. This PR fixes both `opam switch create --empty` to write the `environment` file and also `opam config revert-env` to regenerate it if it's missing (so belt-and-braces approach). Finally, the environment is also not checked in `opam switch create --empty` because of the same branch, and this is fixed (it hurts Windows, which actually updates the environment at this point; it doesn't hurt Unix if you have the shell hook installed).
=> Fix environment file handling for empty switches

Makefile, admin-scripts/compilers-to-packages.ml, src/client/opamAdminRepoUpgrade.ml, src/client/opamInitDefaults.ml, src/state/opamFormatUpgrade.ml, src/state/opamPackageVar.ml, src/tools/dune, src/tools/opam_admin_top.ml
Shedding the weight of some simpler commits:
- `opam-admin.top` - prior to Jbuilder, this was built using `ocamlmktop`. I converted this badly, because the existing code now works as a toplevel, but you can't run a script by having `#!opam-admin.top` or `opam-admin.top foo.ml`. The commit generates the `let _ = Topmain.main ()` in a second file which is used to create `opam-admin.top` and the actual `opam_admin_top.ml` is now used to generate a library. This means that scripts have two choices - you can either `#require "opam-admin.top"` in your script, or you can run an `.ml` file with `opam_admin_top` (although you need `opam_admin_top.cmi` in the same directory as your script).
- `%{exe}%` does exactly what it says on the tin. The main reason for making it a global is to standardise …
=> Bits 'n bobs

src/client/opamAdminCommand.ml, src/client/opamArg.ml, src/client/opamCommands.ml
#3893 uses Windows separators in various opam messages - the ones which are cmdliner terms need to be escaped, which this PR addresses. This PR is also a prerequisite of #3902.
=> Add missing Cmdliner.Manpage.escape calls

src/core/opamStd.ml, src/core/opamStd.mli, src/solver/opamSolver.ml, src/solver/opamSolver.mli, src/state/opamSwitchState.ml
i.e. don't allow to change packages transitively depending on
something marked for reinstall without doing the reinstall.
The first two patches just add helpers to the library:
- a function to compute a dependency graph directly on the opam
packages (going through Dose and using back-and-forward conversion
though). Unused at the moment but may come in handy for some uses
(e.g. opam2web)
- a Set.fixpoint function, used e.g. to directly compute transitive
dependency cones directly on opam packages (without going through
Dose this time)
=> Make reinstall handling stricter

.gitattributes, configure, configure.ac
This is a cosmetic change, since `cppo` is a dependency of several of opam's dependencies, but `opam` checks for the `cppo` ocamlfind package, rather than the `cppo` tool itself. This works fine on an opam installation, owing to https://github.com/ocaml/dune/issues/2353, but fails on Debian, where the `cppo` package (correctly) does not install a `META` file.
With this change, `./configure` now doesn't display the "run make lib-ext" message because of a missing `cppo` package. I have changed the detection to look at `$CPPO`, but this is academic since several of the libraries depend on cppo.
This is for master and 2.0
=> Fix cppo detection in configure

doc/pages/Distribution.md, doc/pages/index.menu
As wiki is disabled, port distribution as part of opam.ocaml.org.
I updated versions information & some urls.
If maintainers (@mehdid @nbraud @avsm @pmetzger @xyproto @david-geiger @roptat @hannesm @TC01 @dra27) can take a look to check them, it'll be perfect. Like that, you'll also know about this page and be able to update it on further releases.
Thanks for all the porting work!
=> doc: add distribution page

src/client/opamCommands.ml, src/state/opamFileTools.ml, src/state/opamFileTools.mli
Some linting related backported commits : 
- be8621b (#3758)  add check-upstream option
- a5895c0 (#3763) & 0f19e1c (#3860) add warning for with-test in run-test field 
- 518e500 (#3871) restrain doc warning to filters
=> 2.0.5 lint backported commits

shell/install.sh
The previous commit updating this to 2.0.5 updated the SHA512
hashes to that version, but forgot to update $VERSION and so was
still downloading the 2.0.4 version of $OPAM_BIN, causing a
checksum mismatch.
=> shell/install.sh: Properly update to 2.0.5, fixing "Checksum mismatch" error

src/client/opamInitDefaults.ml, src/state/shellscripts/bwrap.sh
While answering https://github.com/ocaml/opam/commit/a4648620cf00c10d73222d2a8d3f3482c1c15e6b#commitcomment-34377161 I noticed that the URI was wrong - #3588 should have been cherry-picked to 2.0, so here it is!
=> Update FAQ URI (2.0)

src/client/opamCommands.ml, src/client/opamListCommand.ml, src/client/opamListCommand.mli
opam show no more requires a colon for non _inferred_ fields `:`. Now, by defaults, `opam show pkg -f <field>` displays computed content if it exist, field content otherwise. If `--raw` is specified, it's the field content that is displayed (old `-f <field>:`). For backward compat, `-f <field>:` is still supported. ~it gives the same result than `-f <field>`~
Fixes #3664
=> show: don't require colon for fields

src/state/opamPinned.ml
=> lock: add warning in case of missing locked file

src/format/opamFilter.ml, src/format/opamFilter.mli, src/format/opamFormula.ml, src/format/opamFormula.mli
Intially, this is part of #3866 
from https://github.com/ocaml/opam/pull/3866#issue-287591110 : 
- a compare function for formulas
- a sort function for formulas
- a sort function for filtered_formulas; this one calls also `OpamFilter.simplify_extended_version_formula` on filters
=> Sorting formulas functions

src/client/opamArg.ml
The usage of this variable is correctly spelled: https://github.com/ocaml/opam/blob/abf8fd8d9e2e0cd743e88d61a3dc82661b733e22/src/repository/opamRepositoryConfig.ml#L121
only the man page is wrong.
=> Fix misspelled environment variable in man page

Makefile
Dune 2 only promotes the `.install` if the `-p` is specified, which doesn't work for opam's build system. This commit detects whether the `--promote-install-files` argument is available which isn't particularly pretty, but does mean that opam will build with both Dune 1.x and 2.x.
Ultimately, it would be better to push for Dune features which eliminate the need for the post processing of the `.install` files completely and then just depend on Dune 2.0.
Addresses #3961
=> Preliminary support for Dune 2.0

src/format/opamFormula.ml, src/format/opamFormula.mli
* `compare` cherry-picked from #3894
* `compare_formula` didn't take into account `&` and `|` operators (https://github.com/ocaml/opam/pull/3945/files#r313755211)
=> Sort formula: fix `compare_formula` & add `compare`

src/state/shellscripts/bwrap.sh, src/state/shellscripts/sandbox_exec.sh
See https://discuss.ocaml.org/t/dune-1-11-1-compilation-failed/4248
=> Do not fail if $HOME/.ccache is missing

src/client/opamAuxCommands.ml, src/client/opamClient.ml, src/repository/opamGit.ml, src/repository/opamLocal.ml, src/repository/opamVCS.ml
This PR contains several things:
- add a `git clean` on `reset_tree` to keep source dir clean
- review `sync_dirty` on git:
* use git to synchronize, then rsync & remove others files
* exclude `_build`, `_opam` & vcs directories
- When `--inplace-build` is given, it does a dirty synchronisation of the sources, in order to keep tracking package stats (clean, local or dirty)
=> Git internal & inplace source copy

opam-devel.opam
I just did `opam install opam-devel` to upgrade from 2.0.4 to 2.0.5, and in the end there was this message:
> You should not run it from there, please install the binaries to your PATH, e.g. with
>  `sudo cp <OPAMROOT>/4.05.0/lib/opam-devel/* /usr/local/bin`
I know it's just an example, but that command would actually copy the `META` and `dune-package` files as well. And since there is only a single binary there (`opam`), it seems better to just do:
sudo cp <OPAMROOT>/4.05.0/lib/opam-devel/opam /usr/local/bin
Unless there is a use case in which `opam-devel` has more than one binary file. If so, please ignore this PR.
=> Avoid copying extraneous files in opam-devel example

src/core/opamProcess.ml
Pretty simple PR here, it reuses some definitions of `opamStd` and remove locally defined ones.
A little bit of self-promotion, this redundancy was detected while testing an (experimental) library called [`asak`](https://github.com/nobrakal/asak).
=> Factorize option_map and option_default in `core/opamProcess.ml`

src/client/opamClient.ml
If from a repo, primary url backend changes from archive to vcs, on update, as the package is considered `dev`, `is dirty` check fails. 
Fixes #3991
=> update: don't fail if dev source is not vcs, just set it as non dirty dev package

Makefile, configure, configure.ac
Add `--enable-cold-check` to configure in order to fail if some checks are strongly required (ftm only patch & bunzip2).
Fixes #3842
=> make cold: fail if patch or bunzip2 missing

src/state/opamFormatUpgrade.ml
Config version was set to the current opam version, without updating the config file `format_version`, leading to an error in the `opam-version` field check (`2.1 > 2.0`). On upgrade, instead of setting the current version to config, set the min between current version and lastest compatible config version.
=> 1.2 upgrade fix

src/client/opamSolution.ml, src/repository/opamDarcs.ml, src/repository/opamGit.ml, src/repository/opamHg.ml, src/repository/opamRepositoryBackend.mli, src/repository/opamVCS.ml, src/repository/opamVCS.mli
* Don't fetch dev packages when `working-dir` is set
* Copy uncommited modified versioned file
=> Working-dir fixes

src/client/opamRepositoryCommand.ml, src/state/opamRepositoryState.ml, src/state/opamRepositoryState.mli
When changing a repo url, the previous archive is discarded, but later opam tries extracted it (caching in `repo.repos_tmp`). Adds a fall back for that case.
=> repo: fall back in case archive doesn't exist

src/core/opamDirTrack.ml
the earlier code checked size OR mtime for equality, whereas it should be size AND mtime to avoid bad cache lookups
=> DirTrack: check both size and mtime for cached entries

doc/pages/Packaging.md
It seems that the variable ocaml-native has been renamed to ocaml:native. This pull request updates the documentation accordingly.
=> Update Packaging.md: ocaml-native changed to ocaml:native

doc/pages/Install.md
Built packages are preferred over building your own packages on OpenBSD.
See https://www.openbsd.org/faq/faq15.html
=> Use pkg_add to install opam on OpenBSD

src/client/opamAction.ml
This is a minor improvement of the console logging when building a series of packages. If installation succeeds, the message is `* installed pkg.ver`, but if it fails, it is `the compilation of pkg failed at ...`.
This commits adds the version number to the failure message, for symmetry and to be more explicit.
(this way, one can start investigating the issue before waiting for the final message which does include the version)
=> Include the version number in "compilation failed" messages

src/format/opamFile.ml, src/format/opamFile.mli
this PR consists of two commits:
- add `remove_extension : t -> string -> t`
- change behaviour of `to_string_with_preserved_format` to not treat `x-` specially. I'm not sure why the code was around, is there a test / example for the previous behaviour @AltGr?
=> opamFile extensions (x- fields) enhancements

src/state/opamSwitchState.ml
When pinned package is unpinned without removal, its sources continue to be updated on `opam update`.
=> update: don't update installed dev package that is not pinned

src/client/opamCommands.ml, src/format/opamFile.ml, src/format/opamFormat.ml, src/format/opamFormat.mli, src/state/opamFileTools.ml, src/state/opamFileTools.mli
Add sorting on opam fields, available as a function in opam-lib & as an `opam show` option.
This pr contains several things:
~- a compare function for formulas~
~- a sort function for formulas~
~- a sort function for filtered_formulas; this one calls also `OpamFilter.simplify_extended_version_formula` on filters~
→ on a seperate PR #3945 
- a sort opam file function:
- fields are sorted given alphabetical order: author, tags, depends, depopts, depexts, conflicts, pin_depends, extra_files, extra_sources
- `filtered_fomulas` of `depends`, `depopts`, and `conflicts` are sorted given alphabetical order and their filter : ~`build < <nothing> < test < doc < post`~ alphabetical order too
Related to ocaml/opam2web#173
~_This PR is still a __WIP__. Some discussion needed on **fields sorting**_~
=> Sorting opam fields

doc/pages/Packaging.md
Currently [the docs](https://opam.ocaml.org/doc/Packaging.html) suggest to do
```
git tag -a 0.1
git push 0.1
```
I think the second command should be `git push origin 0.1` (`git push 0.1` tries to push to repository called 0.1).
=> [docs] Fixed git command in packaging docs

src/client/opamConfigCommand.ml
=> env: fish env variables, add colon for MANPATH only, not PATH

src/client/dune
get-git-version isn't a proper module name. This commit switches it into
a valid module name.
In 2.3.0, dune main validation more strict. So we ended up accidentally
breaking this. Opam should not rely on this.
=> Use proper module names

src/state/opamEnv.ml
instead of -t 0 since it can mess up with some shells
(-t 0 checks if the shell is tty, not interactive, even though most of the times it's ok to do so it can fail with some shells)
=> shell: fix zsh check interactive terminal

src/client/opamClient.ml, src/client/opamClient.mli, src/client/opamCommands.ml, src/state/opamEnv.ml, src/state/opamEnv.mli
* Sandboxing update broken in case an matching hash file is present
* When using `-ni` , completion & env hook files were removed
=> Init: fix sandboxing update & `ni` option

src/core/opamSystem.ml
...instead of calling the shell (on linux).
The motivation is performance. It turns out that the speedup of #4064 is due not only to less time being spent launching processes, but also less time being spent calling to the shell in order to resolve the command. Doing the resolution (using PATH) directly in ocaml should be faster.
Note that command resolution was already done in ocaml on Windows, so this PR mostly merges the (previously) windows-specific code with the linux code.
The PR also attempts to streamline a bit the handling of `Not_found` vs `Denied`. The behavior is mostly unchanged when looking up a fully specified path (I added a `Not_found` case for increased precision; previously, a non-existing binary would be reported as "denied").
When a command is looked up in `PATH`, I …
=> OpamSystem.t_resolve_command: use ocaml code for looking up commands in PATH

src/client/opamRepositoryCommand.ml
When `repo add name url` fails because of an already registered repo mismatching url, printing also the opam parsed resulting url helps to understand the error origin (missing `//`, etc.)
Fixes #4085
=> repo: on add error, display also the parsed url

src/state/shellscripts/bwrap.sh, src/state/shellscripts/sandbox_exec.sh
* ccache:
* fix option name
* handle `CCACHE_DIR` env variable in case `ccache` call fails
* fix #4079 
* cache:
* follow links of `~/.cache` & `~/.cache/dune` for bwrap call (maybe we just need to bind just `.cache`?)
* is it needed on mac ?
* fix #4068
=> Sandbox: fix some cache failures

opam-client.opam, src/client/dune, src/client/opamAction.ml, src/client/opamCommands.ml, src/client/opamSwitchCommand.ml, src/client/opamSwitchCommand.mli, src/format/opamFile.ml, src/format/opamFile.mli, src/format/opamPath.ml, src/format/opamPath.mli
Why I'm doing this? I worked on reproducible builds and tooling thereof, where it is very convenient to use opam export and import for rebuilding the same artifact. The current situation that an export contains only a subset of packages (and thus an import may be incomplete or using package metadata from elsewhere) does not fit well into the reproducible builds concept.
~~This PR embeds https://github.com/mirage/ocaml-base64 into opam, I'm happy to remove this and use a dependency for that (but I didn't know how to add depedencies for opam) -- or use a hex encoding if prefered.~~
//cc @rjbou
=> Include extra-files in switch export if `full` is provided, on import create an overlay directory with the file contents

doc/man/opam-topics.inc, src/client/opamCommands.ml, src/client/opamCommands.mli, src/client/opamConfigCommand.ml, src/client/opamConfigCommand.mli, src/format/opamFile.ml, src/format/opamFile.mli
Modifiable fields are `download-command`, `download-jobs`, `jobs`, `best-effort-prefix-criteria`, `solver`, `global-variables`, `eval-variables`, `repository-validation-command`, `solver-criteria`, `solver-upgrade-criteria`, `solver-fixup-criteria`.
On revert mode, value is reverted to its init config value if available, deleted otherwise.
ecit: cf https://github.com/ocaml/opam/pull/3992#issuecomment-557638448
=> config: add 'config setopt' and 'setopt' (sub)commands to modify global config fields

src/client/opamClient.ml, src/client/opamClient.mli, src/client/opamCommands.ml
In case of dependencies only install, there is no need to keep restriction of conflicting package.
Related to #3846
=> install: remove conflicting packages if deps-only

opam-client.opam, src/client/dune, src/client/opamCommands.ml, src/client/opamSwitchCommand.ml, src/client/opamSwitchCommand.mli, src/format/opamFile.mli
this is useful for having an export file which can be imported and will contain the exact same sources (related to #4040), part of reproducibilty efforts
=> opam export: record vcs commit hash when a vcs url is specified

src/state/opamRepositoryState.ml
Revert "repo state cache: disable developer mode check"
This reverts #3795
=> Re-enable (opam) developper mode repository cache check

Makefile
observed in https://github.com/ocaml/ocaml-ci-scripts/pull/258 that opam-format on 4.10 fails to install since warnings are treat as errors (see CI log at https://travis-ci.org/github/ocaml/ocaml-ci-scripts/jobs/666251349?utm_medium=notification&utm_source=github_status).
maybe this should be backported to the 2.0 branch and a 2.0.7 being released?
=> Makefile: add --profile=$(DUNE_PROFILE) to remaning invocations of dune

src/core/opamProcess.ml, src/core/opamStd.ml, src/core/opamSystem.ml, src/solver/opamSolver.ml
(joint work with Armaël Guéneau)
OpamStd.Env.get is opam's entry point to access the process
environment. It caches the whole environment lazily, on the first
environment access. Most environment-accessing parts of the code are
written with carefully placed lazy thunks, to ensure that they are
computed on first need (when the .init functions are called) rather
than at module initialization. This PR fixes a few places that would
still force the environment at module-initialization time.
This is important for programs that would like to modify the
environment (using Unix.putenv) before calling opam-lib functions, and
ensure that opam functions do see the modified environment. Before
this commit, the environment was cached at module-loading time and
could never be modified by user code.
We …
=> ensure that Env.get is initialized lazily, not before .init functions are called

src/client/opamCommands.ml, src/client/opamPinCommand.ml
Fixes #3875
Better handling of:
* Empty file
* `--just-file` errors
* No package found
→ can fail with `Not_found`  (5) or `File_error` (30)
=> Show errors: bette error handling

src/client/opamCommands.ml, src/client/opamSwitchCommand.ml, src/client/opamSwitchCommand.mli, src/state/opamSwitchAction.ml, src/state/opamSwitchAction.mli
We used to release the lock on ~/.opam/config as soon as possible, but that is 
not really compatible with the facts that:
- we may want to set the switch as default upon creation (this was done early,
but could lead to no switch getting selected on error)
- we may want to clear the switch upon error (this was done without proper
locking)
So this keeps the global lock during the switch installation, whith the 
following benefits:
- the selected switch is only changed once installation completes, not just
after creation
- changes to ~/.opam/config are handled safely
The alternative could be to release the lock, then try to acquire it again if 
needed (on error, or for selecting the switch), but we chose the safer
approach. If the user really needs better lock granularity (e.g. creating …
=> Better error handling on switch creation

doc/man/opam-topics.inc, src/client/opamCommands.ml, src/client/opamCommands.mli, src/client/opamConfigCommand.ml, src/client/opamConfigCommand.mli, src/core/opamStd.ml, src/core/opamStd.mli, src/format/opamFile.ml, src/format/opamFile.mli, src/format/opamFormula.ml
This _new_ implementation mainly for UI evolution. The `set-opt` subcommand is replaced by the `option` subcommand:
* `opam config option : list modifiable options and their value (by default switch)
* `opam config option foo`: display `foo` value, available for all fields/sections, not only modifiable ones
* `opam config option foo<=|-=|+=>bar`: update `foo` value
* `opam config option foo=`: revert `foo` value
Options can be given to select scope `--global` or `--switch switch`. If not, `opam option` select by default switch, and other subcommands look at the presence of the field/section name in its internal list to determine the scope. 
`set-var` remain unchanged.
EDIT: update options
=> Option configuration, v2

src/client/opamConfigCommand.ml
=> config exec: error message if command not found

src/client/opamAdminCommand.ml, src/client/opamArg.ml, src/client/opamArg.mli, src/client/opamCommands.ml
This reverts commit 888351728e1e28ddd13ee4de5828e348b6a0bbfa.
This patch makes the cmdliner escapes `$(i,xxx)` appear verbatim in the
man-page. Probably the solution is to replace the file_sep used, or use
another escaping function instead. @dra27 ?
=> Revert "Add missing Cmdliner.Manpage.escape calls"

master_changes.md, src/client/opamSolution.ml, src/state/opamSwitchState.ml, src/state/opamSysInteract.ml, src/state/opamSysInteract.mli
* Refactor `package_status`
* Add an internal type to handle unsupported os families, and add consistency
* Fix centos/rhel install commands
* Fix `config option` in error message
* Add macports commands
=> depext: update

master_changes.md, src/client/opamInitDefaults.ml
With depext now builtin part of opam in opam 2.1 and `ocamlfind` (which uses `m4`) being less and less used, I'm not sure it feels necessary to have a warning recommending to install this package anymore:
```
[WARNING] Recommended dependencies -- most packages rely on these:
- m4
```
=> Remove m4 from the list of recommended tools

Makefile, master_changes.md, opam-client.opam, opam-core.opam, opam-devel.opam, opam-format.opam, opam-installer.opam, opam-repository.opam, opam-solver.opam, opam-state.opam
`opam-%s.install` target was only used by opam files, there is no occurrence of their call in the opam source. Are they used in other projects ? @samoht @avsm @dra27
Fix #4173
=> Update opam file with dune, remove `opam-%-install` target

master_changes.md, src/repository/opamLocal.ml, src/repository/opamVCS.ml, src/state/opamPinned.ml
On syncing (`assume-built`) and for opam file lookup (`recursive`)
fix #4195
=> Ignore `_build`

master_changes.md, src/core/opamFilename.mli, src/state/opamRepositoryState.ml
supersede #4166, see discussions full there.
> When removing temporary stuff, a directory cleaning is done, to remove all intermediate temporary directories. The process is upward: if directory is empty, removes it, and check its on parent, ... On some new containers, when cleaning a temporary repository (new repo mechanism) it reaches `/tmp`, as its only content was those opam repo temporary files.
=> repo: remove temp directory instead of clean_dir

master_changes.md, src/client/opamCommands.ml, src/client/opamListCommand.ml, src/client/opamListCommand.mli
* Display error message for not found packages (not only when no one is found) fix #4164 
* Keep package order given via cli fix #4163 
* Don't restrict apply option to `--just-file`
=> opam show small fixes

master_changes.md, src/state/opamPackageVar.ml
Fix #4224 
If a package is no more available in a repository, and a recompile is trigered, opam can't resolve its name because it is restrained to known packages `st.packages`. Release this constraint.
=> Fix resolve name for orphan packages

appveyor.patch, master_changes.md, src_ext/Makefile
This is because gcc10 defaults to -fcommon which causes
compatibility carnage.  See ocaml/opam-repository#16583.
Reported by @Misterda
=> build cold bootstrap with OCaml 4.10 to fix gcc10 compilation

appveyor.patch, master_changes.md, src_ext/Makefile
This reverts #4234 (1b0f4bacae7fe64b23b802fe04ae75d5c203ce24)
To integrate in #4242
=> Cold boostrap back to 4.07.1

master_changes.md, src/client/opamCommands.ml, src/client/opamConfigCommand.ml, src/client/opamConfigCommand.mli
* No scope needed for variable display (as 2.0 opam var) fix #4183
* Fix package variable display fix #4182 
* Not found message include scope
=> opam var fixes

master_changes.md, src_ext/Makefile.sources
Seems that ygreg.org.ua is no more reachable and  the [package](https://opam.ocaml.org/packages/extlib/extlib.1.7.6/) redirects to ygrek.org.
=> src-ext: fix extlib url

master_changes.md, src/state/opamSysInteract.ml
* arch: use `pacman -Ss <packages regexp>` to have only one exec call. fix #4199
* regexp: transform list string manipulation into regexp to treat sys package manager outputs
* add some example outputs
* fix homebrew package name check, allow `package` and `package@version`
* add environment variabe handling for `OpamSysInteract` commands (addition and overriding)
* force `LC_ALL=C` for query commands
* fix dry run for install commands
=> depext: fix arch/brew, use regexp, environment variable handling, etc.

.travis-ci.sh, appveyor.yml, shell/md5check.ml, src_ext/Makefile
The URL for the opam cache in `src_ext/Makefile` was incorrect. This PR also extends `make -C src_ext cache-archives` to use the opam cache if upstream tarballs aren't available (this was already the case for `make lib-ext`, but if `make -C src_ext cache-archives` fails then the CI build fails...)
=> Allow CI to download archives from opam archive cache

master_changes.md, src/client/opamConfigCommand.ml, src/format/opamSwitch.ml, src/tools/opam_installer.ml
* Switch names (global or local directories) containing  `| '<' | '>' | '!' | '<backquote>' | '$' | '(' | ')' | ':'`, or empty are rejected. For windows compatibility, switch names that begin with `\w:/` & `\w:\` are allowed.  Empty switche names are forbidden.
* Compliance regexp is `^(\w:/\\)?[^<>!$():]+$` (missing the backquote because of markdown) cf. [code](https://github.com/ocaml/opam/pull/4237/files#diff-69b74e9ec849a48241d3e03d0196540bR25)
* Update opam installer to not use an empty switch to retrieve needed paths
* Cherry-picked context-free switch paths from #4147 
* fix opam env `OPAMSWITCH` setting: if empty string, consider it as unset
fix #4231 
@rjbou edit: update content
=> Switch name check

master_changes.md, src/client/opamClientConfig.ml, src/client/opamClientConfig.mli
Same as for `OPAMLOGDIR`, as the default value is defined, the init mechanism ignores its update.
Fix #4241
=> Fix config file solver ignored at init

Makefile, master_changes.md, opam-client.opam, opam-core.opam, opam-devel.opam, opam-format.opam, opam-installer.opam, opam-repository.opam, opam-solver.opam, opam-state.opam
Following the merge of https://github.com/ocaml/opam/pull/4178, the `opam-devel` package now doesn't install anything anymore (see the special `opam-devel.install` makefile rule). 1471a27 should fix that.
Otherwise the rest is more of a collection of various fixes that can be taken independently:
* 8d4ae0d is here because the `opam-%.install` rule is still used in the makefile (see the `installlib-%` rule for instance)
* 5429c09 fixes an issue that happens when an external archive is not available to download and the script tries to get it from the cache but the url does not exist anymore.
* 9f3dacf is a preventive fix in case someone changes the name of the opam binary (in the src/client/dune) it will not try to use the `opam` binary from the PATH (which, if it is not opam 2.1 already is …
=> Fix the opam-devel package + various fixes

doc/pages/Manual.md, master_changes.md, src/client/opamClient.ml, src/client/opamCommands.ml, src/client/opamConfigCommand.ml, src/client/opamSolution.ml, src/state/opamSwitchState.ml, src/state/opamSwitchState.mli
* add depext check to unavailable reason, on the same behavior as in `check_availability`, by displaying the max element depexts. fix #4176
* add depext handling on new pinned packages fix #4189 
* add `depext-bypass`  as a modifiable field in switch config fix #4177
* fix old opam option format in messages
* fix opam list depext handling fix #4205
=> depext fixes: unavailable reason, pin, depext-bypass, list

doc/man/dune, doc/man/dune_man.ml, doc/man/opam-admin-topics.inc, doc/man/opam-topics.inc, dune-project, master_changes.md, opam-client.opam, opam-core.opam, opam-devel.opam, opam-format.opam, opam-installer.opam, opam-repository.opam, opam-solver.opam, opam-state.opam, src/client/dune
Two fixes:
- Building the man pages should never inexplicably block the build
- There's a check to ensure that `%{bin:opam}` refers to something that's just been built and not something in `PATH`
cc @kit-ty-kate (replaces commit in #4229)
=> Harden doc/man/dune

master_changes.md, src/client/opamClient.ml, src/client/opamClient.mli, src/client/opamCommands.ml, src/client/opamSolution.ml, src/client/opamSolution.mli
to install only external dependencies required by the install of targeted package(s).
=> Add `opam install --depext-only` option

master_changes.md, src/repository/opamRepository.ml
This PR is just to upstream a change I've been using in https://github.com/kit-ty-kate/opam-health-check.
This change improves slightly the time it takes to retrieve archives from a local cache by avoiding a rather unnecessary call to `rsync` from the cache to a temporary file (which is then going to be moved to the global download cache in `~/.opam/download-cache`), and replacing it by the `OpamSystem.copy_file` function improved in this wonderful PR: https://github.com/ocaml/opam/pull/4064
This PR approximatively improves the time it takes to retrieve archive by 0.02s per archive in cache on my test server. In my use-case (CI), opam is repetitively called and thus repetitively retrieve archive from the cache.
On a typical medium sized-example: `core.v0.14.0` for instance pulls 59 …
=> Copy files instead of rsync when they are in a local cache

master_changes.md, src/state/opamSwitchState.ml
to allow playing with criteria and seeing if we can solve the
mariadb/mysql dilemma.
With this patch, you can add a `-count[missing-depexts,solution]`
criterion (putting it before the main `version-lag` criteria would be a
bad idea though).
=> Tag packages with missing depexts to the solver

master_changes.md, src/client/opamArg.ml, src/state/opamSysInteract.ml
The new depext system in opam 2.1 has several issues:
* `opam install -y` does not mean `apt-get` will be called with `-yy` anymore, which breaks every CI.
* It's behaviour regarding to whether or not package systems were to ask the user before installing packages has changed from opam-depext 2.0 (see https://github.com/ocaml/opam-depext/blob/2.0/depext.ml#L129)
* This behaviour is not consistent accross platfrom. Meaning some platforms will ask an input from their users by default, and others don't and install anything without any acknowledgement from the user.
What I've done here is the following:
* By default, always ask for user to interactively accept the installation. There are some differences from before: on Gentoo and Alpine, the user was never asked for input on opam-depext2.0. …
=> depexts: Make package system behaviour consistent accross platforms

master_changes.md, src/client/opamClient.ml, src/client/opamClient.mli, src/client/opamCommands.ml
Some fixes:
* handling of post dependencies (leading to an infinite look up of dependencies, or dependency unavailable)
* specific missing dep message
=> Assume built rewriting

doc/pages/Manual.md, master_changes.md, src/client/opamArg.ml, src/client/opamArg.mli
Partial revert of #3499, disable cli options `--recursive` and `--subpath`.
=> Disable recursive & subpath pinning

master_changes.md, src/state/shellscripts/bwrap.sh, src/state/shellscripts/sandbox_exec.sh
Opam 2.1 has support for symlinked cache directory, however currently if the cache directory does not exist, the script will crash with no error message.
```
~/opam-repository$ ls ~/.cache
ls: cannot access '/home/opam/.cache': No such file or directory
~/opam-repository$ OPAM_SWITCH_PREFIX ~/.opam/opam-init/hooks/sandbox.sh build ls
bash: OPAM_SWITCH_PREFIX: command not found
~/opam-repository$ OPAM_SWITCH_PREFIX=blah ~/.opam/opam-init/hooks/sandbox.sh build ls
~/opam-repository$ echo $?
1
~/opam-repository$ sed -i 's/readlink -f/readlink -m/' ~/.opam/opam-init/hooks/sandbox.sh
~/opam-repository$ OPAM_SWITCH_PREFIX=blah ~/.opam/opam-init/hooks/sandbox.sh build ls
CHANGES.md  CONTRIBUTING.md  COPYING  README.md  packages  repo  version
```
=> Fix a crash in sandbox.sh when the XDG cache directory does not exist

master_changes.md, src/core/opamStd.ml, src/state/opamSysInteract.ml
we must juggle a bit between the limited interfaces provided to access
the apt database (e.g. `search` returns virtual pkg matches, but not
their origin package; other queries either don't handle them or don't
have regexps or options...), but it works.
So we call `apt-cache search --full` to retrieve the "provides" data,
then filter just the info we need, and reinterpret just the "provides"
info.
=> depext/debian: restore support for virtual packages with minimal cost

.gitignore, .travis-ci.sh, master_changes.md, src/client/dune, src/format/opamFile.ml, src/state/opamFormatUpgrade.ml
As new fields was added (depext ones), we need to upgrade to avoid syntax errors with an opam 2.0 bnary
fix #4266
=> Config file - opam root bump to format-version '2.1' + travis

master_changes.md, src/state/opamSysInteract.ml
It turns out `zypper` doesn't like the `--non-interactive` option if placed after `install` and only recognize it as an option if placed in second position:
```
$ docker run --rm -it ocurrent/opam:opensuse
opam@bd07475f78e2:~> sudo zypper install --non-interactive m4
The flag --non-interactive is not known.
opam@bd07475f78e2:~> sudo zypper --non-interactive install m4
Loading repository data...
Reading installed packages...
'm4' is already installed.
No update candidate for 'm4-1.4.18-lp151.3.70.x86_64'. The highest available version is already installed.
Resolving package dependencies...
Nothing to do.
```
=> depext: Fix non-interactive mode on opensuse

master_changes.md, opam-solver.opam, src/solver/dune, src/solver/opamBuiltin0install.ml.dummy, src/solver/opamBuiltin0install.ml.real, src/solver/opamBuiltin0install.mli, src/solver/opamCudf.ml, src/solver/opamCudfSolver.ml
A month ago, @talex5 presented a new fast solver for opam in this discourse post: https://discuss.ocaml.org/t/ann-opam-0install-0-1-fast-opam-solver-for-ci-etc/5852
The main goal of the project was to give a fast, CI-oriented external solver without having to use opam.
However for my own CI needs, a builtin solver was more appropriate, thus I started working on a version of this solver which would use the CUDF interface instead of the opam API: opam-0install-cudf (version 0.2 available on opam)
So, after months of testing on [check.ocamllabs.io](http://check.ocamllabs.io) (aka. https://github.com/kit-ty-kate/opam-health-check), where this new solver replaced and outperformed the Z3 builtin solver, I believe the interface in the right one (*) and this is now ready to be included upsteam. …
=> Add an optional solver relying on opam-0install-cudf

master_changes.md, src/client/opamAuxCommands.ml, src/client/opamPinCommand.ml
* With `opam pin target`, when opam file is not versioned and at root, vcs-pin the package instead of path-pin
* With `opam pin add nv target`, take opam file even if not versioned
=> Fix pin kind consistency

doc/pages/Distribution.md, master_changes.md
Note:
Repology url are from `https://repology.org/project/opam/badges`
On the form      : `[![Arch package](https://repology.org/badge/version-for-repo/arch/opam.svg)](https://repology.org/project/opam/versions)`
Transformed into : `[![Arch package](https://repology.org/badge/version-for-repo/arch/opam.svg?header=)](specific package url taken from repology page)`
=> Distrib page: add repology badges

master_changes.md, src/client/opamArg.ml, src/client/opamListCommand.ml, src/client/opamListCommand.mli
#3931 allows `<field>` to refer directly to a raw opam field and so added an entry to `OpamListCommand.field_names`. This list is also used for the `--columns` argument to `opam list` and `opam admin list` which still requires the trailing colon at all times.
This PR removes the spurious `<field>` from the help for `--columns` - this is correct (I think) since `--raw` can't be used here as `--columns` is a list of fields.
=> Fix --columns advertised options

master_changes.md, src/client/opamCommands.ml
`opam pin` has `-n` as an alias of `--no-action` (cf. `-n` meaning `--no-setup` in `opam init` as well)
=> Consistently have -n as alias of --no-action

master_changes.md, src/client/opamAdminCommand.ml, src/client/opamArg.ml, src/client/opamCommands.ml
Best checked commit-by-commit:
- Use `Cmdliner.Manpage.s_` constants instead of hard-coded section names (small tidy-up, although possibly one "bug" found)
- Aliases put the `--help` and `--version` options in `OPTIONS` instead of `COMMON OPTIONS`
- `opam lock --help` was missing all the common information (`ENVIRONMENT`, `BUGS`, etc.)
There are two other things to consider/fix:
- We call the section `ENVIRONMENT VARIABLES` (`OpamArg.help_sections`) but the standard name is `ENVIRONMENT` ([`Cmdliner.Manpage.s_environment`](https://erratique.ch/software/cmdliner/doc/Cmdliner.Manpage.html#VALs_environment)) - any reason not to change this?
- opam lock has a section `What is changed in the lock file?` - this should be in capitals and re-worded. Perhaps `LOCK PROCEDURE`, perhaps?
=> CLI help updates

src/format/opamFile.ml, src/format/opamLineLexer.mll
This is apparently a piece of lost history on my part, but it's resurfaced in #4325. Empty strings cause corrupt environment files, since two tabs are written in a row which are of course lexed as a single piece of whitespace.
For better or worse, my solution in 2016 was to write an empty string as `@`. The ambiguity with the string `"@"` is resolved by writing that as `\@` (since the format already allows `\` to escape _any_ character.
This can go on 2.0 with one caveat - it would mean that any environment updates which intentionally set a value to be `@` will now be empty. That seems unlikely, but it may be reason enough to fix this for 2.1 only.
=> Handle empty environment variable updates

master_changes.md, src/core/opamStd.ml, src/core/opamStd.mli, src/format/opamPackage.ml, src/format/opamSysPkg.ml
Removing unneeded string allocations can possibly have a big impact due
to the large number of set/map operations we have.
Fixes #4245, thanks for the suggestion
=> Optimise package name comparison

doc/index.html, doc/pages/FAQ.md, doc/pages/Usage.md, master_changes.md, src/client/opamAdminCommand.ml, src/client/opamAdminCommand.mli, src/client/opamArg.ml, src/client/opamArg.mli, src/client/opamCLIVersion.ml, src/client/opamCLIVersion.mli, src/client/opamClientConfig.ml, src/client/opamClientConfig.mli, src/client/opamCommands.ml, src/client/opamCommands.mli, src/client/opamMain.ml, src/core/opamCompat.ml, src/core/opamCompat.mli, src/core/opamConsole.ml, src/core/opamConsole.mli, src/core/opamCoreConfig.ml, src/core/opamCoreConfig.mli, src/core/opamStd.mli, src/core/opamSystem.ml, src/core/opamVersion.ml, src/state/opamGlobalState.ml, src/state/opamRepositoryState.ml, src/state/opamStateConfig.ml, src/state/opamStateConfig.mli, src/state/opamStateTypes.mli, src/state/opamSwitchState.ml
Implements the [CLI Versioning spec](https://github.com/ocaml/opam/wiki/Spec-for-opam-CLI-versioning)
Fundamentally, this PR allows the user/author to select backwards-compatibility with the opam 2.0 CLI by setting `OPAMCLI` to `2.0` and forwards-compatibility with future releases of the opam client by passing `--cli=2.1` _anywhere_ on the command line.
This is implemented by increasing the pre-processing which is done to `Sys.argv` before `Cmdliner.Term.eval` is invoked. Various things to note:
- While refactoring, I noticed that there's no reason for not supporting `opam adm` as an abbreviation for `opam admin` so this is now implemented (see `OpamCommands.is_admin_subcommand`).
- I've converted `OpamConsole.log` to use `Format.fprintf` instead of `Printf.fprintf` which has been on my …
=> Implement CLI versioning

master_changes.md, src/client/opamClient.ml, src/client/opamClient.mli, src/client/opamCommands.ml, src/client/opamPinCommand.ml, src/client/opamPinCommand.mli, src/core/opamProcess.ml
`opam pin scan url` lists available package to pin in the given directory
```
$ opam pin scan git+https://github.com/ocaml/opam
opam-state       2.1.0~alpha2  git+https://github.com/ocaml/opam
opam-solver      2.1.0~alpha2  git+https://github.com/ocaml/opam
opam-repository  2.1.0~alpha2  git+https://github.com/ocaml/opam
opam-installer   2.1.0~alpha2  git+https://github.com/ocaml/opam
opam-format      2.1.0~alpha2  git+https://github.com/ocaml/opam
opam-devel       2.1.0~alpha2  git+https://github.com/ocaml/opam
opam-core        2.1.0~alpha2  git+https://github.com/ocaml/opam
opam-client      2.1.0~alpha2  git+https://github.com/ocaml/opam
```
Used with `--normalise`, displays a parseable output
```
$ opam pin scan git+https://github.com/ocaml/opam --normalise …
```
=> `opam pin scan'

master_changes.md, src/client/opamArg.ml, src/client/opamArg.mli, src/client/opamClient.ml, src/client/opamClient.mli, src/client/opamCommands.ml, src/client/opamPinCommand.ml
Add `--with-version` pin option to permit to specify the version of the pinned package.
```
$ opam pin add git+https://github.com/ocaml/opam --with-version 3.0 -n -y
This will pin the following packages: opam-client, opam-core, opam-devel, opam-format, opam-installer, opam-repository, opam-solver, opam-state. Continue?
[Y/n] y
opam-client is now pinned to git+https://github.com/ocaml/opam (version 3.0)
opam-core is now pinned to git+https://github.com/ocaml/opam (version 3.0)
opam-devel is now pinned to git+https://github.com/ocaml/opam (version 3.0)
opam-format is now pinned to git+https://github.com/ocaml/opam (version 3.0)
opam-installer is now pinned to git+https://github.com/ocaml/opam (version 3.0)
opam-repository is now pinned to git+https://github.com/ocaml/opam (version 3.0) …
```
=> `opam pin --with-version'

master_changes.md, src/state/opamFormatUpgrade.ml, src/state/opamFormatUpgrade.mli, src/state/opamGlobalState.ml
When a read lock is acquired, upgrade config file _on-the-fly_ instead of the blocking process.
=> Opam root light upgrade

.travis-ci.sh, .travis.yml, master_changes.md, src/client/opamAction.ml, src/client/opamAuxCommands.ml, src/client/opamAuxCommands.mli, src/client/opamClient.ml, src/client/opamClient.mli, src/client/opamCommands.ml, src/client/opamInitDefaults.ml, src/client/opamInitDefaults.mli, src/state/opamEnv.ml, src/state/opamEnv.mli
The check is done by calling the sandbox script with `sandbox <action> sh -c "echo SUCCESS >/tmp/t && cat /tmp/t"`, and checking that stdout is `SUCCESS`.
Disabling is done by removing from global config sandboxing wrappers, default ones, defined in `OpamInitDefaults.sandbox_wrappers`.
=> On init, check and propose to disable sandboxing if tool present & not working (docker, chroot, WLS1, etc.)

master_changes.md, src/state/opamSwitchState.ml
=> Fix to output a correct note by changing to the --global flag instead

appveyor.yml, appveyor_build.cmd, master_changes.md
Cygwin 3.1.7 was released last week, so AppVeyor no longer needs to use a development snapshot for the Cygwin port's test.
The AppVeyor script now checks the installed version of Cygwin and forces an upgrade if necessary. AppVeyor is on 3.1.2 so for now this is necessary - when the AppVeyor base image is next upgraded, this will go back to installing packages only.
=> Switch AppVeyor back to stable Cygwin

.gitattributes, .travis.yml, appveyor.yml, appveyor_test.sh, master_changes.md, shell/bootstrap-ocaml.sh, src_ext/Makefile
This PR builds on https://github.com/ocaml/opam/pull/4234 to fix the little things that are missing and completely replaces 4.07.1 with 4.10.0 for bootstrapping.
Updating findlib to 1.8.1 is mandatory because 1.8.0 checks for the `-vmthread` flag of `ocamlc` which has been removed in 4.10.0.
EDIT: I removed the 'flexdll appveyor patch' in favor of using the latest flexdll commit available at the time of writing.
I have also updated and expanded Travis test matrix.
=> Bootstrap Opam with OCaml 4.11.1

master_changes.md, src/client/opamClient.ml, src/client/opamListCommand.ml, src/client/opamSolution.ml, src/client/opamSwitchCommand.ml, src/format/opamFormula.mli, src/solver/opamCudf.ml, src/solver/opamCudf.mli, src/state/opamSwitchState.ml, tests/Makefile, tests/reftests.ml, tests/reftests/camelus.test, tests/reftests/conflict-badversion.test, tests/reftests/conflict-camlp4.test, tests/reftests/conflict-core.test, tests/reftests/conflict-solo5.test, tests/reftests/install-pgocaml.test, tests/reftests/show.test
Finally! This needs more testing, so please everyone gather your
extreme conflict messages and send them to me; but this is very
promising.
=> Rewrite the conflict explanation extraction mechanism

master_changes.md, src/solver/opamCudf.ml, tests/reftests/conflict-badversion.test
We were missing some roots when the chain of dependencies ended up of
length 0!
=> Fix missing conflict message when trying to remove required packages

master_changes.md, src/client/opamAuxCommands.ml, src/state/shellscripts/bwrap.sh, src/state/shellscripts/sandbox_exec.sh
=> Fix Init sandbox check

master_changes.md, opam-client.opam, opam-core.opam, opam-devel.opam, opam-format.opam, opam-installer.opam, opam-repository.opam, opam-solver.opam, opam-state.opam
They were referring to the `version` variable already anyway, so I
guess there is no point in keeping them locked to the very obsolete
1.2: you'll probably prefer to use the bootstrap scripts if yiy are in
this case anyway?
=> Update opam files

appveyor.yml
Ref. https://github.com/ocaml/ocaml/pull/9939 for the underlying issue, this 
should be re-enabled once fixed upstream.
=> Temporarily disable appveyor mingw32 runs

master_changes.md, tests/Makefile, tests/patcher.ml
When running through the Makefile, the install binary is picked up and
the tests are run using the default profile. These tweaks ensure that it
is possible to run `dune runtest` directly after `dune clean`.
=> Ensure that a cold `dune runtest` works

master_changes.md, src/client/opamAdminCommand.ml
Caches are taken from the local `repo` file `archive-mirrors` field, then from 
the global opam configuration, if any.
Interestingly, the former (only) was already used by `opam admin add-hashes`, 
but not by `opam admin cache`.
Closes #4352
=> 'opam admin cache': use the configured caches for update

master_changes.md, src/state/opamSysInteract.ml
This PR:
* Adds support for DragonFlyBSD, which use virtually the same package manager as FreeBSD (`pkg`). For our purpose they behave exactly the same way and have the same required commands so I just merged the two together like it's done for centos/fedora/...
* Adds support for NetBSD, it seems like `pkgin` is the default package manager now, the old `pkg_add` is not even configured by default. It is to be noted that OpenBSD's and NetBSD's `pkg_info`/`pkg_add` are two very different software, even if they have the same name.
* Fixes OpenBSD, FreeBSD and Gentoo with regards to package paths. Packages on those systems come from their "ports collection" system and categorize their packages to prevent name conflicts.
- On OpenBSD and Gentoo, packages can be installed using the fullpath …
=> Depexts: Add support for NetBSD, DragonFlyBSD (+ fix OpenBSD, FreeBSD and Gentoo)

doc/pages/Manual.md, master_changes.md, src/client/opamAction.ml, src/core/opamDirTrack.ml, src/core/opamDirTrack.mli
This modification is necessary because `opam-bin` uses the `post-install-commands` to share files between switches using hard links. Unfortunately, without this PR, such actions modify the digests of the files just after their recording, so that `opam remove` will complain that the installed files have been modified.
=> Allow `post-install-commands` hooks to modify/remove installed files

.ocamlinit, Makefile, master_changes.md, src/client/opamClient.ml, src/client/opamListCommand.ml, src/client/opamLockCommand.ml, src/solver/opamCudf.ml, src/solver/opamCudf.mli, src/solver/opamSolver.ml, src/solver/opamSolver.mli, src/state/opamSwitchState.ml
This adds a resolution of conflicts at low-level (directly on the CUDF
that is sent to the solver, but after the satisfiability check so that
it doesn't have an impact on the error messages).
It might be a better replacement for the high-level preprocessing that
tried to remove conflicting compilers in OpamSwitchState, when
computing the universe. Preliminary tests have shown it can be very
efficient for local switch creation cases where the OCaml version is
constrained.
=> [WIP] Cudf request preprocessing

Makefile, master_changes.md, src/client/opamAdminCommand.ml, src/client/opamClient.mli, src/client/opamCommands.ml, src/format/opamFile.ml, src/state/opamFileTools.ml, src/state/opamFileTools.mli
It was hardcoded at too low level, and not properly disabled when not
reading files from repositories.
This also exports a few more helpful functions for plugins.
=> Fix handling of filename-encoded pkgname in opam files

doc/pages/Manual.md, master_changes.md, src/state/opamPackageVar.ml
=> New package variable: `opamfile`

master_changes.md, src/client/opamClient.ml, src/client/opamPinCommand.ml, src/client/opamPinCommand.mli, src/solver/opamActionGraph.ml, src/state/opamUpdate.ml
Fix #4315
Using the same example, it took 4m32 (with download-only option), and now with parallel and reuse of source dir, it takes only 1m32.
It also applies to `pin scan` arguments, and url pin.
cc/ @NathanReb
=> Parallel pin source fetching

master_changes.md, src/client/opamArg.ml, src/core/opamCached.ml
it seems in some cases (large files) there can be a bit of padding, and the
`Marshal` module should already detect size issues, no need do duplicate the 
work.
=> Internal caches: use size checks from Marshal

master_changes.md, src/core/opamHash.ml, src/core/opamSystem.mli
=> openssl invocation: Fix fallback (part of #4448)

master_changes.md, src/state/opamSysInteract.ml
At least on Linux Mint 20, the value of `os-family` is `ubuntu`. This caused `opam depext` to fail for me, as `ubuntu` is not one of the handled cases. This PR treats `os-family=ubuntu` as `os-family=debian`.
=> Treat os-family=ubuntu as os-family=debian

src_ext/Makefile, src_ext/Makefile.sources, src_ext/patches/cppo.common/0001-Restore-4.02-compatibility.patch, src_ext/patches/cppo.common/0001-Treat-tilde-and-hyphen-equivalently-in-semver.patch, src_ext/patches/cudf.pkg/0002-Fix-compilation-using-Microsoft-C-Compiler.patch, src_ext/patches/dose3.common/0001-fixes-for-4.06-safe-string.patch, src_ext/patches/dose3.pkg/0001-Fix-build-process-under-Windows.patch, src_ext/patches/dose3.pkg/0002-Fix-compilation-using-Microsoft-C-Compiler.patch, src_ext/patches/dose3.pkg/0003-Install-.cmx-files-for-packs.patch, src_ext/patches/dose3.pkg/dose3-5.0~rc1.patch, src_ext/patches/extlib.common/0001-Add-support-for-OCaml-4.12.patch, src_ext/patches/extlib.common/0002-caml_hash_univ_param-was-removed-for-OCaml-pre-4.00-.patch, src_ext/patches/extlib/extlib-1.7.5.patch, src_ext/patches/ocamlgraph/ocamlgraph-jbuilder.patch, src_ext/patches/seq.pkg/0001-switch-between-definition-alias-module-depending-on-.patch, src_ext/patches/seq/0001-seq-0.2-for-jbuilder.patch
~~Wants double-checking with 4.12.0~alpha1 - I've seen some failures with cppo, but hopefully they were one-offs.~~
Fixes:
- https://github.com/ocaml/opam/pull/4425#issuecomment-729676670 - we wind extlib forwards to 1.7.7 and apply the patch for 4.12
- Update cppo to 1.6.6 in order to have `dune` instead of `jbuild` files for Dune 2 compatibility.
- cppo patches for 4.12 and 4.02.3
- Update re to 1.9.0 and result to 1.4 in order to have `dune` files instead of `jbuild` files for Dune 2 compatibility
=> 2.0: 4.12 and Dune 2 compatibility

.github/scripts/hygiene.sh, .github/scripts/main.sh, .github/scripts/ocaml-cache.sh, .github/scripts/opam-bs-cache.sh, .github/scripts/preamble.sh, .github/workflows/ci.yml
Divided in several jobs:
* cache for ocaml system compilation
* cache for src_ext archives retrieving
* build on linux 4.0.2.3 -> 4.11.1 & macos 4.11.1
* test (opam-rt) on linux/macos 4.11.1 with an embedded compiler build cache & an opam-rt cache
* upgrade 1.2 -> 2.0 test on linux 4.11.1, with an embedded cache for opam 1.2 root
* make cold test
Travis is not yet disabled, those scripts need to be stress tested.
Jobs are imitating travis ones, ie:
* all linux build to check compiler compliance
* on macos build to check macos compliance
* one test job per platform (we need to introduce here further reftests and disable make tests from main build jobs)
* one make cold job on linux, to test make cold (need on macos also ?)
And:
* builds with fail fast, no need to build them all if there is …
=> Github actions: linux & macos

master_changes.md, shell/install.sh, src/state/opamSysPoll.ml
`armv8l` and `armv8b` actually mean "32bit emulation on an armv8 processor", see https://reviews.llvm.org/rG9b958356983afffaf56788f37bdab9213369fa45
This was causing issue in https://github.com/ocaml/opam-repository/pull/17747 where the package does not work on Arm32, restricted the availability there but 32bit environment is still wrongly detected as `arm64`:
```
#=== ERROR while compiling albatross.1.0.1 ====================================#
```
Test-case:
```
$ docker run --rm -it --entrypoint bash ocaml/opam:debian-10-ocaml-4.11@sha256:ca5b021f7b74707f3d5df69657bb5a34062e81f0cfb71fdf8101cb4b32a8980a
opam@3440e642156a:~$ uname -m
aarch64
opam@3440e642156a:~$ linux32 uname -m
armv8l
```
=> Fix architecture detection when using 32bit mode on ARM64 and i486

doc/pages/Manual.md, doc/pages/Packaging.md, master_changes.md, src/client/opamConfigCommand.ml, src/state/shellscripts/complete.sh, src/state/shellscripts/complete.zsh, tests/reftests/var-option.test
* Don't load switch for some variable looking
* Fix package variables display when no config file is found
* Fix `depext-bypass` removal (`-=`)
* Add var/option test
* Change `opam config list` to `opam var [--package]`. This option need to be deprecated
=> Var option: fix, test, update

Makefile, master_changes.md, src/client/opamAdminCommand.ml, src/client/opamArg.ml, src/client/opamArg.mli, src/client/opamCLIVersion.ml, src/client/opamCLIVersion.mli, src/client/opamCommands.ml, src/client/opamCommands.mli, tests/reftests/cli-versioning.test
Implementing CLI versioning, handling of the different CLIs from [spec](https://github.com/ocaml/opam/wiki/Spec-for-opam-CLI-versioning).
It is only handled for subcommands and flags, not principal commands. A note is added in the manpage depending of flag  validity and requested cli. When a not valid flag is used, a message is also printed to the user with cli indication, etc.
_See discussion below for more precisions_
Summary of new `[N]` and deprecated `[D]` options in 2.1 (diff of manpages from 2.0.7 & master).
* ~`--cli` [N]~
=> Cli versioning

master_changes.md, src/format/opamFile.ml
Fixes #3993. To not merge before #4298
To take the same example, with `opam admin add-constraint dune>=1.11` : 
```diff
diff --git a/packages/hardcaml/hardcaml.v0.12.0/opam b/packages/hardcaml/hardcaml.v0.12.0/opam
index ca3c8171bf..87f513d55c 100644
--- a/packages/hardcaml/hardcaml.v0.12.0/opam
+++ b/packages/hardcaml/hardcaml.v0.12.0/opam
@@ -10,13 +10,13 @@ build: [
["dune" "build" "-p" name "-j" jobs]
]
depends: [
-  "ocaml"            {>= "4.07.0"}
-  "base"             {>= "v0.12" & < "v0.13"}
-  "ppx_jane"         {>= "v0.12" & < "v0.13"}
-  "stdio"            {>= "v0.12" & < "v0.13"}
+  "ocaml" {>= "4.07.0"}
+  "base" {>= "v0.12" & < "v0.13"}
+  "ppx_jane" {>= "v0.12" & < "v0.13"}
+  "stdio" {>= "v0.12" & < "v0.13"}
"topological_sort" {>= "v0.12" & < "v0.13"}
-  "dune" …
```
=> Opam file with preserved format more precise

master_changes.md, src/client/opamClient.ml, src/client/opamClient.mli, src/client/opamCommands.ml, src/client/opamSolution.ml, src/client/opamSolution.mli
This implements #4036  (cc @kit-ty-kate ).
This is still WIP because even when using the option, we get the usual message:
```
The following actions will be performed:
∗ install dune            2.1.3
∗ install conf-gmp        1      [required by z3]
...
===== ∗ 9 =====
Do you want to continue? [Y/n]
```
It would be better to recall explicitly at this point that in fact, this will only fetch the sources of the packages. I'm not sure how to do it though, in part because this message is currently printed using the graph before the build and fetch actions are made explicit, so we only have install/remove/reinstall/(change?) actions.
=> Add a --download-only flag to "opam install"

.github/scripts/main.sh, .github/workflows/ci.yml, master_changes.md
This PR is aimed to fix #4474 by
1) using `$RUNNER_OS` to build a OS-specific URL for opam 1.2 binary (albeit only Darwin and Linux releases are available so Windows is not supported)
2) using `runner.os` when building a cache key for opam 1.2 root (so that MacOS will not try to re-use the linux binary and vice versa depending on which action ran first when the cache was empty)
Note that since the test still passes if the cache was built previously, we might be fine with just implementing 1, but this will lead to not-deterministic test behavior and can bring sorrow down the line.
=> Fix MacOS upgrade CI test using OS-specific opam 1.2 cache

master_changes.md, src/client/opamSolution.ml
* If all action error are fetching failure, return code 31 (`Sync_error`) instead of code 40 (`Package_operation_error`).
* if there is mixed failures, exit with code 40
* if there is some sucess, and some fetching failures, exit with code 31
Fix #4214
=> Rollback to fetch failure

master_changes.md, src/client/opamClient.ml, src/format/opamFile.ml
Closes #4432 (together with defining unreleased versions of `ocaml` as
hidden).
=> Ensure we don't advertise upgrades to hidden versions

master_changes.md, src/client/opamCommands.ml, src/state/opamEnv.ml, src/state/opamEnv.mli
This change is similar in spirit to https://github.com/ocaml/opam/pull/3274/commits/46eab70fd9318057c785a2bcfb31e8184f9fa492 (an open pull request marked as obsolete) with a slightly different implementation.
I'm new to OCaml and been following the instructions to install `opam`, during `opam init` it prints a shell-dependent line that will be added, but incorrectly prints `eval $(opam env)` (I use `fish` so that should be `eval (opam env)`):
```
In normal operation, opam only alters files within ~/.opam.
However, to best integrate with your system, some environment variables
should be set. If you allow it to, this initialisation step will update
your fish configuration by adding the following line to ~/.config/fish/config.fish:
source /Users/name/.opam/opam-init/init.fish > /dev/null 2> …
```
=> Print shell-appropriate eval command on `opam init`

appveyor.patch, appveyor.yml, appveyor_build.cmd, master_changes.md, src_ext/Makefile
mingw-w64 8.0.0 requires some changes in OCaml. These will be in 4.11.2 and 4.12.0, but in the meantime this PR sorts out the AppVeyor workers to eliminate the failures on PRs.
The bump of FlexDLL 0.39 is not necessary to restore the support, but it has the benefit of clearing the AppVeyor caches and rebuilding the compilers!
=> Restore mingw CI testing

master_changes.md, opam-solver.opam
[opam-0install-cudf.0.4](https://github.com/ocaml-opam/opam-0install-solver/releases/tag/v0.4) fixed a rather big issue with the way the solver treated conflicts and the previous version (0.3) should be avoided by end users.
=> opam-solver: Require opam-0install-cudf >= 0.4

master_changes.md, src/state/opamEnv.ml
This fixes an issue whereas disabling the hook script by answering "no"
to the 2nd question of "opam init" you end with an init script that
tries to source the non-existing env hook script.
=> init: fix non-existing file check in csh

master_changes.md, src/client/opamAction.ml, tests/reftests/cli-versioning.test
People who want to use the 2.1 features should be using `--cli=2.1` or `build-env: OPAMCLI = "2.1"`
Tested successfully using the following opam files:
```
opam-version: "2.0"
build: ["env"]
install: ["env"]
remove: ["env"]
```
```
opam-version: "2.0"
build-env: [OPAMCLI = "2.1"]
build: ["env"]
install: ["env"]
remove: ["env"]
```
Fixes #4491
=> Set OPAMCLI=2.0 by default during compilation/install/remove phases

master_changes.md, opam-devel.opam, tests/Makefile, tests/bin/dune, tests/dune
On some systems, opam's tests might be called by opam itself.
However, opam seems to hide parts of the `PATH` that looks like an opam `bin` directory.
To counteract that the tests need to copy `ocamlc` and `ocamlopt` directly before calling the local opam binary.
`openssl` and GNU-`diff` was also missing from the list of test dependencies. For instance those are not installed by default on Alpine.
=> Fix opam-devel's tests on platforms without openssl, GNU-diff and a system-wide ocaml

doc/pages/Install.md, master_changes.md
Opam 2.0.7 binaries for `arm64-macos` was added to `install.sh` in commit 037c31036a0f94d43fdc91856830fb248e63e8b3.
=> Mention pre-built opam for Arm Macs in INSTALL.md

master_changes.md, src/state/shellscripts/bwrap.sh, src/state/shellscripts/sandbox_exec.sh
As the title says. This is a bug that was found while investigating https://github.com/ocaml/dune/issues/4166.
Related issue: https://github.com/ocaml/opam/issues/4068
=> Fix the conflict with the environment variable name used by dune

master_changes.md, src/state/shellscripts/bwrap.sh
Per comment in https://github.com/ocaml/opam/issues/4400#issuecomment-774725510, I don't think we need to worry about supporting older version of bubblewrap.
- Only users on Debian 9 (EOL since July 2020) will have to upgrade bubblewrap
- Also, turns out opam already required bubblewrap >= 0.1.7
Fixes https://github.com/ocaml/opam/issues/4400
=> Kill builds on Ctrl-C with bubblewrap

master_changes.md, src/solver/opamCudf.ml
This bug didn't impact correctness, but it did make it less efficient
(in particular, it could make higher versions of OPAMDIGDEPTH perform less 
trimming !)
=> Fix Cudf preprocessing

master_changes.md, src/client/opamAction.ml
Patch was launched twice on the same file, and the same piece of code lead to an error with dev profile errors enabled : 
```
File "src/client/opamAction.ml", line 305, characters 6-34:
305 |       OpamFilename.patch patch dir)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error: This expression has type exn option job
but an expression was expected of type unit
```
+ ~Add a test  for patching and substitution~ moved to #4546
=> Don't patch twice the same file

master_changes.md, src/state/opamSysInteract.ml
Fixes #4297, see discussion there.
~Variants availability is not part of the PR as it is time consuming: one call per system package to check available variants~ One call is done now
=> depext: macport variants handling

master_changes.md, src/client/opamClient.ml, src/format/opamFile.ml, src/format/opamTypes.mli, src/format/opamTypesBase.ml, src/solver/opamBuiltinMccs.ml.real, src/solver/opamBuiltinZ3.ml.real, src/solver/opamCudfSolver.ml, src/solver/opamSolver.ml, src/state/opamSwitchState.ml
As per https://github.com/ocaml/opam/wiki/Dev-Meeting-2020.11.27#hidden-version, but apparently I forgot to open the issue to track it!
There were two other points:
- Post-process solutions to see if packages have changed to be hidden and warn (with a default of not installing)
- ocaml.4.12.0 needs to be tagged hidden-version
The second point I think has already been addressed addressed by https://github.com/ocaml/opam/pull/4477. I'll open an issue to track the other.
=> Rename hidden-version to avoid-version

master_changes.md, src/state/opamSysInteract.ml
e.g. when libc is upgraded and `opam update --depexts && opam install conf-gtksourceview3` is called, pacman will not upgrade the underlying libc and will result in a link failure similar to `undefined reference to 'stat64@GLIBC_2.33'`
Backported to `opam-depext` in https://github.com/ocaml-opam/opam-depext/pull/138
=> archlinux: Always upgrade all the installed packages when installing a new package

master_changes.md, src/client/opamCommands.ml
Instead of  `compiler_packages` or invariant (which is not necessarily a compiler), ~it looks for installed packages with compiler flag and display their variables.~ it displays variables of installed compilers (packages with compiler flag) and their installed dependencies.
cc/ @dra27
=> config report: fix not found and compilers variables display

master_changes.md, src/state/opamSwitchState.ml
opam 2.0 excludes base packages from consideration with rebuilds. This wasn't particularly correct in opam 2.0, but it limited the chances of being told that you had to use `--unlock-base`.
It makes no sense at all to keep it with switch invariants - if a package has upstream changes, it should be rebuilt regardless of whether it happens to be the compiler or not!
=> Rebuild "base" packages on changes

master_changes.md, src/client/opamPinCommand.ml
Related to #4569, but not itself a bug. Pinning an invariant package still displays this prompt:
```
$ opam pin add ocaml-base-compiler --dev-repo
[WARNING] Package ocaml-base-compiler is part of the base packages of this compiler.
Are you sure you want to override this and pin it anyway? [Y/n]
```
This prompt made sense in 2.0 where the base packages were locked, but it has no place any more with the glory of switch invariants!
**Combined with #4569 and forthcoming amendments PRs to ocaml/ocaml and ocaml/opam-repository, this makes pinning the compiler work naturally!** 🎉
=> Don't confirm pinning invariant packages

master_changes.md, src/client/opamCommands.ml, src/client/opamLockCommand.ml
* fix `--safe` & `--read-only` 
* fix inconsistency with `opam install` : on local pin, always take the last up to date opam file
fix #4320
=> `lock` options fixes

master_changes.md, src/client/opamAuxCommands.ml, src/client/opamClient.ml, src/client/opamPinCommand.ml, src/client/opamPinCommand.mli
It was a blind spot of source fetching
fix #4484
=> Fix `opam install <dir> -w` when package already pinned with another url

master_changes.md, src/repository/opamRepositoryPath.ml
Windows *really* doesn't like that.
=> Fix generation of temporary path with a looooong name

master_changes.md, src/client/opamCliMain.ml, src/core/opamProcess.ml, src/core/opamProcess.mli
split out from #4504
Expose `OpamProcess.create_process_env`, which has the correct way of calling 
cygwin executables from a Windows native opam (without unwanted expansion of 
arguments, etc.)
And use that for `opam exec` (instead of `Unix.execv`) so that it has the 
correct behaviour.
=> Fix `opam exec` on Windows

master_changes.md, src/client/opamAuxCommands.ml, src/state/shellscripts/bwrap.sh, src/state/shellscripts/sandbox_exec.sh
(also: port improvements from bwrap to sandbox_exec, and fix a few
bugs, in particular for detection of the sandbox and newer dune)
The `bwrap` script now bind-mounts the existing `$TMPDIR` read-only,
allowing proper communication from outside the sandbox to the inside;
and re-creates a tmpfs someplace else, re-defining `TMPDIR`.
It might break scripts that accessed `/tmp` directly (instead of
`TMPDIR`) though, since it won't be writeable from within the sandbox.
The previous behaviour was to bind-mount $TMPDIR to /tmp within the
sandbox, and re-set TMPDIR accordingly ; however, this meant that absolute
paths within TMPDIR could be incompatible between the outside and the
inside of the sandbox.
This became a visible problem with dune 2.8, which redefines TMPDIR to a
subdirectory (e.g. …
=> Sandbox script: change handling of TMPDIR

.github/scripts/hygiene.sh, master_changes.md, src/client/opamAdminCommand.ml, src/client/opamAdminCommand.mli, src/client/opamArg.ml, src/client/opamArg.mli, src/client/opamCLIVersion.ml, src/client/opamCLIVersion.mli, src/client/opamCliMain.ml, src/client/opamCliMain.mli, src/client/opamCommands.ml, src/client/opamCommands.mli, tests/reftests/cli-versioning.test
Some deprecated options need to still be accepted (cf. #4503). The default cli is here to allow them when used with no specified cli (not from environment or from option `--cli`). Opam prints then a removal warning notice.
The default version is set to 2.0, it will be upgraded at each major release.
Default cli options are ftm `opam config` deprecated commands.
Example with `config var`:
```
$ opam config var prefix
[WARNING] var is deprecated since version 2.1 of the opam CLI, but version 2.1 has been requested. Use opam var instead or set OPAMCLI environment variable to 2.0.
.opam/switch
$ opam config var prefix --cli 2.0
.opam/switch
$ opam config var prefix --cli 2.1
opam: var was removed in version 2.1 of the opam CLI, but version 2.1 has been requested. Use opam var instead or set …
```
=> Introducing default cli

doc/pages/Manual.md, master_changes.md
Looks like there is no class `opam`. It also prints the span tag sometimes in the manual, see https://opam.ocaml.org/doc/Manual.html
=> Doc: manual - remove useless span tag

master_changes.md, src/state/shellscripts/sandbox_exec.sh
Oops, had this fix lying around on the mac but it got lost in the final reftests PR.
=> MacOS sandbox: fix realpath use

master_changes.md, src/client/opamArg.ml, src/client/opamArg.mli, src/client/opamCommands.ml
This is sat on #4581 and #4575 both of which need merging first. The actual commit itself is tiny - `--silent` is of course retained in the default CLI.
Fixes #4323.
=> Rename opam list --silent to opam list --check

master_changes.md, src/client/opamClient.ml, src/state/opamSwitchState.ml, src/state/opamSwitchState.mli
Currently if for instance `ocaml-base-compiler.4.12.0~beta1` (flagged with `hidden-version) is installed, calling `opam upgrade` results in:
```
$ opam upgrade
Everything as up-to-date as possible (run with --verbose to show unavailable upgrades).
The following packages are not being upgraded because the new versions conflict with other installed packages:
- ocaml.4.13.0
However, you may "opam upgrade" these packages explicitly, which will ask permission to downgrade or uninstall the conflicting packages.
Nothing to do.
$ opam switch invariant
["ocaml-base-compiler"]
```
With this patch it should be upgraded to `ocaml-base-compiler.4.12.0~beta2` in this case.
cc @dra27 @AltGr
=> Allow to upgrade to a hidden-version package if a hidden-version package is already installed

master_changes.md, src/client/opamListCommand.ml
#4565 mentions that it would be good to have the `doc` field in the output of `opam show`.
Rather than a separate issue, here's the one-line PR (for discussion).
=> Include doc field in opam show

master_changes.md, src/client/opamAction.ml
=> pin version: don't error if archive opam file is malformed

master_changes.md, src/state/opamFormatUpgrade.ml, src/state/opamFormatUpgrade.mli, src/state/opamGlobalState.ml, tests/reftests/dune.inc, tests/reftests/gen.ml, tests/reftests/pat-sub.test, tests/reftests/run.ml, tests/reftests/switch-creation.test
The global lock is no more taken regarding opam root format upgrade needs. It is upgraded to the needed one (read ou write) according the kind of upgrade to perform (light/hard, on the fly or not), and released afterwards.
fix #4597
=> Change global lock only if format upgrade is performed

master_changes.md, src/core/opamConsole.ml, src/core/opamProcess.ml, src/core/opamStd.ml
During `opam init`, things proceed nicely until a second or so after the repository tarball is downloaded when the "Processing" message suddenly appears as:
```
<><> Fetching repository information ><><><><><><><><><><><><><><><><><><><><><>
[K[[32mdefault[0m] Initialisedlt[0m: http]
[KProcessing  1/1:
[36m<><>[0m [01mRequired setup - please read[0m
[36m<><><><><><><><><><><><><><><><><><><><><><><>[0m   
```
The problem is that processes invoked by `opam` gain `stdin` and therefore the Console and clear the Console mode (in particular, Cygwin processes seem to do this). They're running in the background, so it doesn't matter whether they behave nicely and restore the console mode on termination, because the message may well be displayed while they're running.
This PR offers …
=> VT100 escape sequences appearing on Windows 10 Console

master_changes.md, opam-admin.opam, opam-client.opam, opam-core.opam, opam-devel.opam, opam-format.opam, opam-repository.opam, opam-solver.opam, opam-state.opam, opam.opam
A few house-keeping amendments:
- Our own opam files should really pass `opam lint` 🙈 (re-wrote the `synopsis` fields not to have `opam` as the first word)
- `opam-format` should pedantically have an explicit dependency on `re`
- `opam.opam` and `opam-admin.opam` changed from being empty files to be minimally populated (they pass both opam lint and opam dune-lint)
=> Clean-up our opam files

master_changes.md, src/client/opamClient.ml, src/client/opamSwitchCommand.ml, tests/reftests/conflict-camlp4.test
This fixes the remaining issues in #4572 - see commits for notes.
=> Update remaining references to base packages

doc/pages/Manual.md, master_changes.md, src/client/opamClient.ml, src/client/opamClient.mli, src/client/opamCommands.ml, src/client/opamInitDefaults.ml, src/client/opamSwitchCommand.ml, src/client/opamSwitchCommand.mli, src/format/opamFile.ml, src/format/opamFile.mli, src/format/opamFormula.ml, src/solver/opamSolver.ml, src/state/opamRepositoryState.ml, src/state/opamSwitchState.ml, tests/reftests/cli-versioning.test, tests/reftests/dune.inc, tests/reftests/gen.ml, tests/reftests/init.test, tests/reftests/run.ml
(todo: add tests)
compared to 2.0, this just adds the new 'default-invariant', and keeps
similar semantics for 'default-compiler', which is only used for 'opam
init' (but must now be compatible with the invariant).
previously the 2.1 branch completely replaced the older meaning of
'default-compiler', using it as 'default-invariant' instead, but the order
of priority was lost.
=> Introduce 'default-invariant' besides 'default-compiler'

master_changes.md, src/solver/opamCudf.ml, tests/reftests/cudf-preprocess.test, tests/reftests/dune.inc
Closes #4624
The issue was that, after pre-processing, we were only considering the 
dependency cone of required packages, plus already installed packages.
It happens this wasn't enough, because reverse dependencies may need to be 
upgraded: in this case, we wouldn't see the new version, and so just remove
the package.
However, once you do that, these newly included package versions may need to 
bring in new dependencies; we could just add their full depdendencies to the
set of packages we need to consider, but that would end up severely reducing
the scope of the trimming;
so, going further, we split the computation of dependencies into strict 
requirements, on the requested packages, bringing constraints that can always
be enforced ; and simple dependencies, computed for all other …
=> Fix bug with Cudf pre-processing leading to some packages unnecessarily removed

master_changes.md, src/client/opamCliMain.ml, src/format/opamPath.ml, src/format/opamPath.mli, src/state/opamFileTools.ml
This is a partial fix for #4619 (the other part would be to remove the plugin symlinks at format upgrade).
This tweaks the plugin detection slightly so that if the symlink is missing, the command is still resolved, but package will be reinstalled in the current switch. This will recreate the symlink and also apply any changes to dependencies (e.g. after an opam client upgrade).
It's demonstrated by this slightly convoluted Dockerfile - commenting out the final `rm` command shows the existing error.
```
FROM ocaml/opam:debian-ocaml-4.12
WORKDIR /src
RUN sudo chown opam /src
RUN git clone https://github.com/dra27/opam.git
WORKDIR /src/opam
RUN opam pin add -n dose3 5.0.1-1
RUN git checkout reinstall-plugins ; opam install dose3 opam-file-format mccs cmdliner
RUN opam exec -- ./configure && …
```
=> Reinstall plugin package if the symlink is missing

master_changes.md, src/client/opamAction.ml, src/core/opamDirTrack.ml, src/core/opamDirTrack.mli, tests/reftests/dot-install.test, tests/reftests/dune.inc
Implements https://github.com/ocaml/opam/issues/4422
Currently opam scans the whole switch directory recursively twice when installing a package (per package). This introduces a huge strain on the IO of the machine. This is especially visible under high load (e.g. in CI)
This PR makes so that opam only scan the files that are going to be installed (if they exist already, this is rare) if the package does not have any `install` field. If the package does have an `install` field the old behaviour is used.
=> Make install faster by not scanning the whole switch when no install field is present

master_changes.md, src/solver/opamBuiltin0install.ml.real
- `+count[version-lag,solution]` tells the solver to always choose the oldest version available instead of the latest (useful to test lower-bound constraints)
- `+removed` tells the solver to not bother trying to keep installed packages. This is useful for CI where you might want consecutive runs of opam to be reproducible.
=> Add support for a few select criteria useful to CI to the 0install solver

Makefile, doc/Makefile, master_changes.md
=> Fix build from source when a dune-project file is presented in the parent directory

master_changes.md, src/state/opamFileTools.ml
Highlighted in https://github.com/ocurrent/opam-repo-ci/issues/93
=> lint W59/E60: don't check vcs upstream

src_ext/Makefile.sources
GLPK 4.63 doesn't appear to build on Fedora 34.
=> Bump lib-ext mccs to 1.1+13 [2.0]

master_changes.md, src/client/opamCliMain.ml, src/core/opamFilename.ml, src/core/opamFilename.mli, src/core/opamSystem.mli, src/state/opamFormatUpgrade.ml
This is the last part of #4619, which it turns out is a bit simpler and less dirty than I feared.
This `Dockerfile` demonstrates the problem:
```Dockerfile
FROM ocaml/opam:debian-ocaml-4.12
WORKDIR /src/test
RUN sudo chown opam /src/test
RUN opam pin add -n dose3 5.0.1-1 ; opam install dune dose3 opam-file-format mccs cmdliner ; opam install opam-dune-lint --deps-only
RUN opam exec -- dune init project foo
RUN echo > dune-project '(lang dune 2.8)\n(generate_opam_files true)(source (github foo/bar))(package (name foo))'
RUN opam exec -- dune build
WORKDIR /src
RUN sudo chown opam /src
#RUN git clone https://github.com/dra27/opam.git -b clear-plugins
#Comment out the line below and uncomment the line above to get the fix
RUN git clone https://github.com/ocaml/opam.git
WORKDIR /src/opam
RUN …
```
=> Delete plugin links on root upgrade

master_changes.md, src/format/opamPath.ml, src/format/opamPath.mli, src/state/opamRepositoryState.ml
At present `$OPAMROOT/repo/state.cache` will be reset if the magic string does not match the version of opam-state / opam. This is tedious when developing and also visible to users as opam-state has a slightly different version from an opam binary.
The fix is quite simple: include the magic string in the filename as well, and tolerate having multiple cache files. `state.cache` is only ever written if something changed, and all that happens now is that `$OPAMROOT/repo/*.cache` is erased prior to writing the new cache (since other opam-state / opam binaries actually must regenerate the file).
As the cache files are all reset at `opam update`, even developers shouldn't see too many of them accumulating.
Fixes #4554. It can't directly be backported to 2.0.9, because 2.0.8 and earlier don't …
=> Allow multiple state caches
