ocaml/opam

master_changes.md, src/client/opamArg.ml, src/client/opamCliMain.ml
- Swap the two paragraphs in the explanation of CLI versioning - i.e. tell the user _what_ to do first and then _why_ to do it second
- More specific message in the help for `--cli` about `OPAMCLI` - they're not entirely equivalent, so we don't claim it.
- Bossier message when `OPAMCLI` is set to anything other than `2.0`: e.g. "`OPAMCLI` should only ever be set to `2.0` - use '`--cli=2.1`' instead."
- Bossier (and clearer) message when `--cli=2.0` is given: "`--cli=2.0` cannot be understood by opam 2.0; set `OPAMCLI` to `2.0` instead"
cc @avsm
=> Clearer warnings and messages about --cli / OPAMCLI

Makefile, master_changes.md
Both the libexec and lib sections install a file called `opam` which of course installs to the same place.
This _doesn't_ fix #4657, the original `opam-devel.install` has merely exposed a bug.
=> Fix opam-devel.install

master_changes.md, src/client/opamAction.ml, src/client/opamConfigCommand.ml, src/client/opamConfigCommand.mli, src/client/opamSolution.ml, src/state/opamEnv.ml, src/state/opamEnv.mli, tests/reftests/switch-creation.test
If one installs a package in a root or switch that is not currently active, and that package calls the `opam` binary during installation, it will not see the correct root/switch because the environment variables are not set.
Examples:
``` shell
opam install coq-tactician-stdlib --root=my-root
opam install coq-tactician-stdlib --switch=my-switch
```
=> Make sure that OPAMROOT and OPAMSWITCH are properly set when executing build commands

master_changes.md, src/client/opamAction.ml, src/client/opamArg.ml, src/client/opamArg.mli, src/client/opamArgTools.ml, src/client/opamArgTools.mli, src/client/opamCLIVersion.ml, src/client/opamCLIVersion.mli, src/client/opamClientConfig.ml, src/client/opamClientConfig.mli, src/state/opamEnv.ml, src/state/opamEnv.mli
Packages build with OPAMCLI=2.0. If the user sets an opam 2.1-specific environment variable, this is passed through to the package and will cause a warning to be displayed in the build log if the package calls opam.
All new environment variables are now scrubbed from the build environment.
=> Scrub OPAM* for variables added since 2.0

master_changes.md, src/client/opamSolution.ml, src/solver/opamCudf.ml, src/state/opamSwitchState.ml
Well, hopefully improve. At the moment, if you install a conf package directly, you get the depext availability message from _before_ solving:
```
dra@thor:~/opam$ opam install conf-capnproto
[ERROR] Package conf-capnproto depends on the unavailable system package
'capnproto libcapnp-dev'. You can use `--no-depexts' to attempt
installation anyway.
```
although the message is not properly formatted. If, as is more likely, the conf package is pulled in via a dependency, the message comes _after_ solving and is a little more intimidating:
```
dra@thor:~/opam$ opam install capnp-rpc-unix
[ERROR] Package conflict!
* Missing dependency:
- capnp-rpc-unix → capnp-rpc-lwt < 0.2 → conf-capnproto
depends on the unavailable system package 'capnproto libcapnp-dev'. Use
`--assume-depexts' to attempt …
```
=> Improve depext unavailable messages from the solver

.github/workflows/ci.yml, appveyor.yml, master_changes.md, opam-admin.opam, opam-format.opam, src/format/opamFile.ml, src_ext/Makefile.sources
Needs opam-file-format 2.1.3 to be released first (and `src_ext/Makefile.sources` updated with it).
This then automatically closes #4394. If you put `opam-version: "2.1"` as the second line of an opam file instead of:
```
error  2: File format error: unsupported or missing file format version; should be 2.0 or older
```
you now get the correct:
```
error  2: File format error at line 2, column 0: Parse error
```
=> Bump to opam-file-format 2.1.3

master_changes.md, src/client/opamAction.ml, src/core/opamSystem.ml, tests/reftests/dot-install.test
#4657 exposed no fewer than 3 bugs! 🐛
- `OpamSystem.install` doesn't the file permissions correctly if the file already exists (since `open_out_gen` only uses the mode if it actually creates the file). The first commit here fixes that and also the case of a symlink being overwritten which is handled by `OpamSystem.copy_file` but wasn't being handled by `OpamSystem.install`.
- `opam-devel.install` installs a file called `opam` twice to `lib/opam-devel` (fixed in #4664)
- The updates in #4494 changed the order in which sections were processed - the second commit here reverses (excuse pun!) that slip
NB `List.flatten` blows the stack w.r.t. the number of lists (which is fundamentally small) and the length of the longest sub-list - this would already blow the stack in an earlier `List.map` …
=> Fix installation order when processing .install files

master_changes.md, src/state/opamSysInteract.ml
The default behaviour as I understand it is that if only one package is being installed it will not prompt for anything (same behaviour as apt) but will prompt if dependencies are required
=> Add support for non-interactive mode in macports

master_changes.md, src/client/opamArg.ml, src/client/opamArg.mli, src/client/opamCliMain.ml, src/client/opamClientConfig.mli, src/client/opamSolution.ml, src/core/opamConsole.ml, src/core/opamCoreConfig.ml, src/core/opamCoreConfig.mli, src/state/opamEnv.ml, src/state/opamSysInteract.ml
Automatic answering depends on several parameters: confirm-level, yes, and no cli flags and environment variables.
In #4582, environment computes an answer, cli flags another one, and those answers were compared to set the run answering (cli > env var). That lead to #4682.
One solution is to check each parameters against its environment variable / cli flags, and then compute the automatic answering. So in  `OpamCore.Config.!r`, answer is no more set, but `confirm_level` and `yes` fields, and a new function permits to retrieve this answer `OpamCoreConfig.answer` (lazy).
One side effect of this mechanism is that if `OPAMCONFIRMLEVEL` is set in the environment, `--yes/--no` are ignored (as confirm-level > yes/no), and it can be resset only by using `--confirm-level`.
=> confirm level/yes/no: better answer computation

master_changes.md, src/client/opamCommands.ml, src/format/opamPath.ml, src/format/opamPath.mli, src/state/opamPackageVar.ml, tests/reftests/var-option.test
Piece of code that resolve the `hash` variables was still relying on the old archiving format (`archive` directory & `pkg+opam.tgz` archive).
=> var: display package hash

master_changes.md, src/state/opamSysInteract.ml
Use `apk policy pkgs` insteald of `apk list --available`
fix #4670
=> External dependencies & alpine: handle tagged repositories

doc/pages/Manual.md, master_changes.md, src/state/opamSwitchState.ml
* update the manual
* fix a misleading unavailability message
Ref. #4662
=> Some clarifications about depexts

master_changes.md, src/client/opamClient.ml, src/client/opamSolution.ml, src/solver/opamCudf.ml, src/solver/opamCudf.mli, src/state/opamSwitchState.ml, src/state/opamSwitchState.mli, src/state/opamSysInteract.ml, src/state/opamSysInteract.mli
Provides the workaround for #4669 discussed last week. This PR temporarily sits on #4678, as it uses some of the refactorings - only https://github.com/ocaml/opam/commit/34d5cafba78d626e565bfe72cb8e1ab4ea6c4188 is new.
With this patch, on CentOS without EPEL enabled you now see:
```
dra@thor:~/opam$ opam install conf-capnproto
[ERROR] Package conf-capnproto depends on the unavailable system package
'capnproto'. You can use `--no-depexts' to attempt installation anyway.
On CentOS/RHEL, many packages may assume that the Extra Packages for
Enterprise Linux (EPEL) repository has been enabled. This is typically
done by installing the 'epel-release' package. Please see
https://fedoraproject.org/wiki/EPEL for more information.
```
Most of the change is refactoring the existing API to separate …
=> Display a message on CentOS if EPEL isn't enabled and depexts aren't available

master_changes.md, src/client/opamSolution.ml, src/core/opamConsole.ml, src/core/opamConsole.mli
=> depext: ignore `--yes` on asking to run install commands

master_changes.md, src/core/opamSystem.ml
Fixes https://github.com/ocaml/opam/issues/4705
Introduced in opam 1.1.0~rc https://github.com/ocaml/opam/commit/fb108835e5182ee17620a724aa3f552822e04052
=> Add missing shell quoting to support space and special shell characters in switch directory path

master_changes.md, src/client/opamInitDefaults.ml
`/usr/bin/sh: ocamlc: command not found` returned for `sys-ocaml-arch`, `sys-ocaml-cc` and `sys-ocaml-libc` if there's no system compiler
=> Fix sys-ocaml-* variables with no system compiler

master_changes.md, src/core/opamConsole.ml
If the console handle is `dup2`'d (which mccs does for `verbose=0`) then the handle becomes invalid.
=> Fix VT100 support (again)

.github/scripts/ocaml-cache.sh, .github/scripts/preamble.sh, .github/scripts/solvers.sh, .github/workflows/ci.yml, CHANGES, src/client/opamArg.ml, src/solver/opamBuiltinZ3.ml.real, src/solver/opamSolverConfig.ml, src/solver/opamSolverConfig.mli
This environment variable is no more needed, so remove it.
fix #4717
=> Fix `OPAMZ3DEBUG` cyclic dependency

CHANGES, src/format/opamFile.ml, src/state/opamFormatUpgrade.ml, src/state/opamGlobalState.ml, src/state/opamStateConfig.ml, src/state/opamStateConfig.mli, tests/reftests/dune, tests/reftests/opamroot-versions.test, tests/reftests/run.ml
* Fix format upgrade when there is missing local switches in the config file
* Fix not recorded local switch handling, with format upgrade
* Set opam root version to 2.1
* Update tests with 2.1, local switch (recorded and not)
fix #4713
=> Format upgrade fix: remove missing switches from config file

master_changes.md, src/state/opamSysInteract.ml
`--confirm-level=unsafe-yes` and "closing stdin" are opam's two non-interactive mechanisms. The latter works correctly with depext (since the package manager will never be invoked) but the former breaks for `apt` if a package has a prompt.
This PR adds `DEBIAN_FRONTEND=noninteractive` to calls to `apt-get install`.
=> Set DEBIAN_FRONTEND=noninteractive for unsafe-yes

master_changes.md, src/state/shellscripts/env_hook.fish
According to https://fishshell.com/docs/current/index.html#id4 
"Previous versions of fish also allowed specifying this as ^DESTINATION, but that made another character special so it was deprecated and will be removed in the future."
fish version 3.3.0 by default gives an error on old syntax
=> deprecated syntax removed

.github/scripts/ocaml-cache.sh, master_changes.md, release/Dockerfile.in, release/Makefile, release/release.sh
* Use Alpine and build really static binaries with Musl
* Add hepers to do the artifacts signatures
* This was used already for the 2.1.0~rc2 binaries (and some of the rc1)
* Temporary fixes using last-minute patches:
- Fix for arm32+musl (see https://github.com/ocaml/ocaml/pull/10471)
- Remove -Wno-stringop-overflow from glpk as it breaks with some (older)
compilers
=> Release scripts update

CHANGES, src/client/opamCommands.ml, src/client/opamConfigCommand.ml, src/state/opamGlobalState.ml, src/state/opamStateConfig.ml, tests/reftests/opamroot-versions.test
Fix `safe_load` behavior to permit to catch format upgrade triggers.
Fix #4748
=> Fix intermediate format upgrade with reinit

CHANGES, src/state/shellscripts/env_hook.fish
Attempt at backporting https://github.com/ocaml/opam/pull/4736 to the 2.0 branch
@rjbou I'm not sure how you usually do, but just in case this is useful.. ^^
=> Backport #4736 to the 2.0 branch

CHANGES, src/state/shellscripts/env_hook.fish
Attempt at backporting https://github.com/ocaml/opam/pull/4736 to the 2.1 branch
@rjbou I'm not sure how you usually do, but just in case this is useful.. ^^
=> Backport #4736 to the 2.1 branch

CHANGES, src/client/opamCliMain.ml, src/client/opamCommands.ml, src/state/opamFormatUpgrade.ml, src/state/opamFormatUpgrade.mli, tests/reftests/opamroot-versions.test
=> Hard format upgrade triggered by a reinit acts as a successful command

CHANGES, src/state/opamSysInteract.ml
Some examples of the new behavior
```
libx11-dev policy:
1.7.1-r0:
lib/apk/db/installed
https://dl-cdn.alpinelinux.org/alpine/v3.13/main
1.7.2-r0:
@edge https://dl-cdn.alpinelinux.org/alpine/edge/main
```
* `libx11` as installed
* `libx11@edge` as available
```
bubblewrap policy:
0.4.1-r2:
lib/apk/db/installed
https://dl-cdn.alpinelinux.org/alpine/v3.13/main
@edge https://dl-cdn.alpinelinux.org/alpine/v3.13/main
https://dl-cdn.alpinelinux.org/alpine/edge/main
@edge https://dl-cdn.alpinelinux.org/alpine/edge/main
```
* `bubblewrap` and `bubblewrap@edge` as installed
```
capnproto policy:
0.8.0-r1:
@edgecommunity https://dl-cdn.alpinelinux.org/alpine/edge/community
```
* `capnproto-dev@edgecommunity` as available
=> Depext: fix alpine tagged repositories handling

shell/install.sh
In https://github.com/ocaml/opam/wiki/How-to-test-an-opam-feature, the following thing is said:
```
To test a release other than the latest, change master to the tag name.
```
I think this is extremely brittle and dangerous. e.g. the script might be buggy and need to be fixed, the checksums of some of the binaries might need to change for some reason, an update to the install script might have been forgotten in the tag, …
The later happened in 2.1.0~rc2 so the following fails:
```
sh <(curl -sL https://raw.githubusercontent.com/ocaml/opam/2.1.0-rc2/shell/install.sh) --dev --backup         
Checksum mismatch, a problem occurred during download.
```
Issue found by @patricoferris
If/Once this is accepted and merged we need to also change the wiki page.
=> shell/install.sh: Add the ability to specify the version of opam you want

.github/scripts/solvers.sh, master_changes.md, src/state/opamFileTools.ml, tests/reftests/dune.inc, tests/reftests/lint.test, tests/reftests/show.test, tests/reftests/upgrade-format.test
Partially fixes https://github.com/ocaml/opam/issues/4598
=> opam lint: Warn if the license field is not present

.github/scripts/changelog_checker, .github/scripts/hygiene-main.sh, .github/scripts/hygiene-preamble.sh, .github/scripts/hygiene-scripts.sh, .github/workflows/main.yml, .github/workflows/scripts.yml, master_changes.md
- specify changed files on when main ci is launched
- separate install script job into a new workflow
- launch main hygiene job if configure/src_ext changed
- update changelog checker whitelist with CHANGES and LICENSE
=> GHA: specialise jobs 

README.md, doc/pages/Distribution.md, doc/pages/Install.md, master_changes.md, release/readme.md, src/client/opamArg.ml, tests/reftests/run.ml
The change of the advised way to call `install.sh` was proposed in https://github.com/ocaml/platform-blog/pull/77 and includes:
* `<()` is a bash syntax, so people using this command in `sh` or `csh` will see the command fail
* `curl` without `-fS` will output things in stdout when something goes wrong (404, and other network failure) and can cause random shell commands being executed. This is what https://brew.sh/ recommend for instance.
=> Doc improvements

.github/scripts/legacy.sh, .github/workflows/main.yml, configure, configure.ac, master_changes.md, opam-client.opam, opam-core.opam, opam-devel.opam, opam-format.opam, opam-installer.opam, opam-repository.opam, opam-solver.opam, opam-state.opam, src/client/opamCLIVersion.ml, src/repository/opamVCS.mli
Continues from #4770. opam-core, opam-format and opam-installer are now tested separately where only the libraries are built.
CI is still quite painful because the ocaml-secondary-compiler, however, I have an overhaul PR ready to go which sorts out the caching for that.
=> Switch minimum OCaml version to 4.08

master_changes.md, src/repository/opamGit.ml
Triggered from [this Discuss comment](https://discuss.ocaml.org/t/removing-fat-compiler-images-on-hub-docker-com-r-ocaml-opam2/6658/6). This PR acts as a tracking "issue" for further discussion. I don't think in the repo backends we _need_ the Git history for the repository being checked out - we just need it to be possible to update it?
So this adds `--depth=1` to the git-fetch call. This reduces opam-repository as a Git clone, for example, from ~95MiB storage to ~15MiB.
But there may be other consequences...
=> Use --depth=1 for Git repos

master_changes.md, src/core/opamSystem.ml
this is #4731 rebased onto master.
=> opamSystem: avoid calling Unix.environment at top level

Makefile, master_changes.md
Issue encountered in #4801 
The fix isn't too great. Ideally I wish I knew a way to scrub the environment of anything non-standard or something like that but it's complicated. Using `su -l $USER -c -- ...` works for this but is rather tricky. If someone knows a way please do propose.
=> Fix the cold target in presence of an older OCaml compiler version on macOS

master_changes.md, src/client/opamAuxCommands.ml, src/core/opamSystem.ml, src/core/opamSystem.mli
The sandbox will attempt to mount the current working directory which may fail (and which we don't necessarily have any business doing).
=> Run sandbox checker in temp directory

.gitignore, master_changes.md, src/core/opamStd.ml
This is a follow-up to the announcement made at https://discuss.ocaml.org/t/ann-windows-friendly-ocaml-4-12-distribution-diskuv-ocaml-0-1-0/8358
Key Changes:
* Use USERPROFILE environment variable on Windows if HOME is not defined
* For the most part treat MSYS2 and Cygwin as equivalent. MSYS2 executables can be detected as `msys-2.0.dll`.
* Symlinks are not portably supported on Windows. Solutions like requiring the developer mode of Windows or Administrator access for NTFS symlinks will always limit the audience on Windows; I don't want to limit the audience. For Opam packages with symlinks the MSYS2 environment will simply default to copying rather than symlinking, but copying has edge cases:
1. When rsync-ing the symlink referent must exist _before_ the symlink (ie. copy) is made. In …
=> Support MSYS2

master_changes.md, src/state/shellscripts/sandbox_exec.sh
I'm not sure what was the reason behind having /tmp rw on macos but read-only on linux.
In opam 2.0 it seem to have been the invert at first (rw on linux and ro on macos) however it was synchronized to rw in both in 2.0.8 in see https://github.com/ocaml/opam/pull/3742.
In opam 2.1~rc a linux-only change was done which made it ro: https://github.com/ocaml/opam/pull/4589, but it was never ported to macos.
=> Sync the behaviour of the macOS sandbox script with Linux's

master_changes.md, src/core/opamProcess.ml, src/core/opamSystem.ml, src/repository/opamDownload.ml
Split off from #3897. @AltGr agreed this was worth doing in https://github.com/ocaml/opam/pull/3897#pullrequestreview-348824024, but it's too close to the 2.1 release for a change which isn't a critical part of that fix, so this can be merged post-2.1
=> Don't connect stdin to sub-processes

master_changes.md, src_ext/patches/mccs.common/0001-Always-include-std-headers-first.patch
The rpcndr.h header includes a typedef for byte which gets messed up when combined with using namespace std and C++17's byte type.
Should fix AppVeyor. We should get https://github.com/AltGr/ocaml-mccs/pull/35 merged and released prior to 2.1.1 (and then switch to the `+14` release of ocaml-mccs and nuke this patch).
=> Patch ocaml-mccs for C++17 on Windows

master_changes.md, src/state/opamSysInteract.ml
#4790 shows that `yum list` is an unreliable command to use and no options seems to be available to make it so.
#4759 also shows that RHEL-based distributions have virtual packages that opam is not taking into account.
For these two reasons I propose we simply remove the use of `yum list` in favour of `rpm -qa` which seems way more reliable and leaps faster (~0.1s vs. ~2s!!).
Sadly we incidently disable the detection of available packages and thus revert to the behaviour of the opam-depext plugin.
IMO this is not a big deal as only a few distributions that we support actually have it disabled as well due to the method to acquire the data being either incomplete or too tedious/unreliable. This is the case currently (in 2.1.0) for FreeBSD, Gentoo, Homebrew, NetBSD and OpenBSD
=> depexts: Disable the detection of available packages on RHEL-based distributions

master_changes.md, src/format/opamFilter.ml
Currently it returns the unconverted value when `no_undef_expand` is true, which means that `lwt:enable` gets rendered as "true"/"false", not "enable" / "disable". This PR applies conversions if there is some value which can be cast to a boolean.
I don't think this affects end users at all, I discovered this behaviour by using `OpamFilter.expand_string ~partial:true` directly.
=> OpamFilter: handle converted variables correctly when no_undef_expand is true

master_changes.md, src/state/opamRepositoryState.ml
Stop scanning once the result is found. Also simplifies the code a bit.
=> Replace linear search with Array.exists

master_changes.md, src/solver/opamBuiltin0install.dummy.ml, src/solver/opamBuiltin0install.real.ml, src/solver/opamBuiltinMccs.dummy.ml, src/solver/opamBuiltinMccs.real.ml, src/solver/opamBuiltinZ3.dummy.ml, src/solver/opamBuiltinZ3.real.ml, src/solver/opamCudf.ml, src/solver/opamCudfSolver.ml, src/solver/opamCudfSolverSig.ml
Closes #4658, see the discussion there.
It'd probably be worth it to check the Dose3 check times though; they
may be due to the increased complexity of the repo, but also maybe to
the new dose3 version ?
Also I didn't re-check the response times of the different solvers in
case of complex, unsat cases : the worrying case here was mccs stalling
for tenths of seconds, even sometimes timing out, while dose3 (which we
would call anyway) would detect the conflict in a fraction of a second.
=> Make the SAT preemptive check optional, by-solver

master_changes.md, src/client/opamCommands.ml
=> repo: don't display global message when `this-switch' is given

master_changes.md, src/core/opamConsole.ml, src/solver/opamBuiltinZ3.real.ml, src/solver/opamCudf.ml, src/solver/opamSolver.ml, src/solver/opamSolverConfig.ml
This adds a lot of factorisation and simplifications to the Z3 solver
backend. On a basic switch creation example, the size of the generated
.smt2 is down from 34000 lines to 6000, and the speedup around 40%.
Also fixes a correction bug that seemed to be present on master.
note: the patches in this PR should probably be squashed.
=> Refactor the Z3 solver backend

master_changes.md, src/state/opamSysInteract.ml
On some settings, some RHEL-based systems do not come with `yum` installed by default.
Encountered by @vsiles on CentOS (Stream) and minimal docker images for Oraclelinux 8 https://github.com/avsm/ocaml-dockerfile/pull/35
=> Fallback on dnf if yum does not exist on RHEL-based systems

Makefile, master_changes.md, src/state/opamStateConfig.ml, tests/reftests/cli-versioning.test, tests/reftests/env.test, tests/reftests/legacy-git.test, tests/reftests/legacy-local.test, tests/reftests/opamroot-versions.test, tests/reftests/run.ml
* Fix meld reftest: open only with failing ones
* Automatically replace opam bin path, add `BASEDIR` environment variable
* Add `grep -v` command, helper instead of just using sed
* On replacement, ~get the latest group for the end of the match, not the first one (in case groups are defined in regexp)~ replace all occurrences [hackish]
* Apply grep & seds on file order
* Precise `OPAMTMP` regexp, `hexa` instead of `'alphanum` to avoid confusion with `BASEDIR`
* Substitution in regexp pattern (for environment variables)
* Substitution for opam-cat content
* Untie opam root version test from current opam root/version
+ some tests update
=> updates on reftests

master_changes.md, src/state/opamUpdate.ml
Fixes https://github.com/ocaml/opam/issues/4411
I can't find any good reason someone would have a custom cache but want the repository one (even a custom local one) to be taken first.
The one annoying issue with this is that this changes behaviour based on the version of opam used by the user, however we can always announce it before the release (or rather before the change in opam-repository), so it should be ok.
=> Set the priority of user-set archive-mirrors higher than the repositories'

master_changes.md, src/client/opamArg.ml, src/client/opamArg.mli, src/client/opamCommands.ml
As we continue the puzzle for allowing CI workflows to work properly with CLI versioning, we hit another slight tweak. In opam-depext 1.2 we focused on ensuring that `opam depext` worked in a compatible way. However, there is a slightly subtle interaction with CLI versioning and built-in depext:
```
OPAMCLI=2.0 opam install conf-npm
```
requires, on Ubuntu, the `npm` package but the package may succeed if the user has installed npm manually (or via another mechanism than apt). opam's built-in depext is now a nuisance, as it forces interaction, cf. [this ocaml-cohttp workflow](https://github.com/dra27/ocaml-cohttp/runs/4190685413?check_suite_focus=true#step:7:211):
```
===== ∗ 163 =====
The following system packages will first need to be installed:
npm
<><> Handling external dependencies …
```
=> Use --no-depexts in CLI 2.0 mode

master_changes.md, src/client/opamPinCommand.ml, src/format/opamPackage.ml, src/format/opamPackage.mli, src/state/opamUpdate.ml
Makes it easier to mix pin packages and packages from the repository without having to set the version again when encountering an issue.
When you take the development version of something you expect more often to be ahead of the latest release rather than the opposite.
Issue encountered by @bikallem
=> Switch the default version when undefined from ~dev to dev

master_changes.md, src/client/opamClient.ml, src/client/opamSolution.ml, src/client/opamSwitchCommand.ml
Currently many of the users encountering issues with opam and asking about it on the forum encounter the following problem:
- They try to install a new package
- It fails because they forgot to call opam update
- They give up or have to ask about it
- If they ask about it, the answer is 99% always the same: you forgot to opam update
This PR makes it so that the reminder to call opam update appears more often, not just on opam upgrade.
=> Check whether the repository might need updating more often

master_changes.md, src/client/opamListCommand.ml
=> Make opam show --list-files <pkg> fail when <pkg> is not installed

master_changes.md, src/core/opamSystem.ml
Without this PR, as a Windows user without "Run as Administrator" permission:
```powershell
opam install `
--root C:\Users\beckf\AppData\Local\opam `
--switch C:\Users\beckf\AppData\Local\Programs\DiskuvOCaml\0\host-tools `
Z:\source\diskuv-communicator-kernel\vendor\diskuv-ocaml\opam-dkml.opam `
--yes --verbose --debug-level 2
```
```text
...
00:19.866  SYSTEM                          install C:\Users\beckf\AppData\Local\Programs\DiskuvOCaml\0\host-tools\_opam\.opam-switch\build\opam-dkml.~dev\_build\install\default\doc\opam-dkml\README.md -> C:\Users\beckf\AppData\Local\Programs\DiskuvOCaml\0\host-tools\_opam\doc\opam-dkml\README.md (644)
00:19.866  SYSTEM                          rm C:\Users\beckf\AppData\Local\Programs\DiskuvOCaml\0\host-tools\_opam\doc\opam-dkml\README.md
00:19.868 …
```
=> Fallback when OCaml says symlinks not supported

master_changes.md, src/client/opamAdminCommand.ml
and add a `--check-all` option for the previous behaviour
=> opam admin cache: only fill missing by default

master_changes.md, src/state/shellscripts/bwrap.sh, src/state/shellscripts/sandbox_exec.sh
bwrap for instance will exit with the confusing "bwrap: execvp <cmd>: No such file or directory"
Example of such confused user can be found here: https://github.com/ocaml/opam/issues/4112#issuecomment-996208463
=> Print user-friendly error messages when a command is not found, before calling the sandbox

master_changes.md, src/core/opamProcess.ml
A specific behavior is set for non windows devices to handle verbose printing of commands and their output. This makes windows workflow go into the fallback one, and have the double printing.
=> Windows: remove double printing on commands and their output

master_changes.md, src/client/opamAdminCommand.ml, src/core/opamHash.ml, src/core/opamHash.mli, src/repository/opamRepository.ml, src/state/opamPackageVar.ml
Add link for other checksum on downloading, if possible. `OpamSystem.link` fallback is to copy, so for some systems, it can lead to multiples copies of a single archive/file.
=> Link archives in cache when several checksum are given

.github/workflows/main.yml, master_changes.md, tests/reftests/opamroot-versions.test, tests/reftests/run.ml
on reftests engine:
* Allow one char package name on repo
* Remove opam output beginning with `###`
* Add `<pin:path>` header to specify incomplete opam files to pin, it is updated from a template in reftest run (no lint errors)
~On tests, adds orphans and imported opam-rt tests (reinstall, big-upgrade, dep-cycles).~
/cc @AltGr
=> Reftests: some updates

master_changes.md, src/state/opamRepositoryState.ml
Apropos this morning's dev meeting, it turns out that #4642 is as correct as @AltGr's assertion in https://github.com/ocaml/opam/issues/4930#issuecomment-979931192 😀
`OpamRepositoryState.Cache.save` clears all the other caches away, which
is correct _except_ when initialising the cache for the first time, which rather defeats the point. This PR ensures that when the cache is written for the first time, it doesn't erase other caches. All the other (external) paths to the repo cache go via the normal `save` method, and will correctly clear any other caches out of the way.
The behaviour can be seen with this repro for #4554 between opam 2.1.1 and opam-state 2.1.0:
```
FROM ocaml/opam
RUN sudo ln -f /usr/bin/opam-2.1 /usr/bin/opam && opam init --reinit -a
RUN cd …
```
=> Actually permit multiple state caches to co-exist

master_changes.md, src/state/opamSysInteract.ml
Mirrors https://github.com/ocaml-opam/opam-depext/commit/bfb81de27552ce854925a6e9b5d8fadd36785e7b for yum/dnf
=> Depexts: Stop zypper from upgrading packages on updates on OpenSUSE

.github/workflows/main.yml, Makefile, appveyor.yml, appveyor_test.sh, master_changes.md, release/Dockerfile.in, release/Makefile, src/core/dune, src/core/opamSystem.ml
=> OpamSystem.real_path: Remove the double chdir trick on OCaml >= 4.13.0

appveyor.yml, master_changes.md, shell/bootstrap-ocaml.sh
Two changes, related inasmuch as they improve the time Cygwin takes on AppVeyor:
- `make cold` build the compiler sequentially on Unix (Windows has always had `-j`). This is historical - the script dates from a time when `make -j` didn't reliably work. This slows down our CI when the cache is invalid or the bootstrap moves forward and it unnecessarily slows down the base image builder.
- Recent versions of Cygwin use WSL symlinks which appear not to work with AppVeyor's caching mechanism. Switch to native Windows symlinks which means the bootstrap compiler is cached again.
I'm very paranoid about changing the bootstrap script, so the AppVeyor fix should go to 2.1 and 2.0, but the parallel build change should not.
=> Tweak bootstrap & CI

master_changes.md, src/client/opamListCommand.ml
Fixes #4997 and partially https://github.com/ocaml/opam/issues/4172
Before:
```
opam show --raw dune.2.9.0  0.94s user 0.32s system 97% cpu 1.286 total
```
After:
```
./opam show --raw dune.2.9.0  0.37s user 0.05s system 97% cpu 0.433 total
```
=> Improve performance of opam show by 300% when the package to show is given explicitly or unique

doc/pages/Install.md, master_changes.md
`shell/install.sh` includes support for both FreeBSD and OpenBSD on the amd64 architecture, so I added entries for those. I also made the formatting  and architecture names consistent for all four operating systems.
=> Install page: clean up "pre-compiled binaries for"

master_changes.md, src/client/opamListCommand.ml
With master (https://github.com/ocaml/opam/commit/f39739b9325ea10d5c733b14c8b14f6dcf46abf2):
```
$ time opam list --available --installable -s --all-version dune.2.9.1
dune.2.9.1
opam list --available --installable -s --all-version dune.2.9.1  54.60s user 0.60s system 99% cpu 55.278 total
```
With this PR:
```
$ time opam list --available --installable -s --all-version dune.2.9.1
dune.2.9.1
./opam list --available --installable -s --all-version dune.2.9.1  2.91s user 0.37s system 98% cpu 3.317 total
```
Incidently, this also makes `OpamListCommand.filter` correct. Previously it would simply ignore its `~base` parameter if the request did not start with a `And` case
=> Improve performance of some opam list combination

Makefile, appveyor.yml, appveyor_test.sh
This fixes issues with the Cygwin run when the bootstrap ocaml compiler does not match the compiler being tested in appveyor.
It also brings faster CI runs.
Backports to 2.1 as mentioned in https://github.com/ocaml/opam/pull/4961#issuecomment-1007509058
=> [2.1 backport] Speed up and fix AppVeyor runs

master_changes.md, src/solver/opamCudf.ml, src/solver/opamCudf.mli, src/solver/opamSolver.ml, tests/reftests/opamrt-big-upgrade.test
For conflicts caused by cyclic actions, the opamCudf API would
previously only allow to observe the cycle with actions described as
strings for human pretty-printing.
We would like to write a script, using the opam API, that can react to
solution errors caused by cycles by patching the query and calling the
solver again. For this we need a machine-readable representation of
conflict cycles. ("We" here is myself and @Armael.)
The present commit makes the minimal change to the opamCudf API to
make this possible:
- The internal representation of cycles is changed to take CUDF
packages (the most general information) instead of strings.
- The `OpamCudf.cycle_conflicts` function has its type changed accordingly
(this changes the module interface and may break library consumers).
- A new …
=> opamCudf: provide machine-readable information on conflicts caused by cycles

master_changes.md, src/solver/opamSolverConfig.ml
Because this function is memoized, it becomes impossible to change the
best-effort setting after the function has been called. The ability to change it
is important for library users that want to make multiple solver calls with
different settings.
The performance implications of this should be minimal, because normally this
function is only called once, and if best_effort is disabled, the `check ()`
function will be short-circuited.
=> Remove memoization from `OpamSolverConfig.best_effort`

doc/pages/Install.md, master_changes.md
This PR reflects three lessons learned when writing the new ocaml.org "Up and Running" guide https://github.com/ocaml/ocaml.org/pull/1165 :
1) Having the binary distribution at the top of this page, when it is not the recommended installation mechanism for most users, is confusing.
2) Brew will shortly be updated https://github.com/Homebrew/homebrew-core/pull/64301 to make opam depend on gpatch, thus removing this instruction from the OS X instructions.
3) OSX is now spelled macOS
EDIT @rjbou: split the PR, reordering question that was blocking the PR is meant to go to another PR
=> ~Reorder options,~ fix brew instructions, spelling

master_changes.md, src/client/opamCommands.ml
=> Update opam repository man doc

master_changes.md, src/core/opamSystem.ml
=> lockf: catch `Unix.EACCES`

Makefile, master_changes.md, shell/bootstrap-ocaml.sh, src_ext/Makefile, src_ext/Makefile.sources
- Move the cold compiler to 4.13 in order to have a version which doesn't suffer from the `SIGSTKSZ` problem with glibc 2.34
- Bump the src_ext dependencies to latest versions while here
- In 4.13, the FlexDLL sources needed to be available _before_ `configure` is run, so move the extraction further up
- The Cygwin32 build is _really_ struggling to build a compiler and run the testsuite at once - the final commit tweaks the build processes so that instead of running `make world` followed by `make opt.opt` we do the fractionally faster `make world.opt` (if the secondary compiler were being built, it does `make world` followed by `make opt`).
=> Move cold compiler on master to 4.13.1

master_changes.md, src/client/opamClient.ml, tests/reftests/remove.test
Follows from #4969 and fixes #4727
Also a fix for #4890
=> Small fix for 'autoremove'

master_changes.md, src/core/opamStd.ml, src/core/opamStd.mli, src/solver/opamCudf.ml, src/solver/opamSolver.ml
We need to revert a huge simply-linked structure; the big cost was allocating 
the intermediate data, so instead of creating the graph or going through sets, 
we use the integer identifiers already defined by Cudf and store that in a 
simple table.
=> Big speedup on reverse dependency calculation

master_changes.md, src/solver/opamCudf.ml, tests/reftests/conflict-resto.test
=> Fix empty conflict explanations

doc/Makefile
dune 2.7 changed the default access to the `_build` to be read-only.
=> Fix make doc

dune-project, master_changes.md, opam-admin.opam, opam-client.opam, opam-core.opam, opam-devel.opam, opam-format.opam, opam-installer.opam, opam-repository.opam, opam-solver.opam, opam-state.opam, opam.opam, tests/cram/unix/dune, tests/cram/unix/list.t
In favour of a built-in 'reftest' feature implemented in #5031"
=> Revert the addition of the unix-only cram test (#5022)

master_changes.md, src/client/opamCliMain.ml, tests/reftests/list.unix.test
Restore the sigpipe handler before exiting, to prevent the finaliser
from crashing on flushes.
Closes #4216: the behaviour on that example is now to exit with code
141, and without an error message.
=> Fix behaviour when stdout gets closed

master_changes.md, src/core/opamParallel.ml
The use of `List.assoc` is incorrect: it relies on the polymorphic equality on an unknown type of vertices (a parameter of the functor), which thus might not be comparable with (=).
Spotted by @art-w , cc @gasche
=> OpamParallel, MakeGraph(_).to_json: fix incorrect use of List.assoc

master_changes.md, src/client/opamArg.ml, src/client/opamClientConfig.mli, src/client/opamRepositoryCommand.ml, src/repository/opamRepositoryConfig.ml, src/repository/opamRepositoryConfig.mli, src/state/opamUpdate.ml, tests/reftests/dot-install.test, tests/reftests/dune.inc, tests/reftests/init.test, tests/reftests/legacy-git.test, tests/reftests/legacy-local.test, tests/reftests/repository.test
~that need a new name, ftm it is hideously named `OPAMNOREPOTARRING`~
/cc @AltGr 
fix #4586 
edit:
By default disabled,  environment variable `OPAMREPOSITORYTARRING` permit to enable it.
=> Improve performance by disabling repo tarring

master_changes.md, src/solver/opamSolver.mli
This is a documentation-only PR: @Armael and myself were looking at `OpamSolver.dependencis`, and we did not know what the labelled argument were referring to. (We are still not fully sure that our documentation is correct.)
=> [documentation] document the options of OpamSolver.dependencies

master_changes.md, src/client/opamArg.mli, src/client/opamArgTools.ml, src/client/opamArgTools.mli, src/client/opamCommands.ml, src/client/opamSwitchCommand.ml, src/client/opamSwitchCommand.mli, src/format/opamFile.ml, src/format/opamFile.mli, tests/reftests/dune.inc, tests/reftests/opamroot-versions.test, tests/reftests/switch-set.test
This implements https://github.com/ocaml/opam/issues/4688 with the same behaviour as `git switch -`
cc @CraigFe
=> Add support for "opam switch -" (go to previous switch)

master_changes.md, src/solver/opamCudf.ml, src/solver/opamCudf.mli, src/solver/opamSolver.ml, src/solver/opamSolver.mli, src/state/opamSwitchState.ml, tests/reftests/list.test, tests/reftests/run.ml
Addresses some remaining costly cases in #4311
The patch includes a small reorganisation of `OpamSolver`, but the general
idea is to fix the performance regression compared to 2.0:
- with the introduction of solver invariants, the pre-processing that trimmed
packages conflicting with the base in `OpamState` was removed
- it was replaced by something much more general (and reliable) at the
`OpamCudf` level
- but only for calls to the external solver, until now
NOTE: this enforces the invariant even for `opam install
--coinstallable-with`, which is consistent with 2.0 but had changed in 2.1.
Without it we can't really expect reasonable performance in general anyway.
=> Add pre-processing to coinstallability checks

master_changes.md, src/state/opamSysInteract.ml
Gentoo, NetBSD, and OpenBSD name packages in a /-separated
hierarchy.  For example, libgmp is available as "dev-libs/gmp"
(on Gentoo[1]) or "devel/gmp" (on NetBSD[2] and OpenBSD[3]).
The first fix in this commit (the change to the `short_name` function)
removes the leading "/" from the package's short name.  Prior to this
commit, if `pkg` were "dev-libs/gmp", then `short_name` would be
"/gmp". That doesn't match the depext name of "gmp" so opam thought
the package wasn't installed.
OpenBSD also uses flavors and subpackages[4] in some of its package
names.  For example, OpenBSD has two subpackages for the "devel/gmp"
package: main and cxx. That means that the full name for libgmp on
OpenBSD is likely to be "devel/gmp,-main".  Prior to this commit,
`short_name` for this package was …
=> Better recognition of depexts on Gentoo, NetBSD, OpenBSD

master_changes.md, src/solver/opamSolver.ml
Built on top of https://github.com/ocaml/opam/pull/5024
It simply uses the new `installable_subset` to implement `installable`
cc @Armael
=> Factorise OpamSolver.installable

master_changes.md, tests/reftests/lint.test
~related # 4960~
/cc @kit-ty-kate 
~fix # 4989~
Only add test, other PR fix linting issues
=> Add lint test 

master_changes.md, src/client/opamAction.ml, src/client/opamAction.mli, src/client/opamSolution.ml, src/core/opamProcess.mli, src/format/opamTypes.mli, src/format/opamTypesBase.ml, src/format/opamTypesBase.mli, src/repository/opamRepository.ml, src/repository/opamRepository.mli, src/solver/opamActionGraph.ml, src/solver/opamActionGraph.mli, src/solver/opamCudf.ml, src/solver/opamCudf.mli, src/solver/opamSolver.ml, src/state/opamUpdate.ml, src/state/opamUpdate.mli, tests/reftests/dune.inc, tests/reftests/shared-fetch.test
Regroup same (shared) archive source packages for fetching. They are regrouped in a single action `'Fetch` node, that now takes several packages. Download functions are also updated to handle fetching an archive once and copy to sources directories.
=> Factorise fetching of shared archive source packages

master_changes.md, src/state/opamFileTools.ml, tests/reftests/lint.test
```diff
${BASEDIR}/lint.opam: Errors.
-           warning 47: Synopsis (or description first line) should start with a capital and not end with a dot
error 57: Synopsis and description must not be both empty
=> lint E57: fix trigger of empty description (lint W47)

master_changes.md, src/core/opamProcess.ml, tests/reftests/dune.inc, tests/reftests/parallel.test
No display was done for jobs that are in jobs pool, unless last one (last one is called with `OpamProcess.wait` that does the print)
```diff
<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
+sh "sleep.sh" "bar" (CWD=${BASEDIR}/OPAM/parallel/.opam-switch/build/bar.1)
- woke up bar
-> compiled  bar.1
```
=> Display parallelised commands in verbose mode

doc/pages/Manual.md, master_changes.md, tests/reftests/legacy-git.test, tests/reftests/upgrade-format.test
Affects only a test + a note in manual
=> Github deprecation of `git://` protocol updates

master_changes.md, src/format/opamFile.ml
see https://github.com/ocaml/opam/issues/4936#issuecomment-983828475
fix #4936
~TODO: add a test~
=> Preserved format errors handling

master_changes.md, src/core/opamStd.ml, src/core/opamStd.mli
Add `REMOVED` variant to permit its code removal from `*Config` setup
=> cli versionning and remove of an environment variable

master_changes.md, src/state/opamUpdate.ml, tests/reftests/repository.test
When an updated repository is loaded from a tarred version, it's not the most up-to-date version that is stored, but the non-updated tarred one.
/cc @Armael @kit-ty-kate 
related #5015
=> Fix repository loading

master_changes.md, src/client/opamPinCommand.ml, src/client/opamSolution.ml, src/core/opamConsole.ml, src/core/opamConsole.mli, src/core/opamCoreConfig.ml, src/core/opamCoreConfig.mli, src/core/opamStd.ml, src/core/opamStd.mli, src/format/opamTypesBase.ml, tests/reftests/assume-built.test, tests/reftests/clean.test, tests/reftests/conflict-resto.test, tests/reftests/inplace.test, tests/reftests/legacy-git.test, tests/reftests/legacy-local.test, tests/reftests/list.test, tests/reftests/lock.test, tests/reftests/opamroot-versions.test, tests/reftests/orphans.test, tests/reftests/source.test, tests/reftests/switch-set.test, tests/reftests/upgrade-format.test, tests/reftests/working-dir.test
Closes #5026
Additionally, also shows the hint on C-c :)
=> Reimplement the depext UI with a menu

master_changes.md, src/client/opamSolution.ml, tests/reftests/working-dir.test
They were not fetched as they were removed from set of packages that need to have its sources downloaded. Only locally pinned packages are removed with this PR.
fix #5060
=> Fix working-dir & fetching non pinned packages

master_changes.md, src/format/opamFile.ml, src/format/opamFile.mli, src/state/opamSwitchState.ml, tests/reftests/dune.inc, tests/reftests/reinstall.test
Fixes https://github.com/ocaml/opam/issues/4647
The tests are nowhere near complete but it’s a start and it shows that https://github.com/ocaml/opam/issues/4647#issuecomment-1098914526 discussed earlier is the only thing needed to get it working amazingly. Thanks a lot!
In this PR I’ve also fixed a bug where adding or removing the `plugin` flag does not reinstall a package, which shouldn’t be the case as currently plugin creating and delation are only done during the installation and removal actions respectively.
Regarding the code, I went the `?(modulo_state=false)` approach instead of duplicating the function because it made thing clearer regarding what is the difference between `effectively_part` and `effectively_part_modulo_state`
=> Rebuild packages only when what is going to be installed can change

master_changes.md, src/solver/opamCudf.ml
The following dockerfile (derived from https://github.com/ocaml/opam/issues/4373#issuecomment-992725743):
```
FROM ocaml/opam:debian-11-ocaml-4.12@sha256:40813dc1391636b4a428afbf0e678d2c81b80d9eade8a5214d8ee271fae155f3
RUN git clone https://github.com/kit-ty-kate/opam.git -b extract_explanations-debug
WORKDIR opam
RUN opam exec -- ./configure --with-vendored-deps
RUN opam exec -- make
RUN sudo ln -f _build/default/src/client/opamMain.exe /usr/bin/opam
RUN opam init --reinit -ni
RUN opam remote set-url default git+https://github.com/ocaml/opam-repository.git#a5d7cdc0c91452b0aef4fa71c331ee5237f6dddd
RUN opam pin add --debug --debug-level=3 --with-version 0.6.1 git+https://github.com/bikallem/resto.git#e725f56dd2d5ca0148272d754a0f29ffe76f94e8
```
now reports:
```
00:10.228  CLIENT …
```
=> Add some debug log to OpamCudf.extract_explanations to help debug #4373

master_changes.md, src/client/opamArg.mli, src/client/opamArgTools.ml, src/client/opamArgTools.mli, src/client/opamCommands.ml
Prints a warning when it is used, and it update the manpage with an `Experimental` annotation.
And a fix on default cli flags
=> Cli versioning: experimental flags handling

master_changes.md, src/core/opamHash.ml, src/core/opamHash.mli, src/state/opamSwitchState.ml
=> Add a warning if an external executable is not in `PATH`

master_changes.md, src/core/opamStd.ml, src/core/opamStd.mli, src/core/opamSystem.ml, src/core/opamSystem.mli
Splitting up https://github.com/ocaml/opam/pull/4813:
> For 92397ac ("Allow MSYS2 to prefer copying over symlinking") I think the code duplication can be reduced if is_cygwin_variant and is_msys2_variant are merged into a single function get_windows_executable_variant : string -> [ `Native | `Cygwin of [`Cygwin | `Msys2] | `Tainted of [`Cygwin | `Msys2] ]. The old is_cygwin_variant and the new is_msys2_variant can then be defined in terms of that function. While it's being added, it would be good to thread the tainting support through to OpamSystem.install (the point of `CygLinked is to warn for the situation where you've accidentally linked with a Cygwin or MSYS2 compiled DLL which usually implies bindings are wrong somewhere). I was initially confused by the title of the commit, as we …
=> Fallback to copying on symlink-less MSYS2

Makefile, master_changes.md
Comment from the original author:
```
This patch is useful only for Debian: It helps dh_auto_test to detect
that there is a testsuite and run it accordingly. dh_auto_test checks
'test' and 'check' targets, but not 'tests'.
```
Partly f.i.x.e.s https://github.com/ocaml/opam/issues/5058
=> Add a 'test' target

master_changes.md, src/client/opamAction.mli, src/client/opamCommands.ml, tests/reftests/source.test
**@rjbou Update**:
* Added a `--no-switch` option fix #4858
* Run on a non switch mode if there is the option or if switch list is empty
---
Here's a draft to fix #4809 as asked by @dra27.
It doesn't typecheck:
```shell-session
$ make
dune build --profile=release --root .  --promote-install-files -- opam-installer.install opam.install
File "src/client/opamCommands.ml", line 3358, characters 44-45:
3358 |           OpamAction.prepare_package_source t nv dir @@| function
^
Error: This expression has type
OpamStateTypes.unlocked OpamStateTypes.switch_state
but an expression was expected of type
OpamStateTypes.rw OpamStateTypes.switch_state
Type
OpamStateTypes.unlocked = [ `Lock_none | `Lock_read | `Lock_write ]
is not compatible with type OpamStateTypes.rw = [ `Lock_write ]
The second …
```
=> Allow opam source to run without a switch, add a `--no-switch' option

doc/pages/Manual.md, master_changes.md, src/client/opamSolution.ml, src/format/opamFile.ml, src/format/opamTypes.mli, src/format/opamTypesBase.ml, src/state/opamSwitchState.ml, tests/reftests/deprecated.test, tests/reftests/dune.inc
=> Add bultin support for the 'deprecated' flag

master_changes.md, src/client/opamAction.ml, src/core/opamDirTrack.ml, src/core/opamDirTrack.mli, tests/reftests/dot-install.test, tests/reftests/pat-sub.test
This PR fixes the main bug reported at <https://github.com/ocaml/opam/issues/5132> by preventing `.changes` files from being updated during dry-run.
This PR also introduces a new trace log to `ACTION` section to make easy to investigate the issue reported at <https://github.com/ocaml/opam/issues/4419>, which may be the same as the second problem reported at <https://github.com/ocaml/opam/issues/5132>.
ToDo:
=> Do not update .changes file during dry-run

master_changes.md, src/state/opamFileTools.ml
Reported in https://discuss.ocaml.org/t/opamlint-error-67-checksum-specified-with-a-non-archive-url/8998
The problem with lint-check 67 (Checksum specified with a non archive url) is that it is checked using `OpamSystem.is_archive`, which expects as parameter: a file on the disk. However currently, only the base name from the url is given (which does not exist on the disk).
This is why the `zip` check fails: the file is not present on the filesystem and thus cannot be checked and returns `false`.
It only works for `tar.*` files because `OpamSystem.Tar.is_archive` also checks the extension if the file does not exists on the system.
Should render https://github.com/ocaml/opam/pull/4834 obsolete
=> opam lint: Fix E67, check checksum only if vcs backend

master_changes.md, tests/reftests/opamroot-versions.test
I had to use `[)]` to escape rather than `\\)`, because backslashes interfere 
with the windows-path rewrite rules...
=> Fix opamroot-versions.test glitch

doc/pages/Manual.md, master_changes.md, src/client/opamAction.ml, src/client/opamAction.mli, src/client/opamArg.ml, src/client/opamClient.ml, src/client/opamClientConfig.mli, src/client/opamCommands.ml, src/client/opamListCommand.ml, src/client/opamListCommand.mli, src/client/opamLockCommand.ml, src/client/opamSolution.ml, src/format/opamFilter.ml, src/format/opamFilter.mli, src/state/opamFileTools.ml, src/state/opamPackageVar.ml, src/state/opamPackageVar.mli, src/state/opamPinned.ml, src/state/opamStateConfig.ml, src/state/opamStateConfig.mli, src/state/opamSwitchState.ml, src/state/opamSwitchState.mli
~At the moment it's not finished, it needs a proper look at the modification (it's just seddish adds)~
fix #4959
**@rjbou edit:**
All clear! Renamed to `with-tools` : available in cli `opam install pkg --with-tools` and in opam files as a variable `depends: "foo" {with-tools}`. Have the same behaviour than `with-test` and `with-doc`.
=> Add development tools recommendation in opam file (variable) and cli

master_changes.md, src/repository/opamRepository.ml, src/repository/opamRepository.mli, src/state/opamUpdate.ml, tests/reftests/repository.test
Currently, `opam update` will reload the state of a repository (reading .opam files, etc) even when the repository has not changed (as detected by the backend).
This PR is an attempt at optimizing this case: if the backend says that a repository has not changed, avoid reloading its contents, allowing for quicker `opam update`s.
(a review is particularly welcome as I am not familiar with this part of opam's code; I might have missed some subtleties wrt synchronization of the on-disk view of the repo and the "repo" in-memory data structure...)
=> opam update: Avoid reloading repository contents when the repo has not changed

master_changes.md, src/format/opamFile.ml, tests/reftests/var-option.test
It is more consistent with other field, besides it fixes depext bypass hints that use the non bracket syntax (single elem).
=> opam config & switch-config: allow depext-bypass with no bracket if single package (depth 1)

master_changes.md, src/client/opamConfigCommand.ml
When it is not lazy, it causes other lazy values to be forced, notably
`OpamStd.Env.list`. This is unexpected, and a bit of a problem for people using
Opam as a library because they may want to set additional environment variables
before callin Opam.
Additionally, I'd expect this to be faster.
=> Make OpamConfigCommand.global_allowed_fields fully lazy

master_changes.md, src/client/opamConfigCommand.ml, src/core/opamSystem.ml, src/core/opamSystem.mli
When using a native Windows opam.exe the PATH from `opam env` is in Windows format.
PowerShell output from `opam env`: `$env:PATH = 'Z:\source\opam\_opam\bin;...'`
CMD.exe output from `opam env`: `SET PATH=Z:\source\opam\_opam\bin;...`
With this change both MSYS2 and Cygwin will Unix-ize the PATH with essentially `cygpath --path $PATH`.
Cygwin output from `opam env`: `PATH='/cygdrive/c/Users/beckf/AppData/Local/opam/diskuv-boot-DO-NOT-DELETE/bin:...'`
MSYS2 output from `opam env`: `PATH='/z/source/opam/_opam/bin:...'`
`cygpath --path` on an already Unix PATH is idempotent, so a Cygwin opam.exe will still work after this change. That is, the following says "MATCHES" on both Cygwin and MSYS2:
```sh
if [[ "$(cygpath --path '$PATH')" = $(cygpath --path "$(cygpath --path '$PATH')") ]]; then …
```
=> Cygpath the PATH from opam env

.github/workflows/ci.ml, .github/workflows/main.yml, master_changes.md, src/core/opamCompat.ml, src/core/opamCompat.mli, src/state/opamSwitchState.ml, tests/reftests/dune.inc, tests/reftests/upgrade-two-point-o.test
This is an alternate approach from #5002 for fixing #4501.
When upgrading a switch from opam 2.0, opam needs to convert a list of base packages to a switch invariant. The process used for that applies three heuristics for package `foo.version`:
- If there's only one version of `foo` available, then the invariant `"foo"` is used (i.e. with no version)
- If there's more than one version, but `version` is the latest, then the invariant `"foo" {>= "version"}` is used (lower-bound with upgrades)
- Otherwise the precise `"foo" {= "version"}` is used (exactly equivalent)
All this is attempting to reconstruct whether the user originally ran `opam switch create my-switch foo` or `opam switch create my-switch foo.version`. There are two intentions:
1. Automatic _upgrade_ to the latest version of a …
=> _Correct_ trying to be too clever when upgrading switches from opam 2.0

master_changes.md, src/core/opamCompat.ml, src/core/opamCompat.mli, src/state/opamSwitchState.ml, tests/reftests/dune.inc, tests/reftests/upgrade-two-point-o.test
=> Backport PR for 2.1.3

master_changes.md, src/client/opamArg.ml, src/client/opamCommands.ml, src/client/opamConfigCommand.ml, src/client/opamConfigCommand.mli, src/core/opamCompat.ml, src/core/opamCompat.mli, src/core/opamStd.ml, src/core/opamStd.mli, src/core/opamStubs.dummy.ml, src/core/opamStubs.mli, src/format/opamTypes.mli, src/format/opamTypesBase.ml, src/state/opamEnv.ml, src/stubs/win32/opamWin32Stubs.ml, src/stubs/win32/opamWindows.c
Splitting up https://github.com/ocaml/opam/pull/4813:
> For 0f0bd98 ("Show eval expression for PowerShell on native Windows"), opam 2.2 should finally see the activation of parent_putenv (and the opam-putenv auxiliary)... on Windows, there's no need to output shell instructions - on Windows, opam env can actually update the environment variables of the shell (see dra27@2934dc4#diff-e21e37a0339dbaafa95fd0b6d57221f656f18d0771c06f6f837bb98c3a71b91aR193). However, that doesn't necessarily preclude merging this first!
For continuity this initial PR is as-is from the original PR.
=> Environments for PowerShell and Windows command line

configure, configure.ac, master_changes.md, src/stubs/win32/build-putenv.ml, src/stubs/win32/dune-win32, src/stubs/win32/opam-putenv.c, src/stubs/win32/opamInject.c, src/stubs/win32/opamWindows.c
Slightly easier seen commit-by-commit. This PR:
- Removes some cruft from an earlier build system where the stubs were always built (including on Linux) if `#ifdef _WIN32`
- Removes a small amount of code related to support OCaml < 4.06
- Uses a somewhat less naïve application of OCaml's GC laws, which results in both shorter and technically more efficient code w.r.t. the GC
- Adds missing uses of `caml_string_is_c_safe` (this is a guard which stops OCaml strings containing `\0` from being passed to C functions which expect null-terminated strings) and releasing the runtime lock on a couple of longer-lived functions
Finally, the main focus is to switch the PR to use Unicode properly, in particular for the environment stubs implementation.
=> Overhaul the Windows C stubs and update them for Unicode

master_changes.md, src/client/opamArg.ml, src/client/opamCommands.ml, src/core/opamStd.ml, src/core/opamStd.mli, src/format/opamTypes.mli, src/format/opamTypesBase.ml, src/state/opamEnv.ml
Record whether the shell was detected as powershell or pwsh, although this information isn't actually used at the moment. Decreases the chance of accidentally only matching on one constructor.
@jonahbeckford - I'm not sufficiently familiar with PowerShell: are there situations where we might need to care whether it's pwsh (PowerShell 6.0) or classic PowerShell Desktop/Core (5.x and earlier)? I'm wondering whether we could risk dropping the `--shell=powershell` option completely?
=> Eliminate the separate constructors for powershell

master_changes.md, src/client/opamCommands.ml, src/state/opamEnv.ml, src/state/opamEnv.mli, tests/reftests/env.test
Fixes #5204 .
It was not just a Windows problem, although only macOS of the *nix variants commonly uses spaces in their directory names.
=> 'opam env' for directories with spaces

master_changes.md, src/client/opamSolution.ml, src/core/opamConsole.ml, src/core/opamConsole.mli
In depext menu for manual install : 
```
Would you like opam to:
> 1. Check again, as the package is now installed
2. Attempt installation anyway, and permanently register that this external dependency is present, but not detectable
3. Abort the installation
```
Default is to check again is the package has been installed. So when launched in script (or test), it loops forever.
Added in `OpamConsole.menu` an [noninteractive] optional argument, that is the default if output is not a tty.
=> depext menu: don't loop eternally in scripts when automatical install is off

master_changes.md, src/client/opamSwitchCommand.ml, tests/reftests/dune.inc, tests/reftests/switch-import.test
The check for reinstall of pinned packages is done at switch loading. Switch import change overlays afterwards, so a second check need to be done to mark changed one to reinstall before launching resolution.
=> switch import: fix installed packages reinstall when import file changed

master_changes.md, src/state/opamEnv.ml
To be rebased on top of #5053 which adds menu support
=> Use the new menus for the initial setup too

master_changes.md, src/format/opamFormula.ml
The regular expression is compiled lazily - on each call to the function!
=> Fix lazy regexp compilation in `OpamFormula.atom_of_string`

.github/scripts/depexts/generate-actions.sh, master_changes.md
archlinux does not upgrade dependencies by default without the 'u' argument and leads to issues where some packages can get installed with several versions of glibc
=> GHA: Fix the archlinux script

master_changes.md, src/client/opamAction.ml, src/client/opamAuxCommands.ml, src/client/opamCommands.ml, src/client/opamSolution.ml, src/state/opamStateTypes.mli, src/state/opamSwitchState.ml, src/state/opamSysInteract.ml, src/state/opamSysInteract.mli, src/state/opamSysPoll.ml, src/state/opamSysPoll.mli, tests/reftests/config.test, tests/reftests/dune.inc
=> Resolve variables before polling system

master_changes.md, src/core/opamStd.ml, src/core/opamStd.mli, src/state/opamEnv.ml
Three little bugs, all to do with changing the shell using the new `opam init` menu:
- On bash, the option crashes opam with `Not_found` because the list of shells used is the ones for init scripts, not the complete of shells - I've introduced a list containing the full list of shells for this purpose.
- When selecting a new shell, the default was forced to "Yes". That's a slight issue when the Windows shell comes because "Yes" isn't always an option but it also doesn't really make sense - the default should stay the same
- Having selected a new shell, `opam init` then wrote the `.profile` (or whatever) using the syntax of the old shell!
=> Fixes to opam init menu

master_changes.md, shell/bootstrap-ocaml.sh
cc @hannesm suggested in https://github.com/ocaml/opam/issues/4894
=> shell/bootstrap-ocaml.sh: do not fail if curl/wget is missing

master_changes.md, src/repository/opamDarcs.ml, src/repository/opamGit.ml, src/repository/opamHg.ml, src/repository/opamVCS.ml, src/repository/opamVCS.mli, tests/reftests/working-dir.test
Splitted on several PRs #5081 #5082  #5083
Keep in this PR the inital purpose : working dir checkout corner case: when reinstalling a package that has a dirty source, if uncommitted changes are the same than remotely committed, opam consider that it is up to date and nothing is updated.
> Add a ~sandbox and~ working dir test plus a fix on working dir checkout corner case: when reinstalling a package that has a dirty source, if uncommitted changes are the same than remotely committed, opam consider that it is up to date and nothing is updated.
>~And some update on reftests: replace opam bin path and add a `grep -v` command~
>
>edit: integrate also a 
>* fix for working-dir & non pinned package, that should be a no-op (fix # 5060)
>* notification when packages are skipped with assume built …
=> Fix working dir checkout

master_changes.md, src/client/opamClient.ml, src/state/opamSwitchState.ml, tests/reftests/dune.inc, tests/reftests/pin.unix.test
fix #5046 See example there or in test file
=> Fix auto pinning and depext handling

master_changes.md, src/client/opamSolution.ml, tests/reftests/dune.inc, tests/reftests/with-tools.test
=> Add `--with-tools` test, resolve for post messages

master_changes.md, src/client/opamAdminCommand.ml
`opam admin list --environment` have a wrong description which lead to a non-sense environment
```diff
-   "VAR=VALUE[;VAR=VALUE]"
+   "VAR=VALUE[,VAR=VALUE]"
```
/cc @balsoft
=> `opam admin list --environement` values

dune, master_changes.md, release/Dockerfile.in, release/Makefile, release/readme.md, release/release.sh, release/sign.sh
One button press to release. So far the QEMU setup is by far the slowest bit (~3/4 hours) but at least it does not require any supervision or setup.
PR on top of #4946
=> Make the release script setup-less using QEMU, Docker and Rosetta 2

.github/scripts/main/opam-rt.sh, .github/scripts/main/preamble.sh, master_changes.md, tests/reftests/assume-built.test, tests/reftests/inplace.test, tests/reftests/json.unix.test, tests/reftests/lock.test, tests/reftests/pin.unix.test, tests/reftests/rec-pin.test, tests/reftests/source.test, tests/reftests/working-dir.test
Fixes everything except for this one, which i have no idea how to fix:
```
diff --git a/_build/default/tests/reftests/working-dir.test b/_build/default/tests/reftests/working-dir.out
index ae774ff60..0e82e5dd7 100644
--- a/_build/default/tests/reftests/working-dir.test
+++ b/_build/default/tests/reftests/working-dir.out
@@ -218,14 +218,14 @@ The following actions will be performed:
<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
Processing  1/5: [qux.4: rsync]
Processing  2/5: [qux.4: rsync] [ongoing: test newfile.txt]
+Processing  2/5: [qux.4: rsync] [ongoing: cat newfile.txt]
+Processing  2/5: [qux.4: rsync]
+Processing  3/5: [qux.4: rsync]
-> retrieved qux.4  (file://${BASEDIR}/qux)
-Processing  2/5: [ongoing: test newfile.txt]
test "-f" "newfile.txt" …
```
=> Fix the tests to be compatible with archlinux/arm64

master_changes.md, tests/reftests/dune.inc, tests/reftests/empty-conflicts-001.test, tests/reftests/empty-conflicts-002.test, tests/reftests/empty-conflicts-003.test, tests/reftests/empty-conflicts-004.test, tests/reftests/empty-conflicts-005.test, tests/reftests/empty-conflicts-006.test
Add all the empty conflict messages shown in https://github.com/ocaml/opam/issues/4373 or https://github.com/ocaml/opam/discussions/5130 except for https://github.com/ocaml/opam/issues/4373#issuecomment-921034945 which seems a bit too complicated to add.
=> Add a series of reftests showing empty conflict messages

master_changes.md, src/client/opamCliMain.ml
There are better ways to fix this, but it got in the way and I don't want to forget about it completely!
=> Fix backtrace for uncaught exceptions on Windows

master_changes.md, src/state/opamSysInteract.ml
Suggestion by @MSoegtropIMC in https://github.com/ocaml/opam/issues/5239
=> Improve the error message when neither MacPorts or Homebrew could be detected on macOS

master_changes.md, src/client/opamClient.ml, tests/reftests/best-effort.test, tests/reftests/dune.inc
In PR #4796 I fixed a problem with `--best-effort`. Subsequently #4975 seems to
have broken this again. Not sure if this is the correct fix. There may also be
additional places where this is going wrong...
=> Fix --best-effort regression introduced in #4975

.github/workflows/ci.ml, .github/workflows/main.yml, master_changes.md, src/core/opamStd.ml, src/state/opamEnv.ml, src/state/opamStateConfig.ml, src/state/opamStateConfig.mli
If `.opam` is found in either `%HOME%` or `%USERPROFILE%` then use that, but roots are otherwise created in `%LOCALAPPDATA%\opam`.
This strategy is forwards-compatible with any switch to XDG (which would definitely introduce the situation where _existing_ roots would be read from locations other than where a _new_ root would be init'd). The location for Windows was discussed in #3766.
=> Create opam root in `%LOCALAPPDATA%\opam` on Windows

master_changes.md, src/client/opamAction.ml, src/client/opamAuxCommands.ml, src/client/opamPinCommand.ml, src/core/opamFilename.ml, src/core/opamFilename.mli, src/core/opamUrl.ml, src/core/opamUrl.mli, src/repository/opamRepository.ml, src/state/opamUpdate.ml, tests/reftests/rec-pin.test
Some examples:
```diff
-root-a_p is now pinned to file://${BASEDIR}/pinnes (a) (version dev)
+root-a_p is now subpath-pinned to directory /a in file://${BASEDIR}/pinnes (version dev)
-root-a-i_g is now pinned to git+file://${BASEDIR}/pinnes#master (a/i) (version dev)
+root-a_p is now subpath-pinned to directory /a in file://${BASEDIR}/pinnes (version dev)
-root-a_p.dev    rsync  file://${BASEDIR}/pinnes (a)
-root-b_g.dev    git    git+file://${BASEDIR}/pinnes#master (b)
+root-a_p.dev    rsync  directory /a in file://${BASEDIR}/pinnes
+root-b_g.dev    git    directory /b in git+file://${BASEDIR}/pinnes#master
--> retrieved root-a-i_g.dev  (git+file://${BASEDIR}/pinnes#master(a/i))
+-> retrieved root-a-i_g.dev  (directory /a/i in git+file://${BASEDIR}/pinnes#master)
-[root-a-i_g.l1] …
```
=> Update subpath display

master_changes.md, src/format/opamFile.ml, tests/reftests/dune.inc, tests/reftests/rebuild.test
Detected in https://github.com/ocaml/opam-repository/pull/22016
=> Do not rebuild packages when an extra-source's url changes but not its checksum

configure, configure.ac, master_changes.md, src_ext/Makefile
The message when vendored mode is automatically turned on has an extra line:
```
============================================================================
Some dependencies are missing. Vendored mode has been automatically enabled.
The sources for opam's dependencies will be extracted in src_ext and built.
============================================================================
```
and the extraction message notes that it's extracting sources to `src_ext/`:
```
Downloading vendored source dependencies... done
Extracting vendored source dependencies in src_ext/... done
```
=> Explain vendored mode more clearly in configure

.github/scripts/cygwin.cmd, master_changes.md
Extracted from https://github.com/ocaml/opam/pull/5171
Fixes the following failure in the Windows CI (the non-cygwin runs):
```
[...]
+ git clean -dfX
Removing 0.40.tar.gz
Removing Makefile.config
Removing _build/
+ [[ -n master ]]
Removing config.log
+ git checkout combak
Removing config.status
Removing ocaml-4.13.1.tar.gz
Removing opam-installer.exe
Removing opam-installer.install
Removing opam.exe
Removing opam.install
Removing processed-opam-installer.install
Removing processed-opam.install
Removing src/ocaml-flags-configure.sexp
Removing src/stubs/c-flags.sexp
Removing src/stubs/libacl/c-libraries.sexp
Removing src/stubs/win32/cc64
Removing src/stubs/win32/dune
Removing src_ext/0install-solver.download
Removing src_ext/0install-solver.pkgdownload
Removing …
```
=> CI: Fix Cygwin Cache

master_changes.md, tests/reftests/assume-built.test, tests/reftests/inplace.test, tests/reftests/parallel.test, tests/reftests/repository.test, tests/reftests/run.ml, tests/reftests/working-dir.test
Command are resolved in opam, which leads to some full path printing. Add `sed-cmd` command to help this rewrite.
```diff
-### opam install ongoing -v | '.*(/|\\|")test(\.exe)?"? "' -> 'test "' 
+### opam install ongoing -v | sed-cmd test
```
=> Reftest: add path replacement command command

Makefile, master_changes.md
We might also want to remove this file entirely and replace it by an environment variable to make our life easier
=> Remove src/client/no-git-version when calling make clean

master_changes.md, src/core/opamProcess.ml
When calling Cygwin binaries, the process invocation manipulates `PATH` to ensure that Cygwin's `bin` directory appears before the Windows `system32` directory to ensure that Cygwin binaries don't unexpectedly start using Window's BSD executables (a normal Cygwin shell avoids this by forcibly putting `/usr/bin` at the beginning of `PATH`).
Unfortunately, I made a slight mistake with the first entry - it's an environment block string, so the first entry is `PATH=<dir>` and the `PATH=` part wasn't split off.
This PR corrects that; therapy will deal with the fact that I discovered this quite old bug the night before a demo...
=> Fix mangling of `PATH` during cygvoke

master_changes.md, src/client/opamSolution.ml, tests/reftests/depexts.test, tests/reftests/dune.inc, tests/reftests/run.ml
```
[1/2/3/4] 1
+ /usr/bin/sudo "apt-get" "install" "-qq" "-yy" "autoconf" "gnuplot-x11"
[ERROR] System package install failed with exit code 100 at command:
sudo apt-get install -qq -yy autoconf gnuplot-x11
- E: Unable to correct problems, you have held broken packages.
[ERROR] These packages are still missing: autoconf gnuplot-x11
opam believes some required external dependencies are missing. opam can:
> 1. Run apt-get to install them (may need root/sudo access)
2. Display the recommended apt-get command and wait while you run it manually 
(e.g. in another terminal)
3. Attempt installation anyway, and permanently register that this external de
pendency is present, but not detectable
4. Abort the installation
[1/2/3/4] 1
+ /usr/bin/sudo "apt-get" "install" "-qq" "-yy" "autoconf" …
```
=> Do not infinitly check for depexts when the system package manager fails

master_changes.md, src/client/opamCliMain.ml
Fixes https://github.com/ocaml/opam/issues/5296
Before this patch, typing `opam upgrde` would take: 1.6s
After this patch, it only takes: 0.2s
=> Make the plugin lookup faster when mistyping a subcommand

master_changes.md, src/client/opamArg.ml, src/client/opamArg.mli, src/client/opamCommands.ml
And use the in `OpamCommands` instead of redefining them
=> Args: externalise some package selections flags

master_changes.md, src/state/opamUpdate.ml, tests/reftests/assume-built.test, tests/reftests/inplace.test, tests/reftests/lock.test, tests/reftests/update-upgrade.test, tests/reftests/working-dir.test
When no working dir given, or no arguments specified 
fix #5294
=> More clear message for pinned package update that have local changes

configure, configure.ac, master_changes.md, shell/check_linker, src_ext/Makefile.packages, src_ext/update-sources.sh
> The egrep and fgrep commands, which have been deprecated since release 2.5.3 (2007), now warn that they are obsolescent and should be replaced by grep -E and grep -F.
https://lists.gnu.org/archive/html/info-gnu/2022-09/msg00001.html
=> Replace fgrep with grep -F

master_changes.md, src/client/opamSolution.ml, src/core/opamConsole.ml, src/core/opamConsole.mli, src/state/opamEnv.ml, tests/reftests/depexts.test, tests/reftests/pin.test
The rationale is now to assume the "no" case in the menus whenever there is no input to read from.
=> Fix behaviour of menu and depexts in non-interactive environments

master_changes.md, src/client/opamCommands.ml
fix #5307 : mention shell hooks prior to eval opam env
=> doc: update switch manpage

master_changes.md, src/client/opamClient.ml, tests/reftests/init.test
Previously, the dl_cache from the InitConfig was never used.
=> opamClient: pass dl_cache from initConfig to config

master_changes.md, src/solver/opamCudf.ml, tests/reftests/conflict-badversion.test, tests/reftests/conflict-core.test, tests/reftests/empty-conflicts-001.test, tests/reftests/empty-conflicts-002.test, tests/reftests/empty-conflicts-003.test, tests/reftests/empty-conflicts-004.test, tests/reftests/empty-conflicts-005.test, tests/reftests/empty-conflicts-006.test, tests/reftests/install-formula.test, tests/reftests/install-pgocaml.test, tests/reftests/unhelpful-conflicts-001.test
This PR simplifies the construction of `ct_chains`. This has several effects:
* This fixes all the empty conflict messages described in #4373 
* This removes the hack added in https://github.com/ocaml/opam/pull/4982
* This makes the conflict messages more verbose. This is not the greatest outcome but this is already what #4373 is about so it will be fixed later (but empty conflict messages are the most important to fix first)
=> Fix all empty conflict messages

master_changes.md, src/state/opamFormatUpgrade.ml, tests/reftests/opamroot-versions.test, tests/reftests/upgrade-two-point-o.test
See https://github.com/ocurrent/ocaml-dockerfile/pull/92
=> Reset the "jobs" config variable when upgrading from opam 2.0

master_changes.md, src/client/opamCommands.ml, src/state/opamPinned.ml, src/state/opamPinned.mli, tests/reftests/pin.test
Reasoning:
`opam pin list` returns something of the form:
```
<pkg>.<version>    <kind>  <target>
```
However users often simply expect that selecting the first column (`<pkg>.<version>`), done very simply by double-clicking on the name on the terminal, to unpin the package would work. However doing this will end up in a rather surprising failure:
```
[ERROR] No package pinned to this target found, or invalid package name/url: <pkg>.<version>
```
This PR removes this surprising restriction
=> Allow opam pin remove to take a package as argument

master_changes.md, src/solver/opamCudf.ml, tests/reftests/init.test, tests/reftests/list.test
On cudf strong and weak dependencies computation, some weak dependencies were wrongly kept, originated from #4627
fix test added in #5329
=> Fix cudf weak dependencies computation

README.md, doc/pages/FAQ.md, master_changes.md
Fix documentation to mention IRC channels in liberachat instead of freenode.
=> Update IRC links

master_changes.md, src/format/opamFormula.ml, tests/reftests/admin-add-constraint.test, tests/reftests/dune.inc
Fixes https://github.com/ocaml/opam/issues/5334
*one more for the books https://github.com/ocaml/ocaml/pull/9928* :disappointed:
=> Fix opam admin add-constraint failing with Not_found in some situations

master_changes.md, src/client/opamClient.ml, tests/reftests/reinstall.test
Fixes https://github.com/ocaml/opam/issues/5224 as well as discrepancies in the result given by the solver between `opam install <pkg>` and `opam reinstall <pkg>` when `<pkg>` is not installed (see the differences in the solver output in the description of https://github.com/ocaml/opam/issues/5227)
---------
~TODO:~
=> Use the default criteria during reinstall/upgrade when requesting at least one non-installed package

master_changes.md, src/client/opamClient.ml, tests/reftests/reinstall.test
Fixes https://github.com/ocaml/opam/issues/5227
---------
~TODO:~
=> Show the reason for installing packages when using opam reinstall

master_changes.md, src/client/opamClient.ml, src/client/opamCommands.ml, src/client/opamListCommand.ml, src/client/opamLockCommand.ml, src/core/opamStd.ml, src/core/opamStd.mli, src/solver/opamCudf.ml, src/solver/opamCudf.mli, src/solver/opamSolver.ml, src/solver/opamSolver.mli, src/state/opamSwitchState.ml, src/state/opamSwitchState.mli
`OpamSolver.dependencies` and `OpamSolver.reverse_dependencies` are for the moment only used in `opam-client`. The main reason to move them is that #5208 use one of them in `opam-state` (`opamSwitchState`), making it depend on `opam-solver` and all of its dependencies. 
Besides, with the rewrite, `dependencies` is more efficient: for a big request (`opam list --required-by patdiff,memtrace_viewer,tezos,bap,mirage --recursive`, resulting to ~800 unique packages), from 1.95s to 0.67s.
Remaining:
=> Move dependencies computation from `opam-solver` to `opam-state`

master_changes.md, src/client/opamCommands.ml, src/core/opamStd.ml, src/core/opamStd.mli, tests/reftests/pin.test
I often find the need to clean all pins from the current switch i am working on, be it because the pin packages have all been released or other reasons, and listing all the packages or repos one by one can be extremely tedious.
=> Add opam pin remove --all

.github/scripts/cygwin.cmd, .github/scripts/main/create-ocaml-cache.sh, .github/scripts/main/ocaml-cache.sh, .github/workflows/ci.ml, .github/workflows/depexts.yml, .github/workflows/lib.ml, .github/workflows/main.yml, master_changes.md
=> GHA: port to new infra, upgrade actions version

master_changes.md, src/solver/opamCudf.ml, tests/reftests/conflict-badversion.test, tests/reftests/conflict-core.test, tests/reftests/dune.inc, tests/reftests/empty-conflicts-001.test, tests/reftests/empty-conflicts-002.test, tests/reftests/empty-conflicts-003.test, tests/reftests/empty-conflicts-004.test, tests/reftests/empty-conflicts-005.test, tests/reftests/empty-conflicts-006.test, tests/reftests/install-pgocaml.test
Backports https://github.com/ocaml/opam/pull/5253 and https://github.com/ocaml/opam/pull/5263 to the `2.1` branch.
=> [2.1] Fix all empty conflict explanation messages

master_changes.md, src/stubs/libacl/opamACL.c
When compiling opam (most recent git) with GCC 11.3.0 on Cygwin64, I get the following error when developer mode is enabled (and NOT during normal compilation since `-Werror` is only activated in developer mode):
```
File "src/stubs/libacl/dune", line 12, characters 19-26:
12 |     (names         opamACL)
^^^^^^^
opamACL.c: In function ‘OPAM_get_acl_executable_info’:
opamACL.c:44:12: error: unused variable ‘siz’ [-Werror=unused-variable]
44 |     size_t siz;
|            ^~~
cc1: all warnings being treated as errors
make: *** [Makefile:144: build-opam] Error 1
```
It doesn’t seem like the `siz` variable is used at all in this file, so I’ve removed it.
Additionally, I wasn't sure which category this would fall under in the changes file - I've currently put it under "Build" since the above …
=> Remove unused variable `siz`

master_changes.md, src/repository/opamGit.ml, src/repository/opamHg.ml
Before, the revision was at most the first 8 bytes in the revision. This can be problematic for reproducibility since the revision may then be ambiguous. I don't know much about mercurial and how their revisions look like.
CC @hannesm
=> git, hg: Use full revision

master_changes.md, src/client/opamTreeCommand.ml, src/core/opamConsole.ml, src/core/opamConsole.mli, tests/reftests/json.unix.test
Closes #5298.
This PR adds support for `--json` option in `opam tree` command.
Here is an example output: https://gist.github.com/cannorin/ae87f55695c38356a9b880e0418a7a12
Currently, the output JSON has the type `Forest` in the following TS definition:
```typescript
interface Package {
name: string;
version: string;
}
interface DepsTree extends Package {
dependencies: DepsNode[];
}
interface DepsNode extends DepsTree {
satisfies: string | null;
is_dup: boolean;
}
interface RevdepsTree extends Package {
requirements: RevdepsNode[];
}
interface RevdepsNode extends RevdepsTree {
demands: string | null;
is_dup: boolean;
}
type Forest = DepsTree[] | RevdepsTree[]
```
We discuss the structure of the output JSON in #5298.
TODO:
=> Support --json option in opam tree

.gitignore, master_changes.md, src/state/opamSysInteract.ml
MSYS2 on Windows uses the same package manager as Arch Linux (`pacman`). It targets several ABIs (compilers, bitiness and Windows C libraries).
This PR builds on the opam global variables that are registered when Diskuv OCaml (DKML) is installed. Those variables became available with DKML 1.1: https://gitlab.com/diskuv/diskuv-ocaml/-/blob/bd5b461b7d267ff897d053a67cce6ed5c26f27b4/CHANGES.md. Any MSYS2 distribution (not just DKML) can set those opam variables:
```console
$ opam var --global
arch                 x86_64                                                         # Inferred from system
exe                  .exe                                                           # Suffix needed for executable filenames (Windows)
...
mingw-chost          x86_64-w64-mingw32 …
```
=> depexts for MSYS2

CODE_OF_CONDUCT.md, master_changes.md
The OCaml Code of Conduct can be found in [ocaml/code-of-conduct](https://github.com/ocaml/code-of-conduct) and has been discussed [in this Discourse thread](https://discuss.ocaml.org/t/ocaml-community-code-of-conduct/10494).
It's been adopted in ocaml/ocaml#11761 and ocaml/dune#6875, and we propose adopting it for ocaml/opam as well.
=> Adopt the OCaml Code of Conduct

master_changes.md, src/core/opamStd.ml
The original code looked like it had a bad merge at some point in its history (duplicates the `if` condition):
```ocaml
if (OpamString.ends_with ~suffix:"cygwin1.dll" tx ||
OpamString.ends_with ~suffix:"msys-2.0.dll" tx) then
(* ... *)
else if OpamString.ends_with ~suffix:"msys-2.0.dll" tx then
```
Without this PR, MSYS2 uses `cp -PRr` instead of the intended `rsync`; `rsync` is a reasonable fallback for the lack of symlinks in MSYS2, and it copies binaries correctly (ex. if both `dune` and `dune.exe` are in the same directory, `cp` will fail).
The PR does not affect Cygwin which by default uses symlinks.
This PR is the real fix to https://github.com/ocaml/dune/blob/fa3aa2891ac74828a81f73894fe247f69c530c81/ci/build-test.sh#L82-L94 and similar failures.
=> Fix: distinguish MSYS2 from Cygwin

master_changes.md, src/solver/opamCudf.ml
This would help debugging issues with dose3.
For example: I'm currently debugging an issue where a simple opam install takes 32GB+ of RAM and seeing something in the logs that would tell me that the call was stuck in dose3 would have made debugging slightly quicker.
=> Log the time dose3's check_request takes

master_changes.md, src/client/opamAction.ml, src/state/opamEnv.ml, src/state/opamEnv.mli, tests/reftests/env.test
Variable interpolations (`%{lib}%`, etc.) are expanded in `setenv` but weren't expanded in `build-env`.
I'd be willing to regard this as having been a bug, and don't expect that we'll find any instances of `build-env` being used where `%{foo}%` was supposed to be treated as a literal string (with this PR, such strange usage should now be written `%%{foo}%%`).
=> Expand variable interpolations in `build-env`

doc/pages/Manual.md, master_changes.md, src/state/opamEnv.ml, tests/reftests/env.test
#4326 fixed the handling of `FOO = ""` in `setenv`/`build-env`, but for all the other operators, although opam can parse the `environment` file, it crashes. The root cause of the crash is that our path split functions return `[]` when passed an empty string (I think is a bad idea, but it comes from ocaml-re, and it's a bit pervasive - `String.split_on_char` in the stdlib I think has a more coherent approach).
The first commit fixes the crash. The second commit capitalises on the fact that opam has _never_ supported `FOO += ""` correctly. The second commit causes opam to _skip_ such updates entirely. This means, for example, that `PATH += ""` is _ignored_ (if the package _really_ intended adding the current directory to `PATH`, then `PATH += "."` already works today).
=> Fix crash for updates to environment with empty strings

shell/dot_ocamlinit
I'm not seeing it being used anywhere so it might be good to remove it to avoid confusion.
=> Remove ancient unused ocamlinit script

master_changes.md, src/core/opamProcess.ml, src/core/opamSystem.ml
Follows-up https://github.com/ocaml/opam/pull/5351#issuecomment-1322077295 with a better approach. The fds used for locking and for the output of running commands are now opened with `O_SHARE_DELETE`. This has no effect on Unix, but it makes the semantics of these files more POSIX-like on Windows. In particular, it means that a switch can be deleted while the lock is still held. This is both simpler than #5351 and also philosophically more accurate - it means that nothing can attempt to take a write lock until after the directory has been completely unlinked.
It's possible that there are one or two other places - in particular, the file used when monitoring an external solver would be another candidate, but these are less critical. In particular, these two mean that cleaning up switches …
=> Always use O_SHARE_DELETE with Unix.openfile

master_changes.md, src/client/opamAction.ml, src/client/opamAuxCommands.ml, src/client/opamCliMain.ml, src/client/opamClient.ml, src/client/opamClientConfig.ml, src/client/opamCommands.ml, src/client/opamConfigCommand.ml, src/client/opamListCommand.ml, src/client/opamPinCommand.ml, src/client/opamSolution.ml, src/core/opamConsole.ml, src/core/opamFilename.ml, src/core/opamParallel.ml, src/core/opamProcess.ml, src/core/opamStd.ml, src/core/opamStd.mli, src/format/opamFile.ml, src/format/opamFormat.ml, src/format/opamFormula.ml, src/format/opamPackage.ml, src/format/opamSysPkg.ml, src/solver/opamBuiltinZ3.real.ml, src/solver/opamCudf.ml, src/solver/opamSolver.ml, src/state/opamEnv.ml, src/state/opamFileTools.ml, src/state/opamSysInteract.ml, src/state/opamSysPoll.ml
To avoid using polymorphic ones.
This PR is the first of more cleaning in code about polymorphic comparison usage
=> Add and use `List` function with comparison functions

master_changes.md, src/client/opamCommands.ml, src/client/opamConfigCommand.ml, src/core/opamStd.ml, src/core/opamStd.mli, src/core/opamSystem.ml, src/format/opamTypes.mli, src/format/opamTypesBase.ml, src/state/opamEnv.ml, src/state/opamSysInteract.ml, tests/reftests/dune.inc, tests/reftests/env.win32.test
There's existing code (of mine) which tries to deal with the fact that environment variable names are case insensitive on Windows. In `OpamStd.Env`, this is dealt with largely correctly in `get`, but the handling in `OpamEnv` is not. When dealing with environment _updates_, it's necessary to transform the names of any updates - i.e. `PATH += "foo"` needs to be transformed to `Path += "foo"` to use the same case as the base environment.
The problem is manifesting itself principally with `PATH`, which by default is actually `Path` on Windows. When reverting the updates in `OpamEnv.get_pure` (for example, to evaluate `eval_variables`), the switch's `bin` directory is correctly ignored when resolving the command, but when the command is executed, it re-emerges, because of a duplicate …
=> Fix case-preserving environment updates on Windows

master_changes.md, src/client/opamSolution.ml
* Take into account not found packages instead of only available ones
* Specify printed message
* No more print system package manager helper if missing packages are only not found ones.
=> depext: improve check again routine

.github/scripts/main/ocaml-cache.sh, .github/workflows/ci.ml, .github/workflows/main.yml, master_changes.md, src_ext/Makefile
Fixes a warning when bootstrapping opam, and some other things (I guess)
cc @dra27
=> Update bootstrap to use FlexDLL 0.42 from ocaml/flexdll

master_changes.md, shell/link_runtime.ml, src/client/opamAdminRepoUpgrade.ml, src/stubs/win32/build-putenv.ml, tests/reftests/dot-install.test, tests/reftests/opamroot-versions.test
With this PR, the reftests are all green on my local machine.
=> Fix the reftests on OCaml 5.0

master_changes.md, src/client/opamSwitchCommand.ml, tests/reftests/switch-import.test
Freeze-exporting packages that have extra-sources without any checksum shouldn't be allowed. This PR fixes this bug.
Side note for reviewers: you can see the diff better using github's "hide whitespace" option
=> Enforce extra-source to have a checksum when using "opam switch export --freeze"

master_changes.md, src/state/opamFileTools.ml, tests/reftests/lint.test, tests/reftests/source.test, tests/reftests/upgrade-format.test
Built on top of https://github.com/ocaml/opam/pull/5069
Since https://github.com/ocaml/opam/pull/5070, opam doesn't enforce `synopsis` to be present, only the presence of either synopsis or description is required.
This breaks the behaviour from opam 2.1 and older which always required synopsis to be present and non-empty.
It is desirable to keep this check around to ensure `opam list` shows something helpful (i.e. anything but blank space)
=> opam lint: Enforce synopsis being always present

master_changes.md, src/state/shellscripts/sandbox_exec.sh
For most users this is strictly equivalent, however in some cases another (possibly broken) bash could be installed and used instead.
Fixes https://github.com/ocaml/opam/issues/5450
=> Enforce the macOS sandbox script to use /bin/bash instead of /usr/bin/env bash for a more consistent experience

master_changes.md, src_ext/Makefile.sources
The 3.5.0 release has a dependency on `bytes` which causes a build error on OCaml `5.1.0+dev1-2022-06-09`:
```
src_ext/dune-local/dune.exe build --profile=release --root .  --promote-install-files -- opam-installer.install opam.install
File "src_ext/base64/src/dune", line 5, characters 12-17:
5 |  (libraries bytes))
^^^^^
Error: Library "bytes" not found.
```
=> Bump vendored base64 to 3.5.1 to fix compilation on OCaml >= 5.0 in vendored mode

master_changes.md, src/client/opamClient.ml, src/client/opamCommands.ml, src/client/opamConfigCommand.ml, src/client/opamSolution.ml, src/format/opamFile.ml, src/format/opamFile.mli, src/state/opamSwitchState.ml, src/state/opamSysInteract.ml, src/state/opamSysInteract.mli, tests/reftests/var-option.test
Add global config field `sys-pkg-manager-cmd` to be able to specify for MSYS2 & Cygwin the command path. In can be used later to specify more precisely used package manager when several exists in the machine, see. #4440
It also permit to not rely on defined variables with the full integration in config file. cc @jonahbeckford 
related to #5348
=> Variable for package manager

master_changes.md, src_ext/Makefile, src_ext/Makefile.packages, src_ext/Makefile.sources
This doesn't seem to be used anywhere. `topkg` stopped depending on it in 1.0.4 and `base64` did it in 1.0.1
=> Remove unused vendored dependency: result

master_changes.md, src/client/opamPinCommand.ml, src/repository/opamGit.ml, tests/reftests/pin.test
Need more testing on distant repos
fix #5324
=> git: differentiate empty repo and branch not found

master_changes.md, src/client/opamAction.ml, src/client/opamAdminCheck.ml, src/client/opamClient.ml, src/client/opamCommands.ml, src/client/opamListCommand.ml, src/client/opamSwitchCommand.ml, src/format/opamTypes.mli, src/solver/opamSolver.ml, src/solver/opamSolver.mli, src/state/opamSwitchAction.ml, src/state/opamSwitchState.ml, src/state/opamSwitchState.mli, tests/reftests/dune.inc, tests/reftests/install-formula.test, tests/reftests/json.unix.test, tests/reftests/opamroot-versions.test, tests/reftests/opamrt-big-upgrade.test, tests/reftests/resolve-variables.test, tests/reftests/switch-import.test, tests/reftests/switch-invariant.test, tests/reftests/switch-list.test
Since invariant is defined and updated, compiler_packages is no more
consistent the way it is. To keep field name, it is still named
`compiler-packages`, but its content is now invariant formula installed
packages and their recursive dependencies. It implies also that switch
state need to be update at each time an install/removal is done, or
invariant changed.
* Remove `universe.u_base` field
* Compute invariant packages instead of compiler packages
* Change PEF `base` field into `invariant-pkg`
* opam list `--invariant` instead of `--base`
* change column name to invariant
* display invariant packages instead of compiler ones
* switch: fill empty synopsis with invariant instead of compiler packages
fix #5202 
fix #5201
=> Compiler packages into invariant packages

master_changes.md, src/core/opamProcess.mli
This is useful when wanting to implement other runners for `OpamProcess.Job.Op`, e.g. based on Dune's Fibers, Lwt or Async as it allows to run the process using their process spawning abstractions.
=> Implement accessors for `OpamProcess.command` type

master_changes.md, src/client/opamLockCommand.ml, tests/reftests/lock.test
On pinning, url section is ignored
=> Lock: remove url section from generated lock file

master_changes.md, src/client/opamAdminCommand.ml, tests/reftests/admin-add-constraint.test
`opam admin add-constraint <cst> --packages <pkg-list>`
Fix #3077
=> Admin: add packages selection for `add-constraint`

.github/workflows/depexts.yml, master_changes.md, src/state/opamSysInteract.ml
** Updated to new version**
Syntax is `dummy-<success|failure>[:<*|0|pkgslist>:*|0|pkgslist>]`
Examples:
- `dummy-success`: install succeed, default: no package installed, all packages available
- `dummy-success:depext-ok:`: install succeed, only `depext-ok` installed, all packages available
- `dummy-failure::*`: install fails, no package installed, all packages available
- `dummy-success:depext-ok:depext-avail`: install succeed, only `depext-ok` installed, only `depext-avail` available
- `dunny-failure::0`: install fails, no package installed, no package available
---
** old version **
Syntax is `dummy-<success|failure>[#installed@<all|none|pkgslist>][#avail@<all|none|pkgslist>`]
Examples:
- dummy-success
- dummy-success#installed@depext-ok
- dummy-failure#avail@all
- …
=> depexts: add more precise depext testing family

master_changes.md, src/client/opamArg.ml, src/client/opamConfigCommand.ml, src/core/opamFilename.ml, src/core/opamFilename.mli, src/format/opamFile.ml, src/format/opamFile.mli, src/state/opamEnv.ml, tests/reftests/env.test
Extracted from #5417, which now just deals with the fully revertible environment updates part.
- we keep taking write lock as something is written in switch
- We want to keep hooks as readonly. The only downside is that when a local switch is moved, the hook takes some times (switch loading) to recompute environment ; prompt will take that time until an opam commands in the terminal with write lock writes the new environment
- We can still add the hook-read-only (read-only except for env) in the future, when it makes sense to move a switch
=> Support atomic environment updates in OpamFile

doc/man/dune, doc/man/dune_man.ml, doc/man/opam-admin-topics.inc, doc/man/opam-topics.inc, master_changes.md, src/client/dune, src/dune, tests/reftests/dune.inc, tests/reftests/gen.ml
The compilation fails if
```sh
$ dune build --only-packages opam-core,opam-format,opam-repository
```
As it tries to build the binary, but can't due to the opam package not being compiled. This adds the `package` stanza to the associated rules to avoid the rules being triggered when the `opam` package is not selected.
=> Add `package` stanza on all rules that depend on opamMain.exe.exe

master_changes.md, src/client/opamSolution.ml, tests/reftests/autopin.test, tests/reftests/depexts.test, tests/reftests/pin.test
I just noticed that "attempt installation anyway" could be misleading because of
the ambiguity between "system installation" and "opam installation".
"Continue anyway" is much more obvious, esp. if you read quickly.
=> depexts: reword message

.github/workflows/ci.ml, .github/workflows/main.yml, master_changes.md, shell/msvs-detect
Update to the latest commit (1 commit past 0.5.0). This will help bootstrapping opam with latest Visual Studio.
Update to [f988164028edd9db3944b7fc18fc2535e8c70ae4][msvs-detect].
- Add metadata for Visual Studio 2022
- Use MSYS2_ARG_CONV_EXCL to disable MSYS2 argument mangling,
replacing the workaround in 0.4.0 (Jonah Beckford)
- Fix strong/weak detection of the environment compiler (Jonah Beckford)
- Fix the vswhere invocation to detect Build Tools (Jonah Beckford)
[msvs-detect]: https://github.com/metastack/msvs-tools/commit/f988164028edd9db3944b7fc18fc2535e8c70ae4
=> Update to latest msvs-detect

Makefile, bench.Dockerfile, master_changes.md, tests/bench/bench.ml, tests/bench/dune
Just a small simple benchmark inspired by https://github.com/ocaml/dune/pull/4507 and https://github.com/ocaml/dune/pull/5034 to test part of https://github.com/ocaml/opam/pull/5518
For now it only shows:
* The time that `opam sitch` (misspelled command) takes (see https://github.com/ocaml/opam/issues/5479)
* The size of the resulting opam binary
More benchmarks will be added later. This is the minimum required for other PRs to be merged as current-bench is currently failing without it.
=> Setup benchmarking using current-bench

.github/scripts/main/main.sh, configure, configure.ac, master_changes.md, release/Dockerfile.in
Currently if dune is not detected, or a dependency is not detected by the configure script (said configure script can well be outdated, e.g. https://github.com/ocaml/opam/pull/5497), the vendoring mode is enabled by default without asking the user.
I think this is not a good default and if it were to be released now i would probably weigh against merging it in this state in opam-repository as the sandbox does not allow network access and the the general behaviour can become non-deterministic very easily. Other system package managers maintainers would probably also get upset by this behaviour.
I thus propose to simply switch the behaviour to "vendor only when `--with-vendored-deps` is given"
=> Stop the configure script from downloading and vendoring dependencies by default

master_changes.md, src/core/opamFilename.ml, src/core/opamSystem.ml
This should fix https://github.com/ocaml/opam/issues/1073 for good.
This also makes opam slightly more portable and not so much reliant on external processes (see e.g. https://github.com/ocaml/opam/pull/3217)
**Warning for testers: This is untested code touching the file system. Only test this in a sandboxed environment.**
=> Use OCaml code to copy/move/remove directories instead of unix commands

doc/pages/Manual.md, master_changes.md
The existing sentence seems to indicate that it evaluates to `true` when it contains undefined variables.
=> doc: `?` evaluates to `true` if defined

configure, configure.ac, master_changes.md
Fixes #4452
Fixes #5523
Extracted from #5525
=> Do not silently disable mccs if a C++ compiler is not present

master_changes.md, src/state/opamEnv.ml
It's less confusing for newcomers.
=> init: change shell setup defaut to true

Makefile, master_changes.md
Having things like `MAKEFLAGS=-j8` in your environment makes most targets of the main makefile fail.
Failure encountered by @MisterDA
=> Ensure all make targets are run serially

master_changes.md, src/repository/opamRepository.ml, tests/reftests/dune.inc, tests/reftests/local-cache.test
Reported by @roburio
Pre-checked by @rjbou 
Ready for integration in https://github.com/ocaml/opam/pull/5444
=> Fix opam installing packages without checking their checksum when the local cache is corrupted in some cases

master_changes.md, src/state/opamSysInteract.ml
As for Msys2, we suppose that cygwin is set in config.
For Cygwin, it is not the same tool that checks installed system packages (`cygcheck` that is in path, and in `sys-package-manager` config field), and to install them (`setup-x86_64`, that we expect to be in Cygwin root path).
=> Depexts: add cygwin support

master_changes.md, src/client/opamCLIVersion.ml
Extracted from #5555: 
>>> What is the origin/point of the second commit `OpamCLIVersion.of_string`?
>>
>> Well, I had to debug why opam was failing to parse/extract its version from the configure file. It was nice to print the actual string to see what happened, a bit like "No such file or directory" is enhanced if you actually know which file or directory has not been found.
>
> Oh i see, for that, it's better to open another PR, to keep them single purpose.
https://github.com/ocaml/opam/pull/5555#issuecomment-1568758308
=> Print version when failing to parse it

master_changes.md, src/client/opamAction.ml, src/client/opamArg.ml, src/client/opamClient.ml, src/client/opamClientConfig.mli, src/core/opamCompat.ml, src/core/opamCompat.mli, src/core/opamCoreConfig.ml, src/core/opamCoreConfig.mli, src/core/opamProcess.ml, src/core/opamProcess.mli, src/core/opamStd.ml, src/core/opamStd.mli, src/core/opamSystem.ml, src/state/opamGlobalState.ml, src/state/opamSysInteract.ml, src/state/opamSysInteract.mli, src/state/opamSysPoll.ml, tests/reftests/env.test, tests/reftests/init.test, tests/reftests/opamroot-versions.test, tests/reftests/var-option.test
At init && reinit, add detection and setup of a pre-existent cygwin installation.
It contains commit of #5543 (see https://github.com/ocaml/opam/pull/5543#issuecomment-1589723915)
=> init: detect local cygwin installation

master_changes.md, src/core/opamConsole.ml, tests/reftests/admin.test
see https://github.com/ocaml/opam/pull/5385#discussion_r1135565693
=> `opam admin lint`: clean output when stdout is not tty

master_changes.md, src/state/opamFileTools.ml, tests/reftests/lint.test
See https://github.com/ocaml/opam-repository/pull/23736
=> The conflicts field's filter does not support package variables: update lint

.github/scripts/main/ocaml-cache.sh, master_changes.md, src_ext/Makefile
Summary
This release fixes support for parallel usage of Dynlink in OCaml 5.x, several issues with parsing archives correctly, and introduces support for MSYS2's mingw-w64 compilers. Cygwin32 support has been completely removed, following the retirement of the Cygwin32 distribution.
- GPR#108: Add -lgcc_s to Cygwin's link libraries, upstreaming a patch from the
Cygwin flexdll package (David Allsopp)
- GPR#112: Put error global variables into thread-local storage (Samuel Hym, Nicolás Ojeda Bär)
- GPR#114: Support for /alternatename directive. Fixes GPR#113 (Jonah Beckford)
- GPR#116: Remove Cygwin32 (David Allsopp)
- GPR#117: Fix handling of object names of length > 16 in archive files. Fixes GPR#110 (Nicolás Ojeda Bär)
- GPR#118: Defer the detection of cygpath to the first time it's …
=> Update bootstrap to use FlexDLL 0.43 from ocaml/flexdll

.github/scripts/main/hygiene.sh, master_changes.md
=> gha: fix master cli version check

master_changes.md, src/client/opamClient.ml, src/client/opamClient.mli, src/client/opamCommands.ml, src/client/opamInitDefaults.ml, src/client/opamInitDefaults.mli, src/client/opamSolution.ml, src/state/opamSysInteract.ml, src/state/opamSysInteract.mli
At init, add an item in the cygwin menu to propose to have a cygwin install internal to opam. It is handled by opam itself (prefix stored in `<opamroot>/.cygwin/root`), when depext are requested, there is no confirmation requested.
It also adds some flags to `init`, to have a cywgin configuration non interactively: `--no-cygwin-setup`|`--cygwin-internal-install`|`--cygwin-local-install` and `--cygwin-location <path>`.
These are experimental as they can change name from the finale release.
=> init: install cygwin internally

configure, configure.ac, master_changes.md
~`src/stubs/win32/cc64` was never written before because the C compiler was always the wrong one (x86_32 when only the x86_64 is available and x86_64 when only the x86_32 one is available)~
~I'm not sure how it ever worked before. Maybe the typical setup always has both x86_64 and x86_32 so it somehow worked out.~
A complementary C compiler (32bit on 64bit platforms and 64bit on 32bit platforms) is required to build opam-putenv on Windows, but the check for those compilers only output a warning instead of an error. Said warning made it seem like it way an optional binary, however this is not the case and is always required on Windows AFAIK.
cc @MisterDA
=> configure: Ensure a complementary (32bit on 64bit platforms and 64bit on 32bit platforms) C compiler is installed on Windows

master_changes.md, tests/reftests/dune, tests/reftests/dune.inc, tests/reftests/gen.ml
Switching between branches prior to the 2.2 bump, the roots for reftests in _build end up either too new or requiring upgrade. This little tweak makes them depend on `OpamFile.Config.root_version`
=> Rebuild the reftest roots if root version changes

Makefile.config.in, configure, configure.ac, master_changes.md, opam-core.opam, src/client/opamCLIVersion.ml, src/core/dune
This PR brings a couple of cleanups noticed when using OCaml >= 5.0:
* In OCaml 5.0 the `bigarray` library was removed. Since opam now requires at least OCaml 4.08 and bigarray has been part of the standard library since 4.08 we can now remove the dependencies on it
* Since OCaml 5.0 `Printf.kprintf` now shows a deprecation warning when used. `Printf.ksprintf` should be used instead
=> Various cleanups related to OCaml 5.0

master_changes.md, src/format/opamFilter.ml, src/format/opamFilter.mli
Adds a new function `OpamFilter.expand_interpolations_in_file_full` that takes both input path and also output path instead of inferring it.
This feature is upstreamed from the dune fork of OPAM.
=> `OpamFilter` file substitutions with source & destination

master_changes.md, src/format/opamFilter.mli
This function is needed by dune to parse variable interpolations from opam fields.
=> Expose string_interp_regex

Makefile, master_changes.md
Partially f.i.x.e.s. #5628
Fixes https://github.com/ocaml/opam/issues/5600
=> Fix "make cold" on Windows when gcc is available

master_changes.md, src/client/opamCommands.ml, src/client/opamTreeCommand.ml, src/client/opamTreeCommand.mli, tests/reftests/tree.test
Fixes https://github.com/ocaml/opam/issues/5493
Fixes https://github.com/ocaml/opam/issues/5287
Additional questions:
* do we want to support `--recursive` and `--subpath` ?
* do we want to support `--with-version` ?
my personal opinion for those is to say *"we can merge this now, open an issue for those options and leave it for later"*
----
TODO:
=> opam tree: Allow packages with a specific version, directories or local opam files, as input

doc/man/opam-admin-topics.inc, master_changes.md, src/client/opamAdminCommand.ml, tests/reftests/admin.test
This is needed with changes in #5564.
Repositories can contain opam file with no extra-files field, as opam automatically adds them. With changes in #5564, this is no more done. This command ease updating the repository to fill all extra-files fields, and permit also with the combination with the option `--hash` to choose & update used hash in a repository.
=> admin: add `update-extrafiles` command

master_changes.md, src/state/shellscripts/bwrap.sh, src/state/shellscripts/sandbox_exec.sh
Bug I introduced by error in https://github.com/ocaml/opam/pull/5634
```
/home/kit_ty_kate/.opam/opam-init/hooks/sandbox.sh contains local modification, overwrite ? [y/n] y
[ERROR] Sandboxing is not working on your platform archarm:
"~/.opam/opam-init/hooks/sandbox.sh build sh -c echo SUCCESS | tee check-write" exited with code 1 "/home/kit_ty_kate/.opam/opam-init/hooks/sandbox.sh: line 105: OPAMROOT: unbound variable"
```
=> Fix the sandbox scripts in absence of the OPAMROOT variable

master_changes.md, src/client/opamArg.ml, src/client/opamArg.mli, src/client/opamCommands.ml, tests/reftests/lint.test
Fixes https://github.com/ocaml/opam/issues/5651
This PR allows to mark a set of warnings as error and make the command fail.
Examples:
* `opam lint -W@0..999` enables all warnings and errors and fail if any is detected.
* `opam lint -W@62` enables W62 and fail if this warning is detected but ignore any other warnings or errors
The syntax is inspired from the `ocamlc -w` option.
=> opam lint: Allow to mark a set of warnings as errors

.github/scripts/cygwin.cmd, master_changes.md, src/repository/opamRepositoryConfig.ml, tests/reftests/download.test, tests/reftests/dune.inc, tests/reftests/run.ml
`OPAMCURL` is ignored if `OPAMFETCH` is set. This is changed to handle `OPAMCURL` specification when `OPAMFETCH` is set to `curl` (simple command, or new arguments). If `OPAMFETCH` is set to another tool, OPAMCURL is ignored.
Todo:
=> Fix `OPAMFETCH`/`OPAMCURL` handling

.github/workflows/ci.ml, .github/workflows/main.yml, master_changes.md
5.x doesn’t support MSVC and PPC64 yet so we can’t use either as default version but we can at least test them in CI as a quick check
=> Test OCaml 5.0 and 5.1 in CI

master_changes.md, src/core/opamSystem.ml, tests/reftests/core-system.unix.test, tests/reftests/dune.inc, tests/reftests/run.ml
This PR contains 2 different fixes, that can't be split. It fixes #5585, #5650 and partially #5597, as it fixes command resolve that is it happen to be a directory. I also add a test for that, and to have the test working, reftest engine needs a fix. It was keeping duplicated environment variables in environment given as argument to process creation, and it was not expanding `PATH` on variable export.
It also add syntax to declare env vars paths additions `PATH+=path/to` or `PATH=+path/to`, to make it portable between unix & windows (`:` versus `;`).
Todo:
=> resolve command: don't select directories

master_changes.md, src/core/opamStd.ml, tests/reftests/core-config.test, tests/reftests/dune.inc
This literally flips the implementation. As you can see in the implementation of `bool_of_string`, the original implementation does not seem correct.
https://github.com/ocaml/opam/blob/b0cb137edebc5e7d7ac1e650086e3be5800ae743/src/core/opamStd.ml#L1666-L1670
In fact, I found this when debugging a GitHub Actions issue, and you can easily reproduce the issue on your computer by just try each of the following commands:
```sh
OPAMVERBOSE=no opam update
```
```sh
OPAMVERBOSE=yes opam update
```
=> OPAMVERBOSE: Fix `level` by flipping the `env_level` implementation

master_changes.md, src/core/opamDirTrack.ml, tests/reftests/dot-install.test
Since #4494, directory tracking is simplified when a .install file is present: only cited files/directories are tracked and marked as changed if necessary.
Intermediate directories were not tracked, so directories are created but never removed.
fix #5688
=> Directory tracking: in presence of .install file, track also intermediate directories

master_changes.md, src/client/opamClient.ml, tests/reftests/assume-built.test
=> check install: undefined variable default to false

.gitattributes, configure, configure.ac, master_changes.md
opam requires both a 32-bit and a 64-bit C compiler when compiling for 64-bit Windows. However, for mingw-w64, the error message confusingly displayed the architecture of the compiler which was _installed_.
=> Fix incorrect error message in configure

master_changes.md, src/core/opamStd.ml, src/core/opamStd.mli, src/stubs/win32/opamWindows.c
In Windows native containers, the `Filename.chop_suffix` call in `windows_get_shell` was occasionally failing. `OpamStubs.getProcessAncestry` can return empty strings. `windows_get_shell` now explictly handles the empty string case and `.exe` is now _optionally_ stripped.
=> Harden `windows_get_shell`

master_changes.md, release/Makefile
abe02fc6ff39c0191406c83de8fc91ab4eeca0b3 added a fix to add the -lsha_stubs only on opam master, but OpenBSD's tar doesn't have the -O option. This commit extracts the tar archive to a temporary directory as a workaround.
=> release: Workaround missing -O option to tar on OpenBSD

.github/scripts/cygwin.cmd, .github/workflows/ci.ml, .github/workflows/main.yml, configure, configure.ac, master_changes.md
=> Add ./configure --enable-static to compile the opam binary statically

doc/pages/Install.md, master_changes.md
If someone is a complete FreeBSD greenhorn newbie, they might not realize that the opam package is `ocaml-opam`, and installing from source is painful.
=> Update Install.md FreeBSD instructions

master_changes.md, src/client/opamConfigCommand.ml
=> opam env: fix carriage return on Cygwin shell

master_changes.md, src/client/opamConfigCommand.ml, tests/reftests/switch-set.test
~Store old `OPAMSWITCH` in last env file, in order to revert it properly~
Don't store `OPAMSWITCH` & `OPAMROOT` in the last environment file, like that they are not reverted. They are set with `--set-switch` and `--set-root`, they are meant to remain in the shell environment.
fixes #5696
queued on #5715 for windows ci
=> `OPAMSWITCH` and `OPAMROOT` reverts

.github/workflows/main.yml, master_changes.md, src/client/opamAction.ml, src/client/opamArg.ml, src/client/opamClient.ml, src/client/opamClient.mli, src/client/opamClientConfig.mli, src/client/opamCommands.ml, src/client/opamConfigCommand.ml, src/core/opamCoreConfig.ml, src/core/opamCoreConfig.mli, src/core/opamProcess.ml, src/core/opamStd.ml, src/core/opamStd.mli, src/core/opamSystem.ml, src/core/opamSystem.mli, src/format/opamFile.ml, src/format/opamFile.mli, tests/reftests/var-option.test
-- *outdated, to be updated* --
At initialisation, check the origin of resolved git command:
* if from Cygwin, ask to install Git for Windows one
* if from Git for Windows, check that it is the good directory in path (`\cmd`)
This is done by checking the existence of a bash executable near git.
+ no more install git in Cygwin initialisation if already present in path
related to #5617 
/cc @jonahbeckford 
todo
=> Git on windows: check and advertise to use Git for Windows

master_changes.md, src/state/shellscripts/sandbox_exec.sh
As noted in #5778, this is a proper bugfix:
- `[ -z /usr/bin/getconf ]` tests if the literal string "/usr/bin/getconf" is empty - which is always false - and doesn't probe the filesystem at all.
- `[ -n "$(which getconf)" ]` actually asks the system if that command exists. The place where it is defined (/usr/bin or anything else) doesn't matter since we call it directly below.
It should be noted that if `$TMPDIR` is not set *and* `getconf` doesn't exist, we carry on the program silently. Is that intended?
I do not have a macos machine on hand and cannot test this, but this could be related to #4958
=> Fix macos sandbox script incorrectly assuming that `getconf` doesn't exist

master_changes.md, src/client/opamInitDefaults.ml, src/state/opamSysInteract.ml
The VCS backends all require rsync, and this enables the local backend by default.
=> Install rsync to the internal Cygwin installation

configure, configure.ac, master_changes.md
Cppo was used directly until #5498. It is still used by dependencies (namely `extlib`) however, so it should stay vendored.
=> Do not check for cppo in the configure script (not used directly anymore)

master_changes.md, src/client/opamCliMain.ml, src/core/opamStubs.dummy.ml, src/core/opamStubs.mli, src/stubs/win32/opamWin32Stubs.ml, src/stubs/win32/opamWindows.c
When the WIndows loader cannot find DLLs, the default, very very legacy behaviour is to display a dialog such as this:
This dialog is problematic, as it's part of the loader, so the application itself is not able to handle this itself. It's doubly problematic for us, as it's blocking.
The convention is that _calling_ applications are expected to disable this error handler. New processes inherit this setting, which causes the loader to suppress the dialog box and instead return an exit code. This is documented best practice (see the notes for `SEM_FAILCRITICALERRORS` in [SetErrorMode on MSDN](https://learn.microsoft.com/en-us/windows/win32/api/errhandlingapi/nf-errhandlingapi-seterrormode)).
=> Disable Windows critical error handler

master_changes.md, src/core/opamStd.ml, src_ext/Makefile.sources
Fixes https://github.com/ocaml/opam/issues/5644
This line was added in https://github.com/ocaml/opam/pull/4816 but looking at the relevant discussion (https://github.com/ocaml/opam/pull/4816#discussion_r927799712) I’m not sure if the change makes much sense to me (but I’m not a Windows user so most of the discussions around Windows doesn’t make sense to me anyway :D )
=> Fix shell detection on Windows when opam is called via Cygwin's /usr/bin/env even though cmd/powershell is used

master_changes.md, src/client/opamClient.ml
Apropos note in #5782. The motivation behind this is to have symlinks available as an optimisation (for example, to allow caches, compiler installations, etc. to use `ln` instead of `cp` to save space, just as on Unix, but not to be a _requirement_ for any packages). There are other ways to enable this, but "Developer Mode" is by far the simplest, and is recommended (or even required) by Microsoft's own SDKs.
=> Recommend Developer Mode on Windows

master_changes.md, src/state/opamEnv.ml, tests/reftests/env.test
Two fixes here, both relatively subtle:
- If the environment contained `FOO=bar`, the update `FOO += ""` would cause opam to execute _without_ `FOO` in the environment
- A small regression in #5356 - in the refactoring for case-preserving updates, a boolean check got accidentally inverted
=> Two (more) environment fixes

master_changes.md, src/client/opamArg.ml
Cygwin support added the need to retrieve some information (cygwin binary path) from the config file before its proper loading by the global state (see https://github.com/ocaml/opam/pull/5544/files#diff-e674376a5ba688da9b6f11571be146af2e7bbde7c583630c6e8d4fc15c575035R575).
Git on windows PR #5718 used the same mechanism to load git location information at an early stage.
This PR fixes that retrieval implemented in #5718: `git-location` was searched among `global-variables` variables, not among field as implemented in this PR.
=> arg: fix loading git location from config file at init

master_changes.md, src/state/opamSysInteract.ml
Fixes https://github.com/ocaml/opam/issues/5781
=> Disable ACL in Cygwin to avoid permission missmatch errors

doc/pages/Manual.md, master_changes.md
=> Documentation: Fix a dead link to SPDX license expressions spec

master_changes.md, src/client/opamClient.ml, src/format/opamFile.ml, src/format/opamFile.mli
=> Add `sys-pkg-manager-cmd`  in init config

master_changes.md, src/client/opamArg.ml
Fix missing spaces in `opam --help`.
=> fix missing spaces

doc/pages/Manual.md, master_changes.md, src/core/opamProcess.ml
~Fixes #5782~ 
Actually no, at least not yet. Upon creating the PR I realized another point in the code also modifies `CYGWIN` (in a destructive manner)
@dra27 I’m reading the comments for `OpamProcess.cygwin_create_process_env` and the use of `win_create_process` (which i’m also realizing does not exist in OCaml >= 5.0, which means opam can’t be compiled on Windows if you’re using ocaml 5) and I’m not sure if it’s just a relic of the past that can now be replaced by `Unix.create_process_env` or not? Was the issue encountered with `Unix.create_process_env` ever got fixed or was it only an issue in opam and thus not something that could actually be fixed upstream?
If it is a relic of the past I’ll go ahead and remove it and together with the current code, it should work.
=> Add winsymlinks:native to the CYGWIN environment variable when running a Cygwin executable on Windows

master_changes.md, src/core/opamSystem.mli, src/state/opamEnv.ml
Fixes https://github.com/ocaml/opam/issues/5804
I personally think keeping the Windows style paths on Windows when using cygwin shell is fine, however none of the paths were previously quoted which is a big issue and the reason why the user in #5804 looked in the file in the first place as such command will always fail on Windows.
On cmd and powershell double quoting is apparently enough to make sure the string can't escape its context (?) (e.g. `"` and `$` are not valid file characters)
=> Quote all the paths to OPAMROOT when creating the init scripts on Unix

master_changes.md, src/client/opamClient.ml
fixes #5845 
If `--git-location` is given and `git-location` is defined, priority goes to the one defined via CLI. Same with `--no-git-location`, it overrides `git-location` definition in config file.
=> init: on windows, fix handling of 'git-location' when defined in init config

.github/workflows/lib.ml, .github/workflows/main.yml, master_changes.md
Related to https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/
`ocaml-opam/cache@opam` needs also to be updated.
=> gha: update checkout to v4

master_changes.md, src/client/opamArg.ml, src/client/opamClient.ml, src/core/opamCoreConfig.ml, src/core/opamCoreConfig.mli, src/core/opamStd.ml, src/core/opamStd.mli, src/state/opamGlobalState.ml, src/state/opamSysInteract.ml, src/state/opamSysInteract.mli
Opam 2.2 init on Windows is focused on resolving a pre-existent Cygwin install, or install opam internal one. Functions that detect if a Cygwin install is present are strictly checking a Cygwin one. This behaviour broke opam usage under MSYS2. As MSYS2 Cygwin is a Cygwin variant, it is not detected, and no specific handling of paths, syscall, etc. are done.
MSYS2 is not officially supported (not testing it in a regular basis), we should ensure that we can keep MSYS2 users to have a way to use opam.
This PR fixes that behaviour by relaxing Cygwin install checks to accept variants. As for Cygwin setup for `opam init`, a check of the install is done, and to keep the information, the config file is appended with
```
global-variables: [os-distribution "msys2" "Set by opam init"]
```
to be sure …
=> Opam 2.2 init with MSYS2

doc/pages/Manual.md, master_changes.md, src/client/opamInitDefaults.ml, src/core/opamSystem.ml, tests/reftests/repository.test
Fixes https://github.com/ocaml/opam/issues/3433
Fixes https://github.com/ocaml/opam/issues/3782
Fixes https://github.com/ocaml/opam/issues/3639 for good
Helps https://github.com/ocaml/opam/issues/3482
While looking at https://github.com/ocaml/opam/issues/3639 happening for many macOS users, I realized that `git apply` basically ships with its own version of GNU patch which works correctly.
The original issue is that macOS is a POSIX-complient OS. However POSIX-complient patch seems to be a nightmare: you can't tell it to delete files. It'll just make it empty instead. There are non-posix options (`-E`) that deletes empty files anyway but those have another problem where it can't distinguish between you deleting the file and emptying the file... This issue also appears on BSDs.
The …
=> Replace the dependency on GNU patch by a strict dependency on git

master_changes.md, src/state/opamEnv.ml, src/state/shellscripts/env_hook.fish, tests/reftests/init-scripts.unix.test, tests/reftests/init-scripts.win32.test
This PR is the third and last off-shoot of #5802, containing the only bugfix in the previous PR: this change `isatty -> status is-interactive`.
=> Fish integration: nitpicking

.github/scripts/main/create-ocaml-cache.sh, .github/workflows/ci.ml, .github/workflows/main.yml, .gitignore, Makefile, master_changes.md, src_ext/Makefile, src_ext/Makefile.dune, src_ext/Makefile.packages, src_ext/Makefile.sources, src_ext/update-sources.sh
Fixes an issue reported in https://github.com/ocaml/opam/issues/5770 that happens on some architectures (e.g. PPC).
Prepares fix for https://github.com/ocaml/opam/issues/5861 (coming in dune 3.14.1)
=> Upgrade the vendored dune to 3.14.0 and other packages to their latest release

master_changes.md, src_ext/Makefile.dune
Fixes https://github.com/ocaml/opam/issues/5861
See https://github.com/janestreet/spawn/pull/58
~To be merged when https://github.com/ocaml/opam-repository/pull/25474 is merged.~
=> Allow to compile opam when the environment contains unicode characters on Windows (upgrade to dune 3.14.2)

doc/pages/Manual.md, master_changes.md, src/client/opamInitDefaults.ml, src/core/opamSystem.ml, tests/reftests/repository.test
Reverts #5400 
After a couple of weeks of tests, `git apply` turned out to be bad choice for 2 main reason:
* the format accepted by it is too strict and will make applications of a number of patches from opam-repository fail. See for example https://github.com/ocaml/opam-repository/pull/25430#issuecomment-2007103671
* The `--unsafe-paths` option is not just used `When git apply is used as a "better GNU patch"` (as the git documentation puts it), but is actually highly unsafe (who could have guessed!) and allows the application of patches outside of the selected path using `../`. However opam requires one part of the behaviour of this option to work: accepting to apply changes inside of a `.git` directory. This is required for `opam update` to function properly.
I've also observed some …
=> Revert "Merge pull request #5400 from kit-ty-kate/no-gpatch"

bench.Dockerfile, master_changes.md, tests/bench/bench.ml, tests/bench/dune
=> Benchmark OpamSystem.read

doc/pages/Install.md, master_changes.md
Update the install page with newer badges for Ubuntu (20.04 -> 22.04) and Fedora (32 -> 39)
=> Update badges to newer distro versions for Ubuntu and Fedora

doc/pages/Manual.md, master_changes.md, src/format/opamFilter.ml, src/format/opamFilter.mli, src/format/opamTypesBase.ml, src/format/opamTypesBase.mli, src/state/opamFileTools.ml, tests/reftests/dune.inc, tests/reftests/lint.test, tests/reftests/opam-pkgvar-with-plus.test
~Per our own documentation, '+' should not be a valid character for packages. However packages like conf-g++ or conf-c++ now exist in the wild. This solution is a compromise in hope for {name1+name2+name3:var} to be parsable again~
Related to https://github.com/ocaml/opam-file-format/issues/59
=> Hijack the %{?val_if_true:val_if_false}% syntax to support extending the variables of packages with + in their name

.github/workflows/ci.ml, .github/workflows/main.yml, master_changes.md, src/client/opamInitDefaults.ml, src/core/opamSystem.ml, tests/reftests/repository.test
Lightweight alternative to #5892 
See #5400 
In this PR, once per process if a patch is going to be applied (either a patch application in a package or a repository update) we first check which patch executable to use. If no GNU patch is detected we display a warning.
On some platforms the name of the `patch` command can change depending on the context (e.g. macOS where Homebrew provides `patch` but Macports provides `gpatch`), so to handle that we simply check both `patch` and `gpatch` and detect which one is GNU patch. On the platforms more likely to have `patch` as GNU patch we check `patch` first and default to it if none were found, and inversely on the platforms that are more likely to have `gpatch` as GNU patch.
=> Warn if GNU patch is not detected when using patch

master_changes.md, src/client/opamCommands.ml, src/repository/opamDarcs.ml, src/repository/opamGit.ml, src/repository/opamHTTP.ml, src/repository/opamHg.ml, src/repository/opamLocal.ml, src/repository/opamRepository.ml, src/repository/opamRepository.mli, src/repository/opamRepositoryBackend.ml, src/repository/opamRepositoryBackend.mli, src/repository/opamVCS.ml, src/repository/opamVCS.mli, tests/reftests/repository.test, tests/reftests/source.test
This PR is about to fix #5061. It turns out we doesn't need a flag for fixing the issue, It is agreed during the `opam-dev` meeting to avoid fetching with `--depth 1` for `opam source` because on the client side it could be confusing, an idea from @kit-ty-kate.
=> `opam source --dev` fetching git repositories without `--depth 1`

.github/scripts/main/preamble.sh, master_changes.md
The default macOS runners are now Ventura (14) which has added a realpath utility which causes brew's coreutils package to install realpath as grealpath. Follow brew's configuration advice for the PATH variable.
=> Fix GitHub Actions for macOS

master_changes.md, src/core/opamConsole.ml
Fixes #5910 
Printf.printf "%f" rounds up so above 30s (30 / 60) rounds up to 1m
Noticed by David during [today's dev meeting](https://github.com/ocaml/opam/wiki/2024-Developer-Meetings#2024-04-08)
=> Fix rounding error when displaying the timestamp in debug mode

master_changes.md, src/client/opamSwitchCommand.ml, tests/reftests/switch-import.test
Fixes #5941 
opam 2.1 used the Base64 module from extlib which does not seem to pad encoded outputs. In contrast, opam 2.2 uses the Base64 module from the base64 library (after extlib's Base64 module was removed in extlib.1.7.8) which by default pads outputs and requires padded inputs when decoding them.
cc-ing base64 implementations maintainers @dinosaure @ygrek 
- Question for @dinosaure: is this fix fine? Should `Base64.encode` be also called with `~pad:false`? What are the pitfalls of disabling padding?
- Question for @ygrek: Just to double-check, am i correct in assuming the output of extlib's base64 implementation is always not padded?
=> Allow to parse opam 2.1 switch import files containing extra-files

master_changes.md, src/format/opamFile.ml, src/state/opamFormatUpgrade.ml, tests/reftests/init-ocaml-eval-variables.unix.test, tests/reftests/init-ocaml-eval-variables.win32.test, tests/reftests/opamroot-versions.test
Fixes https://github.com/ocaml/opam/issues/5816
=> Reset the "jobs" config variable when upgrading to opam 2.2

master_changes.md, src/core/opamStd.ml, src/core/opamStd.mli, src/repository/opamDownload.ml
`OpamDownload.download` downloads a given URL using the basename of the URL as the filename. On Windows, where are there are many restrictions on valid filenames, this causes a problem if the URL includes any query string. Since OpamDownload passes the name used to the continuation, on Windows the illegal characters are simply replaced with underscores.
=> Fix downloading URLs with invalid characters

master_changes.md, src/client/opamClient.ml, src/client/opamClient.mli, src/client/opamCommands.ml
Fixes #5834.
Instead of reusing `--cygwin-internal-install`, it is more suitable to have new option (`--cygwin-packages=CYGWIN_PACKAGES`), to avoid ending up checking the exclusion between `--cygwin-internal-install` and `--cygwin-local-install`.
=> Add CLI option to specify additional packages for internal Cygwin.

master_changes.md, src/state/opamSysInteract.ml
Related to #5793, this adds `--symlink-type native` to the Cygwin setup invocation if the user has the ability to create them. This is more to disable the use of WSL symlinks than to actually enable any additional binaries (Cygwin names binaries `.exe`, but it doesn't do that for a symlink to an executable, so they're not any more available than they were before).
We can save a small amount of time and a potential error message by passing `--no-version-check` - that simply tells Cygwin not to report if the version of setup is older than the latest reported in `setup.ini`.
Hot off the presses in Setup 2.929 is an option to reduce the noise of the installation. We should definitely use the `noinput` version at all times, but the `hidden` version is nice as it suppresses the GUI completely. …
=> Tweaks to internal Cygwin setup

master_changes.md, src/client/opamClient.ml
Fixes #5817 
~Requires #5909 to be merged first~
https://github.com/ocaml/opam/commit/9aa22900ded5bdaeef2e9ac7e2e894d6a4d68a8d changed the behaviour of opam in this particular case. This here PR takes a bit of the previous code to get this behaviour back.
https://github.com/ocaml/opam/commit/9aa22900ded5bdaeef2e9ac7e2e894d6a4d68a8d splits the input atoms and the atoms that are the dependencies of each input atoms. The former is empty when `--deps-only` and the second is empty when not in deps-only mode. Now there is a function that takes the former atoms into "atoms that are already installed" and "atoms that are not installed". Near the end of the function before doing the solve, the function tests if the "atoms that are not installed" is empty and simply stops the function in that case. …
=> Fix performance regression when calling opam install --deps-only on an already installed package

master_changes.md, src/core/opamSystem.ml
Partially addresses the issue reported in https://github.com/ocaml/opam/issues/5782#issuecomment-2108726192
In these situations, Cygwin is most likely to create a JUNCTION, which can't be read by `Unix.lstat`. The fix for now I propose is simply to warn. This has the very big benefit of making ocamlbuild install without needing Developer Mode.
It has the downside that we fail to copy the file... I'm suggesting we might choose to live with that for now.
Note that `OpamSystem.remove_file_t` contained an unnecessary second call to `lstat`. I needed to re-use the actual removal logic for the exception case in `remove_dir_t`, but `lstat` is very expensive in C on Unix, even more expensive in OCaml and indescribably more expensive on Windows, so eliminating the double-call seems better!
=> Mitigate copying/deletion of unrecognised symlinks

master_changes.md, src/state/opamPackageVar.ml, tests/reftests/var-option.test
While browsing logfiles, I spotted a small typo in the opamfile package var output.
This little PR attempts to fix it.
=> Fix opamfile package var typo

master_changes.md, src/client/opamCommands.ml
An incorrectly translated case in #5930 means `opam init` with no arguments at the moment unconditionally installs an internal Cygwin! Easy to review based on the diff of the original commit in https://github.com/ocaml/opam/pull/5930/commits/8bc1214c171e588cd3e574c86c798e6a193ca073 - the ```| `none, None -> None``` deleted case at L419 has no equivalent in the new code (indeed, no case yields `None`).
=> Tweak incorrect case in `--cygwin-extra-packages`

master_changes.md, src/client/opamCommands.ml, src/client/opamConfigCommand.ml, src/format/opamFile.ml, src/format/opamPath.ml, src/format/opamPath.mli, tests/reftests/clean.test, tests/reftests/env.test
Fixes #5823 by storing the last-env `OPAM_LAST_ENV` files in the directory `~/.opam/.last-env` instead of in the switch as the solution described in the issue.
=> Move last-env `OPAM_LAST_ENV` files outside the switch

master_changes.md, src/format/opamFilter.mli, src/format/opamFormula.ml, src/format/opamFormula.mli, src/state/opamFileTools.ml, tests/reftests/lint.test
The compiler packages contain the following snippet:
```
depends: [
"flexdll" {>= "0.42" & os = "win32"}
]
build: [
[
"./configure"
"--with-flexdll=%{flexdll:share}%" {flexdll:installed}
]
]
```
but the use of `flexdll:share` triggers lint warning 41 because the flexdll dependency is guarded by `os`. However, this warning is a bit obtuse given the argument is guarded by `flexdll:installed` (and `:installed` explicitly doesn't trigger lint warning 41).
This PR alters lint warning 41 so that when it evaluates the list of variables used in commands, it scans the filters for instances of `package:installed` and then performs a partial evaluation of the filter with that `package:installed` variable explicitly set to false (but nothing else set in the environment). If the filter reduces to …
=> Relax warning 41 for package variables guarded by a :installed filter

master_changes.md, src/format/opamFilter.ml
- Incorrect handling of `FDefined` and `FUndef`
- harden `fold_down_left` against future changes
@dra27 PR, extracted from #5983, @rjbou reviewed :heavy_check_mark:
=> Fix OpamFilter map/fold functions

master_changes.md, src/state/opamSwitchState.ml, tests/reftests/resolve-variables.test
#2921 added the `?` operator to allow filters to have expressions like `?foo & foo = "foo"`, where `?foo` is true if and only if `foo` is a defined variable (or an expression where all the variables have been successfully resolved).
However, it doesn't seem to have been working, which I'd spotted in the ocaml-system updates in https://github.com/ocaml/opam-repository/pull/25861. Unfortunately, the failure means that the repository can't be used with `--strict`.
The fundamental problem is that the warning about undefined variables is displayed when the variables are being resolved, which sadly includes the moment they are being tested with the `?` operator. However, when a filter is partially evaluated, the resulting filter will only contain undefined variables (and the `post` variable), …
=> Don't display undefined variable warnings when evaluating the `?` operator

master_changes.md, src/state/opamSysInteract.ml
This flag is already passed when initially installing Cygwin, but any subsequent depext installs which don't have it cause the internal installations to be put in the registry (when possible).
From my testing so far, including it with an existing registered installation does not cause Cygwin to _delete_ the existing registration.
=> Always pass `--no-write-registry` to Cygwin setup

master_changes.md, src/state/opamEnv.ml
This should deal with the problem being seen with flexdll on setup-ocaml. The issue there is that the Cygwin bin directory gets pushed past a manual installation of mingw-w64 installed on the GHA runners (in `C:\mingw64`) which includes gcc and which quite rightly confuses OCaml.
=> Don't allow make to become shadowed

master_changes.md, src/core/opamConsole.ml, src/core/opamConsole.mli, src/core/opamSystem.ml
Fixes https://github.com/ocaml/opam/issues/5990
=> Display lock hold/release messages on stderr instead of stdout

master_changes.md, src/core/opamConsole.ml, src/core/opamConsole.mli
The Git-for-Windows and Cygwin options mean at least one Windows user is capable of blowing the previous limit of 9 menu items quite trivally. 1-9 used as before with a-z used for the remaining items.
=> Extend OpamConsole.menu to support 35 options

master_changes.md, src/state/opamEnv.ml, tests/reftests/env.win32.test
Neither of these systems supports quoting (on Windows or Unix).
This should address the regression in #5923, but it's not the final fix for Windows, so that issue should stay open after this is merged.
cc @RyanGibb
=> Change default rule for `PKG_CONFIG_PATH` and `MANPATH` to `target`

master_changes.md, src/client/opamClient.ml
The diff for this PR is horrific in the GH interface, but with `--ignore-space-change`, it is just:
```diff
diff --git a/src/client/opamClient.ml b/src/client/opamClient.ml
index 879b2a770..e768ca879 100644
--- a/src/client/opamClient.ml
+++ b/src/client/opamClient.ml
@@ -654,9 +654,7 @@ let is_git_for_windows git =
end
| _ -> false
-let git_for_windows_check =
-  if not Sys.win32 then fun ?git_location:_ () -> None else
-  fun ?git_location () ->
+let git_for_windows ?git_location () =
let header () = OpamConsole.header_msg "Git" in
let contains_git p =
OpamSystem.resolve_command ~env:[||] (Filename.concat p "git.exe")
@@ -693,7 +691,8 @@ let git_for_windows_check =
warning suggesting that the machine be reconfigured to enable them
in PATH, but also gives the opportunity to use the …
```
=> Rename and slightly repurpose `OpamClient.git_for_windows_check`

master_changes.md, src/core/opamProcess.ml, src/core/opamProcess.mli, src/core/opamStd.ml, src/core/opamStd.mli, src/core/opamSystem.ml, src/core/opamSystem.mli
The `opam init` menu overhaul wants to be able to use `resolve_command` from within `OpamStd.Sys` (to be used with some low-level functions), but this isn't possible at present because the default for `OpamSystem.resolve_command`'s `~env` argument is `OpamProcess.default_env`.
However, since #3348 there's already been a slightly unholy mess (added by me...) to allow OpamProcess to use `resolve_command`. This PR disentagles it slightly, by moving the bulk of the logic to `OpamStd.Sys` and leaving the default argument handling in `OpamProcess` and then simply making `OpamSystem.resolve_command` an alias for `OpamProcess.resolve_command`. Not totally sure why I didn't do that in 2018...
=> Disentangle `OpamProcess.resolve_command` and `OpamSystem.resolve_command`

doc/pages/Manual.md, master_changes.md, src/state/opamEnv.ml
Fixes #5923 
The special casing of PKG_CONFIG_PATH was added in https://github.com/ocaml/opam/commit/fd429e33420cece92d82e803c26079185baafd74 but is not needed anymore since https://github.com/ocaml/opam/pull/5636
=> Do not special case the rewriting rule for the PKG_CONFIG_PATH environment variable

master_changes.md, src/client/opamSolution.ml, src/client/opamSolution.mli
This is a refactoring in `OpamSolution` so that the depext menu can be displayed either with a list of opam packages (as `OpamSolution.install_depexts` presently does, or slightly lower-level where the set of system packages to install is already calculated by the caller (the new `OpamSolution.install_sys_packages`).
Additionally, the existing `OpamSolution.print_depext_msg` is exposed (ultimately to allow it be used by `OpamClient`).
=> API: Allow explicit installation of system packages

master_changes.md, src/core/opamProcess.ml, src/repository/opamDownload.ml
Issue originally reported on [Discuss](https://discuss.ocaml.org/t/windows-compiler-support-in-opam-2-2-0-beta2/14648/28).
The OP was using a native Windows `curl.exe` from Git-for-Windows git-bash (MSYS2 has curl both for its "Cygwin" main install, but also compiled natively - git-bash installs the mingw64 native-compiled version). This yields an exception during `opam init` while attempting to setup the internal Cygwin installation:
```
Fatal error:
OpamDownload.Download_fail(_, "curl: code  while downloading https://cygwin.com/sha512.sum")
```
Note that there is no code. Running the command manually, everything appears to be OK, but if the output is piped to a file, the issue becomes apparent (the various `\r` effects removed):
```
% Total    % Received % Xferd  Average Speed   Time …
```
=> Harden curl output parsing

master_changes.md, src/client/opamArg.mli, src/client/opamArgTools.ml, src/client/opamArgTools.mli, src/client/opamCommands.ml
They are now in the manpage and available in non-windows cli, but error.
=> Args: stop hiding the Windows specific arguments of opam init on non-Windows platforms

master_changes.md, src/core/opamSystem.ml
The `~prefix` argument wasn't passed when recursing. Very niche failure mode, but having spotted it...
=> Fix bug in recursion case in `OpamSystem.mk_temp_dir`

master_changes.md, src/repository/opamRepository.ml, src/state/opamRepositoryState.ml, tests/reftests/download.test, tests/reftests/dune.inc, tests/reftests/update.test
First commit is extracted from https://github.com/ocaml/opam/pull/5883
This should at least mitigate the concerns from users thinking opam might have crashed while waiting for opam update/init to finish.
The second commit is temporary while https://github.com/ocaml/opam/issues/5741 is being fixed.
=> Display a note when reloading a repository

master_changes.md, src/client/opamAction.ml, src/client/opamClient.ml, src/client/opamInitDefaults.ml, src/client/opamSolution.ml, src/core/opamCompat.ml, src/core/opamCompat.mli, src/core/opamProcess.ml, src/core/opamStd.ml, src/core/opamStd.mli, src/core/opamStubs.dummy.ml, src/core/opamStubs.mli, src/core/opamSystem.ml, src/state/opamEnv.ml, src/state/opamEnv.mli, src/state/opamGlobalState.ml, src/state/opamSysInteract.ml, src/state/opamSysInteract.mli, src/state/opamSysPoll.ml, src/stubs/win32/opamWin32Stubs.ml, src/stubs/win32/opamWindows.c
At present includes #5991, #5994 and #5997. The diff becomes slightly less hideous with #5997 merged. The PR includes the behaviour of #5996 and may need #5998 for CI to pass properly.
This PR considerably extends the ideas from #5963. The primary goal is to extend `opam init` on Windows to recognise as many scenarios for getting either Cygwin or MSYS2 as we at present know to exist, so that users are presented with meaningful choices. In particular, this addresses running `opam init` from with a Cygwin or MSYS2 bash shell (in particular, #5952 is fixed).
I think it's helpful to start with some scenarios with beta2, and then explain the fixes from there:
1. From cmd/pwsh, with nothing other than `opam` installed, we already have an excellent experience which recommends pausing to install …
=> Small refactoring and fixes to `opam init` on Windows.

master_changes.md, src/client/opamArg.ml, src/client/opamCliMain.ml, src/client/opamClient.ml, src/client/opamClientConfig.ml, src/client/opamClientConfig.mli, src/client/opamCommands.ml, src/core/opamConsole.ml, src/core/opamConsole.mli, src/core/opamSystem.ml, src/core/opamSystem.mli, src/format/opamPath.ml, src/format/opamPath.mli, src/state/opamStateConfig.ml, src/state/opamStateConfig.mli, tests/reftests/env.test, tests/reftests/env.unix.test
On Windows, opam may install a local cygwin, but cygwin doesn't support having a space in its path. We need then to redirect all opam root into a path with no space. Redirection is done at first init, and afterwards it is followed for each opam call.
So opam root directory can contain either:
*  an unique file `redirected-opamroot` that contains the new path
* or the already known opam root.
related to #5220
=> windows: opam root redirection when path contains spaces

master_changes.md, opam-client.opam
Re.Group.get_opt was added in re 1.10.0
Noticed in https://github.com/ocaml/opam-repository/pull/26053
```
#=== ERROR while compiling opam-client.2.2.0~beta3 ============================#
```
=> Fix the lower-bound constraint on ocaml-re

master_changes.md, src/format/opamFile.ml
Related to https://github.com/ocaml/opam/pull/5822
This line of code defines a dummy default value to pass to the two pretty-printers below.
However the `OpamFilename.of_string` function is going to try to expend this path as much as possible, which it should not do.
=> Fix a wrong use of OpamFilename.of_string

src_ext/Makefile.sources
Using `curl`, ocamlgraph.lri.fr is redirecting to GH which returns HTTP 200 and a page with `Not found` whereas `wget` returns 404.
=> Update URL for ocamlgraph source

master_changes.md, src/format/opamFile.ml, src/format/opamTypesBase.ml, src/format/opamTypesBase.mli, tests/reftests/dune.inc, tests/reftests/effectively-equal.test
Fixes #6028 
Prior to https://github.com/ocaml/opam/pull/5636, opam did not traverse the extension fields when testing equality.
Prior to https://github.com/ocaml/opam-repository/pull/25861, very few packages actually had the `x-env-path-rewrite` field so the problem did not occur.
Users with a fresh install cache saved after an install will also not immediately notice this issue (see https://github.com/ocaml/opam/issues/6031)
The issue was that the extension field carries all the positions of the original file and opam files of installed packages are saved in their normalised form which changes the positions of the fields, so when `OpamFile.OPAM.effectively_equal` is called it would see a difference in the extension field.
=> Nullify positions of the extensions fields in OpamFile.OPAM.effective_part

master_changes.md, src/client/opamClient.ml
Fixes #6013. Mostly this was simply that `~yes` parameters were not provided when they should have been. The slightly more subtle fix is if MSYS2 is initialised which is requires `--confirm-level unsafe-yes` but lacked a `~yes`. In this case, the action for `-y` is simply is to ignore the change.
=> Fix `opam init -yn` asking questions on Windows

master_changes.md, shell/bootstrap-ocaml.sh, src_ext/Makefile
This fix is necessary due to https://github.com/ocaml/ocaml/issues/13237 and allow us to build base images https://github.com/ocurrent/docker-base-images/issues/283 again.
I have tested this patch in the base image builder using this [commit](https://github.com/ocurrent/ocaml-dockerfile/commit/8600d2b94a92e526cfc84d18bfbda042a43942dc) and successfully built a base image with opam 2.0, 2.1 and dev.
=> Patch to move from caml.inria.fr to gitHub.com

.github/scripts/main/ocaml-cache.sh, master_changes.md, release/Makefile, release/readme.md, release/release.sh, src_ext/Makefile
Fixes https://github.com/ocaml/opam/issues/5734
=> Add windows to the release script

master_changes.md, shell/install.ps1
Fixes https://github.com/ocaml/opam/issues/5800
=> Provide an install.ps1 PowerShell script to install opam on Windows

master_changes.md, release/readme.md, src/format/opamFile.ml, src/state/opamFormatUpgrade.ml, tests/reftests/opamroot-versions.test
Opening this in ahead of the final release so that the work has already been done and it's easy to merge.
backported into 2.2 in #6056
=> Bump opam-root-version to 2.2

master_changes.md, src/client/opamCliMain.ml, src/client/opamClientConfig.ml, src/client/opamCommands.ml, src/state/opamStateConfig.ml, src/state/opamStateConfig.mli
#5457 changed the signature of `OpamStateConfig.opamroot` between beta2 and beta3 which has broken the opam-dune-lint plugin along with a few other packages. This seems a shame, given that it's quite trivial and indeed natural to have two functions and simply have the provenance-returning version have a new name.
Given that ~~it looks like we'll need an rc2 to deal with the Cygwin hang~~it's a demonstrably safe internal API restoration, I'm hoping we can slip this API change in ~~at the same time~~to the final release. If we do, https://github.com/ocaml/opam-repository/pull/26066 can be reverted.
**Backported into 2.2 in #6058**
=> Restore signature of OpamStateConfig.opamroot

master_changes.md, src/state/opamSysInteract.ml
Fixes #6041 - an additional option might be to explicitly abort when run non-interactively as well, but it's getting a bit niche because if you're non-interactive and expecting depext to work with an external Cygwin then clearly you must have specified `--confirm-level unsafe-yes`.
**Backport into 2.2 in #6057**
=> Adjust common flags passed to Cygwin setup

master_changes.md, tests/reftests/legacy-git.test, tests/reftests/legacy-local.test
`head -c` is not posix-compliant, use `cut -b` instead.
=> Avoid head -c GNUism in reftests

master_changes.md, src/client/opamClient.ml
This at the moment sits on top of #6033. #6033 is a bug-fix and needs to go in 2.2.0 - the extra commit here follows a discussion last week with @kayceesrk regarding making `opam init -ya` to be potentially less confusing for students. In this mode, `opam init` looks more like:
```
C:\Users\David Allsopp>\\tau\devel\opam\opam init -ya
No configuration file found, using built-in defaults.
[NOTE] opam is storing files in C:\opamroot
<><> Windows Developer Mode <><><><><><><><><><><><><><><><><><><><><><><><>  🐫
opam does not require Developer Mode to be enabled on Windows, but it is
recommended, in particular because it enables support for symlinks without
requiring opam to be run elevated (which we do not recommend doing).
More information on enabling Developer Mode may be obtained from …
```
=> Suppress Windows-specific menus with `opam init -ya`

master_changes.md, release/Makefile, src_ext/Makefile
mccs was missing. Noticed in https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/68529
Backported in 2.2 by https://github.com/ocaml/opam/pull/6067
=> release: Fix the creation of the opam-full-<version>.tar.gz archive

master_changes.md, release/Makefile, src_ext/Makefile
Backport of https://github.com/ocaml/opam/pull/6066 for the 2.2 branch
=> [2.2 backport] release: Fix the creation of the opam-full-<version>.tar.gz archive

.github/scripts/depexts/generate-actions.sh, master_changes.md
Major ones:
* Fix centos by faking on with almalinux
* Fix conf-* packages install and check
* Add packages with `os-version` to check
* More caching in docker build
_I'll backport once green_
=> GHA: Several fixes on depexts workflow

master_changes.md, tests/reftests/dune.inc, tests/reftests/init.test
Update it to be no repo + add erroneous case where invariant got removed from install actions
=> reftests: updates on init test

master_changes.md, release/Dockerfile.in, release/Makefile, release/readme.md
Simplifies the release script and makes it less likely to have errors
Related to https://github.com/ocaml/opam/pull/6082 and https://github.com/ocaml/opam/pull/6083
Backported to 2.2 in https://github.com/ocaml/opam/pull/6085
=> Remove opam 2.1 support from the release script

master_changes.md, src/state/opamSysInteract.ml
dpkg-query output have the information in the first column, but only the second character needed to be looked up.
=> depext: fix Debian/apt lookup for installed packages

.ocp-indent
```
if ... then a else
b
```
A good portion of the code are indented to use this code pattern and this makes reading that code really hard to me. Forcing the indentation of `b` in the example above makes it much more readable, especially for large functions.
New indented code would look like:
```
if ... then a else
b
```
=> ocp-indent: disable unindented else block

release/Dockerfile.in, release/Makefile, release/readme.md, release/release.sh, release/sign.sh
This would allow us to use the release script as-is from the tag instead of from master. This would help reproducibility
See https://github.com/ocaml/opam/pull/6082
Backports https://github.com/ocaml/opam/pull/6084
=> [2.0 backport] Port the release script from master

release/Dockerfile.in, release/Makefile, release/readme.md, release/release.sh, release/sign.sh
This would allow us to use the release script as-is from the tag instead of from master. This would help reproducibility
Related to https://github.com/ocaml/opam/issues/5958
Backports https://github.com/ocaml/opam/pull/6084
=> [2.1 backport] Port the release script from master

master_changes.md, src/repository/opamDownload.ml, tests/reftests/download.test
Currently on system that have wget2 (e.g. Fedora 40), downloading archives do not work if wget is used.
Per wget2's man page:
```
--content-disposition
If this is set to on, experimental (not fully-functional) support for “Content-Disposition” headers is enabled.  This can currently result in extra round-trips to the server for a “HEAD” request, and is
known to suffer from a few bugs, which is why it is not currently enabled by default.
This option is useful for some file-downloading CGI programs that use “Content-Disposition” headers to describe what the name of a downloaded file should be.
```
I don't think we want to enable an experimental argument. Given we use `-O` already I'm not sure what the goal of it was.
This was original added 9 years ago in …
=> Add support for wget2

master_changes.md, src/client/opamAdminCommand.ml, tests/reftests/admin.test
`opam admin add-hashes` creates a cache that is actually stored under `~/.cache/hash-cache`. Move it in `<opamroot>/download-cache/hash-cache`.
=> admin hashes cache: move under opam root

.github/scripts/cygwin.cmd, master_changes.md, src/client/opamAdminCommand.ml, src/repository/opamRepository.ml, src/repository/opamRepository.mli, tests/reftests/admin-cache.test, tests/reftests/admin.test, tests/reftests/archive.test, tests/reftests/dune.inc, tests/reftests/extrasource.test
Fixes https://github.com/ocaml/opam/issues/6064
Backported in 2.2 by https://github.com/ocaml/opam/pull/6069
=> Add every listed checksums of a given archive to the cache when fetching from it

bench.Dockerfile, master_changes.md, tests/bench/bench.ml
Required for https://github.com/ocaml/opam/pull/6078 as it makes the new benchmarks stable enough to be merged.
=> Make the benchmark setup process faster and the benchmark itself more stable

master_changes.md, src/format/opamTypesBase.ml, src/format/opamTypesBase.mli, src/state/opamSwitchAction.ml, src/state/opamUpdate.ml
Related to https://github.com/ocaml/ocaml/pull/9928
=> Stop using polymorphic comparison when comparing switch_selections

bench.Dockerfile, master_changes.md, tests/bench/bench.ml, tests/bench/dune
This PR aims at showing whether or not https://github.com/ocaml/opam/pull/5518 actually improves performance.
The idea is similar to https://github.com/ocaml/opam/pull/5900
=> Add a benchmark showing the current performance of OpamVersionCompare

master_changes.md, src_ext/Makefile
Small fix for 2.1 only - the full tarball doesn't include the 0install solver. master/2.2 isn't affected by this.
=> Ensure all archives are retrieved in `make cache-archives`

Makefile, master_changes.md
Otherwise if for example `z3` is installed in your local switch `make cold` fails with:
```
Downloading vendored source dependencies...
done
Extracting vendored source dependencies in src_ext/... done
env PATH="`pwd`/bootstrap/ocaml/bin:$PATH" CAML_LD_LIBRARY_PATH= OCAML_TOPLEVEL_PATH= make
make[1]: Entering directory '/home/kit_ty_kate/work/opam'
src_ext/dune-local/dune.exe build --profile=release --root .  --promote-install-files -- opam-installer.install opam.install
File "src/solver/opamBuiltinZ3.ml", line 1:
Error: /home/kit_ty_kate/.opam/default/lib/z3/z3.cmi
is not a compiled interface for this version of OCaml.
It seems to be for a newer version of OCaml.
make[1]: *** [Makefile:146: build-opam] Error 1
make[1]: Leaving directory '/home/kit_ty_kate/work/opam'
make: *** …
```
=> Unset OPAM_SWITCH_PREFIX when using make cold

master_changes.md, tests/reftests/env.test
=> Reftest: add `build-env` overwrite predefined build env opam vars

master_changes.md, src/client/opamCommands.ml, src/client/opamSwitchCommand.ml, src/client/opamSwitchCommand.mli, tests/reftests/switch-import.test
Flag `--deps-only` for `opam import` that install only non root & compiler packages.
Fixes #5200
=> Add dependencies only switch import

master_changes.md, tests/reftests/clean.test
=> test: add sources directory cleaning test

master_changes.md, src/client/opamCommands.ml, tests/reftests/config.test
Supersedes https://github.com/ocaml/opam/pull/5799 as it was its original intent behind that PR.
I don't see a reason why `repositories` should only be shown when a switch is set, so this PR makes it so that it is always displayed.
=> Always list all the repositories in 'opam config report' regardless of whether or not a switch is currently set

master_changes.md, src/client/opamAction.ml, src/client/opamArg.ml, src/client/opamClientConfig.ml, src/client/opamClientConfig.mli, src/core/opamStd.ml, src/core/opamStd.mli, tests/reftests/dune.inc, tests/reftests/verbose-on.test
Implementation of #5331 
Add a `verbose-on=PACKAGES` parameters to build options. For the time being, it's equivalent to a simple `-v` for a list of package.
I'm not sure how I'd be able to simulate a modification of the opam file of a specific package to change add the verbose flag, so it's not exactly what #5331 asked for, however if there's a way I'd be glad to implement it!
=> Add a verbose-on option.

README.md, doc/pages/Manual.md, master_changes.md
Minor documentation update (README & User Manual) about version ordering in opam:
- Add a note to distinguish the version scheme used for the opam binary from that of user packages
- Add an example of how to execute the function implemented in opam for quick sanity checks
This follows a discussion in #6118 where I had some questions about this.
OCaml REPL snippet curtesy of @kit-ty-kate in https://github.com/ocaml/opam/issues/6118#issuecomment-2252387409_
=> doc: add brief note about version ordering and OCaml REPL example

master_changes.md, src/client/opamClient.ml, tests/reftests/deps-only.test
It was added in #4564, accidentally removed in #4975.
Backported in 2.2 in #6126
=> Fix regression: deps-only setting direct dependencies as root packages by default

.ocp-indent
Makes the indentation style switch from:
```ocaml
let () =
begin match x with
| Some _ -> ()
| None -> ()
end
```
to the more common:
```ocaml
let () =
begin match x with
| Some _ -> ()
| None -> ()
end
```
Some of our use of `begin match` already use this indentation style manually
=> ocp-indent: make sure 'begin match' doesn't add an extra indentation

master_changes.md, src/client/opamClient.ml, tests/reftests/dune.inc, tests/reftests/install-check.test
As the test show non-existing packages (or atoms requiring a version that does not exist yet for example) does not currently work when using `opam install --check`
=> Fix "opam install --check pkg" when pkg depends on a non-existing package

doc/pages/Install.md, master_changes.md
We forgot to update that page after the release of opam 2.2
=> Update the installation documentation after the release of opam 2.2

doc/pages/Manual.md, master_changes.md
The broken formatting is pretty apparent on the published docs currently: https://opam.ocaml.org/doc/Manual.html#Environment-update-portability
=> Fix markup for inline code in section on `Environment update portability`

master_changes.md, src/core/opamVersionCompare.ml
Test-case:
```ocaml
let ()
let x0 = Gc.stat () in
assert (OpamVersionCompare.compare "1.2.3" "1.02.3" == 0);
let x1 = Gc.stat () in
Printf.printf "minor_words: %.0f\n" (x1.minor_words -. x0.minor_words)
```
Before: minor_words: 156
After:  minor_words: 84
This just passes all the parameters to `loop` rather than getting them from the context. Then `loop` itself isn't needed.
Ideally, there would be no allocations at all. However, removing the others makes the code quite messy so I just did the easy change here.
See https://roscidus.com/blog/blog/2024/07/22/performance-2/#statmemprof for some real-world profiling of the CI solver service, showing this to be a problem.
=> Reduce allocations in opamVersionCompare

master_changes.md, src/core/opamVersionCompare.ml
~Doing so does, for example, speeds-up typical `opam show <pkg>` by 50%~
I also tried a completely new implementation of `OpamPackage.Version.compare` that would have sped-up the comparison function by 30% instead but doing so made `OpamPackage.Version.of_string` slower, as i was actually parsing the string first and pre-processed it so the comparison function is faster, but it wasn't worth it in the end.
~F.i.x.e.s. https://github.com/ocaml/opam/issues/5479 as it speeds-up switch loading time from 0.22s to 0.044s on my M1Pro.~
Related to https://github.com/ocaml/opam/issues/4245 (cc @emillon)
Requires #6078
=> Speedup OpamVersionCompare by 15%

.github/workflows/ci.ml, .github/workflows/depexts.yml, .github/workflows/main.yml, master_changes.md
Bump version for cache, checkout upload-artifact. 
Remove also ocaml-opam/cache use /cc @dra27 
~queued on #6079~
**Backport to 2.2 by #6087**
=> GHA: bump version of actions

master_changes.md, tests/bench/bench.ml
Benchmark made for https://github.com/ocaml/opam/pull/5317
=> Add a benchmark for opam list --installed on non-installed packages

master_changes.md, src/repository/opamRepository.ml, tests/reftests/download.test, tests/reftests/swhid.unix.test
In https://github.com/ocaml/opam/issues/4586#issuecomment-1018774363 we can see that to download an archive, opam currently does basically:
```
+ curl -L -o "${OPAM_SWITCH_PREFIX}/.opam-switch/sources/dune.2.9.1/dune-2.9.1.tbz.part" -- "${ARCHIVE}"
+ mv "${OPAM_SWITCH_PREFIX}/.opam-switch/sources/dune.2.9.1/dune-2.9.1.tbz.part" "${OPAM_SWITCH_PREFIX}/.opam-switch/sources/dune.2.9.1/dune-2.9.1.tbz"
+ mv "${OPAM_SWITCH_PREFIX}/.opam-switch/sources/dune.2.9.1/dune-2.9.1.tbz" "/tmp/opam-14-82d098/dune-2.9.1.tbz"
+ tar xfj /tmp/opam-14-82d098/dune-2.9.1.tbz -C /tmp/opam-14-1e6357
+ cp -PRp /tmp/opam-14-1e6357/dune-2.9.1/* /home/opam/.opam/4.13/.opam-switch/sources/dune.2.9.1
+ cp -PRp "${OPAM_SWITCH_PREFIX}/.opam-switch/sources/dune.2.9.1" "${OPAM_SWITCH_PREFIX}/.opam-switch/build/dune.2.9.1" …
```
=> Remove unnecessary copies/move when fetching archives

master_changes.md, src/client/opamCommands.ml, tests/reftests/switch-creation.test
`opam switch create foo --repos bar=[url]` should no longer require `git+` to be accepted. Consistent with `opam repository add`.
fixes #4673
=> Consistent accepted repository links 

master_changes.md, src/client/opamArgTools.ml, src/client/opamCLIVersion.ml
=> CLI: add 2.3 in supported versions

Makefile, master_changes.md, tests/reftests/dune.inc, tests/reftests/gen.ml, tests/reftests/run.ml
This is an attempt to have a generalization to filter arbitrarily reftests, with the main objective being having a command that run quickly locally.
The approach is to use custom-defined tags in the testfiles and injecting corresponding variable in the dune command environment (in a way that doesn't affect exisiting behavior). The lack of expressivity in dune files limits filter expressivity but I think this is good enough as a first step toward something we'd want to use more systematically.
Also, this makes tests summary more broadly available to other rules
=> Mechanism for reftests filtering

master_changes.md, src/repository/opamGit.ml, src/repository/opamRepository.mli, src/repository/opamRepositoryBackend.mli, src/repository/opamVCS.mli, tests/reftests/dune.inc, tests/reftests/fetch-package.test, tests/reftests/source.test
Backport of https://github.com/ocaml/opam/pull/6146 to the `2.2` branch
=> [2.2 backport] Disable shallow clone by default except for opam repositories

Makefile, master_changes.md
Opening https://github.com/ocaml/opam/pull/6154 made me realised that the reason `make reftest-gen` is slow is that we're removing `tests/reftests/dune.inc` which lists all the opam roots/opam repositories and tar.gz targets, so dune build will scan the directory and remove everything that it doesn't know about and given those targets are not defined anymore it will then remove everything.
Simply not emptying that file fixes the issue. If in the future we need to upgrade the syntax or whatever we can always remove that file manually and the error message should make it obvious. But in the meantime this change is extremely beneficial to the day-to-day development setup by not having to remove then re-download, unpack and recreate 5GB everytime that rule is called
=> Speedup "make reftest-gen"

master_changes.md, src/state/opamEnv.ml, tests/reftests/env.unix.test
Fixes https://github.com/ocaml/opam/issues/6158
I chose to keep in a single line instead of 2 just because we'd want to have it on a line starting with `# ` and i'm worried people would also copy the prefix when copy/pasting
=> Make the shell environment update hint easier to copy/paste

.github/scripts/main/preamble.sh, master_changes.md, src/repository/opamGit.ml, tests/reftests/dune.inc, tests/reftests/git.test
Fixes https://github.com/ocaml/opam/issues/6131
=> Fail when a git submodule fails to update instead of ignoring the error

master_changes.md, src/client/opamClient.ml, src/client/opamClient.mli, src/client/opamCommands.ml, src/format/opamFormula.ml, src/format/opamFormula.mli, tests/reftests/install-check.test
Fixes https://github.com/ocaml/opam/issues/6097
Queued on top of #6121 
Queued on https://github.com/ocaml/opam/pull/6123
=> Make "opam install --check" check if all dependencies are installed recursively

master_changes.md, release/Dockerfile.in
Would prepend the output of the configure script before.
Fixes https://github.com/ocaml/opam/issues/6174
Backported to 2.2 in https://github.com/ocaml/opam/pull/6175
Backported to 2.1 in https://github.com/ocaml/opam/pull/6177
Backported to 2.0 in https://github.com/ocaml/opam/pull/6178
=> release: fix the docker phase

master_changes.md, release/Dockerfile.in
Backports https://github.com/ocaml/opam/pull/6175
=> [2.1 backport] release: fix the docker phase

master_changes.md, src/core/opamSystem.ml, tests/lib/patcher.expected
This has sadly been wrong since #3349 was fixed in #3449 (which equates to "it's always been wrong", as that was during 2.0.0's dev cycle).
Patches require transformation to deal with line-endings - patch can cope with patching CRLF files, but the diff needs to have the same line-endings as the files. Prior to applying a patch, `OpamSystem.translate_patch` checks the files to which the diff is being applied and transforms the patch. If no transformations are needed (which is pretty much always - most release tarballs use Unix line-endings, even on Windows), then the patch is simply copied.
The process works fine, except for a teeny detail. Owing to a badly made logging transformation in #3449, the transformation was only written to the patch file if debugging mode was enabled 🤦
On …
=> Fix highly embarrassing mistake in patch transformation

master_changes.md, src/client/opamCommands.ml, tests/reftests/cli-versioning.test, tests/reftests/config.test, tests/reftests/list-large-dependencies.test, tests/reftests/switch-invariant.test, tests/reftests/switch-list.test
Fixes https://github.com/ocaml/opam/issues/5491
=> Make opam config report and opam switch set-invariant return the actual invariant syntax expected by --invariant

master_changes.md, src/core/opamSystem.ml, tests/lib/patcher.expected
Reverts ocaml/opam#6183
After discussion, since the new release cycle is now shorter we would like to reserve the backports to regressions and security fixes.
=> Revert "[2.2 backport] Fix highly embarrassing mistake in patch transformation"

master_changes.md, src/format/opamFile.ml, tests/reftests/lint.test, tests/reftests/pin.test
Fixes #6188 and addresses the note in https://github.com/ocaml/opam/pull/5665#discussion_r1742278703
=> Return parse errors for 2.2/2.3 formats

master_changes.md, src/format/opamFile.ml, src/format/opamPp.ml, src/format/opamPp.mli, src/state/opamFileTools.ml, tests/reftests/pin.test, tests/reftests/repository.test
Fixes https://github.com/ocaml/opam/issues/5631
This makes it possible to have a smoother upgrade path for the opam repository when opam adds a new syntax for example.
In the future it would be nice to have a specific error message to tell the user why this package is not available, but I feel like we can do this later (TODO: open a ticket for it if this is merged first)
=> Silently mark packages requiring an unsupported version of opam as unavailable

master_changes.md, release/Dockerfile.in
~Follow-on from #5381 - it can't actually be removed until the release scripts stop being used for 2.2 and older.~
Following the merge of https://github.com/ocaml/opam/pull/5381 this workaround is no longer needed
=> Remove the getgroups workaround allowing users belonging to more than 32 groups

doc/pages/Manual.md, master_changes.md, src/client/opamPinCommand.ml, src/state/opamFileTools.ml, src/state/opamFileTools.mli, src/state/opamUpdate.ml, tests/reftests/admin.test, tests/reftests/extrafile.test, tests/reftests/legacy-git.test, tests/reftests/legacy-local.test, tests/reftests/lint.test, tests/reftests/readme.md, tests/reftests/reftests.test, tests/reftests/repository.test, tests/reftests/run.ml
Current behaviour is at lint stage, if an extra-files is found in `files` directory, but not in the opam file, it is added in the opam file automatically.
This behaviour is removed, all extra-files need to be declared in opam file.
/cc @hannesm @reynir
=> Stop populating opam file with extra-files

doc/pages/Install.md, master_changes.md
At present this is a redirection to the same script on github
See https://github.com/ocaml-opam/opam2web/pull/241
=> Documentation: Update the command to install opam to point to the new simplified url on opam.ocaml.org

master_changes.md, src/client/opamPinCommand.ml, tests/reftests/fetch-package.test, tests/reftests/pin.test, tests/reftests/rec-pin.test
**Backported in 2.3 with  #6222**
The origin of the issue is from the magic to retrieve the opam file even if it is not committed added in #4300. To do that, the local vcs url was changed to local rsync, in order to get all source not only committed files. In the next synchronisation, as opam file contains the vcs url, the synchronisation fixed that anomaly.
Fix #5809
~~Queued on #6135~~
=> Pin: fix first local vcs fetch rsyncing all source

master_changes.md, src_ext/Makefile.dune, src_ext/Makefile.sources, tests/reftests/repository.test
Backport of https://github.com/ocaml/opam/pull/6223
=> [2.3 backport] Update the vendored dependencies and unlock OCaml 5.3 compatibility

master_changes.md, src/core/opamStd.ml
Split off from https://github.com/ocaml/opam/pull/6217
Fixes https://github.com/ocaml/opam/issues/6215
with_process_in was fairly brittle and would display stderr by default and ignore errors. The new version of that function (renamed process_in) now uses Unix.open_process_full and returns None if anything went wrong, fixing the issue on OpenBSD where `getconf LONG_BIT` would fail.
Backported to 2.3 in https://github.com/ocaml/opam/pull/6228
=> System polling: Harden the process calls to account for failure

master_changes.md, src/core/opamStd.ml
`with_process_in` was fairly brittle and would display stderr by default and ignore errors. The new version of that function (renamed `process_in`) now uses `Unix.open_process_full` and returns None if anything went wrong, fixing the issue on OpenBSD where `getconf LONG_BIT` would fail (End_of_file wasn't handled)
Backports https://github.com/ocaml/opam/pull/6230 to 2.3
=> [2.3 backport] System polling: Harden the process calls to account for failure

master_changes.md, src/client/opamSolution.ml, tests/reftests/cache.test, tests/reftests/dune.inc
Upgrades from 2.2 to 2.3 can trigger issues where a repository forgot to add the missing extra-files field.
opam tells the user they should upgrade as the opam file changed (as extra-files was added automatically), then the build fails and upon fixing the error, opam still says the package is to be rebuilt because the previous version of the opam file was stored in the install cache.
This should be backported to the 2.3 branch as it can easily be triggered during the upgrade from 2.2 to 2.3.
Backported to 2.3 via https://github.com/ocaml/opam/pull/6214
Potentially related to https://github.com/ocaml/opam/pull/5922
=> Fix the install cache storing the wrong version of the opam file after a build failure

master_changes.md, src/core/dune, src/core/opamCommonStubs.c, src/core/opamStd.ml, src/core/opamStubs.mli, src/core/opamStubs.unix.ml, src/core/opamUnix.c, src/core/opamWin32Stubs.win32.ml
Fixes #6243 
Tested on:
- Linux/glibc
- Linux/musl
- macOS
- FreeBSD
- OpenBSD
- NetBSD
- Cygwin
Can't test:
- DragonFlyBSD (they package manager just crashes after an update), however given DragonFlyBSD derives from FreeBSD, there is no doubt to guess it would work just the same.
- MSYS2 (i couldn't find the way to build an opam targeting msys2 instead of Windows, but like DragonFlyBSD, MSYS2 is a fork of Cygwin so it should just work)
The only change of behaviour between the code previous to #6230 and this one is that prior it would default to 80 column only if you had all 3 (stdout, stdin, stderr) redirected, but now it would default to it if only stdout is redirected, which i think is an improvement.
Backported to 2.3 in https://github.com/ocaml/opam/pull/6246
=> Fix the detection of the current terminal size

.github/scripts/main/main.sh, .github/scripts/main/preamble.sh, .github/workflows/ci.ml, .github/workflows/main.yml, master_changes.md
Generation of documentation with `make doc`
=> GHA: add doc job

doc/pages/Install.md, master_changes.md, release/Dockerfile.in, release/Makefile, release/readme.md, release/release.sh
Fixes #6007 
Fixes #6232 (although looses support for OpenBSD 7.5, which is EOL only in 6 months)
Forward-ported to master by #6242
=> [2.3] Release script improvements after 2.3.0~beta1

release/Makefile, release/release.sh
Successfully built during the 2.3.0~beta2 release
Forward-ported to master in https://github.com/ocaml/opam/pull/6259
=> [2.3] Release script: Add NetBSD/x86_64 to the build matrix

release/readme.md, release/windows.md
This change helps release faster and with less stress
=> Reorder the release steps

master_changes.md, src/client/opamArg.mli, src/client/opamArgTools.ml, src/client/opamArgTools.mli, src/client/opamCLIVersion.ml
=> Add cli version for 2.4

doc/man/opam-admin-topics.inc, master_changes.md, src/client/opamAdminCommand.ml, src/format/opamFormula.ml, src/format/opamFormula.mli, tests/reftests/admin.test
Add a new CLI `opam admin compare-versions` to compare package versions for sanity checks.
This command has 2 modes:
1. By default - user interactive.
In this mode, we provide two versions, and opam outputs a user-friendly expression with the result of the comparison, spelled out. For example:
```sh
$ opam admin compare-versions 0.0.9 0.0.10
0.0.9 < 0.0.10
```
The command exits 0 regardless of the result of the comparison.
2. For use in scripts - if needed. Provide an optional operator { --eq, --geq, --gt, --leq, --lt, --neq }
In this mode, the output is suppressed (the command is silent). The result of the command will be encoded in the exit code, to be used in bash conditionals:
exit 0: the comparison holds
exit 1: it doesn't
For example:
```sh
$ opam admin compare-versions 0.0.9 --lt …
```
=> Add an admin command to compare 2 package versions (named operators)

master_changes.md, src/client/opamClient.ml, tests/reftests/avoid-version.test, tests/reftests/deprecated.test, tests/reftests/init.test, tests/reftests/install-formula.test, tests/reftests/switch-invariant.test, tests/reftests/upgrade-two-point-o.test
Fixes https://github.com/ocaml/opam/issues/6270 and also the confusing message about `--verbose` when it is unnecessary.
=> Improve the messages when a package is not up-to-date on opam upgrade

CHANGES, release/readme.md
Ports parts of https://github.com/ocaml/opam/pull/6279
=> Port missing changelog from the 2.3 branch and improve release steps

.github/scripts/main/main.sh, .github/workflows/ci.ml, .github/workflows/main.yml, master_changes.md, src/client/opamCommands.ml, src/client/opamPinCommand.ml, tests/reftests/pin.test, tests/reftests/rec-pin.test, tests/reftests/switch-import.test
Implementation of issue #5533 
It works, but I'm not sure it's the best way to do it
=> Make it so pin list display the current revision of the pinned repo

doc/pages/Manual.md, master_changes.md
As discussed with @kit-ty-kate. It would for sure make sense to add version information on more fields in the documentation. But for me that is pretty tedious since I'd have to manually look every field up. I'll do when I dig around more fields. But maybe someone else has the stamina to go through the entire manual.
=> Manual: add information when flags (avoid-version, deprecated) were introduced

master_changes.md, src/core/opamCommonStubs.c, src/core/opamStd.ml, src/core/opamStd.mli, src/core/opamStubs.mli, src/core/opamStubs.unix.ml, src/core/opamStubsTypes.ml, src/core/opamUnix.c, src/core/opamWin32Stubs.win32.ml, src/state/opamSysPoll.ml
~Queued on top of #6216~
~F.i.x.e.s #6215~
~For the backport to 2.3, do we want to backport the entire PR or just the OpenBSD fix?~
~Partially backported to 2.3 in https://github.com/ocaml/opam/pull/6228~
~Queued on #6230~ merged
=> Use a C stub to call the uname function from the C standard library instead of calling the uname POSIX command

.github/scripts/main/hygiene.sh, .github/workflows/ci.ml, .github/workflows/main.yml, master_changes.md, shell/install.sh
This is a partial subset of https://github.com/ocaml/opam/pull/5778.
This PR is meant as a way to more easily kickstart the use of shellcheck to lint checkout shell scripts.
Details of reason behind the shell changes:
* [SC2006](https://www.shellcheck.net/wiki/SC2006): `$()` vs backticks
* [SC2268](https://www.shellcheck.net/wiki/SC2268): The x-prefix is actually unnecessary
* POSIX shell doesn't support `local`
* [SC2145](https://www.shellcheck.net/wiki/SC2145): `$@` in strings
* missing quotes
* [SC2162](https://www.shellcheck.net/wiki/SC2162): `read` without `-r` will interpret backslashes
* variables inside the format string for `printf` could contain `%` which could make the command fail
This PR also make sure the script keeps passing `shellcheck` by adding it to our CI.
=> Run shellcheck on shell/install.sh and make it pass, add a CI job to check next changes

master_changes.md, src/client/opamCommands.ml, tests/reftests/switch-list-available.test
Required for #6186 
Giving several arguments would never have given any results before. Furthermore it now matches the behaviour of `opam list`
=> Fix opam switch list-available when given several arguments

master_changes.md, src/client/opamCommands.ml, tests/reftests/switch-list-available.test
Adresses #6152 
Queued on #6318
=> Fix `opam switch list-available pkg.version` pattern

.gitignore, master_changes.md, src/core/opamFilename.ml, src/core/opamFilename.mli, src/core/opamSystem.ml, src/core/opamSystem.mli, src/repository/opamDownload.ml, tests/reftests/download.test, tests/reftests/swhid.unix.test
* Fix archive cooking request for `wget`, the wrong option was given
* Fix SWH liveness check, no POST request. It is a hidden bug, it was failing with no error code for curl and as wget had the wrong POST request option it wasn't showing.
* Update SWH API request: [`vault/directory`](https://archive.softwareheritage.org/api/1/vault/directory/doc/) is deprecated in favor to [`vault/flat`](https://archive.softwareheritage.org/api/1/vault/flat/doc/)
* Some doc
fixes #5721
=> Software Heritage fallback fixes

master_changes.md, src/state/shellscripts/bwrap.sh, src/state/shellscripts/sandbox_exec.sh
Users can set `DUNE_CACHE_ROOT`, which has a higher priority than other environment variables.
Currently, there are some cases where the cache functionality does not work well when `DUNE_CACHE_ROOT` is set.
Ref: https://dune.readthedocs.io/en/stable/caching.html
=> sandbox: respect the `DUNE_CACHE_ROOT` environment variable if it exists

master_changes.md, src_ext/Makefile, src_ext/Makefile.sources
now depends on menhir instead of ocamlyacc.
Requires https://github.com/ocaml/opam-file-format/pull/60
=> Upgrade to opam-file-format 2.2.0~alpha1

.github/scripts/main/main.sh
Backported to 2.3 in #6337 
Currently our Github Action script uses either opam-rt's master branch or a branch with the same name as the source branch. Obviously when a change to opam-rt is required between master and a backport branch such as 2.3, master becomes only available for opam master and the backport PRs will start failing.
This PR fixes this by simply looking up if the name of the target branch is available in the opam-rt repository and use that instead.
=> Fix GHA when opam-rt uses a diverging API

.github/scripts/main/main.sh
Backport of https://github.com/ocaml/opam/pull/6336 in the 2.3 branch
=> [2.3 backport] Fix GHA when opam-rt uses a diverging API

doc/pages/Install.md, master_changes.md
This was added to the ocaml install instructions in: https://github.com/ocaml/ocaml.org/pull/2658
=> docs: Add winget command for installing opam

master_changes.md, src/client/opamAdminCheck.ml, tests/reftests/admin.test
Backport of https://github.com/ocaml/opam/pull/6331 to the 2.3 branch
Queued on #6337
=> [2.3 backport] Fix opam admin check in the presence of the with-dev-setup variable

master_changes.md, src/state/shellscripts/bwrap.sh
Upstreams changes from https://github.com/NixOS/nixpkgs/pull/363770
The issue is that in the bubblewrap sandbox `/run` is mounted as tmpfs so its content is emptied inside the sandbox and Nix makes use of `/run/current-system/sw` to store the whole system (everything symlinks to it if i understand correctly).
cc @RyanGibb just in case you can tell me if i've done/said something awful
=> Fix sandboxing support in NixOS

bench.Dockerfile, master_changes.md, tests/bench/bench.ml
This PR is meant to show the performance gain from https://github.com/ocaml/opam/pull/6210
=> Add benchmarks for opam show and String.split

.github/workflows/ci.ml, .github/workflows/main.yml, master_changes.md, src/core/opamStd.ml
this cuts the time spent on parsing `pacman -Si` significantly down
Commit by @c-cube split from https://github.com/ocaml/opam/pull/5757
Queued on #6212
=> perf: optimize OpamString.split

.github/workflows/ci.ml, .github/workflows/main.yml, master_changes.md, src/client/opamInitDefaults.ml, src/core/opamSystem.ml, tests/lib/patcher.ml, tests/reftests/repository.test
Homebrew changed behaviour in Homebrew/homebrew-core#174687
~This is only an optimization (avoids the (probably) unnecessary `patch --version`), this doesn't change the general behaviour at all.~
EDIT: actually nevermind, this changes the behaviour in case, neither `patch` or `gpatch` are available and GNU patch. In that case, it would default to use `patch`, but now it will use `gpatch` by default. Which means that if someone hasn't installed gpatch, previously it would show a warning and used `patch` anyway, but now it will show a warning and fail to execute `gpatch`.
=> Lookup at gpatch before patch on macOS now that both homebrew and macports expose gpatch as gpatch

master_changes.md, src/client/opamCommands.ml, src/client/opamRepositoryCommand.mli, tests/reftests/repository.test
=> Check that the repositories given to "opam repository remove" actually exist

doc/pages/Install.md, master_changes.md
Arch Linux community repo was merged into extra repo:
https://archlinux.org/news/git-migration-announcement/
=> Docs: Fix broken link to non-existing community repo

.github/scripts/depexts/generate-actions.sh, .github/workflows/depexts.yml, master_changes.md
See https://github.com/ocaml/opam-repository/pull/27249
The gentoo job goes from 16m to 10m
=> GHA: Fix the alpine depexts test + speedup gentoo

master_changes.md, src/state/opamSysInteract.ml
uses the whole list of installed packages for depext, and not only the packages  manually installed.
=> depext: relax OpenBSD lookup for installed packages

master_changes.md, src/client/opamCommands.ml, src/client/opamListCommand.ml, src/core/opamConsole.ml, src/core/opamConsole.mli
Example of the new output with `opam show ocaml-base-compiler`:
Fixes #6354, probably the less intrusive solution if the color scheme works for you. Compared to removing them completely as suggested in the ticket, it brings an issue of clarity of meaning between what yellow or red means, although this concern seems pretty minimal to me compared to the other UX concerns brought by a potential addition of `--all`.
=> Display the version number of packages flagged with avoid-version/deprecated gray

shell/install.sh
It should be super simple and quick to install opam on various Linux distros and macOS. Some of the targeted OSes might not have the bash command needed for the invocation
```
bash -c "sh <(curl -fsSL https://raw.githubusercontent.com/ocaml/opam/master/shell/install.sh)"
```
Instead, `install.sh` should be invokable via
```
curl -fsSL https://raw.githubusercontent.com/ocaml/opam/master/shell/install.sh | sh
```
However, a problem with that is that, when piping the downloaded script into `sh`, `/dev/tty` is not connected, so we cannot read from stdin.
This patch remedies this issue by changing `install.sh` to explicitly `read` from `/dev/tty`. It also factors out the prompting into a function `prompt`.
Note: if any of the other commands called by `install.sh` require user interaction via …
=> explicitly connect /dev/tty. Allows running via sh

.github/scripts/main/ocaml-cache.sh, .github/workflows/ci.ml, .github/workflows/lib.ml, .github/workflows/main.yml, master_changes.md, src_ext/Makefile.dune, src_ext/Makefile.sources
Split off from https://github.com/ocaml/opam/pull/6189 as OCaml 5.3 is not released yet and contains several issues such as incompatibility with C++ (https://github.com/ocaml/ocaml/issues/13422) and Cygwin (https://github.com/ocaml/ocaml/issues/13421)
=> GHA: Add OCaml 5.3 to the build matrix

.github/scripts/main/test.sh, master_changes.md
Adds a custom test for the issue fixed in https://github.com/ocaml/opam/pull/5662
=> GHA: Make sure opam init works in the absence of OPAMROOT

master_changes.md, src/client/opamPinCommand.ml, tests/reftests/assume-built.test, tests/reftests/autopin.test, tests/reftests/config.test, tests/reftests/conflict-resto.test, tests/reftests/fetch-package.test, tests/reftests/inplace.test, tests/reftests/json.unix.test, tests/reftests/list-large-dependencies.test, tests/reftests/lock.test, tests/reftests/pin-legacy.test, tests/reftests/pin.test, tests/reftests/rec-pin.test, tests/reftests/switch-import.test, tests/reftests/tree.test, tests/reftests/update-upgrade.test, tests/reftests/upgrade.test, tests/reftests/working-dir.test
Fixes https://github.com/ocaml/opam/issues/3199
While reading https://github.com/ocaml/opam/issues/3199 i asked myself why this question was asked and i couldn't find any reason. It was added in https://github.com/ocaml/opam/pull/1335 with no reasoning behind it either.
In my opinion the question is redundant as the user is already asking to pin the package(s).
=> Don't ask confirmation when pinning a new package

master_changes.md, tests/reftests/download.test
Example of random failure: https://github.com/ocaml/opam/actions/runs/13137623611/job/36656730451?pr=6273
```
diff --git a/_build/default/tests/reftests/download.test b/_build/default/tests/reftests/download.out
File "tests/reftests/download.test", line 1, characters 0-0:
"C:\Program Files\Git\cmd\git.exe" --no-pager diff --no-index --color=always -u --ignore-cr-at-eol _build/default/tests/reftests/download.test _build/default/tests/reftests/download.out
Command exited with code 1.
index c01c510..e2a08c0 100644
--- a/_build/default/tests/reftests/download.test
+++ b/_build/default/tests/reftests/download.out
@@ -262,7 +262,6 @@ SYSTEM                          mkdir ${OPAMTMP}
Processing  1/1: [baz.1: http]
+ wget "--header=Accept: */*" "-t" "3" "-O" "${OPAMTMP}/v1.0.0.tar.gz.part" "-U" …
```
=> Make sure download.test does not fail due to a checksum collision in the download cache

master_changes.md, src/client/opamClient.ml, tests/reftests/avoid-version.test, tests/reftests/deprecated.test, tests/reftests/upgrade.test
Fixes https://github.com/ocaml/opam/issues/6271
=> opam upgrade: Do not show the not-up-to-date message with packages tagged with avoid-version

doc/pages/Tricks.md, master_changes.md, src/client/opamArg.ml, src/client/opamClientConfig.mli, src/solver/opamBuiltin0install.ml, src/solver/opamBuiltinMccs.dummy.ml, src/solver/opamBuiltinMccs.real.ml, src/solver/opamBuiltinZ3.dummy.ml, src/solver/opamBuiltinZ3.real.ml, src/solver/opamCudf.ml, src/solver/opamCudfSolver.ml, src/solver/opamCudfSolverSig.ml, src/solver/opamSolverConfig.ml, src/solver/opamSolverConfig.mli
Partially fixes https://github.com/ocaml/opam/issues/5504
Partially fixes https://github.com/ocaml/opam/issues/3447
Partially fixes https://github.com/ocaml/opam/issues/5353
Partially fixes https://github.com/ocaml/opam/issues/4794
Fixes https://github.com/ocaml/opam/issues/3230
Requires https://github.com/AltGr/ocaml-mccs/pull/40
Optimizing solvers can be an annoying breed, sometimes a problem is just too complex for solver A but easy for solver B, and on some other problem solver B might take too long where solver A takes no time at all.
To partly solve the numerous timeout issues that have been plagued opam, I introduce this new environment variable that allows `builtin-mccs+glpk` (default solver) to not wait around for too long when it found a solution but the solution is not the …
=> Add the OPAMSOLVERTOLERANCE environment variable to allow users to fix solver timeouts for good

master_changes.md, src/client/opamAuxCommands.ml
=> Do not ask to install pin-depends twice

master_changes.md, src/client/opamClient.ml, tests/reftests/upgrade.test
Regression introduced in 4db0c139ce184e7f49bdde63c8ffb6dbd1bb87d4, which is
dedicated to a different case (functionality of this patch is preserved)
=> Fix regression on 'opam upgrade <package>' upgrading unrelated things

master_changes.md, src/client/opamClient.ml, src/client/opamSolution.ml, src/core/opamConsole.ml
Supersedes https://github.com/ocaml/opam/pull/6290
This implements https://github.com/ocaml/opam/pull/6289#pullrequestreview-2428097616
=> Do not pre-write the answer to questions with the default anwser

.github/scripts/cygwin.cmd
diffutils 3.11 is broken and should not be used. This causes problems in our `patcher` test:
```
diff --git a/_build/default/tests/lib/patcher.expected b/_build/default/tests/lib/patcher.output
index 8164fa1..bc5074d 100644
--- a/_build/default/tests/lib/patcher.expected
+++ b/_build/default/tests/lib/patcher.output
@@ -2,11 +2,9 @@ PATCH                           No CRLF adaptation necessary for b/always-crlf
PATCH                           No CRLF adaptation necessary for b/always-lf
PATCH                           CRLF adaptation skipped for b/no-eol-at-all
PATCH                           No CRLF adaptation necessary for b/no-eol-at-eof
-PATCH                           CRLF adaptation skipped for b/null-file
PATCH                           No CRLF adaptation necessary for b/test1
PATCH …
```
=> GHA: Avoid the broken diffutils 3.11 release

master_changes.md, src/client/opamListCommand.ml, src/client/opamSwitchCommand.ml, src/state/opamGlobalState.ml, src/state/opamRepositoryState.ml, src/state/opamStateConfig.ml, src/state/opamStateConfig.mli, src/state/opamSwitchState.ml, src/state/opamSwitchState.mli
Fixes https://github.com/ocaml/opam/issues/5487
The current code shows issues with our internal uses of such functions, opening as a draft for now and I will point out where the issues are.
=> [API] Make the ?lock_kind parameters non-optional to avoid breaking the library users after they upgrade their opam root

master_changes.md, src/client/opamLockCommand.ml, tests/reftests/lock.test
=> lock: fix pin-depends with `with-` variables

master_changes.md, src/state/opamFileTools.ml, tests/reftests/lint.test
fix #5795
This lint doesn't detect when the versions mismatch.
=> lint: add W74 to detect 'pin-depends' packages that are not present in 'depends' nor in 'depopts'

master_changes.md, src/client/opamInitDefaults.ml, tests/reftests/init.test
Fixes #3509
I don't think having `ocaml-system` in the list of default compiler is a good choice.
Most platforms actually won't work if you installed the `ocaml` package alone. They usually all require some sort of extra `ocaml-compiler-libs` to be complete and not end up in very confusing error messages for new users.
System compilers are also not tested in the CI for opam-repository as of today (see https://github.com/ocurrent/opam-repo-ci/issues/327) and end up breaking packages from time to time.
Experienced developers can always use `opam init -c ocaml-system` if they really want a system compiler and `ocaml-system` can always be installed explicitly later if needed, but as a default for everyone it seems to brittle to me.
=> Remove ocaml-system from the list of default compilers used during opam init

master_changes.md, src/core/opamProcess.ml
On Windows, "negative" exit codes are probably `NTSTATUS` values. For example, if a program accesses an invalid memory location, Unix sends a `SIGSEGV` signal which, if unhandled, will terminate the process (setting some kind of non-zero exit code - for example, Linux sets the exit code to 128 + signal number to give a fairly memorable 139). In the equivalent scenario, Windows throws an `EXCEPTION_ACCESS_VIOLATION` which, if handled by the default exception handler, will terminate the process with exit code `STATUS_ACCESS_VIOLATION`. These codes are large negative numbers, which are not terribly memorable in decimal, so for negative exit codes we instead display them in hexadecimal as `0xc0000005` is slightly more memorable than `-1073741819`.
These exit codes can also occur if an …
=> Display Windows `NTSTATUS` exit codes in hex

master_changes.md, src/client/opamCommands.ml, src/client/opamLockCommand.ml, src/client/opamLockCommand.mli, tests/reftests/lock.test
=> lock: add '--keep-local' argument to add local pins to 'pin-depends:' field

master_changes.md, src/client/opamListCommand.ml, src/core/opamStd.ml, src/core/opamStd.mli
Queued on https://github.com/ocaml/opam/pull/5488
Reasoning to avoid polymorphic comparison functions in https://github.com/ocaml/ocaml/pull/9928
=> Avoid polymorphic comparison functions in OpamListCommand

master_changes.md, src/client/opamAuxCommands.ml, tests/reftests/pin.test
Force the version constraint on requested package when a simulate pin is done.
See explanation in https://github.com/ocaml/opam/issues/6379#issue-2836236793
Fixes https://github.com/ocaml/opam/issues/6379
Fixes https://github.com/ocaml/opam/issues/6248
~This PR is queued on top of #6209~
~The current title is temporary while i'm trying to understand what is the cause of the bug~
~I'm really confused as to what is making the made-up test work just fine but the test with goblint fail.~
~I'd like to understand what is making opam get almost all the dependencies but miss `ppx_blob` in the first deps-only install.~
~Ideally once we understand what's happening we should be able to build a dedicated test and remove the one relying on opam-repository~
=> Ensure the right versions of packages are used when simulating pinning

master_changes.md, tests/reftests/lock.test
The change in lock test is needed for #6319.
Queued on 
edit: 
* untied from #6409 
* No more in the PR: While changing the test, i found the bug with git `remote get-url`, which is specific to `opam lock` handling, extracted in #6422
=> reftest: untie lock test from OPAMEDITOR hack, and fix lock VCS remote detection

.github/workflows/ci.ml, .github/workflows/main.yml, configure, configure.ac, master_changes.md, opam-core.opam, opam-repository.opam, src/client/opamAction.ml, src/client/opamAction.mli, src/client/opamInitDefaults.ml, src/core/dune, src/core/opamFilename.ml, src/core/opamFilename.mli, src/core/opamSystem.ml, src/core/opamSystem.mli, src/repository/dune, src/repository/opamHTTP.ml, src/repository/opamLocal.ml, src/repository/opamRepository.ml, src/repository/opamRepositoryBackend.ml, src/repository/opamRepositoryBackend.mli, src_ext/Makefile, src_ext/Makefile.sources, tests/lib/dune, tests/lib/patchDiff.expected, tests/lib/patchDiff.ml, tests/reftests/repository.test, tests/reftests/update.test
Fixes https://github.com/ocaml/opam/issues/6019
Fixes https://github.com/ocaml/opam/issues/3782 by removing any handling of chmod entirely (git extensions). Every patched files keep their permissions and every new file has the default file permission (644).
Fixes https://github.com/ocaml/setup-ocaml/pull/933
Fixes #6052
see #5891 
A large amount of work was necessary in the `patch` library to make this work. See https://github.com/hannesm/patch/pull/9, https://github.com/hannesm/patch/pull/7 and especially https://github.com/hannesm/patch/pull/22
Moving the logic of `OpamSystem.translate_patch` into `patch` can be done later. Possibly during the 2.4 alpha phase.
The 2.4 alpha phase will also serve to test this new version of patch (3.0.0), once it has been sufficiently tested the stable …
=> Replace every use of GNU Patch by the OCaml patch library

master_changes.md, src/client/opamSolution.ml, tests/reftests/dune.inc, tests/reftests/keep-build-dir.test
Fixes https://github.com/ocaml/opam/issues/4255 for good
Partially f.i.x.e.s https://github.com/ocaml/opam/issues/5448
Reasoning:
The build directory is cleared anyway before each builds and is available in `sources` already so keeping it around doesn't have any purpose and only wastes precious disk space.
=> Do not keep the build directory of the pinned packages

master_changes.md, src/client/opamAuxCommands.ml, src/client/opamClient.ml, src/format/opamFile.ml, tests/reftests/pin.test, tests/reftests/show.test, tests/reftests/working-dir.test
Fixes https://github.com/ocaml/opam/issues/5567
Fixes https://github.com/ocaml/opam/issues/4507
Queued on #6438 
I have no idea why `for_view` was introduced in https://github.com/ocaml/opam/commit/9b2a67f36d9d0e20b734ff85ddef470268aabb25 but i've tested `opam show` and i'm not seeing any breaking nor does the testsuite.
The bypass here was causing local packages to be put in the `already_pinned` set. However this set is only used to update the `<switch>/.opam-switch/sources/<pkg>` directory, not the `<...>/overlay` directory as the assumption with this set is that the package description hasn't change.
Removing that bypass makes the function much more consistent.
The `reinstall` bit is a bit easier to understand: when using `--deps-only` or `--show-action`, the codepath goes through …
=> Fix opam install on a local directory not updating pinned packages' metadata

master_changes.md, src/client/opamPinCommand.ml, tests/reftests/pin.test
Closes https://github.com/ocaml/opam/issues/6322
This could happen with things like `opam pin <typo> <url>` or a typo in the `pin-depends` definition.
The interactive edition based on the dummy opam file template is now only allowed if the user is purposefully requesting it using `--edit` or `opam pin edit`.
=> Fail when trying to pin a package whose definition could not be found instead of forcing interactive edition

master_changes.md, src/client/opamSolution.ml, src/state/opamSysInteract.ml, src/state/opamSysInteract.mli
opam only look at `os-distribution` to know if it should download Cygwin's `setup.exe` or not:
https://github.com/ocaml/opam/blob/1458aa74921cd71b8a0f0182de308bd06e7146a6/src/client/opamSolution.ml#L1222
https://github.com/ocaml/opam/blob/1458aa74921cd71b8a0f0182de308bd06e7146a6/src/client/opamSolution.ml#L1254
The tests have been failing quite frequently over the past two days due to some network issues with `cygwin.com`. Setting `os-distribution` to not be `cygwin` should alleviate this.
=> Only download Cygwin's setup.exe when the command is actually going to be displayed or used

master_changes.md, src/state/opamSysInteract.ml
Split off of https://github.com/ocaml/opam/pull/6431
See https://github.com/ocaml/opam/pull/6431#issue-2944043215 for explanation
=> Disable the detection of available system packages on SUSE-based distributions

README.md, master_changes.md
It's obsolete, a no-op, and its semantics are not even specified.
> `(no)dosfilewarning` - This option had been disabled for quite some
>                        time and nobody missed it.
=> Don't suggest setting the `nodosfilewarning` option of `CYGWIN`

.github/scripts/main/ocaml-cache.sh, .github/workflows/ci.ml, .github/workflows/main.yml, master_changes.md
This cache was broken during the switch from `ocaml-opam/cache` to `actions/cache@v4` in https://github.com/ocaml/opam/pull/6081
This reduces the time the CI takes by at minimum 8 minutes overall.
Tested successfully on my local fork in https://github.com/kit-ty-kate/opam/pull/12. Both cache creation and restoration work fine.
=> GHA: Restore the OCaml cache for the Windows jobs

master_changes.md, src/client/opamArg.ml, src/client/opamCliMain.ml, src/client/opamClientConfig.ml, src/client/opamClientConfig.mli, src/core/opamSystem.ml, src/core/opamSystem.mli, src/format/opamFile.ml, src/format/opamFile.mli
especially in long-running applications that use opam as a library reading and/or writing lots of opam files, this lead to a huge amount of memory usage for no obvious gain.
Partially addresses #6484
=> Fix a memory leak by removing OPAMSTATS

master_changes.md, src/state/opamSysInteract.ml
Partially f.i.x.e.s https://github.com/ocaml/opam/issues/6474
Fix #6495
=> Cygwin: Fallback to the existing setup-x86_64.exe if its upgrade failed to be fetched

master_changes.md, src/client/opamAuxCommands.ml, src/state/opamStateTypes.mli, src/state/opamSwitchState.ml, tests/reftests/dune.inc, tests/reftests/pin.test, tests/reftests/simulated-pin.test
When a package `pkg` is already installed and `opam install ./pkg --deps` is called, if there is a conflict between installed `pkg` dependencies and local `pkg` declaration, the conflict is not seen and the already installed `pkg` is kept.
For the code itself, the universe given to the solver was retrieving information from the simulated switch state, so the simulated pinned package information, not the good opam definition. We keep then the old information in the switch state, like that we can rearrange the package set given to the solver when creating the universe.
Fix #6529
=> `opam install . --deps-only` comply with the real constraints of packages

master_changes.md, src/client/opamClient.ml, src/state/opamSwitchState.ml, tests/reftests/deps-only.test
Fixes #6535
https://github.com/ocaml/opam/pull/6530 fixed the issue in the solver but created a discrepancy between what the solver gives displays and what is actually going to be executed.
To fix this we simply move the bit that re-add the non-simulated opam definitions, up before any solver/actions, and after any code specific to `--deps-only` where we actually need those information.
After careful review of the different usages of the autopin system, i think most other commands do not require fixes, at the exception of:
- the already broken `opam tree`: https://github.com/ocaml/opam/issues/6543
- possibly `opam switch create --deps-only` but i haven't managed to produce a test-case that show any issue yet. In any case i suspect this would be a very niche corner case if there is an …
=> Fix opam install --deps-only using the opam description of the wrong package in some cases

.github/scripts/depexts/generate-actions.sh, master_changes.md
See https://github.com/fedora-cloud/docker-brew-fedora/issues/119
=> GHA: gawk was re-added to the base fedora images

master_changes.md, src/client/opamSwitchCommand.ml, tests/reftests/switch-creation.test
=> on `opam switch create <version>`, use avoid-version compiler if it is the only one available

master_changes.md, src/client/opamPinCommand.ml, tests/reftests/pin.test
Backport of #6597 to the 2.4 branch
=> [2.4] Fix opam pin when the source of the pinned package doesn't exist

master_changes.md, src/client/opamCliMain.ml, src/core/opamConsole.ml, src/core/opamCoreConfig.ml, src/core/opamCoreConfig.mli
Alternative to https://github.com/ocaml/opam/pull/6486
=> Do not keep log messages before initialization if the code is ran through a library

doc/pages/Manual.md, master_changes.md
Add a mention of the `opam admin compare-versions` command in the manual.
This is a continuation of #6197 to improve discoverability (small qol).
Thanks!
=> doc: mention the compare-versions command in the manual

master_changes.md, src/client/opamCommands.ml
Inspired by https://discuss.ocaml.org/t/opam-pin-does-not-have-the-desired-effect/17084/7
=> Improve the opam pin man page by being more explicit about which arguments are optional

doc/pages/Usage.md, master_changes.md
It's currently interpreted as a relative path, and in the rendered version over at https://opam.ocaml.org it points to https://opam.ocaml.org/doc/www.softwareheritage.org.
=> Fix URL to Software Heritage

.github/scripts/depexts/generate-actions.sh, master_changes.md
Noticed in https://github.com/ocaml/opam/pull/6648
```
#8 6.951 copying path '/nix/store/zhv8ib8y1zfi76afddfnp8fmm562bgaa-git-2.50.1' from 'https://cache.nixos.org/'...
#8 7.544 copying path '/nix/store/xipypc58mgavflc7am3m28sk9hpczwf6-git-2.50.1-debug' from 'https://cache.nixos.org/'...
#8 8.094 copying path '/nix/store/bcw9f6r9v2fm3kv7d15fcrya0mf34xds-gcc-wrapper-14.3.0' from 'https://cache.nixos.org/'...
#8 8.715 building '/nix/store/28lm0m00ki2l3306j9glqnqnxzpgzfvq-user-environment.drv'...
#8 8.871 error: Unable to build profile. There is a conflict for the following files:
#8 8.871 
#8 8.871          /nix/store/q1fl77bw1h5am01g1qg081f30gkg5ml8-git-minimal-2.50.1/libexec/git-core/git-branch
#8 8.871          /nix/store/zhv8ib8y1zfi76afddfnp8fmm562bgaa-git-2.50.1/libexec/git-core/git-br …
```
=> GHA: Fix the nixos depexts tests

.github/scripts/common/hygiene-preamble.sh, .github/scripts/common/preamble.sh, .github/scripts/depexts/generate-actions.sh, .github/scripts/main/main.sh, .github/scripts/main/preamble.sh, .github/scripts/main/upgrade.sh, master_changes.md
Follow-up to https://github.com/ocaml/opam/pull/6394#discussion_r2294659403 to ensure similar problems don't happen in the future.
`set -o pipefail` could also be added at some point in the future for even more safety, however this one is usually a bit trickier.
=> GHA: Ensure every part of the scripts are run with 'set -ue'

.github/workflows/ci.ml, .github/workflows/main.yml, master_changes.md
For some reason this action can sometimes fail on master (e.g. https://github.com/ocaml/opam/actions/runs/16059563611/job/45322179882)
=> GHA: Only run the get-changed-files action when in a PR

.github/scripts/main/main.sh, .github/scripts/main/preamble.sh, .github/workflows/ci.ml, .github/workflows/main.yml, master_changes.md, release/readme.md
In it based on the same mechanism than opam-rt, it permits to keep them synchronised with the current API
TODO
This PR also contains an enhancement of changed files step (and it use/conditionning).
=> GHA: add a job that test opam libs dependencies compilation

master_changes.md, src/state/opamFormatUpgrade.ml, src/state/opamFormatUpgrade.mli, src/state/opamRepositoryState.ml, src/state/opamSwitchState.ml, tests/reftests/opamroot-versions.test
Current mechanism permit to load on-the-fly if no write lock is required global config files. These files are written if at global, repo or switch level a write is requested.
We want to change repo state format, so we need to update that mechanism to act also on repo & switch config files.
In this PR, we still have the old system : hard upgrade that block, light upgrades that don't block (confirmation message), and on-the-fly upgrade on global config. Plus, is added a mechanism to retrieve repo & switch config on-the-fly if lock read or none is requested, and if write lock is required a global upgrade with writes is launched (global lock required).
I've put it in its own commit the comment about no more upgrading hard upgrade version for visibility (and in changes)
=> Complete format upgrade mechanism at repo & switch level

.github/workflows/ci.ml, .github/workflows/main.yml, master_changes.md
opam isn't compatible with macOS 15's openrsync
=> GHA: Fix macOS builds by installing rsync

.github/scripts/main/main.sh, master_changes.md
Follow-up to #6394  
- Pin local dev repo of a package that has correctly identified branch, (instead of pinning with `kind git`)
- Filter out packages that are not coinstallable with opam libs.
=> GHA: reverse dependencies job follow-up

.github/workflows/ci.ml, .github/workflows/depexts.yml, .github/workflows/main.yml, master_changes.md, opam-core.opam, opam-repository.opam
I somehow forgot to update the constraint in https://github.com/ocaml/opam/pull/6580
=> Update the dependency constraint on patch to now require its stable version

master_changes.md, src/repository/opamLocal.ml, src/repository/opamLocal.mli, src/repository/opamRepository.ml, src/repository/opamVCS.ml, src/state/opamFileTools.ml
This is the first PR extracted from https://github.com/ocaml/opam/pull/6625
Quite simple so far but it is only the basis for the rest
=> OpamLocal.rsync_* doesn't use its return value

master_changes.md, tests/reftests/pin.test
See https://github.com/ocaml/opam/issues/6111
=> Add a test showing the behaviour of version pins when one of the dependencies isn't up-to-date

.gitignore, master_changes.md, src_ext/Makefile, src_ext/Makefile.dune, src_ext/Makefile.sources, src_ext/patches/re/0001-Backport-to-OCaml-4.12.patch, src_ext/patches/re/0002-Backport-to-OCaml-4.08.patch
Queued on 
* https://github.com/ocaml/opam-repository/pull/28544
Changelogs:
* dune: https://github.com/ocaml/dune/releases/tag/3.20.0
* re: https://github.com/ocaml/ocaml-re/releases/tag/1.13.0 and https://github.com/ocaml/ocaml-re/releases/tag/1.14.0
* menhir: https://discuss.ocaml.org/t/ann-new-release-of-menhir-20250903/17212
=> Update all the download-if-missing dependencies to their latest version

.github/scripts/main/hygiene.sh, master_changes.md, src_ext/update-sources.sh
Required during #6700 to update menhir as the URL couldn't be parsed.
While trying to fix that i found the script too complex so i chose to simplify it instead.
=> Simplify the src_ext/update-sources.sh script

master_changes.md, src/state/opamFileTools.ml, tests/reftests/extrafile.test
Discovered in the tests of https://github.com/ocaml/opam/pull/6614
The extra-files loader on Windows breaks when the file is contained in a directory and thinks there is a mismatch between the files listed in the field and the files detected on disk. The faulty behaviour can't be seen in the tests as i'm running them on Unix but it can be seen in the tests results of https://github.com/ocaml/opam/pull/6614 on Windows.
```diff
diff --git a/_build/default/tests/reftests/update.test b/_build/default/tests/reftests/update.out
index 8f52cdb..cd9a0db 100644
--- a/_build/default/tests/reftests/update.test
+++ b/_build/default/tests/reftests/update.out
@@ -415,6 +415,8 @@ EOF
<><> Updating package repositories ><><><><><><><><><><><><><><><><><><><><><><>
[git-test] synchronised from …
```
=> Fix the false-positive mismatch debug warning during "opam update" when faced with nested extra-files on Windows

master_changes.md, tests/reftests/env.test
Noticed in https://github.com/ocaml/opam/pull/6709
```diff
diff --git a/_build/default/tests/reftests/env.test b/_build/default/tests/reftests/env.out
index 981afd3..1bbb7e0 100644
--- a/_build/default/tests/reftests/env.test
+++ b/_build/default/tests/reftests/env.out
@@ -609,6 +609,7 @@ OPAMSWITCH=bd
OPAM_PACKAGE_NAME=to-build
OPAM_PACKAGE_VERSION=2
OPAM_SWITCH_PREFIX=${BASEDIR}/OPAM/bd
+__CF_USER_TEXT_ENCODING=0x1F5:0x0:0x0
PATH=${BASEDIR}/OPAM/bd/bin
The following actions will be performed:
@@ -650,4 +651,5 @@ OPAMSWITCH=bd
OPAM_PACKAGE_NAME=another-package
OPAM_PACKAGE_VERSION=another-version
OPAM_SWITCH_PREFIX=${BASEDIR}/OPAM/bd
+__CF_USER_TEXT_ENCODING=0x1F5:0x0:0x0
PATH=${BASEDIR}/OPAM/bd/bin:another-path
```
Tested successfully in …
=> GHA: Make the reftests pass with the macos GHA runner-images >= 20250928
